A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
Now the ECAM switch to the APU page automaticaly when apu master is on. If no external power is connected, only stay on the APU page for 10 seconds then switch to the DOOR page.
ECAM now start on the DOOR page, was previously the FUEL page.
Everything tested in sim, seems to work.
=> New automatic ECAM page switch

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/layout.json
The timer for the self test relies on external power being on as when I was using the simvar for getting the battery state it was not working properly, and in the real aircraft none of the displays are actually supposed to be on if there is no external or apu power and only battery. However feel free to edit it if you'd prefer to have it triggered by the battery.
=> Added self tests to all displays

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
APU gauge now show XX when it's is off. it diseaper a few seconds after the master is pressed
fixed a bug where apu page would not automaticaly show up
this hasn't been tested in sim
=> APU now shows XX + bug fixes

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
This in turn disabled the functionality I added for making the screens also go off when shutting down the aircraft (still works when powering on), but it's better than having the displays off when not starting cold and dark until I work on a solution.
=> Fixed a bug that made the displays go off when starting on the runway at certain airports

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
Fixes #20 
Couldn't get it to work with engine GEN because there is not enough simvar for it, will wait until someone does a more realistic ELEC system
=> APU gen arrow only show when no EXTERN POWER connected

.github/workflows/check_git_diff.sh, .github/workflows/ci.yml, A32NX/build.py, A32NX/layout.json, README.md
Hello!
I'm very happy to see some open source work being done in FS2020. I'm still working my way through the SDK docs and getting familiar with this project, so in the meantime I thought it might be nice to add a CI system.
This PR adds a few things:
- A GitHub Actions workflow with a single `CI` job. This will execute on every pull request and any pushes/merges into `master`. Right now, this verifies that `build.py` has been run before a PR can be merged.
- Refactors the `build.py` to move some of the logic into separate functions.
- Modifies `build.py` to sort `layout.json` alphabetically so we get a consistent result regardless of any Python version or OS inconsistencies.
Let me know your thoughts! And thanks for open sourcing this project :D
=> Refactor `build.py` and add GitHub Actions CI

.github/workflows/ci.yml
This PR fixes an issue introduced by https://github.com/wpine215/msfs-a320neo/pull/108 where the GitHub Actions `ci` workflow fails with a `Permission denied` error.
=> [Fix] CI permission denied error

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html
Replaced wind arrow on top left of ND to more closely resemble irl.
IRL:
Asobo:
My change:
=> Replaced wind arrow on ND

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
temporary fix modified the APU startup time from 20 sec to 3 according to @Dalmont (Flap opens much quicker on the NEo)
=> Update A320_Neo_LowerECAM_APU.js --APU Startup Time 

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixed Advisory messages after take-off. 
Previously showing green message on the ground and then moved to a caution once in the air.
#193 
#214
=> Advisory ECAM Message Fix

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml
fixes #237 
Makes it so NO SMOKING will appear on ECAM memo when set to AUTO and landing gear is more than 50% down.
=> show NO SMOKING on ECAM memo when set to AUTO

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Fixed altitude selection requiring to be clicked every time the altitude is updated.
Based on feedback from real pilots and engineers, it will now work as follows:
If in level flight, changing the altitude dial will adjust the visible target altitude on the PFD, but not start a climb until it is pressed.
If in a climb/descent, changing the altitude dial will adjust the visible target altitude on the PFD and adjust the target altitude of the climb/descent.
=> Fixed altitude selection requiring to be clicked every time the altitude is updated.

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/layout.json
Fixed various FMA issues, fixed ILS landing 'CAT' logic.
Asobo actually had all the code for 'CAT', 'SINGLE', and 'DUAL' in place! But... It turns out they're checking a condition which doesn't return correctly. Amazing.
I re-wrote the logic for when 'CAT 1', 'CAT 2', and 'CAT 3' should appear based on feedback from an IRL pilot, and the ICAO criteria for each category. 👍
=> Fixed various FMA issues, fixed ILS landing 'CAT' logic.

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml
In the real aircraft, the message shows "IR IN ALIGN" instead of the current "IRS IN ALIGN".
=> Changed "IRS IN ALIGN" to "IR IN ALIGN"

A32NX/.editorconfig
This PR adds an [EditorConfig](https://editorconfig.org/) file.  This does not force anything, rather it provides a baseline encoding / formatting config for different text editors.
It can be used if desired by contributors, and optionally enforced later at the decision of the team.
Relates to / part of #212.
=> build: add .editorconfig

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js, docs/a320-simvars.md
closes #147 
Ties PFD FAIL elements to the new local var L:A32NX_ADIRS_PFD_ALIGNED, so that PFD won't become available until 40% through alignment.
=> align PFD 18 and 28 seconds into alignment

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Fixes #343 
Just needed to not do setVsiible on the target alt, since the main code will do that every frame anyways.
Before the updateFail code would force the selected altitude to be visible which is wrong.
tested spawning in apron and runway.
=> fix target alt not going away on PFD

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
fixes #357
fix so ECAMs don't blank out after hitting APU MASTER with external power off
and so you aren't forced onto the APU page for 85 seconds
also puts you on DOOR page instead of APU page again after the 85 seconds is up
needs more work, but this fixes the major issues
CC: @ThePilot916
=> fix so ECAMs don't blank out after hitting APU MASTER

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
This puts the panels in "self-test" mode after the knob has been turned from off to another position.
Known issue: We can't seperate the panels yet so when the FO turns his knob to off and back to something, the captains side will also self test. This can be fixed when we can seperate the panels somehow.
=> Selftest after off status knobs

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #67, #271, #449 (those are the ones that are open)
* Fixes ILS button by using `<POTENTIOMETER_SEQ2>` to tie the panel brightness to only the text instead of the whole button.
* also remove a ton of whitespace.
before, the button was always off if the panel backlight was off.
panel backlight off:
panel backlight on:
I'm not sure if much can be done about the brightness differences between buttons. the FD button is on a completely different set of templates from the LS button, and the LS button shares templates with the ND display buttons (CSTR, VOR D, WPT, etc...). That seems to be the root of the problem, but trying to find whats so different about each one is a rabbit hole.
=> Fix ILS button brightness

README.md
Since this repository was moved, if you unpack the release .zip, the parent folder (that you should NOT copy) is named "flybywiresim-a32nx" not "msfs-a320neo-master".
=> Rename the parent folder referenced in the README

types/types.d.ts
This PR adds base TypeScript definitions files.
This does not modify any JS code and does not interact with MSFS in any way. This is purely for convenience and development. Any modern text editor (VSCode, IntelliJ-based IDEs, etc.) will automatically detect those files and use them for type checking JavaScript files. The advantage of this is that currently, editors might report functions as non-existent due to the non-standard and builtin functions used by the code. With these type definitions, this problem is alleviated as the editor can now use them to understand that those values and functions do exist.
That assistance can always be disabled if it is problematic in any way.
It is encouraged to add onto those definitions when coming across a function that is …
=> build(type-definitions): add initial type definition file

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
*  Added functional CLR and RCL buttons 
*  Master caution/warning will now automatically deactivate when messages are removed from ecam
The light on the clear button does not illuminate because it is missing a SEQ2 emission texture.
=> ECAM clear and recall buttons

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #110 
**Summary of Changes** Fixes the haphazard PR  #491 
Fixed ATHR unstable on TOGA
- Updated engine N1, EGT and Oil pressure values to match A320Neo engine limits.(temperature is in rankine, pressure in pounds per sq feet)
- N1 and EGT now have dynamic limits based on throttle state(arrow does not turn red beyond 100%N1 on TOGA upto 101.5% for 5min).
- TOGA state limits on N1 and EGT are only allowed upto 5min on both engines after which it comes down to MCT limits.
APU Guage now features a dynamic EGT warning marker.
Increased gauge px thickness by 1px.
=> Toga engine fix and ecam updates 

types/types.d.ts
This PR adds quite a lot of simvar unit types. Some of them have very inconsistent spelling and capitalization in the original code, might wanna clean that up at some point.
N/A
N/A
=> fix(typescript): add some more simvar unit types

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #198 (which was closed by mistake)
Fix `UNLK` text so it properly illuminates. This PR also replaces the default landing gear light template so it's easier to understand and maintain.
Before:
After:
After (at night):
Funny enough the real fix here was to not do whatever Asobo was doing to calculate if this light should be on. Something about setting a simvar in the same expression block screwed things up.
=> Fix Landing gear Indicator text illumination

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
**Fixes:** #472 
- Added new secondary ECAM memo for wing anti-ice and engine anti-ice
- Added new secondary ECAM memo for GPWS Flaps 3 mode (tied to INOP Flaps 3 push button)
- Added new secondary ECAM memo for Hydraulic PTU, which is displayed when the PTU sound plays
- Moved speed brake secondary ECAM memo higher up in priority list (referenced from FSLabs A320)
=> Added new secondary ECAM memos

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.html
N/A
Correct the default orientation of the valves in the lower ENGINE ECAM, should be vertical for open and viceversa.
N/A
[https://youtu.be/Zsk72luNZvc?t=717](https://youtu.be/Zsk72luNZvc?t=717)
=> [ECAM] Correct the orientation for the valves in the lower ENGINE ECAM

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #500 
- IRS alignment times based on latitude have been re-calculated
- IRS alignment ECAM memo now skips "IR IN ALIGN 0 MN" to match the real aircraft
- IRS alignment ECAM memo now skips "IR IN ALIGN 7 MN" to match the real aircraft
- IRS alignment ECAM memo now rounds up when converting seconds to minutes
- GPWS Terrain button now displays FAULT when IRS not aligned
- GPWS Sys button now displays FAULT when IRS not aligned
- IRS ECAM memo now goes up to >10 MN instead of >7 MN
- "IR IN ALIGN" replaced with updated "IRS IN ALIGN"
=> Adjusted IRS alignment time, ECAM memo, and effect on GPWS buttons

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
* Slight redesign to the rudder axis, see this video: https://www.youtube.com/watch?v=HBeFp08XG5M
* Add moving max rudder indicators, according to this graph 
provided by @JackZ974. The actual max rudder from the sim matches surprisingly well with this curve.
=> Small redesign for the F/CTL rudder axis, add moving rudder limit

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Also show LVR CLB warning in the Climb phase, instead of only the TakeOff phase
Based on changes made in issue #397, resolves bug introduced by those changes.
Before this change, if the acceleration altitude was the same as or lower than the thrust reduction altitude, the plane would enter the climb phase, and the LVR CLB warning would not show on the FMA, even though it should.
Take Off settings:
Before:
After:
=> Fix LVR CLB warning not showing up when in Climb phase

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
Makes it so the altimeter on the PFD smoothly animates to the current altitude (from 0) once the altimeter becomes avail during alignment.
reference (Partu_Grunt): https://youtu.be/qsQZsPFEf9o?t=67
after my changes:
=> animate pfd alt during alignment

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #283
The values shown on the upper ECAM and lower ECAM (FUEL page) are modified according to the constraints discussed in issue #283.
They now have a precision of 20kg for fuel remaining and 10kg for fuel used.
=> Fixed fuel display on ECAM as discussed in #283

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Airbus_A320neo_Checklist.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
In the checklists, removed INOP from the Vspeed settings and Predictive Windshear System. 
Also moved EXT PWR (ON IF AVAIL) before the APU fire test & start, which makes more sense to me and seems to be the suggested flow by 320 Sim Pilot (see https://youtu.be/Zsk72luNZvc?t=180).
=> Checklists: less INOP again

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
* Adds dynamic switching of ECAM pages when no page is selected.
* Modeled after this graphby discord user Ares#3394:
* Still got an issue, when the engine mode selector is turned to crank or ignition start, not only does the ecam page open up, but the button gets illuminated as well. It's just visual though, and the page switches back to normal as expected.
=> ECAM automatic switching

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Fixes #599
Calculate Take-off Weight (TOW) automatically in MCDU's INIT B page.
- TOW/LW is read-only green ([ref](https://discordapp.com/channels/738864299392630914/739223532269076561/754002161402118279))
- TOW = ZFW + BLOCK - TAXI, recalculated if one of them changes ([ref](https://discordapp.com/channels/738864299392630914/739223532269076561/754005483391680683))
=> Automatically calculate TOW if possible

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Fixes #578 
On plane power on, so either when powering on the plane from C&D or when entering the cockpit when starting the flight from the runway, the current MSL altitude of the ground is determined. That altitude + 1500 will be set into the thrust reduction altitude and the acceleration altitude on the PERF Take Off page, like it would in the real plane.
Before: 
After:
=> [CDU] Automatically fill in thrust reduction altitude and acceleration altitude based on runway height

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes #637 
Make TAXI fuel default value from "empty" to "0.2" as per commonly used AMI. See references.
References
[IRL pilot comment 1](https://discordapp.com/channels/738864299392630914/739223532269076561/754004668744728577)
[IRL pilot comment2 ](https://discordapp.com/channels/738864299392630914/739223532269076561/754051275397529672)
=> [MCDU] Default INIT B taxi fuel to match real aircraft

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Fixes #126
Change the viewbox for the attitude lines to make horizon and attitude lines move with each other
Change the seperator between bottom and top horizon y and thickness to make it centered and match closer to an actual PFD
Reduce medium/short pitch line width to closer match actual PFD
**Before:**
**After:**
For the line widths, I referenced these images from the reference photos channel in discord:
* https://cdn.discordapp.com/attachments/747724538095075369/748291724400656474/unknown.png
* https://cdn.discordapp.com/attachments/747724538095075369/748293186841215096/-pjZVGJfvHISJEI82UzqzRj4zo89kN764ulSC3_Dr0WnG4Uo8DptB7rXLQAt09P3Ahd67wxdnVphElO5qyPgvnbVxRJc6qMb3RNV.png
* …
=> Fix horizon

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
Fixes #58
Use low pass filter to compute the acceleration trend
**Videos**
(before) https://cdn.discordapp.com/attachments/739973060857167912/754242118750568518/before-speedtape.mp4
(after) https://cdn.discordapp.com/attachments/739973060857167912/754242159686844426/after-speedtape2.mp4
Reference: https://cdn.discordapp.com/attachments/747572666780745828/747661622637494373/speed-trend-vector-comparison_oBL4JKfz.compressed.mp4
=> Make speed tape more responsive

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js
Changed the v/s alert threshold according to the Airbus FCOM
Update VerticalSpeedIndicator.js
Fixes #[issue_no]No number
Airbus V/S Alert threshold was not implemented 
Implemented the alert threshold
Modified the digital display to start at v/s>200ft/min
=> [PFD] V/S indicator Update (VerticalSpeedIndicator.js)

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixes #592
Sets default screen brightness in C&D start to 0.1 (first setting)
See conversation in #592 on the authenticity of this decision.
I feel like even if we wanted to interpret a "cold and dark" state to mean something akin to "this plane has been in storage for a month so everything is just off", the amount of complaints we've gotten from users thinking the screens are broken is a problem on it's own. Just my 2 cents.
=> Update default screen brightness in C&D

types/types.d.ts
- Adds `position 32k` simvar unit as number type
- Adds `EICASTemplateElement::init` declaration
N/A
N/A
=> build(typescript): add EICASTemplateElement::init, more simvar units

types/types.d.ts
* Fixed error in the typescript file
* Added more enum options
I found the file where those enums are defined, as well as the Simplane functions (if that was not already known). For Steam installs, it's located in `Steam\steamapps\common\MicrosoftFlightSimulator\Packages\fs-base-ui\html_ui\JS` in `SimPlane.js`. There are many more functions in Simplane, if you want I can look through them and maybe add a few more interesting ones for convenience
=> Add more enum options, fix error in types.d.ts

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
This fixes the green dot speed that is displayed on the PERF TAKEOFF and APPROACH pages of the MCDU. It utilises the formula from Airbus of:
`(gross weight in thousandths * 2) + 85kts`
It previously referenced random numbers added to the aircraft weight.
=> Fix MCDU green dot speed

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixes #516
Adds check to ensure external power is both on AND available, not just on.
no external power:
external power:
This problem resulted in AC power being supplied to systems like the main screens.
=> Add additional check for external power availability

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
Partially takes care of #660
The F/CTL ECAM page will now have controls amber when both engines are not started.
This is temporary behaviour until we have proper modeling of the hydraulic systems.
N/A
=> feat(ecam/f-ctl): make controls amber when both engines dead

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js
General update/fix/cosmetic of the Alt scale
Fixes #[issue_no] 
Esthetic improvements and behaviour
- Added STD (Boxed)/QNH display.
- QNH legend is separated from value, so QNH can be in white
- Added small ">" for each alt in the alt scale
- the alt display window is now yellow as it should be
- the target alt cursor has been resized
- the target altitude has been aligned to the left of the alt scale
Before:
After:
=> [PFD] Altimeter strip Update (AltimeterIndicator.js)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes #643 
Aircraft should aim for V2+10 at takeoff until climb phase is achieved. Fix includes only CDU part. PFD support seems to be lacking and is to be fixed separately.
**Note**: For me at least MSFS doesn't do great job keeping the speed but at least it's better than the old +190kt target which is clearly wrong.
[Discord ref](https://discordapp.com/channels/738864299392630914/739223532269076561/755091076238409760)
[From Issue](http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.16.html)
=> [MCDU] Fix takeoff speed to V2+10

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.css
Fixes #690 
* Fix positioning of lower ECAM self-test position by bumping it up 5%
* Also remove styles for `SelfTest` since it was just making this problem more complex, and it really isn't needed since the element fills the parent wrapper anyway.
Before:
After:
Discord username:
=> Fix lower ECAM self-test position

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js, types/types.d.ts
* Update UpperEcam.js with new changes (#719)
* Update `types.d.ts` with Simplane functions
* Flaps are functionally the same, except for a caching feature in `Simplane.getFlapsHandleIndex()`, which doesn't seem to cause any issues. Also can be overridden if necessary.
* Changes to the throttle mode do not seem to break anything after a short testing.
=> Port Upper ECAM changes from 1.8.3

A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js
Fixes: engine 1 shutdown issue
Engine #1 no longer shuts down when APU master is turned off without fuel in center tank.
=> Temporary fix for engine 1 fuel flow being cut off during APU shutdown

A32NX/html_ui/Pages/A32NX_Core/A32NX_BrakeTemp.js, A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js, docs/a320-simvars.md
* Move brake temp logic into A32NX core
* Improve heatup and cooldown formulas
* Make heatup dependent on amount of brakes applied, and wheel RPM
* Cooldown is now based on the temperature difference to the ambient temperature
* Cooldown is also now a function of airspeed, and if the gear is deployed or not.
This is a "continuation"/replacement of #631 by @Benjozork.
**Additional testing of the cooldown and heatup speed is required and probably needs to be tuned**
See #632 for more discussion
=> Brake temp improvements

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.css
Added a dark background color that shows up at night. emulates the backlighting of the LCD screen. 
The background color still varies with the brightness button under the glareshield.
Modified the background color in the css
Before:
After:
Full brightness:
Daylight:
IRL:
No incidence on the behaviour
=> [FCU] Added background lighting at night (Update A320_Neo_FCU.css)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
- Do not show "REV" and thrust limit % when thrust reversers are active
re. Ares#3394 on discord and F-COM
=> fix(ecam/ewd): do not show REV and thrust limit in reverse

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Fixes #552 
Fixes #733
Most credit to @RikvanD1997 (see commits). Hope you don't mind me opening the PR! Opened PR as previous one had a mishap and there was another bug report too which this change fixes.
- Change acceleration altitude to be based on from "Above Ground Level" to "Main Sea Level" as in real A320
- Fix issue where "LVR CLB" is shown on FMA too early due to missing THR RED/ACC information on Simplanes's state.
[Reference](https://discordapp.com/channels/738864299392630914/739223532269076561/753381220523442277)
Discord username (if different from GitHub): VeGe-#4631
=> Acceleration altitude should be MSL instead of AGL

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
Changed the type of the Emergency Exit Status light to be 'Dummy', so it does not appear clickable, as it is not a push button
Discord username (if different from GitHub): Benjwri#2516
=> Set Emer Exit light to dummy

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #783 
Overspeed warning re-implemented. Master caution and ECAM message.
Conditions:
- A/C Speed/Mach above VMO+4kt
- L/G not uplocked or L/G doors not closed and above VLE + 4kt
- A/C Speed above VFE + 4kt, with slats and/or flaps extended.
*Entered overspeed with flaps down*
=> Fix #783 Overspeed Warning

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
* Fixes issue where automatic ECAM page selection would override the manually selected page.
* ~~Maybe a problem: A page triggered by a failure will not override the selected page, I don't know if this is expected behaviour or not~~
* ~~Problem: When Engine mode selector is not in normal, the engine page would come up, but will not go away, somewhere it overrides the currently selected page.~~ Should be fixed now
=> [BUGFIX] Prevent ECAM auto page switching when page is selected

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #797
* When ECAM STS page is selected, the light on the button is now illuminated
* When there are failures to clear, the ECAM CLR light illuminates.
* Prepared ECAM ALL button for usage. Button can be held, Simvar is A32NX_BTN_ALL
* Backlight of ECAM CLR, RCL, STS and ALL buttons backlight now working
Before:
After:
=> Ecam sts fix

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Fixes N/A
Fixes an issue where sometimes random decimals are shown on the flight plan waypoint restrictions when above transition altitude.
N/A
N/A
=> [CDU] Remove decimals from flight plan altitude FL constraints

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Fixes #742
Manually specify what box style should be used for each row, rather than checking if it's row 1. I'm not exactly sure how the 4th column (Cat 3 w/ Dual or Single) should work - I think it should be one big box around row 1 and 2, as shown below.
Before:
After:
Example of box around Cat 3 + Single - not sure if this is right
Discord username (if different from GitHub): 1Revenger1
=> [PFD] Fix boxes

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/approach.FLT, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/cruise.FLT, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/final.FLT, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/runway.FLT, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/taxi.flt, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Fixes #444
Fixes #843
Fixes descent phase so that it is at least activated. It's not 100% realistic, it just fixes a small bug in the original asobo code that kept descent phase from activating at all.
Also fixes so Activate appr phase is not an option on the DES page when not actually in the DES phase, but it does show up when in DES phase on the DES page.
Also some more tweaks to the yellow aircraft symbol on the pfd att indicator.
Made the center rect 2 px bigger, and made it so the yellow border goes in front of the green FD bars, but the black rect is behind the green FD bars.
Also sets default brightness for ECAMs to match PFD and ND.
=> Fix DES phase

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Fixes #862
Makes some FMAs have permanent boxes based on this site:
I believe if it has a box around it on that site, then it means it should always have a  box.
http://www.a320dp.com/A320_DP/nav-autoflight/sys-13.3.0.html
Also fixes FMA box timers so that that last only 10 seconds instead of ~20 seconds.
I applied that fix to all PFD elements and ECAM pages.
Also fixes blinking FMAs, like LVR CLB so that it will blink.
Here is also a video showing that MAN TOGA seems to be permanent boxed: https://www.youtube.com/watch?reload=9&v=ECV3IBkzZLc
=> make some FMAs have permanent box

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
Adds back G/S* logic that was overwritten when porting in asobos patch changes.
Fixes vertical FMA line not disappearing for things like the LAND FMA.
**Steps To Test**
- when intercepting the glideslope with APPR mode on, FMA should show G/S* when trying to get on the glide slope, then G/S when on glide slope
- When landing with ILS and really c;ose to the runway, LAND  FMA should appear and the vertical line between FMA columns 2 and 3 should disappear
=> Fixes G/S* and LAND vertical line on FMA

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_ECAMGauge.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #867
**Changelog**
- Increased flap/slat SVG thickness and updated colors
- Changed flap/slat markers from circles to parallelograms
- Increased text sizes for all elements
- Updated bounding box for N1 and EGT gauge values
- Decreased thickness and length of N1 and EGT inner markers
- Modified ECAM thrust state position and alignment
- Modified ECAM memo separator position and thickness; added rounded ends
**Before:** 
**After:**
=> Improve upper ECAM visuals

.github/CHANGELOG.md, A32NX/ModelBehaviorDefs/A32NX/A32NX_Exterior.xml
* Reduces engine rotation animation speed (Forgot to multiply with 0.01 in the original PR, percentages and all)
* Adjust the blur mesh thresholds accordingly
**References**
* See for example @JackZ974's comment on #753 
* Please let me know how it looks now, maybe if it's too slow. Especially shutdown might look weird now, since the fan stops way too fast at the moment, but that is being worked on.
<!-- You may optionally provide your discord username, so that we may contact you directly about the issue. -
=> Engine rotation speed fix

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.css
Patches #911 
Changed Amber colour on ECAM DOOR Page from Yellow to Amber.
Before:
After:
**References**
Feedback from @Ares1378 A320 Pilot
=> Patch #911 Lower ECAM DOOR Page

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js
Fixes #957 
- Battery Indicators on the OVHD Panel have been changed from WHITE to AMBER.
- Font Size Increased.
- ANN LT shows BATT "88.8v".
Before:
After:
**References**
=> Fix #957 Battery Indicators

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_HoldAtPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
Starts implementing #673 
Added Hold page and some functionality to set and validate input values. 
Missing waypoint routing logic, so purely cosmetic so far.
No before as the page is new. 
**References**
[A320DP Docs](http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.8.17.html)
[Hold Page Demo YT](https://youtu.be/D2iNDQohwDk?t=46)
Discord username (if different from GitHub): s3p1r0th#8483
=> optically working hold page, missing wp insert + routing

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
- Added arrows to F/CTL spoiler indicators which reflect position of individual speedbrakes
- If no hydraulic pressure (simulated with engine running state), display numbers instead.
- Change ELAC/SEC warning color from red to amber
**References**
Discord username (if different from GitHub): Iceman#5540
=> Add spoiler functionality to F/CTL ECAM page, adjust ELAC/SEC warning color

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js
Fixes #127, #148, #819 and improvement towards #31.
- available bleed pressure will now appear with no engines started
- igniters will be active between 18-55% N2
- igniters will swap between engines initially
- improved layout and design regarding igniters and valves
[https://www.youtube.com/watch?v=qAVQKnlzO7g](https://www.youtube.com/watch?v=qAVQKnlzO7g)
**References**
See related issues above.
Unsure if the N2 values need to be tweaked, feel free to give input.
Given the state of the bleeds system, only APU bleed is available at this moment.
Known issue: igniters will stop showing after engines are restarted, requires some logic gymnastics and a lot more code to implement it true to life, can see an …
=> [ECAM] Improve Lower ENGINE ECAM

A32NX/manifest.json
* name -> "A32NX" instead of "A320NX"
* author -> "FlyByWire Simulations" instead of "Iceman"
* version -> "0.3.1" instead of "0.1.51"
**References**
N/A
N/A
=> fix(manifest): correct author, name and version

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixes: Partially #1153
* ECAM wheel page is now only auto-selected when all gears are downlocked.
* See #1153
=> Fix ECAM wheel page appearing before gear is downlocked

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
AUTO BRK level would always show in amber because of an omission in the hydraulics available update.
Pretty self explanatory.
N/A
N/A
=> fix(ecam/wheel): fix auto brake quantity showing in amber

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Rework of #871
- Added the ability to highlight the text in magenta in the CDU
- Constraints above TRANS ALT will show as FL
- Entering a number below 1000 will insert a FL (e.g. 180 -> FL180)
- Adjusted empty brackets spacing
Seems to be different kind of shades of purple in different sources/videos, chose one to be inline with current colors. 
Open to changes.
=> [CDU] Add support for magenta color and improve the VERT REV page

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixes  #1232
Fix door video div hiding self-test
N/A
N/A
N/A
=> fix(ecam/door-video): fix door video div hiding self-test

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1265
- The new custom font uses a different character to represent slashes, I changed the parser at https://github.com/flybywiresim/a32nx/blob/74e2661c42aae84b1ac2715096921343dc425574/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1236
- Made the PLUS/MINUS button actually shows plus signs now.
Discord username (if different from GitHub): Lucky38i
=> Fixed ZFW/ZFWCG bug due to new custom font

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes complaint in the discord that users can't enter in ZFWCG
Reverted from using pipe character back to slashes, pipe character in new font is for spacing it seems
Various complaints in #help about not being able to enter ZFW/ZFWCG at all. This was due to the Div button outputting "/" but the method to parse ZFW/ZFWCG check for a | character.
Discord username (if different from GitHub): Lucky38i
=> fix: not being able to enter ZFWCG

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #1054 
Introduced a ECAM & aural warning for when landing gear is not down in the following conditions:
*Ref. FCOM*
*Ref. ESLD*
=> Fix #1054 L/G ECAM Warning

A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, docs/a320-simvars.md
* Adds functionality to the MAN V/S CTL switch, the CAB PRESS MODE SEL pushbutton, the LDG ELEVATION knob, and the guarded DITCHING pushbutton.
* Known issues: 
* The LDG ELEVATION knob should have a pull functionality, to select the manual mode (pushed in is auto). This isn't possible since there is no animation for that.
* The way the animations works for pushbuttons that should stay in isn't quite right, that needs to be done in the model animation as well
* The DITCHING pushbutton has no emissive
(Note that the scale in the model goes from -2000 to 15000, so i went with that.)
* No changelog since no proper functionality was added.
The build.py will have already been run with the latest changes, so …
=> Add functionality to CABIN PRESS knobs

A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior.xml
* Change the FBW knob template to be able to set the animation variable type to LVars, at @ThePilot916's request
=> Fix knob animation value not being accessible

.github/CHANGELOG.md, A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #596
Ensures the right DECEL light comes up during autobrake usage
Before
After
Lots of mentions by 320 sim pilot, for example
https://youtu.be/32q0xHybKmA?t=1440
"Decel light should show up medium 'cause that's what we use"
Discord username (if different from GitHub): Jokey | Markus#0001
=> Issue 596 decel wrong light

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #1350
* Removes the glow from the steering tillers.
* This also removes the text integrated lighting, since the button model and text are in the same mesh. I don't know if the text should have integrated lighting anyways, so it would be nice if someone could comment on that.
=> [Fix] Remove glow from tiller

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
- Imprroved FUEL page styling to more closely match IRL
Before:
After:
https://www.youtube.com/watch?v=5r0HsCmV4vU&list=PLizmZUECr7f2sL0c6nruV60MWcqFp_vaw&index=17
=> fix: improve FUEL page styling

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.html
- Match indicators and lines to be closer to IRL
Before:
After:
https://www.youtube.com/watch?v=VUjfYWNijA8
=> fix: improve lower ECAM styling

A32NX/ModelBehaviorDefs/A32NX/A32NX_Interior_Generics.xml, A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_ADIRS.xml, A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Includes.xml, A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, docs/a320-simvars.md
* Clean-up of ADIRS ModelBehaviors (knob + light templates)
* Added functionality to "FAULT" indication (simvar `L:A32NX_ADIRS_X_FAULT`)
* Needed for #1355
=> refactor: clean up ADIRS knob/light templates

A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseAirliners.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Com/A320_Neo_Com.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js, A32NX/html_ui/Pages/VCockpit/Instruments/FlightElements/Waypoint.js, A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js, A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Adresses #1603, Fixes #1600, Fixes #1599, Fixes #1601
* Partially port Asobo 1.10.7 update changes
* Not integrated yet: changes to AttitudeIndicator.js, ILSIndicator.js, NDCompass.js (some of it may be related to HUD stuff, don't know if we should inegrated that)
* Some changes to FMCMainDisplay.js aren't integrated yet, not sure if that is wanted
* Changes to A320_Neo_CDU_AvailableArrivalsPage.js not integrated, same as above
* XML changes, fuelsystem changes not integrated yet
* None of the CSS changes integrated yet, also not sure if we want to integrate those
* Also includes an Asobo update to the CDU, current AIRAC cycle from the internal MSFS database is now displayed on the MCDU
* Please check if I missed something
Every new commit to …
=> [Fix] Include some of the Asobo 1.10.7 changes

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
The current condition checks whether FD is turned OFF, instead of ON.
Fixes #1403
The current condition in the checklist checks whether FD is turned OFF, instead of ON.
n/a
n/a
n/a
Discord username (if different from GitHub): acro#2421
=> Fix FD in Taxi Checklist (fixes #1403)

.github/CHANGELOG.md
* Moves misplaced changelog entry from 0.4 to the 0.5 section.
=> Fix misplaced changelog entry

A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js, A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/A32NX_Utils/NXDataStore.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes PR #1280
Port ATSU logic to new Server API
Screenshots in original PR #1280
References in original PR #1280 
This PR implements the new Server API and is intended to be merged into `atsu-edwin` branch (PR #1280).
=> Fix ATSU, AIDS, CFDS issues

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes an issue introduced by #1725, where the crossfeed button would disable fuel flow to the left engine, thus shutting it down.
=> [FIX] Fuelsystem crossfeed bug

.github/workflows/pr.yml
Fixes #1827 
Actions for PRs now only run when:
* Non-Draft PR has been created
* Non-Draft PR has been updated
* Draft has been converted to Non-Draft PR
=> Don't run actions on Draft PRs

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fix for the recently introduced bug in the performance page, I think that the structure of the code used by Asobo does not allow multiple declarations of entities in the same file. The issue was because a `const` was declared before the `class`
Fixes #1841
I believe the Issue was introduced  in this PR https://github.com/flybywiresim/a32nx/pull/1583
Discord username (if different from GitHub): Union Araken#4083
=> [CDU] Fix Performance page broken

A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
* This change fixes the wrong "Too low, Terrain" warning on takeoff
* It was caused by the fact that the radio alt is set to a non zero value while loading (in my testing around 300ft), which caused problems.
=> [FIX] "too low terrain" warning on takeoff

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSInit.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
In some cases, the MCDU requires multiple colors per cell. A good example is the INIT B page, where the user may edit the fuel, but not the number of minutes (which are computed). Hence the cell is split in blue and green, which is not supported out of the box by the MCDU template. There are other in-cell formatting changes
To fix this in the past pages, various pages use a little marker in their template (e.g. ` {smallFront}` and `{smallEnd}`) together with script that replaces these markers in the innerHTML with `<span>`s using the corresponding CSS classes. This is a bit ugly, especially as multiple pages need this.
As part of #1342, @tyler58546 built a little helper for the CDU code that generalized the markers and applies them everywhere by default. Unfortunately #1342 is pretty …
=> [CDU] Add MCDU formatting helpers

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Fixes a tiny logical issue in some init page math that resulted in coordinates always showing N and E, instead of N or S and W or E respectively.
To test this (small) fix:
1. Spawn at an airport that is in the southern hemisphere and/or west of Greenwhich, e.g. SBGL, cold and dark
2. Turn on external power
3. Set all 3 ADRIS knobs to NAV
4. On the MCDU, open the INIT page and enter an arbitrary FROM/TO
5. Click the `IRS INIT>` LSK
6. Check that the coordinates show the expected hemisphere (N/S) and the expected side of Greenwich (W/E), e.g. S/W in SBGL
Discord username (if different from GitHub): BehEh#1234
The build script will have already been run with the latest changes, so no need to rerun it once …
=> [CDU] Fix IRS coordinates always showing N/E

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1795 
Permanent location reporting. Only FreeText is opt-in.
Do not persist accessTokens across sessions.
Fix the ATC issue by not resetting the FlightNumber SimVar.
Server is already updated to support the disabling of FreeText in the backend.
=> [CDU] Add location reporting and fix ATC issue

.github/CHANGELOG.md, A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_FCU.xml
Fixes #1871
Change the behavior of the altitude knob when the increment is 1000. It should first jump to the next number that is divisible by 1000 rather than just plainly adding 1000 to/subtracting 1000 from the previous altitude. The following table shows the changed behavior:
|original altitude  | -100  | +100  | -1000   | +1000   |
|---|---|---|---|---|
|   100| 100  |200   | 100  | **1100**  |
|  400 |  300 | 500  | 100  | **1400**  |
|  4000 | 3900  | 4100  | 3000  | 5000  |
|  4400 |  4300 |  4500 | **3400**  | **5400**  |
| 49000  |  48900 | 49000  | 48000  | 49000   |
|original altitude  | -100  | +100  | -1000   | +1000   |
|---|---|---|---|---|
|   100| 100  |200   | 100  | **1000**  |
|  400 |  300 | 500  | 100  | **1000**  |
|  4000 | 3900  | 4100  | 3000  | 5000  |
|  4400 | …
=> Fix altitude knob increment/decrement

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
This PR greatly improves the look of lateral revision page (LAT REV) in the MCDU, which right now is quite a bit away from the reference documentation.
Please note that this is mostly fixes visual issues on the LAT REV page only, not any behaviours and not any of the subpages, e.g. HOLD or AIRWAYS are out of scope for this PR. Items that were non-functional are also marked in gray now, but the behaviours were never there in the first place (nothing has been removed as part of this PR).
Here's a list of all the changes:
* Three primary versions: departure airport, enroute waypoint, destination airport
* ENABLE ALTN is only visible if an alternate is set on the init page, and only on enroute waypoint and destination
(note that the wrong N/E vs N/W coordinates were fixed after these …
=> [CDU] Improve LAT REV page layout

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
* Shows TELEX options page on first use of the plane to ask for consent regarding plane position uplink.
=> feat: ask for online services consent on first use

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/master.yml, .github/workflows/release.yml
Relates to #1789 #1790
Upload release artifacts to CDN + GitHub
Naming of the ZIP file changed to be in line with master
Tested in my fork and test CDN credentials.
=> Release to CDN

A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
* After the changes from #1715 by @antikythera288, go around flight phase is now implemented, so now, the "Too low terrain" warning on go-around should be no longer playing.
* "Don't sink" warnings on takeoff on some airports should also be fixed.
=> [FIX] Wrong GPWS warnings

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
Fixes #1941
* Reverts a css class change to the MCDU, which broke the color blue in the MCDU
=> [FIX] Revert css changes to MCDU by #1938

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #565
Fixes #782
Fixes some one part of #422
Fixes some one part of #760
- ATHR now targets climb speed for managed speed mode instead of next flap retraction speed
_ATHR now accelerates past F and S speed marker as it should do_
https://www.youtube.com/watch?v=gLBlHOEQrIM&feature=youtu.be
=> [CDU] Fix athr targeting flap speed on climb

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
Fixes #1976 
Unit of cabin pressure change is feet/minute in code but not in the display.
Fixed this typo.
Before:
After:
https://www.youtube.com/watch?v=sRiEf-at0Bs&feature=youtu.be&t=896
=> Fix typo for cabin vertical speed

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Engine.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Right now, the EICAS/ECAM code is shared between the lower and the upper DU. This is mostly fine, except for updating pages when it's not needed. Most critically, `getActiveFailures` calls a lot of simvars to check the active ECAM failures, and is run from the bottom screen. This is completely unnecessary. My upcoming PR on the FWC #1943 also runs twice without this.
Note that while testing, in some cases I've seen the new page briefly flash with old data. This issue existed previously, and the inactive pages were never updated previously. This change purely disabled:
- the top ECAM screen being silently refreshed the bottom screen
- the bottom page being silently refreshed the top screen
I'm not sure this is worth a CHANGELOG entry - it's hidden to users, but may have a slight …
=> [ECAM] Stop updating the ECAM pages twice

A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
* This changes the AP takeover pushbutton to our own template
* Now, when the AP is engaged, pressing the button will disconnect it.
* When it isn't engaged, as long as the button is held, the LVar "L:A32NX_PRIORITY_TAKEOVER:x" will be set to 1, where x corresponds to the side (1 is left, 2 is right)
* This is only for compatability with YourControls, and has no WWise events hooked up.
1. On the right side, click on the **Artifacts** drop down and click the …
=> Add custom sidestick priority template

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1720
Fixed an issue where the precomputed ZFW/ZFWCG values were not properly updated if the weight load was changed from the game menu.
Details to reproduce and check are in the linked issue.
=> [CDU] Update the precomputed ZFW/ZFWCG values when weight parameters are changed

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
- Fixed athr targeting flaps speed on acceleration/climb when no cruise alt/fl is set.
(No changelog because this pr fixes the same bug as #1944, but caused by slightly different parameters)
=> [CDU] Fix athr still targeting flaps speed

A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.html
Fixes #1995
ECAM COND-Page:
- Enabled rotation of trim air valves
- Fixed color of hot air valve (always displayed in amber)
- Implemented trim air outlet temperature
- Added gradual cabin temperature adjustment
- Current pack flow influences temperature adjustment rate
- Cabin temperatur now gets calculated by trim air outlet 
- By closing the hot air valve cabin temperature will sink to pack outlet temp
Tim#0335
MrMinimal#8489
1. On the right side, click on …
=> Enhance ECAM COND Page

.github/CHANGELOG.md
=> fix: add missing CHANGELOG line

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.css, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgConstraintElement.js
Add missing constraint symbol in the navigation display when CSTR is selected.
Video: https://youtu.be/TEi-WX08ov8?t=243
Discord username (if different from GitHub): Union Araken#4083
=> [ND] Add missing altitude constraint symbol

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
Fixes #1964
- Provide a temporary fix for self-test text being borked, since I could not find a culprit in the jungle of CSS and templates.
=> fix(ecam): temporary fix for self test font size

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Use the `TITLE` SimVar to report the correct AC type to the API
Fix some minor bugs
- Destination and origin from the previous flight  were reported
- A connection with an empty flight number could be established
Reported AC type in the API
=> [API] Report AC type to API

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css
Followup to  #2012 where the wrong interval was used, based on the reference linked below (where QNH flashes in a 1s interval).
Nothing about the logic was changed, just the animation. No changelog entry should be necessary as this was just introduced.
https://www.youtube.com/watch?v=UWLYjD6P-RU
=> [PFD] Fix QNH blinking interval

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Core/A32NX_FWC.js, A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js, docs/a320-simvars.md
This PR is a followup to #1943, incorporates some feedback from there and improves the ECAM inhibit and recall behavior to be more accurate. Where previously there was no distinction between inactive messages and inhibited message, this PR splits those two out so that the inhibit behavior can be implemented more accurately. This allows the flight phase inhibition to be correctly overridden using the recall button, and also ensures warnings stay visible during a flight phase change if they were visible previously.
The PR also provides some minor fixes to some ECAM messages themselves, by fixing colors and improving when and how some of the messages appear. See the full changelog below:
- Active warnings persist through flight phase changes, even if they would be inhibited  
*For example, …
=> [ECAM] Improve inhibit and recall behaviour

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Fixes #499
The goal of this PR is to be able to insert the constraints symbols that were always hardcoded before. The goal of this PR is not to update the AP behavior in order to follow those constraints but only to be able to insert and persist that data.
In order to see the new constraints and the symbols, you need to toggle the CSTR button until you see them, that issue if it's one in real life is not related to changes of this PR.
- Update flight plan page to accepts `+`,  `-`  and non-symbols values.
- Persist the waypoint constraints symbols.
- Kept the already implemented asobo feature that sets the constraints symbols if not already set by the user.
**Please watch the demo video in order to get more context about this PR.**
https://www.youtube.com/watch?v=Qoz-j4g87S8
Thanks to …
=> [CDU] Added constraints symbols logic to flight plan

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
Fixes #2032
Change heading calculations to stay within 0-360 degree range.
Bug was caused by the compass rotating to 720/1080/1440/etc. degrees after multiple rotations.
To test, spin your Airbus 1080 degrees left or right and monitor the compass when it rotates over 0 degrees.
It shouldn't wildly spin in the opposite direction doing so.
Previous behaviour (also works on ground if you spawn on runway): https://youtu.be/xRalxEtV7wc
The compass shouldn't spin wildly after the 2-3rd full rotation.
Discord username (if different from GitHub): MrMinimal#8489
1. Make sure you are signed in …
=> Fix compass spinning wildly

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
Use a custom L-variable from custom FBW to display sidestick position in PFD and to detect if flight controls page needs to be displayed.
=> Use L-variable for sidestick position

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
- Made takeoff speeds not set by default
Before:
After:
=> [CDU] Fix negative default takeoff speeds

.github/workflows/cfbw.yml
* Add CI build workflow (only uploads to CDN) for custom fly-by-wire system branch
=> build: add build workflow on fbw branch

A32NX/html_ui/Pages/A32NX_Core/A32NX_Vspeeds.js
Fixes #2173
- Corrected Flaps 1 and Flaps 1+F logic.
=> [CORE] hotfix gd not visible

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
This PR repositions the `CLR` five spaces into the scratchpad.
Honeywell CDU:
[(full video)](https://github.com/flybywiresim/a32nx/pull/1824#issuecomment-734339999)
FSLabs:
=> [CDU] Fix CLR position in scratchpad

.github/PULL_REQUEST_TEMPLATE.md
This PR is a GitHub-only change. It adds a notice to the pull request template to educate contributors about using GitHub's feature of automatically closing issues correctly when multiple issues are referenced.
=> Add auto-close notice to PULL_REQUEST_TEMPLATE.md

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Fixes #1402
Changed the check for whether to show the airplane icon on the ND based on ADIRS state to occur no matter what ND mode is selected, whereas before it only checked when PLAN was selected.
Before
After
N/A
Previously, when the ADIRS were aligning, if the user selected PLAN mode on the ND, it would check the ADIRS state and hide the airplane icon. If the user left PLAN mode while the ADIRS were still aligning, the check would never be performed again and after the ADIRS aligned the icon would not be visible until the user reselected PLAN and the check reoccurred. Now, the check will occur no matter what mode is selected, provided the airplane icon exists.
Discord username (if different from GitHub): ThatRedMelon#6756
Every new commit to this PR will cause a new A32NX artifact to …
=> Fix ND Invisible Airplane Icon

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_CIDS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Fixes #2238
- Added new options menu (CIDS) with option to replace "NO SMOKING" memo with "NO PORTABLE DEVICES", which are commonly found on Neo aircraft
- Added PACKS/NAI/WAI text indicator on upper ECAM, which is visible when thrust mode targets TOGA, FLEX/MCT, or SOFT GA.
- Added REFUELG left memo when fuel truck connected
- Added OUTR TK XFRD left memo when fuel is actively being transferred from outer to inner tanks
- Added CABIN READY right memo according to documentation (flight phases 2, 6, and 7)
- Added FUEL X FEED right memo when fuel cross-feed is on
- Added ADIRS SWTG right memo when either Air Data or IRS switching knobs on the pedestal are in use
- Adjusted position of AUTO BRK right memos to reflect documentation
- Adjusted positioning of N2 and FF text on the EWD, as it …
=> Various fixes/additions to ECAM, FWC, and FMA

A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Fixes #2336, Fixes  #2185
* Fixes a bug where the retard callout would not play
* The retard callout now stops when the thrust levers are below 5%, instead of excatly at idle. This should fix the issues with it playing in a loop.
This logic is still not what it is in RL, and will need to be implemented in the FWC at some point.
=> [FIX] Retard callout bugs

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Core/A32NX_ATSU.js, A32NX/html_ui/Pages/A32NX_Utils/SimBriefApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_SIMBRIEF.js
Allows user to insert a SimBrief user ID instead of username.
N/A
N/A
Discord username (if different from GitHub): pareil6#0990
=> [CDU] Allow SimBrief user IDs instead of usernames

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_Init.js
Fixes #2560.
Reuses existing seconds -> hh:mm function to fix formatting bug in function used in two places in the INIT/REVIEW B page, causing minutes values below 10 to be zero padded on the right instead of the left.
SimBrief OFP:
Before:
After:
N/A
N/A
Discord username (if different from GitHub): pareil6#0990
=> [CDU] Fix incorrect block time display on INIT/REVIEW

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
If the active SimBrief OFP has different origin/destination airports to the currently active flight plan, enable the INIT REQUEST option on the FP INIT A page. This allows a new SimBrief flight plan to be loaded after a flight, by loading the new OFP from the INIT/REVIEW screen, then returning to the FP INIT A screen and selecting INIT REQUEST to overwrite the existing flight plan.
Loading initial flight plan:
After loading new SimBrief OFP data from the INIT/REVIEW page:
Flight plan waypoints successfully cleared and replaced:
N/A
I can't find any obvious reference for how this behaviour works in the real MCDU - if anyone has details, let me know and I can update this to match. Intuition says that the INIT REQUEST text on the INIT A page should maybe be cyan instead of amber if there's …
=> [CDU] Allow SimBrief OFP to override previous flight plan

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes  #2613
* The flaps indicator on the upper ECAM was broken after the Sim update 2. This fixes it.
=> [FIX] Broken flap indicator

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_Misc.xml
Fixes #2586.
Fixes autobrake max disengaging after a short period of time while on the ground, caused by a subtle logic error introduced in the RNP conversion.
N/A
N/A
N/A
Discord username (if different from GitHub): pareil6#0990
Try setting autobrake max, try taxiing, using the foot brakes and checking that doesn't reset it, take off and check it clears after the landing gear comes up, check it can't be selected once in the air.
1. On the right side, click on the **Artifacts** drop down and click the …
=> [MISC] Stop autobrake max disengaging on the ground

.github/CHANGELOG.md
Fixes #2639, fixes #2640
Fixed an issue caused by #2614 that caused the f/o displays to be synced with the captain displays.
Make sure F/O displays are independent of the captain displays.
=> Fix F/O displays

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
This fixes some references to non-existent class properties in the CAB PRESS SD page, which could (rarely) cause a race condition and make the instrument fail to update.
* Verify that the PRESS page still has the same functionality
=> fix: invalid code in CAB PRESS page

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
Fixes #2843
Fixed a typo in the Descent preparation checklist.
none
none
none
1. Open "Descent preparation" checklist.
1. Go to checkpoint after "PERF DES Page".
=> Fixed typo in Descent Preparation checklist

.github/Contributing.md
No issue relates to this PR as it is a simple broken link fix.
This is a simple fix to the Discord invite link that is currently broken.
Currently, when clicking the Discord link, you get an error saying "Invite Invalid":   
N/A
I am a Software Developer that wants to get involved in this project.  This is the first time I am using GitHub for version control (normally use Gitlab or BitBucket) and it is also my first time contributing to a public repository.  Hence why I spotted an opportunity to go through the process with a trivial change.
I have not modifed the changelog.md as this does not really relate to any real changes to the aircraft.
Killer_Klient#0559 (alias 777GE90)
I reviewed the new contribution.md file and tested the new link …
=> Fixed broken discord link in contribution.md

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html, docs/resources.md, typings/fs-base-ui/html_ui/JS/common.d.ts
When developing the a32nx in combination with WebUI-DevKit for debugging purposes, the upper ECAM often showed the engineering mode overlay instead of the normal view. Whenever this happened, there were many errors in the console stating an `update` function couldn't be found on the `eicas-common-display`.
I traced this issue to the loading of scripts using the `import-script` attribute. Scripts by default are loaded asynchronously, meaning the declaration order isn't the loading order. In practice, usually this doesn't lead to problems because the file system and browser cache provides files at a quick enough rate for the order to be respected in most cases. However, as WebUI-DevKit has cache-busting code which removes caching altogether, the issue was more likely visible with it. The …
=> fix: upper ECAM showing engineering mode overlay

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_PRESS.js
Fix pressure page javascript error
n/a
n/a
Enable msfs dev util, go to lower ECAM pressure page, ensure no javascript errors.
=> Fix pressure page javascript error

A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Increased engine N2 required for engine to supply bleed air
@hotshotp 
=> fix: variable for packs sound

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_FCU.xml
Fixes #2687
- Removes overlapping text on the FCU Baro knob ( credit to @DarkOfNova for the texture fix)
- Adds additional template to prevent the FCU Baro knob emissive to load since the Baro knob is not backlit. 
BEFORE:
AFTER:
Baro knob should not be backlit. Confirmed by multiple real-world pilots.
DarkOfNova#2688
Imenes#8739
Tier 1 test required. Make sure the FCU baro knob does not light up at any point and test the functionality of the knob.
Check the text on the knob to make sure the overlapping text issue is fixed. 
1. Make sure you …
=> fix: FCU baro knob overlapping text and emissive removed

A32NX/html_ui/Pages/VLivery/Liveries/Printer/Printer.css, A32NX/html_ui/Pages/VLivery/Liveries/Printer/Printer.js
Fixes #3187
* Fixed printer using small font unnecessarily
* Switched printer font to ECAM font as it is closer to the real font and is more readable 
Before:
After:
Print messages with different lengths and make sure they are formatted correctly. The printer should only use the small font size for very long messages, such as when requesting weather from 4 airports at once.
=> fix: printer font fixes

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
- Disables left steering tiller emissive since the tiller deflection plate should not be illuminated.
BEFORE:
AFTER:
The Tiller plate is not backlit as confirmed by IRL A320 pilots.
Discord username: Imenes#8739
Tier 1. Make sure that the left steering tiller deflection plate is not illuminated. 
=> fix: disable tiller plate emissive

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Utils/NXSpeeds.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
The MCDU PERF APPR page has a landing config selection, allowing either FULL or CONF 3. This selection alters the speeds displayed on the page, and the target approach speed V<sub>APP</sub>.
I have adjusted the formatting for the CONF 3 and FULL items on the APPR page to match the Honeywell manual. The latest rev. of the Honeywell FMS changes the format slightly but I have been unable to get a solid reference to date so I've elected to stick with step 1A for now (future PR to update if we decide to).
Before:
(R4 and R5 INOP)
After:
Full config selected (default):
CONF3 selected:
Honeywell Step 1A MCDU:
FCOM (older unfortunately):
FCOM bulletin 46/2:
Prior to approach phase, the values shown on the PERF page are based on estimated landing weight, which in turn is based on ZFW and our EFOB …
=> feat(mcdu): Support CONF 3 Landing

.github/CHANGELOG.md
- Added back the inHg/hPa indications above the QNH knob. The placing position is limited until we are able to edit the model, so I could not move it further down like it is on the reference. 
Before:
After:
Discord username: Imenes#8739
Tier 1. Make sure textures display correctly both lit and unlit. 
=> fix: add inHg/hPa above QNH knob

.github/CHANGELOG.md
Fixes #2971, Fixes #3213
- Fixed the missing throttle lever detent decal
- Corrected misspelling of "compass" 
- Redrawn the lines at the bottom of the cockpit text decal UV
BEFORE:
AFTER:
Since the detent decal is taken from a shared spot I decided to do a full rework of the lines at the bottom of the UV these ones:
I looked at the default, dev, and reworked version to see if there are any issues caused by the line rework, and as far as I can tell there are no new ones actually it fixes some other line issues, but it will need at least tier 2 QA testing to make sure no new issues appear.
For future reference, I will post pics of the cockpit before and after the rework below:
Before:
After:
QA might notice that the throttle decal is not backlit at the top. This is the same in default A320 …
=> fix: throttle lever detent decal and removed extra S from compass

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes issue reported on Discord by danbw9#7028
Fix a race condition on spawning directly into approach phase.
PFD before when spawning directly into approach phase:
PFD healthy after fix:
No changelog needed since the bug never made it into a release I think?
Discord username (if different from GitHub): tracernz#3313
Spawn directly into approach at IAF and ensure PFD is operative.
=> fix(mcdu): fix race condition when spawning directly into approach

scripts/build.sh, scripts/dev-env/run.sh
Fixes the build metadata in the delivery. It will then correctly contain the sha, ref and actor.
=> build: fixed build metadata when run on github action

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js, docs/a320-simvars.md, src/systems/a320/src/lib.rs, src/systems/systems/src/apu/air_intake_flap.rs, src/systems/systems/src/apu/mod.rs, src/systems/systems/src/simulator/mod.rs
This further improves the FLAP OPEN indication on the APU ECAM page.
It is displayed when:
1. The flap is fully open
2. The flap was fully open and is closing, but not fully closed.
3. The flap was fully open, started closing, but started opening again before fully closing.
Additionally this PR ensures that while the FLAP OPEN indication is shown, the APU N and EGT are displayed (instead of amber XX); even when the APU N = 0 and MASTER SW is OFF.
1. Click on the **Checks** tab on …
=> feat(apu): FLAP OPEN indication until fully closed

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Recently the `FBW_Push_Toggle` XML template was added. It has many great features which simplify the way we define elements in the cockpit. However, not all buttons that use `LEFT_SINGLE_CODE` have the `DOWN_CODE` set; while they should. For the APU MASTER SW specifically this caused a bug where one could reverse the push state of the push button: the button was `in` when OFF and `out` when ON if you didn't turn on the batteries before pressing the MASTER SW.
1. Start with a cold and dark cockpit.
2. Press the APU MASTER SW.
3. Turn both batteries ON.
4. Press the APU MASTER SW.
Expected: The APU MASTER SW is ON, with the button pushed in.
Actual: The APU MASTER SW is ON, with the button out.
Every new commit to this PR will …
=> fix(apu): MASTER SW reversed push state

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, src/instruments/src/EFB/StatusBar/StatusBar.tsx, src/instruments/src/EFB/index.jsx, src/instruments/src/EFB/react-app-env.d.ts
* Add very basic battery logic to EFB
* Click on the EFB to turn it on (no need for aircraft DC or AC power)
* Observe startup sequence
* Turn off EFB by clicking on the yellow indicator on the top right
* Observe shutdown
* Observe turned off state
* Click on the EFB to turn it on
* Observe startup sequence
=> feat(efb): make EFB have its own battery

src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Fix fuel capacity and cargo capacity values, change MRW, MTOW, MZFW to use metric units for consistency with fuel capacity and cargo capacity. Also changes the units for fuel capacity from kg, which is incorrect, to l.
Fixes https://github.com/flybywiresim/a32nx/issues/3307
Partially addresses https://github.com/flybywiresim/a32nx/issues/3299
From Airport Planning Document:
From FAA Type Certification Data Sheet:
MSFS Fuel Quantity in Liters (Add them up):
It might be nice to be able to have this page show the values in U.S. units when the user has U.S. units selected in the MSFS options menu. Should probably also add max landing weight.
Actual fuel capacity in liters is 23,724.  MSFS uses gallons as the base value, and the fuel quantity of each tank in gallons is specified in the …
=> fix: EFB Dispatch page fuel quantity, cargo capacity, MRW, MTOW, MZFW

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
* The AIRLINER_DECISION_HEIGHT simvar was previously initialized in the PFD. This PR changes that, now it is initialized in the FMC/MCDU.
* This is also a bugfix for the custom PFD, because without the old PFD this would be initialized as 0 instead of -1, which actually means 0 DH, so the PFD would show that, even if nothing was entered in the MCDU.
* Make sure that when loading the plane, the DH is correctly initialized (i.e. nothing is shown on the FMA). Since the DH can only be shown on the FMA in approach and descent, I would recommend spawning in approach.
The build script will have already been run with the latest changes, so no need to rerun it once …
=> refactor: move DH LVar init into FMC

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.css
APU GEN title must be white when running (load, V and Hz within operational conditions).
Wrong:
Right:
https://www.youtube.com/watch?v=Im0OFRxImYw
=> fix(apu): APU GEN title must be white when running

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
The RADNAV page is finally fun to use :D
My second pass over the RADNAV page to improve quality as it lags behind other pages of the MCDU. Main goal is to get accurate display of everything you need. Navaids reception problems are not goal of this PR. The list below might extend while progressing.
**Attention! The RADNAV page is only to show what is set up, not how the reception is. That can be checked on the ND wether it shows any identifier. MSFS2020 is very limited in its navaid reception, eg. ILS only closer than around 25nm.**
**Allowed field input formats:**
**VOR1/2:** XX, XXX, 123, 123.4, 123.45 (Range 108-117.95)
**CRS:** 1, 12, 123 (Range 1-360) (limited due to system, IRL its 0-360)
**LS/FREQ:** 123, 123.4 (Range 108-111.95)
****ADF1/2**:** XX, XXX, 123.5, …
=> refactor(mcdu): RADNAV (part 2)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
This PR fixes the alignment of the PERF TAKE OFF page heading. For one, it ensures it's vertically aligned to the letters below, as in reality, and secondly it ensures the runway is left-padded to 3 characters with white space according to the reference below.
Not adding a change log as this new page layout was only introduced this release cycle.
=> fix(mcdu): correct alignment of PERF TAKE OFF page title

README.md
Changed CFBW download link in Readme, so it does not point to the old CDN
CDN was changed and old is disabled now
Foxtrot Sierra#6420
None
=> fix(docs): Change CFBW download link in Readme

.github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/release.yml, package.json, scripts/fragment.js
After the normal build process, the artifact gets split up into multiple, smaller zip files and uploaded to a new CDN.
N/A
N/A
* Make sure the aircraft loads and functions (download the artiffact)
=> build: use fragmenter for optimised distribution

package.json
* Forces version of rollup plugin to not update to 1.0.4
=> build: force version of @flybywiresim/rollup-plugin-msfs

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml, docs/README.md, src/behavior/src/A32NX_Interior_Misc.xml
Adds the missing throttle levers detent and reverse lock sounds
Discord username (if different from GitHub): Imenes#8739
=> fix(autopilot): enable detent sounds

.github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/release.yml, package.json
- Remove the `--ascii` option from the lftp mirror action
- Zip artifacts beforehand to reduce the size since Github doesn't compress the zip when uploading the artifact.
N/A
N/A
N/A
The artifact size should be reduced by ~50%. The downside of this is a zip file within the downloaded zip artifact. Make sure you can still fully unzip the A32NX directory and that the A32NX is loading screens + systems in the sim.
=> build: fragmenter fix & artifact size reduction

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, src/instruments/src/EFB/Settings/Settings.tsx, src/instruments/src/EFB/Settings/sync.ts
* Adds an adjustable brightness setting to the flyPad
* Make sure the brightness slider works
* Make sure the brightness range is acceptable
* Make sure the brightness setting persists over MSFS restarts
=> feat(efb): add adjustable brightness setting

A32NX/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
- Removed not needed back door to skip flight phase preflight in case of mid air reload.
With this fix:
- Spawn on airport e.g. GCXO. observe flight phase is correctly preflight
Without this fix:
- Spawn on airport e.g. GCXO observe flight phase is CLIMB/CRUISE
=> fix(fmgc): bad flight phase change on spawn

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, src/instruments/src/EFB/index.jsx
Fixes #3887
* Remove `MouseRect` interactivity preventing use of touchscreen
* Handle interactivity directly inside of React
* Make sure the EFB can be turned on by clicking on it (tooltip is gone, unfortunate side effect)
* Make sure EFB can be turned off and turned back on
=> fix(efb): restore interactivity after MSFS 1.14.5.0

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js, src/behavior/src/A32NX_Interior_FCU.xml
* Fix vertical speed knob and FCU not using the correct V/S holder variable indices
* Make sure that V/S and FPA works as it did before (behaviour is probably still wrong like it was before on the development version; correct behaviour is on the custom autopilot and isn't here)
=> fix: vertical speed FCU logic

scripts/cdn.sh
Certain cURL versions cause issues with the `-F` option. Replaced it with `--data-binary`.
N/A
N/A
N/A
N/A
=> build: improve cdn upload script

.github/workflows/master.yml, .github/workflows/release.yml
Enable the use of the secret token for CDN purges
N/A
N/A
N/A
=> build: use secret token for CDN purge

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
A very short and quick fix for a bug I inadvertently introduced in #3870 where waypoint and it's details appeared instantly after setting it on the MCDU, even before ADIRS aligned. Added a separate condition to fix this.
Discord username (if different from GitHub): sidnov#8337
1. Spawn C/D, power up the aircraft, align ADIRS, observe ND loads completely with waypoint set to PPOS and no other visible details.
2. Restart, spawn C/D, power up the aircraft, set departure/arrival airports on the MCDU. It should not instantly update waypoint name, time/distance on the ND (top-right corner). Should stay on "PPOS". Now, align ADIRS and wait, check the waypoint details appear only after alignment is complete.
Every new commit to this PR will cause a new A32NX artifact to be created, built, and …
=> fix(nd): quick fix for PPOS/Wpt when ADIRS not aligned

src/.eslintrc.js
As we already have automatic CRLF handling (#1927) there's no need to have AirBNB's linebreak-style rule. We can simply turn it off and all is well.
=> chore(eslint): turn linebreak-style rule off

.github/CHANGELOG.md, src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
Fixes #4057 
I have added the "font-mono" class to the container div holding the loadsheet. This causes it to show in monospace font as intended.
Before
After
n/a
This is my first proper issue / pull request combination. Please be kind :-)
Discord username (if different from GitHub): Chriskgk#4359
Check if the OFP imported from simbrief is correctly shown with monospace font.
=> fix(efb): Use monospace font to render OFP on EFB.

src/systems/a320_systems/src/electrical/mod.rs, src/systems/systems/src/apu/aps3200.rs, src/systems/systems/src/apu/mod.rs, src/systems/systems/src/electrical/emergency_generator.rs, src/systems/systems/src/electrical/engine_generator.rs, src/systems/systems/src/electrical/external_power_source.rs
In #4064 @hotshotp mentioned an issue where "when the left engine is shut down the aircraft loses and gains power making many sounds at once play". This PR fixes this issue.
The frequency and potential of the power sources are only known at the end of a simulation tick, due to them being directly related to the power consumption (large changes can cause spikes and dips). However, the decision if a power source can supply power is made much earlier in the tick. This is especially of great consequence when the power source no longer supplies potential but the previous tick's frequency and potential are still normal.
To fix this, I include whether or not the power source `should_provide_output` in the `output_within_normal_parameters` function. `should_provide_output` is always up-to-date …
=> fix(elec): lack of power not detected in same tick

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes discord issue
- Remove rounding inadvertently applied to BARO and RADIO during review fixes.
- Remove ILS check for RADIO (that's already in the UI code, but a slightly different check, don't want a disagreement)
Honeywell Step1A data formats.
On PERF APPR:
- Ensure values in BARO and RADIO fields are not rounded to nearest 10 feet
- Ensure RADIO height (DH) can be entered when an ILS approach is selected in the flight plan
=> fix(mcdu): do not round baro/radio, remove ILS check on PERF APPR

.github/CHANGELOG.md, A32NX/ModelBehaviorDefs/A32NX/Airbus.xml, A32NX/ModelBehaviorDefs/A32NX/AirlinerCommon.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
This adds integral illumination to the RMP knobs as seen on never RMP panels.
- added illumination for the RMP volume knobs controlled by integral light knob with the rest of pedestal integral lighting
- reduced the brightness of the RMP volume knobs when selected or with the annunciator test light on by a small amount
Thanks to @Benjozork and @NathanInnes for helping out!
Brightness comparison :
Discord username (if different from GitHub): Imenes#8739
Make sure RMP volume knobs illuminate on both sides with the pedestal integral light knob and that they illuminate more brightly when the annul test light is on or they are pulled out. …
=> feat(RMP): add illumination to the RMP volume knobs

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #4093
- Route reserve weight is now calculated from trip weight rather than block fuel.
- retrieving extra fuel now correctly removes or adds route reserve weight to it's calculation depending on if the plane is flying or not.
- Minimum Destination FOB now update at the correct sequence when using fuel planning
- Pegasus Step 1A (Rev 0), 2009 edition manual
Lucky38i
For Testers, verify the following:
- After entering block fuel/using fuel planning, try to change the reserve fuel percentage, confirm the extra fuel changes
- MinDestFob is Alternate Fuel + Final Fuel.
- After entering block fuel, default route reserve weight is 5% of trip weight, if not ignore, this is instead 5 minutes of holding fuel.
Every new commit to this PR will cause …
=> fix(mcdu): revise route reserve calculation

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes the ACP CALL button green indicators to be independent of the integral light knob position, while the text is still controllable by the integral knob.
BEFORE:
https://user-images.githubusercontent.com/71195324/112672181-7887bc00-8e63-11eb-890e-5265552f2acd.mp4
AFTER:
https://user-images.githubusercontent.com/71195324/112672149-6d349080-8e63-11eb-89bf-56c010f45f8a.mp4
Noticed this bug while working on volume knobs, this should hopefully fix it.
Discord username (if different from GitHub): Imenes#8739
Confirm that the ACP CALL buttons now light up with ANN LT on, regardless of the integral light knob. 
1. On …
=> fix(ACP): correct CALL buttons behaviour when ANN LT is on

README.md
Updates the Readme.md to include the new custom autopilot build instead of the custom fbw build
Discord username (if different from GitHub): Nyhmbo#9999
=> docs: update readme to include custom autopilot build

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
makes holds show as inop until they can be properly flown
should reduce the amount of questions why they don't work but can be inserted
Discord username (if different from GitHub): Nyhmbo#9999
spawn, load a flightplan, insert a hold
=> fix: make holds inop

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.css, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Partial fix for known issue under custom AP/FBW branch.
Refer to previous #4214 for more details
The values for N2>100 are only visible with the custom AP/FBW at the moment, which is why the glitch went unnoticed.
Fixed-
Discord username (if different from GitHub): sidnov#8337
1. Spawn at a runway.
2. Observe variations to N2 value on EWD/ Upper ECAM by changing thrust, especially values above 100.
3. Make sure alignments remain uniform throughout the testing, and there is no overlap.
1. Click on the **A32NX** download link at the bottom of the …
=> fix(ecam): fix EWD N2 overlap >100 and code cleanup

.github/CHANGELOG.md
Updated the glareshield leather, ipad holder is clean plastic, tray table dirt is removed, overhead has darker AO and less green reflection, push buttons are more dark on AP panels and overhead panels
@MoreRightRudder (Mike)#7453
Observe ipad holder, tray table, and overhead panels in various lighting conditions.
Check black push button switches.
Check glareshield leather.
Check the rest of the cockpit for any errors. Thanks!
=> fix(textures): textures-v3 updated glareshield leather, ipad holder, tray table, overhead, and push buttons

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js
Solves an edge case where before when exactly at 200nm neither early descent nor normal descent would have activated.
Following FCOM normal descent start < 200 nm from destination, hence early descent start 200 >=.
=> fix(fmgc): fphm early descent initiation

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js
Fixes #4328 
When the navigation mode is not GPS Primary (i.e. ADIRS is not fully aligned), line 5R of the progress page displays nothing. When it is (i.e. ADIRS is fully aligned), "GPS PRIMARY" is shown in green. 
ADIRS not aligned:
Aligned (Line 5R shows the same thing as before this PR):
Step 1A manual prog page chapter
Discord username (if different from GitHub): NONAmr2433#8777
- When spawning in C&D, line 5R of the progress page shouldn't say GPS PRIMARY until the ADIRS is fully aligned
- It should disappear with the GPS PRIMARY LOST scratchpad message and appear with the GPS Primary message
1. On the left …
=> feat(mcdu): Progress Page line 5R only shows GPS Primary when it is available

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ADIRS.js
In the [video supplied by Parorng[Z+7]#4524](https://discord.com/channels/738864299392630914/739225362642501672/825628162271477760) the ON BAT light doesn't activate until approx. 10.5 seconds after the ADIRS selectors are moved to the NAV position. Adjust the ADIRS on bat timer to match this.
https://discord.com/channels/738864299392630914/739225362642501672/825628162271477760
Power up aircraft, and switch an ADIRS on. Observe 10.5 second delay until ON BAT light illumination (note, alignment time is not affected), and 5 seconds later extinguishment. …
=> fix(adirs): delay "on bat" activation

package.json, scripts/fragment.js
Add new modules to reduce the size of `base` which is downloaded every time. This leads to a size reduction from 28MB to 92KB. The new module `MarketplaceData` 27MB in size and should rarely change. The new `Panels` module is 550KB in size.
N/A
N/A
N/A
N/A
=> build: improve fragmenter modules

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/DisplayUnit.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/MFD/A320_Neo_MFD.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/PFD/A320_Neo_PFD.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/PFD/A320_Neo_PFD.js
Fixes #945
Display units run a self-test. This self-test should only be executed when the display unit was unpowered for 10 seconds or more.
Additionally this PR also fixes an issue I uncovered where turning on the chrono (shown on the MFD) with the DU off wouldn't turn the chrono on until the DU was turned on. Now the chrono runs irrespective of the DU being powered or not.
@komp1821 posted a video showing the behaviour which can be found [here](https://discord.com/channels/738864299392630914/754851312306487326/758257387432968222).
In some instances the original screen content still appears for a brief instant when turning the display unit on. This was already happening before this PR, and isn't fixed by this PR.
- For each …
=> feat(du): self-test only when unpowered over 10 seconds

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_RMP.xml
This enables the small round LED lights next to the RMP push buttons to illuminate when testing the annunciator lights.
Thanks, @davidwalschots for the help on this one.
- Test if the LED lights illuminate when the Annunacatior light test is performed.
- Check for any unexpected behavior and previously implemented functionality is still there. 
=> feat(RMP): enable RMP LED indicators when testing ANN lights

.github/workflows/experimental.yml, .github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, src/instruments/src/EFB/tailwind.config.js
* Only enable tailwindcss purging in production to improve build times.
* Ensure EFB works properly and does not have UI glitches
=> build: only enabled tailwindcss purging in production

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavaidPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_WaypointPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCDataManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
The data manager sometimes returns the same waypoint/navaid more than once in result list. This was worked around previously by a filter on the duplicate names page, after we'd already decided to show that page which sometimes resulted in us showing that page with only one option (see https://github.com/flybywiresim/a32nx/pull/3752#issuecomment-817873934). I have implemented a filter in the FMC instead, so it can check properly the de-duplicated list before deciding if the duplicate names page is needed. I changed the criteria to the `icao` field matching as this identifies unique waypoints/navaids/airports/etc. in the MSFS database, rather than simply comparing locations.
Additionally there are quite a few pages that use GetOrSelect*ByIdent will not return to the correct page when the …
=> fix(mcdu): Duplicate waypoints page callback

igniter.config.mjs
* Uses builtin functionality of igniter (that is already used in the build steps of instruments/model/behavior) to skip building of the fbw/autopilot/fadec when nothing has changed.
=> build: skip fbw and fadec builds if nothing changed

docs/README.md, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h, src/fbw/src/model/AutopilotStateMachine_data.cpp, src/fbw/src/model/AutopilotStateMachine_types.h
Fixes #4622
This PR adds support for the key event `AUTOPILOT_ON` to engage the autopilot. The logic is as follows:
- for the event to be effective, engage condition for the AP must be valid (once > 100 ft RA, > 5 s after lift-off)
- when no AP is engaged, AP1 engages
- when one AP is engaged and LAND mode is armed or engaged, the second AP is added
This is no IRL event, so behavior cannot be compared.
=> feat: add support for AUTOPILOT_ON event

README.md
This PR is partly a duplicate to #4205 and should be closed should #4205 get merged before this PR.
It updates the name of the aircraft folder, mentioned in the installation section of the readme to prevent future issue like [this one](https://github.com/flybywiresim/a32nx/discussions/4659#discussion-3345602).
I make this PR because #4205 seems to still take a while.
Discord username (if different from GitHub): `ExampleWasTaken#0886`
=> docs(readme): update aircraft folder name in readme

src/instruments/src/PFD/FMA.jsx
* Removes unused lvar and replaces it with the correct one, see https://github.com/flybywiresim/a32nx/pull/4555#issuecomment-830871338 for the issue it fixes
Note that this feature is not used yet, this is only for when #4555 adds it.
* No testing needed, this feature is not used yet.
=> fix(PFD): dont display presel speed when autothrust message is displayed

src/fbw/src/model/FlyByWire.cpp
This PR improves the state machine to determine if A.FLOOR should be inhibited. The A.FLOOR inhibit is now always triggered when the aircraft is on ground and not only when it was at least above 100 ft RA before.
This is hard to test and usually should barely happen, but on ground alpha sometimes reaches very high values (i.e. 170°).
Fix a potential situation where A.FLOOR is not inhibited correctly, i.e. after using slew being shortly just above ground but not reaching higher than 100 ft RA and then going back to ground again.
- Try with extreme wind on ground
- Try from C&D
- Try after spawning on the runway
- Try after landing
- Try after using slew …
=> fix: ensure that on_ground always inhibits alpha floor (e.g. after using slew)

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_Handling.xml, src/fbw/build.sh, src/fbw/src/ElevatorTrimHandler.cpp, src/fbw/src/ElevatorTrimHandler.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/RateLimiter.h, src/fbw/src/RudderTrimHandler.cpp, src/fbw/src/RudderTrimHandler.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/interface/SimConnectInterface.h, src/fbw/src/model/FlyByWire_data.cpp, src/fdr2csv/src/FlightDataRecorderConverter.cpp
This PR introduces custom handling of rudder trim and elevator trim.
The rudder trim now features a much more close deflection rate than it was before. It also has a realistic reset rate which is slightly different than the deflection rate (1.5°/s vs. 1.0°/s).
The elevator trim now stops the trim wheels when end position is reached. Before this PR using the events the wheel was continuing to move. The change rate when using events has been reduced for finer control on ground.
- rudder trim switch is only operational when AP is off
- rudder trim moves by 1.0°/s when switch is operated
- rudder trim moves by 1.5°/s when reset switch is pressed
- rudder trim can be operated between L 20° and R 20°
- elevator trim can be operated between 4.0 DN and 13.5 UP
The following items are not modelled …
=> feat: improved and custom rudder and elevator trim

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/SAI/A320_Neo_SAI.js
This reverts commit 4eea0e70433019ca8893859545e5a7f8e612051b.
The PR contained a bug where the + and - buttons always emit light, even when AC 1 isn't powered.
The PR uses a template that isn't currently suited for handling this type of button.
=> revert: isis brightness buttons push&hold (#4736)

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h
Fixes #4795
This PR improves the following transitions in the autopilot around LAND modes (G/S*, G/S, LAND, FLARE, ROLLOUT):
- when HDG knob is pulled G/S now correctly reverts to V/S (fix for #4795)
- V/S knob can now be pulled to exit G/S
- ALT knob can be pulled or pushed to exit G/S
- to engage LAND track mode radio altitude must be 1.2 s below 400 ft
- to engage RWY the SRS mode must be engaged 0.9 s
- disengage AP1+2 on go around after either lateral or vertical GA mode disengages and not directly on go around engagement
- disengage autopilot when applying go around on ground
- do not allow V/S knob to be pushed in LAND modes
Videos from my own testing:
- https://youtu.be/DcrRhIiYvm8
- https://youtu.be/k7ghKZMPa7I
- https://youtu.be/9fX2JA3QC34
- https://youtu.be/hPVWpcV_wVk
- …
=> fix: #4795 and other transition improvements

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fbw/src/model/AutopilotStateMachine.cpp
This PR allows to push V/S knob during APPR mode.
While the FCOM is only talking about pulling the V/S knob to exit APPR mode (to be more specific: the G/S* and G/S mode), IRL pilot feedback was that it's also possible to push the V/S knob to level off.
- fly an approach and try if you can level off using V/S knob push when in G/S* or G/S
- in LAND, FLARE and ROLLOUT this is inhibited
=> feat: allow V/S being pushed to level off in APPR

src/systems/a320_systems/src/electrical/alternating_current.rs, src/systems/a320_systems/src/electrical/direct_current.rs, src/systems/a320_systems/src/electrical/mod.rs, src/systems/systems/src/apu/mod.rs, src/systems/systems/src/electrical/battery_charge_limiter.rs, src/systems/systems/src/electrical/mod.rs
Goal is to expose `A320Electrical.in_emergency_elec()` so this information can be used by the hydraulic system. The logic which determines if the aircraft is in an emergency electrical situation was scattered in various places. Now unified in `EmergencyElectrical` type which no longer is exclusive to the battery charge limiter.
Everything was and is covered by extensive automated tests. No manual testing is necessary.
=> refactor: emergency electrical logic for hydraulics

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js
Similar to #4629 the returned weather report is blank when no airport was specified on request. This PR fixes this issue in that it cancels the request when no airport is specified and displays `NO AIRPORT SPECIFIED` in the scratchpad.
- Check that weather cannot be requested when no airport is entered in the above fields and you get a `NO AIRPORT SPECIFIED` message in the scratchpad.
- Make sure that weather can be requested if the the upper two fields are automatically  filled in with the departure and arrival airport.
1. On the left side, click on the bottom **PR** …
=> fix(mcdu): empty weather request

.github/CHANGELOG.md, Cargo.lock, src/systems/a320_systems/Cargo.toml, src/systems/a320_systems/src/electrical/alternating_current.rs, src/systems/a320_systems/src/electrical/direct_current.rs, src/systems/a320_systems/src/electrical/galley.rs, src/systems/a320_systems/src/electrical/mod.rs, src/systems/a320_systems/src/hydraulic.rs, src/systems/a320_systems/src/lib.rs, src/systems/systems/src/apu/air_intake_flap.rs, src/systems/systems/src/apu/electronic_control_box.rs, src/systems/systems/src/apu/mod.rs, src/systems/systems/src/electrical/battery.rs, src/systems/systems/src/electrical/battery_charge_limiter.rs, src/systems/systems/src/electrical/consumption.rs, src/systems/systems/src/electrical/emergency_generator.rs, src/systems/systems/src/electrical/engine_generator.rs, src/systems/systems/src/electrical/external_power_source.rs, src/systems/systems/src/electrical/mod.rs, src/systems/systems/src/electrical/static_inverter.rs, src/systems/systems/src/electrical/transformer_rectifier.rs, src/systems/systems/src/engine/leap_engine.rs, src/systems/systems/src/engine/mod.rs, src/systems/systems/src/landing_gear/mod.rs, src/systems/systems/src/pneumatic/mod.rs, src/systems/systems/src/shared/mod.rs, src/systems/systems/src/simulation/test.rs
Primarily makes the ENG FIRE push button affect the IDG's ability to provide energy.
This PR doesn't improve the inner workings of the IDG. There are still a lot of possible improvements in this area.
Next to the main feature of the PR, it also addresses some other things.
3c82c3d1075b7c3760350e98fde80cdd922afab4: moves the `EngineFireOverheadPanel` out of hydraulics so it can be used elsewhere.
8378f1d75f312323189c3f8e57fdf9c345a0fca4: as I was adding tests for the fire push button's effect on the electrical system I got fed up with some of the duplication and thus introduced parameterised tests.
265d99627087af4f743159dae6ce1137ca17a582: The effect of the fire push button on the contactors.
623cfa989b9522d99a5678d9aec96d1772a5cba3: Preparing to share the fire push button state with the …
=> feat(elec): eng fire and gen buttons affect idg

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #4789
- Fixed descent initiation condition where it was impossible to enter descent phase (+200nm and below FL200)
- Fixed `NEW CRZ ALT - AAAAA` message appearing constantly
- Fixed descent initiation not able with FPA mode.
Perform a flight as per usual and use the following functionalities:
- During climb increase the fcu target alt in steps, then set last fcu alt 2000ft higher as originally set/defined cruise altitude
_Setting the fcu alt 2000ft higher as crz alt will result in the message `NEW CRZ ALT - AAAAA`_
- After reaching your newly defined cruise altitude, perform a step climb
- Perform an early descent, descent initiation 200nm away from your destination
Every new commit to this PR will cause a new A32NX artifact …
=> fix(fmgc): descent initiation and crz fl change

.github/CHANGELOG.md, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp
This PR improves the speed hold characteristic of OP CLB/DES and CLB/DES modes. Especially on (OP) CLB there was a small offset in speed hold. This should be solved now.
- fly normal flights and check if OP CLB/DES works properly
- fly also in turbulence and check if it's acceptable (also in comparison with previous version)
=> feat: improved OP CLB/DES, CLB/DES speed hold characteristic

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
Added correct emissive behavior for the ECAM EMER CANC button. Both the button and the text now light up depending on the pedestal integral light setting.
Discord username: Imenes#8739
Check the EMER CANC button behavior, you should only be able to turn the backlighting on when AC power is available like the rest of pedestal integral lighting. Make sure that the button still has its previous functionality (open cover, press in).  
=> feat(ECP): EMER CANC emissive behaviour

.github/CHANGELOG.md, src/instruments/src/SD/Pages/Fctl/Fctl.tsx
* Change F/CTL page hydraulic indications to use the hydraulic system simulation
* Pitch trim direction indication is not displayed when pitch trim is between -0.05° and 0.05°
* Visual changes to spoiler indication: 
* Increase size of numbers when pressure is low
* Display triangle indication in amber even when pressure is low and spoiler is deployed
* Make sure that the F/CTL indications behave as described above
* Make sure that the F/CTL hydraulic indications behave as expected
1. Click on the **A32NX** download …
=> feat: F/CTL page hydraulic indications, small misc changes to F/CTL page

.github/CHANGELOG.md, docs/a320-simvars.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml, src/behavior/src/A32NX_Exterior.xml, src/fbw/build.sh, src/fbw/src/AnimationAileronHandler.cpp, src/fbw/src/AnimationAileronHandler.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/SpoilersHandler.cpp, src/fbw/src/SpoilersHandler.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/instruments/src/SD/Pages/Fctl/Fctl.tsx
Fixes #4805
This PR introduces **visual** aileron droop and anti-droop function:
- the ailerons are drooping 5° down on both sides when flaps are extended
- the ailerons are anti-drooping when ground spoilers are fully applied / deployed (not on partial deployment)
Visual means that the droop and anti-droop of the ailerons is visible on the 3D model and on the FCTL SD page but it's not visible in simulation variables and also has no impact on the flight model.
https://www.youtube.com/watch?v=fEyOEUGiBi0
https://www.youtube.com/watch?v=CmHPzIs38sY
- test if ailerons move properly in normal flight and with AP on and off
- test if ailerons droop with flaps (and only with flaps)
- test if ailerons anti-droop when **all** of the following conditions are true:
- ground spoilers fully deployed …
=> feat: aileron droop and anti-droop

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/model/AutopilotLaws_data.cpp, src/fbw/src/model/AutopilotLaws_types.h, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h, src/fbw/src/model/AutopilotStateMachine_data.cpp, src/fbw/src/model/AutopilotStateMachine_types.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp, src/instruments/src/PFD/FMA.jsx, src/instruments/src/PFD/style.scss
This PR adds:
- triple click and blinking of white box on FMA due to mode reversions
- automatic arm of NAV when on ground and flight plan becomes available
- automatic connection of flight directors on FCU power-on (no simulation of FCU startup-procedure)
According to FCOM the following cases need to be considered.
- `NAV` is lost (manual or automatic): reverts to `OP CLB`
- when not confirmed within 5s with
- FCU ALT change
- V/S push
- V/S pull
- engage of another vertical mode
- triple click and white box blinking for 10s
- `NAV` is lost (manual or automatic): reverts to `V/S`
- when not confirmed within 5s with
- FCU ALT change
- V/S push
- V/S pull
- engage of another vertical mode
- triple click and white box blinking for 10s
- in `OP CLB` and FCU altitude is changed below current …
=> feat: added FMA triple click mode reversion logic + automatic NAV arm on ground + connect FDs on FCU power on

docs/a320-simvars.md, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h
This PR adds a local variable to tell if ground spoilers are active/fully deployed. This information is needed for the upcoming work of custom auto brake implementation.
This is by intention not added to changelog because it's implementation details and a non-visible feature to the user.
- test if variable `A32NX_SPOILERS_GROUND_SPOILERS_ACTIVE` goes to 1 when ground spoilers are fully deployed.
=> feat: added lvar if ground spoilers are active

package.json, scripts/setup.sh, src/instruments/src/EFB/webpack.development.config.js, src/instruments/src/EFB/webpack.msfs.config.js
Removes `--legacy-peer-deps ` from `setup.sh`.  Fixes peer dep errors with tabler-icons.
Removes and replaces `awesome-typescript-loader` with `ts-loader`. This was done since `awesome-typescript-loader` is now marked legacy.
Discord username (if different from GitHub): blurpyx#2092
Make sure everything works fine, especially the EFB.
=> build: remove legacy deps and peer deps 🚀

package.json, src/instruments/src/EFB/Dashboard/Dashboard.tsx, src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx, src/instruments/src/EFB/Settings/Settings.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
Fixes #4761
PR is to address the missing icons in the EFB Map. This has been done with the introduction of @flybywiresim/react-components, as well as this I've updated the Slider and Toggle components which were also migrated across to the component library.
* Added @flybywiresim/react-components
* Swapped and removed @flybywiresim/map for @flybywiresim/react-components in EFB Dashboard
* Replaced Slider and Toggle components with @flybywiresim/react-components
Open the EFB, view the map, make sure that the icons are in the control panel in the bottom right of the map. …
=> fix(efb): Fix for missing icons in EFB Map

package.json
Fixes build errors with broken v0.2.9 `react-components`.
Discord username (if different from GitHub): blurpyx#2092
=> build: quick fix for component errors 🎉

.github/CHANGELOG.md, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/SpoilersHandler.cpp, src/fbw/src/SpoilersHandler.h, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h
This PR improves:
- the `AP` and `ROLL OUT` mode disengage / disconnect conditions
- the ground spoiler logic
- disconnect when Pitch attitude > 25°
- disconnect when Pitch attitude < -13°
- disconnect when Bank angle > 45°
- disengage when flight phase `DONE`
- disengage when on ground more than 10s and `APPR` is pushed on FCU
- disengage when runway heading from ILS to aircraft track is > 7° (remark: on slow speed aircraft heading is used due to unreliable track info from the sim)
- ground spoilers are now also deploying when they are not armed and both levers in reverse
- the logic now uses ground speed and not CAS
This PR uses information from FCOM.
If AP and ROLL OUT mode is disconnected in flight phase done is not fully clear (no documentation found), but looking at YouTube videos …
=> feat: improved ROLLOUT and AP disengage conditions + improved ground spoiler logic

.github/CHANGELOG.md, src/fbw/src/model/Autothrust.cpp
Fixes #5020
This PR fixes the incorrect activation when A/THR disconnect buttons have been used.
- test if in flight when thrust levers are in CLB detent with A/THR engaged in SPEED and you disconnect A/THR using FCU button THR LK appears on FMA and thrust is kept on current level
- test if in flight when thrust levers are in CLB detent with A/THR engaged in SPEED and you disconnect A/THR using red disconnect buttons on thrust levers thrust immediately go to level defined by TLA
=> fix: corrected THR LK activation (#5020)

.github/CHANGELOG.md, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/model/Autothrust.cpp, src/fbw/src/model/Autothrust.h, src/fbw/src/model/Autothrust_data.cpp, src/fbw/src/model/Autothrust_types.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp
Fixes #5016
This PR introduces support for the normal procedure *NO FLIGHT DIRECTOR TAKEOFF*.
**Remark:**
This PR only covers the area of A/THR logic and nothing related to managed/selected speed management.
FCOM PRO-NOR-SRP-01-30
For the following checks no actual take-off is needed
- on ground, FMGC flight phase 0, disable both FD, set levers to TOGA: no FMA indication, thrust limit TOGA applied
- on ground, FMGC flight phase 0, disable both FD, set valid FLX temperature, set levers to FLX: no FMA indication, thrust limit FLX applied
- on ground, FMGC flight phase 0, both FD enabled, set levers to TOGA: FMA indication, thrust limit TOGA applied
- on ground, FMGC flight phase 0, both FD enabled, set valid FLX temperature, levers to FLX: FMA indication, thrust limit FLX applied
This part …
=> feat: support FD off take-off procedure (#5016)

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fbw/src/model/AutopilotStateMachine.cpp
This PR improves managed speed and V2 validity.
The managed speed validity is improved. This leads to managed speed in cold and dark or spawning on the runway without an entered V2 to selected speed with default 100 kn. Managed speed cannot be engaged until a V2 is entered. This has no impact on the availability in flight when AP is engaged or when in approach phase.
As outlined, when a flight without V2 entered is performed, the managed speed can be used in FMGC approach phase, but when FMGC changes in done phase, the managed speed reverts to selected speed (below 100 kn it will be 100 kn).
The V2 is now assumed valid when equal or greater than 90 kn.
The FMA speed protection for V/S or FPA mode is only shown blinking in amber and a triple click when the AP is engaged. When manually …
=> feat: improved managed speed validity + VS speed protection and LOC/GS arm fix

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fbw/src/model/FlyByWire.cpp
This PR is about FCU initialization and in flight start experience
The high alpha protection and alpha floor is now inhibited for 10s after flight start or plane reload. This allows the plane to settle values and filters and avoids unnecessary triggering of alpha floor and alpha protection law.
- SPD = 100 kn
- HDG = 0°
- ALT = 100 ft
- SPD = current speed rounded to 1 kn
- HDG = current heading rounded to 1°
- ALT = current altitude rounded to 100 ft
- V/S = current V/S
Remark:
1. The V/S part showing +0000 is left out because it's unclear when and based on which condition on ground this changes to dashes. This will be fixed in an upcoming PR when this is clear.
2. When starting in flight, the speed sometimes changes quite fast without the user seeing it (bc the PFD is not yet shown), …
=> feat: init FCU with correct default values and improved flight / plane load for alpha protection

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #4635
- Added additional check for current performance page and current flight phase
- Fixed page refresh when when having next flight phases performance page open before flight phase transition into next phase
e.g. flight phase descent, performance page approach -> flight phase transition into approach -> performance page didn't reload (now reloads)
Any flight phase transition observe performance page is updated on every phase change.
Best example to test with:
From phase DES into APPR.
Go to performance page APPR during DES phase.
When reaching DECEL waypoint and FMGC transitions to flight phase approach -> monitor performance page reload (prev page indication and action will disappear)
Use managed speed mode and monitor …
=> fix(mcdu): performance page refresh on flight phase transition

src/instruments/src/Common/persistence.tsx
Fixes #5110
This addresses an issue where the value 0 would not be saved to persistent storage because it is considered falsy in JS. Consequently, when the refuel rate was set to "Real" on the EFB, this was encoded as a 0 and not saved properly, so when the plane was reloaded, the incorrect refuel rate was selected. Additionally, I noticed that the "PTU audible in cockpit" setting was also not saved properly due to the same issue. This has now been fixed.
1. Load up the airplane anywhere (cold & dark or not)
2. Set the refuel rate on the EFB to **something other than "Real"** and turn "PTU audible in cockpit" **on**.
3. Restart the flight and make sure both values were as you set them before reloading.
4. Now, set the refuel …
=> fix: Fix falsy SimVar values not being persisted properly

docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Added 5 simvars which reflect the state of FCU indicators, primarily those for managed modes. This applies to managed speed/mach, managed heading (with separate variables for managed and managed OR armed), managed altitude, and managed vertical speed/FPA.
These simvar calls occur in the `refresh` method of the FCU classes, which are only called when the value changes, so the simvar is only changed when the value updates (rather than every frame). Therefore, there is no effect on performance.
N/A
Discord username (if different from GitHub): Iceman#5540
No QA testing is necessary.
1. On the left side, click on the …
=> feat: Add autopilot simvars for FCU hardware use

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #5226
Improved initialization of the flight phase manager.
- `A32NX_FlightPhaseManager` get constructed immediately and updates the flight phase based on flt state or defaults to preflight if not defined (this has not been changed)
- `A32NX_FlightPhaseManager` now has it's own init to initialize the initial flight phase which may need additional fmgc data which has not been processed, therefore the `flightPhaseManager.init()` is placed at the bottom of the fmgc initialization.
Spawn on apron, runway, mid flight and approach and check for correct flight phases. (use the Prog and perf pages)
And also ensure that everything is working as normal.
- apron and runway: observe prog page shows TO and take off page is not green,
- mid …
=> fix(fmgc): flight phase initialization

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #5275
Adds `AC1 BUS` to `FCU LED DISPLAY` so its backlight is off and unlit when aircraft it unpowered.
Correct bus verified by Joeri [Z+2] (engineer) @ #pilot-feedback
Discord username (if different from GitHub): bouveng 
1. Spawn C/D
2. Verify that the `FCU LED DISPLAY` backlight not is controllable by potentiometer.
=> fix: FCU LED display power

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
This PR reverts #5276 
@davidwalschots 
=> revert: FCU LED display power fix

src/instruments/README.md, src/instruments/buildSrc/browserBuild.mjs, src/instruments/buildSrc/directories.mjs, src/instruments/buildSrc/igniter/tasks.mjs, src/instruments/buildSrc/plugins.mjs, src/instruments/buildSrc/simulatorBuild.mjs, src/instruments/buildSrc/templatePlugins.mjs, src/instruments/ecam-page-template/rollup.js
Couldn't build instruments in watch mode on Windows using the changes introduced in  #4750. This PR enables multi-platform file path support.
No need to test by QA. Maybe a developer can test on their non-Windows environment if it still work as expected 😀.
=> feat(build): multi-platform file path support

README.md
Updated Known Issues text to be more relevant.
Removes old already fixed known issues (i.e. #974), updates this to the more frequent known issues/support requests and links to the github issues page. 
- Captain's PFD may occasionally turn off during flight
- No Smoking switch doesn't use a full range of motion.
- Automatic ECAM page switching has minor bugs.
- AP not following the flight plan (leaking input values affect, but don't disconnect the AP) [Workaround: Set dead-zones for your input device higher]
- Autopilot goes direct to RWY on APP (same with the default A320) [Workaround: Use DIR to a waypoint or selected heading]
- Upper ECAM displays wrong THR levers position / N1 rating.
- Newly added ASOBO A320 liveries are incompatible with the A32NX mod.
- Rudder …
=> chore(readme): updated known issues to be more up-to-date with latest dev progress

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
=> fix: wiped flight plan when approach begins

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Fixes various waypoint indexing weirdness in the flight plan page causing waypoint/discontinuity deletion to fail.
=> fix: discontinuities/waypoints not clearing

src/fbw/src/FlyByWireInterface.cpp
* This adds missing assignments to StateMachineOutput that were forgotton to add in #4985.
* This only affects the usage of the FBW/AP system in combination with Simulink. No user facing changes.
No normal testing possible
=> fix: Add missing StateMachineOutput assignments

.github/auto-merge.yml
Configures the auto-merge bot.
This will automatically merge PRs when they have at least one approval and the "Auto Merge" label.
This should only be used when one does not want to wait for a CI build to finish.
=> ci: auto-merge bot config

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css, src/behavior/src/A32NX_Interior_MCDU.xml, src/instruments/src/ATC/style.scss, src/instruments/src/BAT/style.scss, src/instruments/src/Clock/style.scss, src/instruments/src/Common/pixels.scss, src/instruments/src/DCDU/style.scss, src/instruments/src/PFD/style.scss, src/instruments/src/RMP/style.scss, src/instruments/src/RTPI/style.scss
:closed_book::green_book::blue_book:
This PR adds **pixels** to the following screens:
- `PFD` - pixels, tint and subtle backlight bleed
- `ND` - pixels, tint and subtle backlight bleed
- `EICAS 1 + 2` - pixels, tint and subtle backlight bleed
- `DCDU 1 + 2` - pixels (checkered), tint
- `SAI/ISIS` - pixels, tint
- `FCU/MCDU` - pixels, tint
Large screens have a subtle blue tint and a small backlight bleed that can be seen in the dark in a favorable setting (dark and high intensity setting).
DCDU screens have a light white tint and a checkered large pixel pattern.
<p align="right"><i>MCDU, SAI/ISIS, letters and WX.<br/>(watch images at 100% to see effect properly)</i></p>
<p align="right"><i>Subtle small backlight bleed can be seen on the large screens in favorable settings (dark and high …
=> feat(displays): Add pixelated screens

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/data/flightplan.ts, src/fmgc/src/guidance/ControlLaws.ts, src/fmgc/src/guidance/Geometry.ts, src/fmgc/src/guidance/GuidanceManager.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts, src/fmgc/src/guidance/lnav/legs/TF.ts, src/fmgc/src/guidance/lnav/legs/VM.ts, src/fmgc/src/guidance/lnav/legs/index.ts, src/fmgc/src/guidance/lnav/transitions.ts, src/fmgc/src/types/fstypes/FSTypes.d.ts, src/fmgc/tsconfig.json, src/instruments/src/ND/elements/FlightPlan.tsx, src/instruments/src/ND/elements/ToWaypointIndicator.tsx, src/instruments/src/ND/elements/WindIndicator.tsx, src/instruments/src/ND/index.tsx, src/instruments/src/ND/pages/ArcMode.tsx, src/instruments/src/ND/pages/PlanMode.tsx, src/instruments/src/ND/pages/RoseMode.tsx, src/instruments/src/ND/utils/MapParameters.ts, src/instruments/tsconfig.json, src/shared/src/MathUtils.ts, typings/fs-base-ui/html_ui/JS/simvar.d.ts
This is an initial refactoring of leg building and flight path rendering.
* Legs are now declared in `guidance/lnav/legs`.
* Multiple leg geometry now generates transitions (still hard-coded to Type I) for all legs in the flight plan.
* This allows us to use a simple reverse-iteration instead of having different / repeated logic for different legs or transitions.
* Leg and transition indices in Geometry are now different. Transition at index n is now the transition after leg at index n.
* The flight plan rendering code has been cleaned up to match the reverse iteration for geometry generation, and not contain special edge cases for first / second leg / transition.
Additionally, the following changes have been introduced to help the refactor:
* VM legs are now generated from waypoints for …
=> feat(fpm, lnav): refactoring of flight path building / rendering. add support for VM legs

src/systems/a320_systems_wasm/src/lib.rs, src/systems/systems/src/simulation/test.rs, src/systems/systems/src/simulation/update_context.rs
Fixes #5395
In `a320_systems_wasm/src/lib.rs` #5242 added (merged yesterday 10:49Z):
```rust
reader.add("VELOCITY WORLD Y", "feet per minute", 0)?;
```
and #5159 added below it (merged yesterday 20:08Z):
```rust
reader.add("VELOCITY WORLD Y", "Feet per Second", 0)?;
```
Thus `feet per second` is read, whereas #5242 assumes `feet per minute`.
=> fix: vertical speed indication seems locked at 0 feet per minute

flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css, src/instruments/src/Common/displayUnit.tsx, src/instruments/src/Common/pixels.scss, src/instruments/src/PFD/index.jsx
Fixes #5390 #5397
Fixed a bug where `CPT PFD` was turned **off** by `F/O PFD` potentiometer.
Lowers the intensity of pixel effect to mitigate some of the moiré effect at lower resolutions.
Removes a pair of forgotten `console.log()`'s.
Discord username: @bouveng
1, turn down the `F/O PFD` potentiometer to 0%.
2, verify that `CPT PFD` still is on
=> fix(displays): Fix potentiometer bug - adjust pixel intensity

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cockpit.cfg, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/interface/SimConnectInterface.h
Fixes #5487
This PR introduces a workaround for the altimeter issues in MSFS.
The issue in MSFS is that the pressure altitude and indicated altitude
are not correctly calculated. Additionally when the barometer setting
is set to STD both altitudes are not equal.
The impact is that when sea level pressure changes the error between
pressure and indicated altitude varies. The autopilot is using the
pressure altitude as reference when in ALT HOLD mode. Due to this,
when flying through different pressure zones the AP will divert from the
altitude it should follow.
The changes that are made with this commit are as follows:
- add an additional altimeter (index 2)
- force this altimeter to baro setting STD
- use the indicated altitude as pressure altitude
This fixes the autopilot to divert from …
=> fix: workaround for #5487 in regards to altitude issues

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/cockpit.cfg
Under MSFS Sim Update 5, the external view HUD for the FBW A320 changed to a GA-airplane style HUD. This PR changes it back to an airliner style HUD.
Adds a new variable introduced by SU5 to indicated the style of HUD to display in the external view.
Before: 
After:
Discord username (if different from GitHub): donbikes#4084
The only thing that changed was to add a variable to the cockpit.cfg that controls which style of HUD is displayed in the external view. Switch back and forth between internal and external views.
1. Click on the **A32NX** download link at the …
=> fix: change external view HUD back to airliner type (SU5 compatibility fix)

README.md
The README was full of clutter and duplication when compared to our beautiful website. The download link for the stable release was also broken. So I decided to cut out a lot of stuff in hopes of keeping the content up to date.
=> docs(readme): reduce docs/website duplication

docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/interface/SimConnectInterface.cpp
Fixes #5479
This PR improves the event initialization between JS and WASM.
Up to now there was an issue since SU5 that caused the HDG pull to not work correctly right after the fbw wasm was compiled. The same applied to a not often used event to reset the ATHR state when it was been disabled after pressing ATHR disconnect for more than 15 s.
- delete the compiled wasm cache (above work folder)
- load updated A32NX and on first flight test if HDG pull is working
- setup a flight with start and end and on final press ATHR disconnect button for more than 15s -> this is permanently disable ATHR (can be seen also on local variable `A32NX_AUTOTHRUST_DISABLED`)
- after landing when FMGC resets (FMA goes from ROLL OUT to initial state with usually CLB …
=> fix(fcu): improved event initialization after wasm compilation

.github/CHANGELOG.md, src/systems/a320_systems_wasm/src/lib.rs
Fixes #5516
Longer delay to avoid retrigger. 
Drawback is you can't change autobrake setting for 1.5s after you first hit a button.
Check that all autobrake modes (except MAX in flight) can be armed when clicking buttons / using key bindings / using thrustmaster TCA quadrant.
Check that any armed mode won't disarm by itself after some time be it seconds or minutes (unless it's max mode self disarming after 10s airborne)
=> fix(hyd): fix tca autobrake button after SU5

flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_FCU.xml, src/behavior/src/A32NX_Interior_Fire.xml, src/behavior/src/A32NX_Interior_Generics.xml, src/behavior/src/A32NX_Interior_Handling.xml, src/behavior/src/A32NX_Interior_MCDU.xml, src/behavior/src/A32NX_Interior_Misc.xml
Additional changes to cockpit soundscape:
- all round-buttons, like chrono, calls, rudder trim, etc.. (except fire test and the three on the FCU) now have their own custom roundbutton sound event.
- Red sidestick button
- DCDU buttons
- MCDU brightness 
- Fire test buttons on the fire panel now have their own firetestbutton event (the same event is used for the sidestick AP disengage)
Credit for the custom wwise events goes to @hotshotp 
Discord username: Imenes#0001
Test all the buttons described above, and please also click all the square push buttons to make sure they don't play the new roundbutton sound but remain the same as they were before.
1. …
=> feat(sound): cockpit sounds part 4

.github/CHANGELOG.md, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/interface/SimConnectInterface.h
Fixes #5633
This PR fixes an issue with handling of events `RUDDER_AXIS_PLUS` and `RUDDER_AXIS_MINUS`. To do this it allows to disable XBOX controller compatibility for those axes.
This can be done by putting the file `ModelConfiguration.ini` with the following content into the work folder:
```
[flight_controls]
disable_xbox_compatibility_rudder_axis_plus_minus = true
```
Disclaimer:
I did not code-style clean up going along with this PR.
Test if you can assign independent axis to Rudder Axis Left and Right assignment and that it works as expected. The expectation is that one axis is from neutral to full left and the other from neutral to full right. If both axis are applied the same time the last wins.
⚠This PR needs to be tested with an XBOX Controller!
Every new commit to this PR will …
=> fix(fbw): improved handling of rudder axis plus/minus

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_MCDU.xml
Restores `PFD/MFD/EICAS/DCDU` and `MCDU` emissive brightness to sane levels.
This PR renders https://github.com/flybywiresim/a32nx/pull/5571 redundant.
<p align="right"><i>Normalized screen @100% potentiometer setting with subtle tint, bleed and dust.<br/>(watch image at 100% to see effect properly)</i></p>
Screens with **pixels** and **reflections** became _overpowered_, causing **bleed** and other strange **artifacts** during some of the following fixes and/or reflective screens.
Discord username (if different from GitHub): @bouveng
1. Spawn.
2. Try screens during day, night, during sunshine and overcast.
1. On …
=> fix(screens): Adjust emissive power for screens to sane levels

src/instruments/src/ISIS/ISISDisplayUnit.tsx, src/instruments/src/ISIS/style.scss
Fixes #5637
Adds back pixels to ISIS screen that was lost during react conversion.
<p align="right"><i>Before: no pixels</i></p>
<p align="right"><i>After: restored pixels (watch image at 100% to see effect properly)</i></p>
Discord username: @bouveng
1. Spawn
2. Move down and forwards as close to ISIS screen as possible.
3. Verify visible pixels
4. Verify that they disappear when moving back/zooming out
=> fix(screens): Restore pixels on ISIS

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #5574 
Closes #5595 
The strobe flashing post-SU5 was incorrect due to a missing xml parameter. (An interim PR to fix strobe flashing until the strobe sync PR by @bouveng  is ready)
**BEFORE:**
https://user-images.githubusercontent.com/29005005/129617835-c7b38f35-4b72-4fac-a99e-54c9c62e67ae.mp4
**AFTER:**
https://user-images.githubusercontent.com/29005005/129617899-bc59778d-4016-4620-b653-2767412e15b3.mp4
Discord username (if different from GitHub): sidnov#8337
Strobe switch set to OFF: No Strobe lights
Strobe switch set to Auto: No Strobe lights on ground, Strobe flashing on wheels up
Strobe switch set to ON: Strobe lights flash both on ground and on wheels up
Try with multiple departures, spawning on runway is fine. For best results, set time to night.
Every new commit to this PR …
=> fix: strobe flashing

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Fixes #5527 
Corrects a mistake in the designation of a local variable in the code to determine whether the autopilot is on or off.
Conduct landings with and without autopilot engaged. Verify that "retard" callout occurs just after the 20 foot radio altitude callout with autopilot off and just after the 10 foot radio altitude callout with autopilot on.
=> fix: Retard callout at 20 ft with autopilot off

.github/CHANGELOG.md, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/FlyByWire.cpp, src/fbw/src/model/FlyByWire.h, src/fbw/src/model/FlyByWire_data.cpp
This PR introduces the following improvements:
* allow to push V/S knob and therefore to level off during ALT*
* improved rudder / turn coordination when flying with AP off (especially with low speeds)
* fly with AP off with different speeds and check if turn coordination is working
* fly with AP engaged and check of turn coordination is working
* do manual landing with different wind conditions
* do autoland with different wind conditions
=> feat: V/S push in ALT* and improved turn coodination

src/fmgc/src/flightplanning/GeoMath.ts, src/fmgc/src/guidance/Geometry.ts, src/fmgc/src/guidance/GuidanceManager.ts, src/fmgc/src/guidance/lnav/legs/TF.ts, src/fmgc/src/guidance/lnav/transitions/Type1.ts, src/instruments/src/ND/elements/FlightPlan.tsx, src/shared/src/MathUtils.ts
* We change the sequencing method of Type 1 transitions. Instead of checking for both directed DTG to the TERM FIX and directed DTG to INP, we now simply check for directed DTG to ITP. This aligns with the system sequencing behaviour of the FMS, but NOT with the visual sequencing behaviour, which is less important right now.
* We make sure to also include the transition onto the active leg as part of the active path geometry, in order to guide along the transition after sequencing instead of guiding along the active leg
* Clean up various directed DTG calculations
* Ensure that sequencing works correctly with all leg types (try SIDs with MANUAL legs, try RNP approaches)
* Ensure there is no excessive sequencing
Every new commit …
=> fix(lnav): sequence type 1 at ITP, not INP

.github/CHANGELOG.md, src/.eslintrc.js, src/instruments/src/Common/displayUnit.tsx, src/instruments/src/Common/persistence.tsx, src/instruments/src/EFB/ATC/ATC.tsx, src/instruments/src/EFB/ChartsApi/Navigraph.tsx, src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx, src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx, src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx, src/instruments/src/EFB/Efb.tsx, src/instruments/src/EFB/Navigation/Navigation.tsx, src/instruments/src/EFB/Settings/Settings.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx, src/instruments/src/EFB/Settings/sync.ts, src/instruments/src/SD/Pages/Crz/Crz.tsx, src/instruments/src/SD/Pages/Eng/Eng.tsx, src/instruments/src/SD/Pages/Fuel/Fuel.tsx, src/shared/src/persistence.ts
The underlying Coherent datastore errors out when anything other than a
string is set.
Fixes #5722
Fixes  #5751
The Coherent datastore cannot store anything other than strings. Our typescript NXDataStore implementation was attempting to store numbers. The exception was being caught by the SetStoredData function in JS, which returned null, and we ignored that return value so the failure was silent.
Ammed the NXDataStore class to only take strings as it's type and adjust consumers to use strings. Hopefully we can come up with a solution later, but TS overloads don't seem to be useful here, and generics won't do it.
Additionally the SimVarSyncedProperty did not make a lot of sense, as it was attempting to sync in the opposite direction to what _all_ of the consumers desired. Use the new …
=> fix: NXDataStore cannot store numbers

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Pack sounds were still using MSFS APU speed variable, so the sounds were borked.
I did a grep for other stuff still using old APU vars and didn't find anything.
Check that pack sounds are working now on APU bleed.
=> fix: pack sounds use new apu speed variable

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic.rs
This is a simvar trigger used to generate specific high pitch PTU sound.
A32NX_HYD_PTU_HIGH_PITCH_SOUND will go to 1 whenever PTU is activated while there's a lot of pressure differential between green and yellow circuits.
This is a placeholder, will be removed when PTU new model handles this by design.
Simvar A32NX_HYD_PTU_HIGH_PITCH_SOUND should go to 1 whenever ptu is activated while there is more than 2700psi pressure difference between yellow and green circuits.
So it's expected to go 1 on second engine master on when the usual PTU self test is ran, or if EDP is shutdown on one side and ptu off, then ptu reactivated when pressure is close to 0 on the shutdown circuit.
Using PTU while just running yellow electric pump …
=> feat(hyd): ptu first start sound trigger simvar

.github/CHANGELOG.md, src/instruments/src/EFB/Failures/FailureButton.tsx, src/instruments/src/EFB/Failures/Failures.tsx
EFB Failure buttons now look a lot more neat. Also uses a grid pattern, as more failures are added these will conform to the grid automatically.
Discord username (if different from GitHub): AbsoluteNath#9406
Go to the Failures page in the EFB and check the buttons look neat and are in a grid 4 columns wide.
=> feat: grid-layout same sized buttons on failure page

src/instruments/src/PFD/AttitudeIndicatorFixed.tsx
This PR tweaks the height of the top-most yellow triangle near the top of the PFD that indicates 0 degrees roll.
Comparing it to references recently I found it significantly too tall, and have thus reduced it's height. See screenshots below.
Left is old, center is reference, right is new.
1. The changes are extremely minor and visual only. Nonetheless, start up as usual, make sure the PFD still works
2. In flight, roll a bit or reach extreme roll angles and confirm the triangle continues to be displayed as expected
1. …
=> fix(pfd): correct roll indicator triangle height

.github/CHANGELOG.md, src/systems/systems/src/navigation/adirs.rs
When the aircraft has less than 50 knots of ground speed, the IRSs should use the  current heading as track, which they currently do not. This commit fixes that.
This is especially noticeable when spawning in on the ground, or when pushing back, as the track bug at the bottom of the PFD might be not visible at all or initialized in a weird place.
Spawning or Pushback on Ground (**Old**):
The green track diamond at the bottom of the PFD is not visible because it is behind the aircraft or out of view.
Spawning or Pushback on Ground (**New**):
The green track diamond at the bottom of the PFD is forced to the current heading below 50 knots, which ensures it's always visible.
1) Video: https://www.youtube.com/watch?v=cv41hm4JEB8#t=16s
Notice how the green track diamond is visible at the center …
=> fix(adirs): use heading as track at low ground speeds

.github/CHANGELOG.md, src/instruments/src/PFD/SpeedIndicator.tsx, src/instruments/src/PFD/index.tsx
This PR fixes the case where the mach number is between 0.450 and 0.500 and the indicator in the bottom left flickers in same-speed flight. This was because it was using the computed airspeed trend to decide which threshold (0.450 and 0.500) to use. As an aircraft flying at a fixed speed will be kept at the speed by the autopilot modulating thrust downwards and upwards just a tiny bit, the trend was constantly switching between positive/negative. If the indicated mach number was at say 0.475, this would mean that it would constantly switch being above or below the threshold, causing flickering.
The new behavior is as follows:
- when the mach number was below .45, it stays hidden until increasing above .5
- when the mach number was above .5, it stays visible until reducing below .45
- …
=> fix(pfd): fix mach number flickering between mach 0.45 and 0.5

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
There are two places where the A320 has shown the cabin readiness in the past:
- the right column on the EWD, as a memo
- in the left column on the EWD as part of the T.O and LDG MEMO
After reviewing some references and footage, we think that CEOs originally only showed it in the right column, and eventually got an option to move it into the T.O/LDG MEMO instead. NEOs nowadays seem to always show it in the T.O/LDG MEMO, and the option does not really exist anymore.
In any case, showing the cabin readiness in two places seems nonsensical, and this PR drops the memo from the right column so that it's only showed in the T.O and LDG MEMO.
https://discord.com/channels/738864299392630914/817470205260726322/885981452800491531
Video showing an A21N landing with the cabin readiness only in the LDG …
=> fix(ecam): drop redundant CABIN READY memo

src/instruments/src/EFB/Components/Progress/Progress.tsx
Fixes issues detected by linting which popped up as `eslint-plugin-react` `v7.25.2` was released.
> /external/src/instruments/src/EFB/Components/Progress/Progress.tsx
187:5  error  defaultProp "bgcolor" has no corresponding propTypes declaration            react/default-props-match-prop-types
188:5  error  defaultProp "height" has no corresponding propTypes declaration             react/default-props-match-prop-types
189:5  error  defaultProp "width" has no corresponding propTypes declaration              react/default-props-match-prop-types
190:5  error  defaultProp "borderRadius" has no corresponding propTypes declaration       react/default-props-match-prop-types
191:5  error  defaultProp "labelAlignment" has no corresponding propTypes declaration …
=> fix: default-props-match-prop-types lint errors

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXUnits.js
Changes kilograms per pound units conversion in our utilities coding to better match what MSFS uses internally. This PR is intended to complement PR #5895 (although that PR is not necessary for this one to be merged).
The current conversion in the NX Utilities package is 2.20462 kg/lb. This PR changes it to 2.204625 lb/kg. Although that is not the exact conversion you will find in any online converters ( 2.2046226218 kg/lb), it is what is necessary to match MSFS weights. See the following screenshots with weights in pounds and then with kilograms:
I filled each loading station and fuel tank with the max allowed by the slider in order to maximize the weights and therefore the accuracy of this check.
Here is a screenshot of a spreadsheet I used to find a conversion, …
=> fix: Pounds - kilograms units conversion

scripts/cdn.sh
The CDN script now fails after 5 retries per file and will let the GH action fail if the file can not be uploaded.
N/A
N/A
N/A
None. Only CI changes that will not impact the addon itself.
=> build: retry uploads to Bunny CDN if required

src/systems/systems/src/simulation/update_context.rs
Error in coordinates for local acceleration caused autobrake to use lateral acceleration instead of longitudinal.
Autobrake check:
Rejected take off in LO / MED / MAX should provide expected deceleration rate. 
Landing in LO / MED should provide expected braking distances.
=> fix(hyd): wrong acceleration coordinates causing autobrake fail

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml
The asobo sub template already applies the potentiometer, so we don't need to
The integ lighting brightness on the autopilot buttons was double multiplying the potentiometer setting. Fixed.
Asobo template code:
```xml
<EMISSIVE_CODE>#EMISSIVE_CODE# (A:LIGHT POTENTIOMETER:#POTENTIOMETER#, Percent over 100) *</EMISSIVE_CODE>
```
Check brightness of button integ lighting on glareshield/FCU.
=> fix(fcu): autopilot button integ light brightness

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg, flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/A32NX_Registration/Registration.html, flybywire-aircraft-a320-neo/html_ui/Pages/VLivery/Liveries/A32NX_Registration/Registration.js, src/instruments/src/EFB/Settings/Settings.tsx
Add an option to the EFB to disable the dynamic registration decal on the fuselage. The decal is generally not desirable for real world liveries that have a painted registration.
When reviewing, check the feat commit. The earlier ones are importing the Asobo files as-is, and reformatting them.
Check that decal appears and disappears with the setting. Disable, then load a default aircraft and check it's unaffected.
=> feat: registration decal setting

docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/CSS/A32NX_Display_Common.css, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js, src/instruments/src/Common/displayUnit.tsx, src/instruments/src/Common/pixels.scss, src/instruments/src/DCDU/index.jsx, src/instruments/src/DCDU/style.scss, src/instruments/src/ISIS/ISISDisplayUnit.tsx, src/instruments/src/ISIS/style.scss
Fixes #6097
Reverts our pixels implementation because of the new subpixel LCD effect that was added in SU6. Keeps the bleed effect + tint.
Discord username: 2Cas#1022
1, Spawn
2, Verify that the pixel filter is removed from PFD, ND, EICAS, MCDU and DCDU. (Subpixels should be there still).
=> revert: remove pixels (after SU6)

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/model/models.json
Fixes #6128
Fixes #5670
This PR removes the glass effect on the displays to fix the brightness issues in clouds since SU6.
- load plane and check if brightness is ok and glass effect is removed
- fly through clouds and observe if behavior can now be considered as normal again
=> fix: removed glass due to issues with brightness in clouds since SU6

src/fmgc/src/guidance/Geometry.ts, src/fmgc/src/guidance/GuidanceComponent.ts, src/fmgc/src/guidance/GuidanceController.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts, src/fmgc/src/guidance/lnav/PseudoWaypoints.ts, src/fmgc/src/guidance/lnav/legs/RF.ts, src/fmgc/src/guidance/lnav/legs/TF.ts, src/fmgc/src/guidance/lnav/legs/VM.ts, src/fmgc/src/guidance/lnav/legs/index.ts, src/fmgc/src/guidance/lnav/transitions.ts, src/fmgc/src/guidance/lnav/transitions/Type1.ts, src/fmgc/src/guidance/vnav/VnavDriver.ts, src/fmgc/src/guidance/vnav/descent/DescentBuilder.ts, src/instruments/src/ND/elements/FlightPlan.tsx
Part of cFMS v2 migration.
This patch changes the FMS architecture to keep geometry and legs object around until the flight plan changes. This not only allows (primarly) for stateful legs (useful for HX) and transitions, but is also less intensive.
Additionally, pseudo waypoints now work when they end up in the middle of a transition path.
Guidables (so, legs and transitions) now have a `recomputeWithParameters` method which is called every X seconds. This re-computed the geometry of the guidable, without re-creating the entire instance, using new parameters (TAS, GS, etc.) …
=> refactor(fms): stateful geometry+legs, improved pseudo waypoints

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Fixes #6170
Fixes #6174
When creating the electrical system initially (in #2582) I didn't add the AC GND FLT SVC BUS and DC GND FLT SVC BUS. As those buses were not available, the captain dome and nav lights were assigned to the wrong (often "parent") bus in #3980. #4544 added the GND FLT SVC BUSes and thus we can now assign lights to them.
The Capt. dome light is assigned to DC GND FLT SVC BUS.
The NAV lights are assigned to AC GND FLT SVC BUS.
Aside from the information in the summary, it is useful to know that DC/AC GND FLT SVC BUS is powered when:
- AC BUS 2 is powered, and TR2 hasn't failed.
- AC BUS 2 is unpowered, and EXT PWR is AVAIL.
Every new commit to this PR will cause a new A32NX artifact to be created, built, …
=> fix(elec): connect captain dome and nav lights to gnd flt svc buses

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Fixes #6196 ?
Add `false` as `SET_CURRENT_FLIGHTPLAN_INDEX ` second argument
=> fix: su7 fpm SET_CURRENT_FLIGHTPLAN_INDEX fix

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightplanning/FlightPlanAsoboSync.ts, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Fixes flight plan syncing from world map issues in Experimental branch where runway symbol would not be displayed on the ND.
Refactor of index values to properly set originRunwayIndex and destinationRunwayIndex, and to use these index values to retrieve onewayRunway objects where needed.
You will need to test several permutations of the following:
1. Loading in from the world map using MSFS flight planning
2. Manual entry in the MCDU
3. Loading flight plan from SimBrief
4. Loading flight plan from a .PLN save file (saved route from the world map menu)
AND
1. Flight plan with no SID/STAR but departing/arriving to a runway, test at least between 2 different routes*
2. Flight plan with SID but not STAR, test at least between 2 different routes
3. …
=> refactor(fmgc): fix asobo flight plan syncing issues

.github/CHANGELOG.md, src/model/models.json
Fixes #5325
Fixes #1224 
Adjust heat blur effect on `ENG1` + `ENG2` to more reasonable levels.
Blur effects are **moved back** slightly and **only 50%** so big.
Still visible from windows, just not as much as before, as a result of conversation in #2221 taken into account.
One could argue that this could/should be a setting, in EFB perhaps:
```
[ ] Default
[x] Minimal
[ ] Off 
```
Where `minimal` is the contents of this PR.
Discord username: @bouveng 
1. Spawn on runway.
2. Observe blur on ENG1 and ENG2 from wing views.
3. Observe blur on ENG1 and ENG2 from external views / drone cam.
4. Take off, observe blur from wing views and external views / drone cam.
1. Make sure you are signed in to …
=> fix(model): Adjust heat effect on ENG1+2

.github/CHANGELOG.md, src/instruments/src/PFD/SpeedIndicator.tsx
This PR improves the behavior of the speed tape at speeds between 0 and 72 knots.
Specifically, it improves the alignment of the right speed tape edge with the 30 tick and hides the bottom speed tape until the bottom corner of the right edge passes it.
https://www.youtube.com/watch?v=TEi-WX08ov8#t=5m41s
Discord username (if different from GitHub): BehEh#1234
1. Start a flight without ADIRS aligned. Observe no changes to before when not aligned (see reference above)
2. Align the IRS. Check the white line is not visible.
3. Play close attention when taking off. Between 0 and 30 knots you should see no difference.
4. Above 30 you should see the right edge moving downwards, aligned with the tick (see above)
5. Around 72 knots you should see the right edge reaching reaching the bottom and the …
=> fix(pfd): speed tape outline at low speeds

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js, src/fmgc/src/flightplanning/FlightPlanManager.ts
Partial #2068
Transition altitude and level are not available yet in the MSFS navdata, so we weren't able to populate them until now. I asked Navigraph if they could include the transition altitude and level in the OFP, and they very speedily obliged, so thanks very much to them. When you retreive a navigraph OFP via ATSU, the transition altitude and level will be used as database values.
Needs #4953, and then retargeted onto `master`.
Check that trans alt and level are filled by ATSU.
1. Click on the **A32NX** …
=> feat(atsu): get trans alt and level from simbrief

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/components/EfisLabels.ts, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/lib/FmgcComponent.ts, src/fmgc/src/loop.ts
Refactor transition altitude and level handling a little to accomodate secondary and alternate flight plan (future). Fix trans alt and level not being sent to EFIS when from DB (currently only Navigraph OFPs).
Note: no changelog as there are no user visible changes since the previous stable release.
Fetch an OFP from SimBrief and note the transition altitude and level are automatically filled from the database. Climb through the transition altitude and ensure QNH blinks on the PFD. Activate STD, reach cruise, then descend through the transition level and ensure STD blinks on the PFD.
1. Click …
=> fix: transition alt/level

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #6257
FCU display lighting is now fed from correct bus. It will only be available when AC bus 1 is live.
FBW-22-06
=> fix(fcu): feed display lighting from correct bus

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.css, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.html, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js
Fixes #6305 
Show cyan dashes in place of gross weight when no engine is running.
- With timestamp: https://youtu.be/uz5HT8K-g8I?t=235
- FBW-31-04
- FCOM:
- Load up cold and dark
- Power up
- Observe gross cyan dashes in place of gross weight value
- Start one engine
- Observe gross weight value showing
=> fix(ecam): fix gross weight being shown without engines running

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
Fixes #6264 
The Pilot and Co-pilot weights were removed from the flight_model.cfg weight-and-balance section by PR #5895 since the flightcrew are included in the operating empty weight of the airplane. An unintended side effect was that the co-pilot (and for some people, the pilot) no longer appears in the external view. (It was not known that the pilot and co-pilot entries in the weight-and-balance section of the flight_model.cfg file affected the appearance of their avatars in the external view. This is not mentioned in the MSFS SDK.)
This PR adds the pilot and co-pilot entries back into the weight-and-balance section of the flight_model.cfg file. It assigns them weights of 1 pound each so that it does not materially affect the weight-and-balance distribution. (I tried using 0 pounds …
=> fix: Co-pilot not showing

docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fbw/src/FlyByWireInterface.cpp, src/instruments/src/PFD/index.tsx
This PR renames the local variable used for altitude constraints sent from the flight management (FM) to the flight guidance (FG). The new name is used to streamline the name of the variables.
Do a flight that uses altitude constraints **that are known to you that they work** and see if it still does.
=> refactor: rename altitude constraint LVAR

src/systems/systems/src/pneumatic/mod.rs
This fixes an issue where the APU AVAIL light would not turn off. This happened because the Rust process crashed when a new `EngineState` value introduced in #6284 was not recognized by the bleed system.
- Start cold & dark
- Turn on APU
- Turn on engines
- Turn off engine number 2
- Make sure you can operate the hydraulic pumps on the overhead panel, i.e switch them off and back on.
- Make sure you can use the toe brakes and set the parking brake.
- Turn off engine number one and check the two items above again.
- Make sure you can turn off the APU. Observe APU shutting down properly and all of the APU lights turning off on the overhead panel.
Every new commit to this PR will cause a new A32NX artifact to …
=> fix(apu): fix APU not shutting down properly

.github/CHANGELOG.md, docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCDataManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js, src/instruments/src/ND/pages/ArcMode.tsx, src/instruments/src/ND/pages/RoseMode.tsx, src/instruments/src/PFD/HeadingIndicator.tsx, src/instruments/src/PFD/index.tsx
Fixes #2568 
Fixes #5788
ILS' can now be tuned by ident on the rad nav page. ILS course can now be entered on the RAD NAV page. The course dagger on the ND and PFD is sourced from the correct data depending on entry, and availability of database or radio info. The `RWY/LS MISMATCH` scratchpad message is implemented, and is generated when the ILS/LOC manually tuned doesn't match the database one for the runway, or the entered course does not match the database.
The new facility search API introduced in SU6 returns ILS in the VOR search results, making this possible. This PR switches the data manager from the old FS9GPS search API to the new one for all search types, yielding a substantial improvement in performance for all database searches for idents.
Honeywell manual.
Discord username …
=> feat: Manual ILS Tuning by Ident, Course

.github/CHANGELOG.md, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h
This PR fixes:
- CLB did not correctly engage on take-off even when conditions
where satisfied
- added time delay for ALT condition to ensure it only engages when
altitude is captured. This improves some situation when in ALT*
the barometer setting is changed, and the altimeter is going through the target
altitude. Now it keeps in ALT* and recaptures it
- Take-Off with CLB and NAV armed
- at acceleration altitude CLB should engage
- test if altitudes can be correctly captured
=> fix(ap): CLB engagement on take-off, improved ALT condition

src/instruments/src/ND/elements/CrossTrack.tsx, src/instruments/src/ND/pages/PlanMode.tsx
This PR adds the XTE indication, which was missing in PLAN mode, and also changes the XTE in all modes to only display 1 digit of precision.
Image credit: @tshomas 
Make sure that the XTE indication shows correctly, both in PLAN and also in the other ND modes.
=> feat(nd): Add XTE display in PLAN mode, reduce XTE display precision

docs/Configuration/ModelConfiguration.ini, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp
This PR moves the flight director smoothing from the FlyByWireInterface into the Matlab model.
Also, the smoothing behavior was slightly changed, which means that the lateral FD now uses a lag filter, while the vertical FD uses a rate limiter. This should make them behave closer to real life.
Discord username (if different from GitHub): 
Fly the aircraft, and observe the behavior of the two FD bars. Compare them to some real-life or level-D sim footage, to determine if they are realistic. Also Test the FD with the TRK/FPA mode enabled.
1. Click on the **A32NX** …
=> refactor(ap): Move FD smoothing from C++ Interface to model

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/final.FLT, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/runway.FLT, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/SpoilersHandler.cpp, src/fbw/src/SpoilersHandler.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp
Fixes #6442 
**Revised to add changes to runway,flt file in addition to final.flt file**
The runway.flt file is used when starting the airplane on the runway. The final.flt file is used when starting the airplane with only the destination airport/runway set in the MSFS Flight Planner. 
Due to changes in how flap/slat configurations are handled in the FBW A32NX, these files no longer start the airplane in the appropriate configuration (a takeoff flap in the runway.flt file and landing flaps in the final.flt file). The default airplane starts in CONF 1+F when starting on the runway and CONF 4 when starting at the final approach phase. This PR makes changes to restore starting with CONF 1+F on the runway and in the full landing configuration for the final approach. There are also other minor …
=> fix: Flap settings and lighting in runway.flt and final.flt files

manifest-base.json, package.json, scripts/build.js
This PR introduces an improved title and versioning in the content manager of the sim:
* Version
* It will show the short git commit hash along with the version
* Title
* It will show "A32NX (STABLE)" for stable version
* It will show "A32NX (DEVELOPMENT)" for development version
* It will show "A32NX (BRANCH xy)" for any other build
* test if this package can be loaded successfully and the git commit hash is shown and the title as spec above
Remark: not all kinds of editions can be tested for the PR. This will take place when we update the development version with this PR and when the next stable version is released.
1. Click on the **Checks** tab on …
=> build: updated dependencies and improve title and version in content manager

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
PBD input was ignoring the decimal point on distance. Fixed that,
Check that PBD works with and without decimal on distance in F-PLN, new waypoint, and PROG.
=> fix(fmgc): parse decimal point for PBD input

src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Fixes #[5634]
Adjusted dashboard weather widget to use selected barometer from sim options page.
Discord username (if different from GitHub): bdepz#1564
Load various flight plans into the EFB and switch barometer in sim settings menu. The weather widget on the dashboard should change accordingly.
=> feat(efb): EFB Dashboard Weather Widget uses selected barometer setting

src/systems/a320_systems_wasm/src/lib.rs
Two aircraft variables were missing, causing unexpected behaviour within the aircraft system simulation.
=> fix(gear): add missing aircraft variables

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js
Fixes an issue reported a few times on Discord, but no bug recorded that I could find.
Simbrief includes the destination airport as the last waypoint in the flight plan. We have logic that filters out waypoints that are part of a SID or STAR, which normally excludes it, but if your flight plan doesn't have a STAR the airport ends up being inserted, and then when you select an approach in-sim it goes after the airport waypoint. Now we filter an airport waypoint that is the last in the flightplan.
Route: YSSY/34L WOL2 WOL H20 NWA DCT URBOB DCT MER DCT YMER/03
Before:
After:
Import SimBrief routes with no STAR, check that the destination airport doesn't get added as part of the route (it will still get added as the destination). Check routes with …
=> fix(atsu): don't include airport as waypoint in route uplink

.github/CHANGELOG.md, src/systems/a320_systems/src/pneumatic.rs
Starting state of air pressure in hydraulic reservoir was a bit low as in a long cold start case, it could cause blue pump fault depending on local atmospheric pressure.
We called the maintenance crew and now they have pressurised all 3 reservoirs to 50 psi.
No fault appears on pumps be it on cold start or runway start.
=> fix(hyd): Increased default reservoir air pressure values

src/instruments/src/PFD/index.tsx
This PR improves the behaviour of the speed trend arrow on the PFD, by making it more reactive. It also swaps the order of filters that are applied.
Example for the speed trend behaviour: https://www.youtube.com/watch?v=bjGT9aJU6jo
This PR only affects the yellow speed trend arrow on the PFD, on the speed scale. It is a very subtle change, and you should mostly make sure nothing has broken.
Fly a few circuits and observe the speed arrow. It should generally increase when the speed is increasing, and decrease when the speed is decreasing. However when the speed change is very extreme, the arrow will intentionally take a moment to catch up.
1. Make …
=> feat(pfd): Improve behaviour of the speed trend on the PFD

.github/CHANGELOG.md, src/instruments/src/EFB/Settings/Settings.tsx
Fixes #6396.
The EFB TAF options do not match what is available from our API. I have always thought that TAFs just weren't available for the airports I fly in/out of... until I had a play with the API's swagger web UI, and it worked. So then I look at the TAF options available in the EFB and they do not match the API! This is fixed.
While at it I also fixed #6396.
EFB:
https://github.com/flybywiresim/a32nx/blob/f808039638890cba8a27195b9617929971bd9c7e/src/instruments/src/EFB/Settings/Settings.tsx#L558-L561
Note the NOAA setting, and some others, are mapped to different names in the ATSU before they hit the API because it's boring without a few layers of indirection:
https://github.com/flybywiresim/a32nx/blob/f808039638890cba8a27195b9617929971bd9c7e/flybywire-aircraft-a320-neo/html_ui/Pages …
=> fix(efb): fix faa taf option to match fbw api

src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
Fixes #6524
Changed input component on EFB dashboard weather widget for ICAO input. 
- Used SimpleInput instead to prevent leaking key presses to the sim. 
- Added input box around ICAO in EFB dashboard weather widget to signifying that an input can be made
See issue https://github.com/flybywiresim/a32nx/issues/6524
Start flight anywhere
Turn on EFB and enter an ICAO (or any value) into the airport ICAO fields ("----").
Make sure that no input is leaked to the sim. 
Examples: 
"L" in the sim should trigger lights on/off - should not trigger it while in ICAO input field
"O" in the sim should trigger Strobes on/off - should not trigger it while in ICAO input field
Test flight plan import and any other related option to see if …
=> fix: Fixed input for ICAO on EFB dashboard to avoid key press leaks to sim

.github/CHANGELOG.md, src/fbw/src/model/FlyByWire.cpp, src/fbw/src/model/FlyByWire.h, src/fbw/src/model/FlyByWire_data.cpp
Recently, a compensation for spoilers has been added to the C* law. This should not happen for ground spoilers to avoid a pitch up moment on landing. This PR removes this compensation.
- Do several landings with ground spoilers armed
=> fix: no ground spoiler compensation in C* law

src/fmgc/src/flightplanning/LegsProcedure.ts
* Temporary fix of FC leg mapping to TF leg until LNAV supports FC legs
NONE!
* Test arrival at EGGD ILS27 via BRI (first one)
=> fix(fpm): properly map FC legs

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml, flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_ATC.xml, src/behavior/src/A32NX_Interior_Generics.xml, src/behavior/src/A32NX_Interior_Handling.xml, src/behavior/src/A32NX_Interior_MCDU.xml, src/behavior/src/A32NX_Interior_RMP.xml, src/model/models.json
Fixes #5602
This PR increases the **speed** (between 2-3x) of **all** buttons, switches, knobs and korry buttons.
This PR does the following
- Introduces a **utility template** for animation **interactions**, that holds a subset of the different animation properties. This allows for a **single place of configuration**.
- **Splits** the WX radar component into **2 separate templates**, for separation of concerns and allowing of individual animation properties for switches and knob.
- Removes **one state** for the ATC ALT RPTG knob. 2 instead of 3.
- Adds standardized comments where useful, following panel/item naming in cockpit.
- Many changes, but the changes is of the **same sort**, see below.
- PR has **0 impact** on any functionality.
Most changes looks like this, change of template, …
=> feat(misc): Animation speed/behaviors for button, switches and knobs

src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp
This PR improves the following:
- decreased minimum flare height to 40 ft
- tuned gains of G/S law
- added option to use calculated ILS deviations
- perform multiple Autoland in various conditions
Headwind: 30 kt
Tailwind: 10 kt
Crosswind: 20 kt
Headwind: 30 kt
Tailwind: 10 kt
Crosswind: 15 kt
=> feat: improved G/S and FLARE law

src/instruments/src/EFB/Settings/Pages/RealismPage.tsx, src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx, src/instruments/src/EFB/Settings/Settings.tsx
Split SimOptions Settings page into SimOptions and Realism page
As in current Development
-
=> fix: Split SimOptions Settings page into SimOptions and Realism page

.github/CHANGELOG.md, src/fbw/src/model/Autothrust.cpp, src/fbw/src/model/Autothrust.h, src/fbw/src/model/Autothrust_data.cpp
This PR fixes the ATHR alt soft mode gain. It reacted to agile in alt soft mode.
do some tests in ALT CRZ and other mode and observe if the reaction in ALT CRZ is not so agil.
=> fix(athr): alt soft mode

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fix a bug that's been around on master for a while.
Set FCU higher than CRZ alt and see if you get the scratchpad message.
=> fix(fms): cruise alt message

.github/CHANGELOG.md, src/systems/systems_wasm/src/lib.rs
We identified some conditions, for example reloading plane from dev menu, causing huge delta times of 6 seconds that can break system simulation.
Right now I just cap the delta time to a maximum value. Feel free to propose any other or additional protection.
-Using dev mode/aircraft selection/reload airplane do not break hydraulic simulation (pumps on/off have correct consequences)
-Ending a flight by shutting down both engines, then restarting them, do not break hydraulic simulation. …
=> fix(bleed): Huge delta time can break the system simulation

.github/CHANGELOG.md, src/systems/systems/src/electrical/engine_generator.rs
Avoids triggering emergency elec on first ticks after initialisation. Initializing plane in flight is causing a short emergency elec condition which triggers the RAT. This is a fix for this case.
Init the plane in flight from game map. Check that RAT is not out on Hyd Ecam (Should not see a solid green arrow for RAT)
After init in cold and dark, wfter engines are started, engine generators should provide electric current as expected.
=> fix(elec): remove in-flight engine generator spool up time

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
When maximum takeoff performance is required, it is possible to do a packs off takeoff. It is normal to takeoff with the packs turned off, and turn them on upon reaching the thrust reduction altitude. If you forget to do so the cabin will not remain pressurised when climbing to higher flight levels. My general feeling from the community is that this does happen quite frequently since we actually simulate the pressurisation system now. This PR adds the ECAM warning that exists to prevent such an occurence.
The exact logic requires some additional system implementation that is out of scope for this PR, so a few of the conditions have been approximated for now. The whole thing will later be replaced with the new FWS, but I felt this was still worth a small amount of effort …
=> feat(ecam): packs off abnormally warning

docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fmgc/src/efis/EfisVectors.ts, src/instruments/src/ND/pages/ArcMode.tsx, src/instruments/src/ND/pages/RoseMode.tsx, src/instruments/src/PFD/AttitudeIndicatorFixed.tsx, src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, src/instruments/src/PFD/FMA.tsx, src/instruments/src/PFD/index.tsx, src/shared/src/autopilot.ts
The track line is now also displayed when NAV is armed per reference below.
Also the usage of magic numbers in the code has been refactored and a helper function added to simplify detection of armed modes.
On HDG switching from NAV blue to LOC blue:
https://youtu.be/bjGT9aJU6jo?t=625
N/A
Refactoring testing:
* regular flight
* check FMA
* check that colour of the constrained altitude in managed CLB/DCT is correct
* check FD/FPV indicator (bird)
Bugfix testing:
* check track line on ND in e.g. HDG mode disappears when NAV is armed
* check that it stays visible in LOC blue until LOC*
* check for ROSE(NAV) and ARC mode
1. Click on the **Checks** tab on the …
=> fix: ND track line when LOC is armed

.github/CHANGELOG.md, src/fbw/src/model/AutopilotStateMachine.cpp
This PR fixes an issue when flying in ALT CST and the altitude constraint jumping to the FCU altitude. Now the DES mode is correctly engaged, and the aircraft descends to the FCU altitude. When nothing further changes, it will capture the altitude with ALT* and will end in ALT.
The broken behavior before was that DES only disarmed and the plane incorrectly remained in ALT CST. This error only happened when FCU altitude and new altitude constraints were equal. This applied only to DES and not to CLB.
- test the above-described scenario:
- set 6000 ft on the FCU altitude and climb/descend to it
- engage NAV
- set an altitude constraint with +5000 ft
- set FCU altitude to 4000 ft
- push ALT knob to engage DES
- plane should capture the constraint of 5000 ft (and end in ALT CST)
- for next …
=> fix: ALT CST and DES logic

src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/a320_systems/src/pneumatic.rs
Ignore a few tests that take ~25s to run on my machine. The pneumatic tests are primarily intended to draw graphs and will be moved to a separate application by @BlueberryKing at a later time. The hydraulic tests try to ensure we're not leaking hydraulic fluid due to floating point precision issues. They simulate a lot of time to do so.
All these tests can still be used by executing: `cargo test -- --ignored`.
Testing is not unnecessary.
1. Click on the **A32NX** download link at the bottom of the …
=> test: ignore long-running tests

src/instruments/src/Common/metarTypes.ts, src/instruments/src/EFB/Dashboard/Dashboard.tsx, src/instruments/src/EFB/Dashboard/Widgets/ColorMetar.tsx, src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx, src/instruments/src/EFB/Store/features/dashboard.ts, src/instruments/src/EFB/Store/store.ts, src/instruments/src/EFB/Utils/parseMetar.spec.ts, src/instruments/src/EFB/Utils/parseMetar.tsx
- Added colored METAR 
- created separate parseMetar function and removed "aewx-metar-parser library"
- added unit tests for parseMetar
- Keeping state when changing EFB pages 
- added Redux state for Dashboard
- Added a fix so barotype works for user ICAOs as well 
-  AUTO: choose baro type based on ICAO or respect the setting in the EFB. 
TBD
=> feat: Advanced weather widget for flypadosv3 

src/fadec/src/EngineControl.h
There has been at least one report in experimental version that the CLB thrust limit was not restored to normal from FLX reduction. It ended for the user not being able to climb beyond FL2070.
To avoid this situation the condition to trigger the transition has been revisited.
- do a FLX TO
- after thrust reduction altitude and lever being set from FLX/MCT detent to CLB detent, the transition should start after 10 s (thrust will increase)
=> fix(athr): improved condition to transition CLB limit from FLX TO

.gitignore, src/instruments/src/Common/index.tsx, src/sentry-client/src/FbwAircraftSentryClient.ts, src/tcas/src/components/TcasComputer.ts
* Runs root client flow (consent gather) 1 second after `FlightStart` event instead of immediately
* Tweak message to make it more clear this is from the A32NX and not MSFS
* Add generated `sentry-client` to `.gitignore`
* Fix a stray non-singleton `JS_LISTENER_SIMVARS`
* Make sure toggling of error reporting in the EFB ATSU/AOC settings works
=> fix(sentry): improvements to sentry.io client

src/instruments/src/EFB/ATC/ATC.tsx
#6730 introduce a bug by not converting a string to lower case before comparing.
This fixes this. 
EFB ATC page should work as before and show available ATC frequencies. 
=> fix: Fixes check for correct ATC source

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_DepartReq.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_MessagesSent.js
Fixes two Sentry-issues
Fixes a mid-flight crash when the origin airport is not defined.
Fixes a crash after a message is deleted in the SENT MESSAGES menu
- Test if PDC still works
- Test if DEPART REQ page is shown if origin or destination is missing
- Delete a message in MESSAGES SENT and MESSAGES RECEIVED in AOC menu
=> fix(atsu): Fixes in DEPART REQ and MESSAGES

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #6764
* Adds a missing `bind` call to a function passed in as a value
* Make sure no errors occur while pressing the V/S knob to initiate a step descent.
=> fix: add missing bind call on function value

.github/CHANGELOG.md, docs/a320-simvars.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp, src/fbw/src/model/Autothrust_data.cpp
Increase speed of spool up/down of engines for ATHR modes `THR IDLE` and `THR CLB` to better match real-life (see on discord channel ATA-22).
Improved (again) the FLARE law for Autoland capability. Landings are now a bit harder but better match the target touchdown point. The touchdown sound is now using the landing rate instead of plain vertical speed which is more realistic in cases of sloped runways. 
- fly level and engage OP CLB
- fly level and engage OP DES
- do several Autoland
=> feat: AP and ATHR improvements

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Boarding.js
When A32NX_DEVELOPER_STATE is true, MCDU reloads will not affect payload or pax values.
Discord username (if different from GitHub): sidnov#8337
Developer-side changes, no QA needed.
=> feat: add developer state protection from payload reset

src/instruments/src/PFD/AttitudeIndicatorFixed.tsx, src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, src/instruments/src/PFD/LandingSystemIndicator.tsx, src/instruments/src/PFD/index.tsx
This PR aims to improves the FPV (flight path vector, bird) and FPD (flight path director) in the following ways:
* Firstly, the FPA is now no longer the aerodynamic FPA (AOA + pitch), but the kinematic FPA (atan(VS / GS)).
* Improved behaviour in gusty weather: The bird no longer jumps around as erratically
* The roll and pitch commands of the FPD are improved:
* The roll command now actually displays the desired roll angle, instead of being scaled down slightly like before this PR
* The pitch command now actually points to the desired pitch angle.
* Improved drawing priority: The FPA/FPD is now rendered above the fixed aircraft symbol (the yellow/black aircraft shape) and the rising ground (the lower "earth-colored" sector that rises as the radio height decreases). I'm not entirely sure …
=> feat(pfd): improved FPV and FPD

.github/CHANGELOG.md, src/instruments/src/EFB/Dashboard/Widgets/ColorMetar.tsx, src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx, src/instruments/src/EFB/Settings/Settings.tsx
Fixes #6751 
This PR adds a setting to the EFB to enable/disable colored METAR display in the Dashboard Weather Widget. 
Also changes the color red to a lighter version after feedback from colorblind user. 
brightness max:
brightness min:
Test the new setting and check the raw METAR on the weather widget to be either complete in the default white font or colored for severe and very severe values.  
Check readability in various lighting and brightness conditions - esp. the red color was problematic.  …
=> feat: Setting to enable/disable colored METAR in the weather widget

src/fmgc/src/efis/EfisSymbols.ts, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/guidance/lnav/transitions/HoldEntryTransition.ts, src/instruments/src/ND/elements/FlightPlan.tsx
- I made a small mistake in rewriting HX entries, forgetting to account for turn direction in the roll anticipation calculations. This caused a turn in the wrong direction before turning back to the correct direction for left turn holds.
- FC and FD legs were mapped incorrectly from the source data... now the geometry is correct (perfect implementation will need to wait for cfms-20, as I don't want to do two refactors of the magnitude required prior to that).
- Enroute runways weren't shown quite right on the ND (they should be centred on the runway location).
- There was an exception thrown in the FMGC when the map reference point was undefined in plan mode (happens briefly while creating a new flightplan... but whichever part of the FMGC decides the MRP should actually …
=> fix(lnav): fix HX entry RAD, FC and FD legs, and enroute runway

src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h
This PR removes two INI file settings related to the custom FMS implementation, namely if the custom FM variables should be used for AP computations or not. Since the cFMS is on master for a long time, this setting is now useless so I removed it.
* There should be no functional changes, this is only a refactor. Simply make sure that the NAV mode still correctly follows the flight plan.
=> refactor(ap): Remove useless ini file settings

src/instruments/src/ND/elements/Traffic.tsx
Improves the draw response of TCAS traffic on ND on mode and range change.
Received traffic from the computer is kept in state. The `alive` attribute is kept and used for mode and range changes.
Range change: https://youtu.be/8QzlOwrUDDs?t=439
Discord username (if different from GitHub): coolll.sk#0022
Observe ND traffic markers position change:
* immediately on range change
* very shortly after mode change (ARC to ROSE, ROSE to ARC)
To ensure that the previous draw functionality is preserved the traffic markers should keep ~1s cadence update when:
* flying
* changing heading
Observe performance.
1. On the left …
=> refactor(tcas): Improve traffic draw

.github/CHANGELOG.md, README.md, docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Status.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js, src/failures/src/a320.ts, src/instruments/src/EFB/failures-orchestrator-provider.tsx, src/instruments/src/PFD/AltitudeIndicator.tsx, src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, src/instruments/src/PFD/VerticalSpeedIndicator.tsx, src/instruments/src/PFD/index.tsx, src/systems/a320_systems/src/lib.rs, src/systems/a320_systems/src/navigation.rs, src/systems/a320_systems_wasm/src/lib.rs, src/systems/systems/src/failures/mod.rs, src/systems/systems/src/navigation/ala52b.rs, src/systems/systems/src/navigation/mod.rs, src/systems/systems/src/navigation/radio_altimeter.rs, src/tcas/src/components/TcasComputer.ts
Fixes #5883
This PR introduces a proper dual radio altimeter system featuring more realistic readings during (de)rotation, an accurate refresh rate, and ARINC 429 outputs. It improves the accuracy of the PFD display, and puts a system in place ready for the upcoming FWC to use.
The new radio altimeters are based on the Honeywell ALA-52B, require their appropriate bus to be powered and can be failed using the standard failure system in the EFB. They take a few seconds to start up after being powered.
The existing PFD, FWC, TCAS and GPWS have been updated to use the new radio altimeter sources, including fallback to the other system on failure. Some systems like TCAS will fail outright if no RA is functioning.
Video of new rotation: https://streamable.com/zpb7j3
- …
=> feat(navigation): add radio altimeter systems

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Fixes #6818
This PR fixes the above mentioned issue.
- in flight
- put speed to managed
- turn the speed knob, select a speed different from current airspeed
- pull speed knob
- selected speed should become selected airspeed
=> fix: selected speed not accepted

src/systems/a320_systems/src/hydraulic/mod.rs
Cargo door opening unit test was sometimes failing due to too small margin in test timing between unlock and hydraulic control start.
No test needed as long as unit tests are GO.
=> fix(hyd): fix cargo door unit test

src/systems/a320_systems/src/pneumatic.rs, src/systems/a320_systems_wasm/src/lib.rs, src/systems/systems/src/air_conditioning/acs_controller.rs, src/systems/systems/src/pneumatic/mod.rs, src/systems/systems/src/shared/mod.rs
There was an issue in the pack flow valve control logic that had it remain until an engine master switch was turned on, instead of closing the valves when the engine mode selector is switched to IGN. This PR should fix this behavior.
- Make sure you can still start an engine.
- Make sure that you cannot hear the packs anymore when you turn the engine mode selector to ignition.
- Make sure the packs come back after engine start.
1. Click on the **A32NX** download link at the bottom …
=> fix(bleed): fix pack flow valves not closing when switching to ignition

src/fadec/src/SimVars.h
This PR fixes an issue where PACK toggle did not correct engine N1 limits. Pack states were controlled by the A32NX_PACKS_{index}_IS_SUPPLYING LVars; these variables are obsolete. The new A32NX_COND_PACK_FLOW_VALVE_{index}_IS_OPEN is being used for these purposes.
Discord username (if different from GitHub): TazX [Z+2]#0405
Turning both Packs ON or OFF should see a change in the N1 Limit as per FCOM. 
Easiest way to test is on runway on standard conditions. TOGA Limit drops 0.4% with both Packs On.
1. Click on the **A32NX** download link at the …
=> fix(bleed): Engine Thrust Pack Corrections

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
This PR fixes a small regression introduced in #6736. Due to a bad variable type, the LDG MEMO did not appear on the ECAM when descending through 2000ft. It only appeared below 800ft (when an alternative condition kicks in).
1. Take off and climb above 2200ft indicated altitude
2. Descend through 2000ft
3. Observe the LDG MEMO appearing on the ECAM
=> fix(fws): LDG MEMO not appearing below 2000ft

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic/mod.rs
Pushback tug wasn't steering the nose wheel correctly during pushback with an angle.
Check that nose wheel is steered correctly when pushback is connected and is pushing with an angle.
=> fix(hyd): Nose wheel should turn with pushback tug

src/mcdu-server/client/src/App.jsx
This PR fixes a small issue where the Web MCDU showed the background MCDU image in "fullscreen mode".
Before fix:
After fix: 
Start the MCDU Server and open the MCDU in a browser or remote device. 
To enter the "fullscreen mode" either click on the display title or add "/fullscreen" to the URL (http://localhost:8125/fullscreen).
Check that there is no background in the fullscreen mode. 
=> fix: Web MCDU Interface fullscreen mode showing background

src/fbw/src/model/FlyByWire_data.cpp
This PR aims to improve the flare behavior in manual flight. For this purpose the authority of the underlying pitch attitude law has been reduced.
- perform several manual landings with different weights and CG positions
=> feat: improved flare behavior in normal law

src/fmgc/src/guidance/lnav/transitions/FixedRadiusTransition.ts, src/fmgc/src/guidance/lnav/transitions/PathCaptureTransition.ts
* Fixes an issue with path capture transitions wrongly having TAD in some edge cases (previous overshot + very low or very high sweep angle + too big for previous leg), causing some corrupted drawing
* Fixes an issue with wrong orthodromic calculations when placing the ITP of path captures that have TAD
**Before**
**After** (keep in mind the speed prediction is still wrong here, not the scope of this PR)
* Test various departures at high speed
=> fix: path capture tad

src/instruments/src/PFD/LandingSystemIndicator.tsx
For a short moment, NAV FREQUENCY:3 can return 0 which crashes the PFD as it tries to split that frequency for displaying. This PR adds a check that the frequency is splitted correctly and aborts further execution if it's invalid.
Enable the LS info on the PFD and enter different ILS frequencies (in range, out of range, valid and invalid combinations) and make sure the PFD stays on all the time and shows valid information.
=> fix: do not crash pfd when ls frequency = 0

src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts
- Sequence a discontinuity after the last leg of the flight plan.
- Revert to correct vertical guidance modes.
AMM 22
Create a flightplan with only a departure and then a discontinuity... fly past the end of it (in a managed climb) and ensure the guidance reverts to HDG and OP CLB mode.
Setup a STAR but delete a leg to create a discontinuity.. fly past it in managed descent and make sure the guidance reverts to HDG and V/S.
Fly a normal approach and make sure everything is fine as you pass the runway threshold (lateral guidance will revert here if in NAV mode, as the missed approach segment is not available in this older flight plan manager).
Every new commit to this PR will cause a new A32NX artifact to be created, built, and …
=> fix(fmgc): fix discontinuity guidance logic

src/instruments/src/PFD/FMA.tsx
Fixes #6774
* Fixes the logic for shortening the first FMA line, when an AB3 message (SPD SEL or MACH SEL) is displayed.
=> fix(pfd): Correctly shorten border when AB3 message is displayed

src/fadec/src/EngineControl.h
Fixes #6862 (partially)
With the new EGT cooling constant, the engine maintains a "shutting" state for a long time (instead of switching to "off" state once N2 gets to zero). Due to this change in the engine state model, fuel used was not being reset. This issue is being solved with this PR.
Discord username (if different from GitHub): TazX [Z+2]#0405
One way to do it:
1. Start aircraft on runway
2. Switch SD to ENG and burn some fuel (until it is shown in the SD)
3. Turn Engine 2 OFF (Master Off) and let it roll back
4. Switch igniter ON
5. Start Engine 2
6. Used fuel should reset to 0
1. On the left side, click …
=> fix(fuel): turnaround fuel used reset

.github/CHANGELOG.md, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/FlyByWire.cpp, src/fbw/src/model/FlyByWire.h, src/fbw/src/model/FlyByWire_data.cpp
Fixes #6890
This PR introduces the following changes:
- fix for #6890, V/S target of +1000 fpm in case of altitude change < 1200 ft is only applicable for OP CLB, not for OP DES, CLB or DES
- improves transition between flight an ground in case of Autoland, it basically removes the flickering of ailerons/spoilers on ground during ROLLOUT
- test ALT -> FCU + 1100 ft -> OP CLB -> SPEED | OP CLB -> ALT
- test ALT -> FCU + 1200 ft -> OP CLB -> THR CLB | OP CLB -> ALT
- test ALT -> FCU + 1000 ft -> CLB -> THR CLB | CLB -> ALT
- test ALT -> FCU - 1000 ft -> OP DES -> THR IDLE | OP DES -> ALT
- test ALT -> FCU - 1200 ft -> OP DES -> THR IDLE | OP DES -> ALT
- test ALT -> FCU - 1000 ft -> DES -> THR IDLE | DES -> ALT
- test ALT -> FCU - 1200 ft -> DES -> THR IDLE | DES -> ALT
- perform Autoland …
=> feat: autopilot improvements

src/fadec/src/EngineControl.h, src/fadec/src/Tables.h
Preliminary Idle N1 values were calculated solely as a function of altitude  by the FADEC. This worked as expected for ground operations at very low speeds (static and taxi). This PR fixes Idle N1 by making it also a function of speed (Mach). 
The FADEC calculated Idle N1 (A32NX_ENGINE_IDLE_N1) should match now actual N1 at Idle TLA.
Discord username (if different from GitHub): TazX [Z+2]#0405
To be assessed and determined:
**ON GROUND (Static and Taxi)**
Check that A32NX_ENGINE_IDLE_N1 = Actual EW/D N1
**CRUISE**
1. Cruise at CLB detent (leveled flight at fixed Mach)
2. Bring TLA to Idle detent
3. Watch FADEC Idle N1 go down as Mach also goes down
4. Actual N1 should be also rolling back but with a certain lag with respect to FADEC due to rapid decrease of Mach
5. NOTE: Hard to see that …
=> fix(engine): tuned FADEC Idle N1 calculation

.github/CHANGELOG.md, docs/a320-simvars.md, src/instruments/src/PFD/AttitudeIndicatorFixed.tsx, src/instruments/src/PFD/SpeedIndicator.tsx, src/instruments/src/PFD/index.tsx, src/systems/a320_systems_wasm/src/lib.rs, src/systems/systems/src/navigation/adirs.rs, src/systems/systems/src/simulation/test.rs
This PR:
* Outputs SSM=FW for all ADR labels when the ADR is off or not aligned
* Improves the ADR behaviour for low speeds. The following values are now coded as NCD with value=0 when below a threshold:
* CAS, when below 30kts
* TAS, when below 60kts
* Mach, when below 0.1
* All 3 ADRs now output temperature values, instead of only 1 and 3.
* Added new data outputs to the ADR:
* Angle of Attack (coded NCD below 60kts CAS, but the actual value is still output)
* Added new data outputs to the IR:
* Drift Angle (DA), which is 0 below 50kts GS
* Kinematic Flight Path Angle (gamma_k), which is 0 below 50kts GS
* The Body axis rotation rates: p, q, r
* Derived from these the Pitch/Roll/Heading rates: Theta_dot, Phi_dot, Psi_dot
* The Body accelerations: a_x, a_y, a_z
The FPA and DA are now …
=> feat(adirs): Improve ADIRS SSM and behaviours

igniter.config.mjs, src/systems/a320_hydraulic_simulation_graphs/Cargo.toml, src/systems/a320_hydraulic_simulation_graphs/src/main.rs, src/systems/a320_systems_wasm/Cargo.toml, src/systems/a320_systems_wasm/src/elevators.rs, src/systems/a320_systems_wasm/src/lib.rs, src/systems/a320_systems_wasm/src/nose_wheel_steering.rs, src/systems/a320_systems_wasm/src/rudder.rs, src/systems/systems/src/shared/low_pass_filter.rs, src/systems/systems_wasm/Cargo.toml, src/systems/systems_wasm/src/aspects.rs, src/systems/systems_wasm/src/electrical.rs, src/systems/systems_wasm/src/failures.rs, src/systems/systems_wasm/src/lib.rs, src/systems/systems_wasm/src/msfs.rs
In the coming period I want to reduce the barrier to entry for developers new to A320 systems programming. This PR prepares our Rust environment for providing improved developer documentation through `cargo doc`.
No testing is necessary.
=> docs: prepare for documentation improvements

src/instruments/src/EFB/StatusBar/StatusBar.tsx
This interval is not cleaned up on unmount of the component and therefore runs when the EFB is turned and is created multiple times when it's turned back on. Switching it to make use of `useInterval` which does a proper cleanup.
1. Make sure the time in the EFB status bar is still being updated.
=> fix(efb): useInterval to cleanup interval properly

src/shared/src/ata.ts
adds the missing ATA 34 description for the flypadosv3 failures page.
Discord username (if different from GitHub): Earthsam12#5545
=> fix(efb): add missing ata 34 description

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
If a Websocket fails to connect it doesn't seem to close but stays open (visible in the debugger and in ram usage). If the MCDU Server is not used this leaks a Websocket connection every attempt. This slowly fills up the RAM and lead to increased CPU usage.
I removed the "readyState" condition on a reconnect so the old socket is closed and properly garbage collected.
Before:
Lots of sockets...
After:
Just one WebSocket that also reports closed.
1. Click on the **A32NX** download link at the bottom of …
=> fix: close old websocket before every connection attempt

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_MCDU.xml
Credits to our modelers
- Make sure displays are not unreadable in bright conditions.
- Check if the reflection effect still looks fine.
=> fix: increase brightness + reduced reflections

src/instruments/src/EWD/elements/PseudoFWC.tsx
Fixes #6962
The signs ecam landing memo logic should be satisified when the no smoking switch is in either auto or on. Currently, this only works in auto if the landing gear is more than 50% down.  This reflects the previous logic. 
1. Spawn in on approach.
2. Once the landing memo appears, confirm that SIGNS.......ON is replaced by SIGNS ON when the seatbelt sign switch is set to ON and the no smoking switch is set to AUTO and ON (check both)
=> fix(ewd): Landing memo no smoking sign logic

src/fbw/src/FlyByWireInterface.cpp
Fixes a weird issue with SU9 that causes the engine control to stop working. This happens when 100% is written to the sim throttle. In many cases this is when TOGA thrust is applied and the plane starts rolling and thrust limit is further increased.
- start on the runway in SU9
- take-off with TOGA power
=> fix: SU9 issue with engine control

src/tcas/src/components/TcasComputer.ts
- use the actual radio altitude value
- reset all variables when TCAS is turned off to ensure clean state when you have been in a TCAS RA
- fly the plane and try to get into TCAS RA
- turn TCAS off -> result should be a clean state on the PFD
=> fix: some small TCAS improvements

.gitignore, src/fadec/build.sh
This PR changes the target directory for the object file that is generated during compilation of the fadec wasm module.
- spawn on runway and check if engines are working normal and can be controlled
=> build: compile fadec object file in separate directory

src/systems/systems/src/pneumatic/mod.rs
This PR fixes a small issue introduced with #6810 where the systems wasm module would run into a stack overflow which leads to a sim crash. The stack overflow only occurs if there ever appears a NaN in a PneumaticContainer (which should never happen).
Really not needed because it just switches around the if condition.
=> fix(bleed): Fix stack overflow when container contains NaNs

src/systems/systems/src/hydraulic/flap_slat.rs
Now flap moving sound should stop as soon as they really stop.
Verify that flap sound stops as soon as they stop moving (previously there was a 1 to 2s lag for sound to stop)
=> fix(hyd): fixed 2s lag for stoping flap/slat moving sound

src/sentry-client/src/FbwAircraftSentryClient.ts
* Changes sentry.io sample rate to 10% to avoid exceeding our quota. Default was 100%, which is way too much.
* Make sure screens still work, ig
=> fix: change sentry.io sample rate to 10%

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js
Fixes #7054
The amber boxes should not be show without an LS frequency, and instead the field should display as follows:
```
CRS
[  ]
```
The amber boxes should only appear when the frequency is set manually. When setting an ident, the CRS is set automatically.
| ![image](https://user-images.githubusercontent.com/1857322/163272819-f4de13b2-1e0d-47e8-aba5-af013968e61e.png) | ![image](https://user-images.githubusercontent.com/1857322/163272844-0cd38ce1-9517-49a8-85b5-15c03cbd6b53.png) |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1857322/163272931-c0eebf5e-2af0-4545-87b0-2c802b12c21a.png) | ![image](https://user-images.githubusercontent.com/1857322/163273180-434a30de-4ee5-4100-af08-64b27831eef2.png) |
Ensure …
=> fix(mcdu): radnav manual ils freq entry no crs set

.github/CHANGELOG.md, docs/Configuration/ThrottleConfiguration.ini, docs/a320-simvars.md, src/fbw/src/ThrottleAxisMapping.cpp, src/fbw/src/ThrottleAxisMapping.h
This PR adds an option to the Throttle configuration that allows the change of the increment that is used when key events are pressed (normal and small).
The default increment is as before, and users should not see any difference. If a user wants to change that, he will be able to do so using the configuration file.
If requested, this can be added to the EFB later as an additional option in the Throttle calibration.
Test if the values can be changed in the `ThrottleConfiguration.ini` with the following entries:
```
[throttle_common]
; determines the increment for a key event (+/-):
key_increment_normal = 0.05
; determines the increment for a "small" key event (+/-):
key_increment_small = 0.025
```
Change the values in the config file and reload them (you can use the EFB button to load the …
=> feat: added config parameter to change key increment for throttles

src/fmgc/src/efis/EfisSymbols.ts, src/fmgc/src/guidance/GuidanceManager.ts
VA legs are not implemented yet. Map them to CALeg for now to pick up some of the improved logic there when they're the first leg of a SID... Fixes KDEN25 BAYLR6 for example. Further improvements also in #6850.
Try some SIDs beggining with a VA leg.
A random selection to help you (no criteria like runway length applied sorry):
airport_identifier | procedure_identifier | transition_identifier
-- | -- | --
LPAZ | RODI4N | RW36
LIMZ | ENOB8Q | RW03
VTCC | KEDO1B | RW36
ROTM | TIT8 | RW06
CYYC | YYC7 | RW29
WIII | CA2K | RW24
KCXO | KARRR6 | RW14
KYIP | CLVIN2 | RW05B
KLAX | MUELR4 | RW25R
CYKF | CYKF3 | RW26
KCVG | ROCKT1 | RW36R
KARR | OBENE3 | RW33
LIRM | SOR1P | RW24L
KDEN | EPKEE7 | RW34B
VOBL | AKTI7C | RW09R
KBWI | CONLE4 | …
=> fix(fmgc): map unimplemented VA legs to CA

src/fmgc/src/efis/EfisSymbols.ts
Tweak the EFIS airport overlay runway criteria. We now require a runway with length of at least 1500 m and width of at least 30 m to show the airport. This is from feedback from pilots... the airlines will have their own criteria for which airports they include in their nav database but in the sim we need to do it in the aircraft as the nav database has everything.
Press the ARPT button while flying and make sure you see all the airports expected but not too many?
1. Click on the **A32NX** download …
=> fix(fmgc): tweak efis airport option criteria

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_Fire.xml, src/systems/systems/src/overhead/mod.rs
Fixes #4596
After being pushed, the fire buttons couldn't be stowed. Now, the LVAR for a specific fire push button takes its opposite value every time there's a click on it. This couln't be done without changing a condition in Rust: at each frame it updates the LVAR with a variable but this variable was always true as soon as the button was pushed.
Discord username (if different from GitHub): Julian Sebline#8476
1) Open the guard of a given fire push button
2) Click twice on the fire push button
=> fix: fire handles can't be stowed

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, src/fbw/src/model/AutopilotStateMachine.cpp
Fixes #7098
This PR fixes an issue in the FCU when in mode `NAV` and HDG is selected by rotating the knob. After `45 s` the display clears automatically (again showing `---`). When the knob was pushed it should directly clear the display and show `---`. The timeout was cleared but the HDG was still shown (without any timeout).
Additionally, this PR fixes an issue with armed NAV. When a flight plan is available and the `XTK > 10 nm` the `NAV` mode is not engaged but armed. When the flight plan was lost, it didn't disarm. This is now working.
- enter `NAV` mode, the display on the FCU should show `---`
- select a heading by rotating the HDG knob
- push the HDG knob -> FCU should display `---`
- select a heading by rotating the HDG knob
- wait for `45 s` -> FCU should display `---`
- enter a …
=> fix: reset display on HDG push in NAV and disarm NAV when flight plan is lost

docs/a320-simvars.md, src/systems/systems/src/navigation/adirs.rs
This PR adds true heading and true track into the current ADIRS data.
FBW-34-01
Discord username (if different from GitHub): Erick [Z-6]#6484
Make sure that the ND still accurately represents the heading and track on the display.
=> feat: add true heading and track

.github/CHANGELOG.md, src/model/models.json
Change RMP SEL indicator colour from green to amber.
FCOM
Select the other side's VHF channel to turn on SEL light... make sure it's amber. Check both sides.
=> fix(rmp): SEL indicator colour

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightphase/FlightPhaseManager.ts, src/fmgc/src/flightphase/Phase.ts
This PR allows to transition from APPR flight phase to CLB by entering a new and different CRZ altitude as documented in the FCOM.
Related to #6905 but does not completely resolve it.
- enter an origin and destination airport
- enter a cruise altitude of say FL120
- get into APPR flight phase on the FMGC
- enter a new cruise altitude of say FL130
- FMGC should move to CLB phase
=> fix(fmgc): allow flight phase transition from APPR to CLB

scripts/build.js
Adds a colored INOP sticker for Stable.
Color is FBW color 00e0e7
This can only be tested by devs during local building. 
master branch should show yellow sticker.
exp and any other branch builds should show red sticker
stable should show fbw-color sticker
=> feat: Updated build script and INOP label for all versions

scripts/dev-env/run.cmd, scripts/dev-env/run.sh, src/systems/a320_systems_wasm/src/nose_wheel_steering.rs
This PR switches the control of the nosewheel steering to the new axis for steering that was introduced in SU9.
**For that purpose this PR also updates the dev-env to use SDK 0.18.0.0.**
**NOT TO BE MERGED BEFORE SU9 RELEASE**
- test if airplane still works normal (FBW, AP, Systems)
- test if nosewheel steering is working with new axis
=> feat: use new steering axis for nosewheel

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsWeather.js, src/atsu/src/com/webinterfaces/HoppieConnector.ts, src/instruments/src/DCDU/index.tsx, src/instruments/src/EFB/Settings/Settings.tsx
Fixes findings in Discord
The AOC-ATIS and AOC-Weather pages handle the SEND*- and SEND-strings in RSK6 wrong.
This PR removes the * if a request is in the send-queue of the A/C or if no airport is set.
An other finding is that the DCDU runs through the selftest if the sim is started on the runway.
A fix is provided that the selftest is only executed during a cold&dark sim-start, otherwise is the system directly active.
Additionally is a persistent global flag set that defines if Hoppie is enabled or not.
Otherwise is it currently impossible to deactivate the Hoppie connection
- Fill out INIT A
- Check Hoppie enabled is deactivated in EFB/Settings/AOC
- Hoppie enabled is deactivated -> MCDU/ATC COMM/Notification -> Enter callsign …
=> fix(dcdu,mcdu): dcdu/mcdu visualization issues

src/fmgc/src/flightplanning/ManagedFlightPlan.ts
There was a bug when building departures if the second waypoint was a "duplicate" of the first (also happens if the second leg is effectively null, e.g. a CA leg with the same altitude as the first CA leg), the departure segment would be deleted and the remaining legs would be inserted into the "EmptySegment" which is effectively a black hole for legs. This would only occur for poorly coded procedures, in this case the LPMA DEGU1E departure from runway 05 when using Navigraph/Jeppesen data (MSFS/Navblue and NavDataPro/LIDO databases have a better coding for this departure).
Try loading some departures and checking they appear okay. …
=> fix(fmgc): don't add legs to the empty segment

src/instruments/src/ISIS/AutoBrightness.tsx, src/instruments/src/ISIS/ISISDisplayUnit.tsx
Fixes #6950
* Brightness should now be adjustable in home cockpit mode
* Popup display should no longer contain reflections of cockpit interior when brightness is low
Old:
New:
https://user-images.githubusercontent.com/15316958/164970274-6c791d15-c5e8-4028-b34b-fcd34630cc08.mp4
* Spawn C&D
* Open EFB Settings > Realism - Turn home cockpit mode on
* Attempt to adjust brightness on ISIS
* Brightness should increase/decrease
* Popout display with RALT+Left Click on ISIS display
* No cockpit reflections/transparency should be present
1. On the left side, click on …
=> fix(isis): Brightness adjustment in home cockpit mode

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_Core.js, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_TipsManager.js
This PR introduces a warning screen when one of the following incompatible assistance functions is active:
- ASSISTED TAKEOFF
- ASSISTED LANDING
- AI AUTO-TRIM
The very offensive re-appearing of the warning is intentional. The plane cannot be properly flown when one of the assistants is active (i.e. engine stops after take-off).
- enable one or more of the mentioned assistants
- spawn on runway with engines running
- warning should appear
- turn off assistant
- warning should disappear after timeout
⚠️ it turned out that the related sim variable is not always `1` when the assistant is `on`. Depending on the situation it can still be `0` but get `1` in a situation when the assistant might get active. For example, the take-off assistant seems not active with engines off. The warning might …
=> feat: show warning when incompatible assistance functions are enabled

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/EICAS_Common.js, src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, src/instruments/src/PFD/FlightPathDirector.tsx, src/instruments/src/PFD/FlightPathVector.tsx, src/instruments/src/PFD/PFD.tsx, src/systems/systems/src/navigation/adirs.rs
* Output correct units for Rotation rates and Body accelerations: Previously, RPM and percentage were used, instead of the correct units of deg/s and G.
* Use correct sign for Rotation rates and Attitude to conform to Aeronautical standards, in particular, flip the signs of Pitch, Bank, q, p, theta_dot, phi_dot.
* Add the gravitational vector to the body accelerations, since the sim does not include it in the body acceleration simvars.
* Change the G LOAD indication on the SD permanent data area to use IR data (Body Normal Acceleration):
* It is now shown if the acceleration data is valid and above 1.4G or below 0.7G for more than 2s
* It disappears 5 seconds after the acceleration returns to normal, or the data goes invalid.
* If it is shown while the data is invalid (only during the 5s …
=> fix(adirs): various IRS data fixes

src/instruments/src/PFD/AttitudeIndicatorFixed.tsx, src/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, src/instruments/src/PFD/SpeedIndicator.tsx, src/instruments/src/PFD/instrument.tsx, src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx, src/systems/systems/src/landing_gear/mod.rs
Should avoid speedtape showing error state when the nose is being lifted
Fixes #7124
Before that change, only the center/nose gear was used to determine whether the plane was on ground. This can cause issues with the Toolbar Pushback, as the raises the nose which can decompress the gear and show faulty speedtapes on the PFD. This replaces some usages of "onGround" with the left or right maingear.
1. Use toolbar pushback and verify the nose is lifted.
2. Speedtape is showing correctly on the PFD during pushback.
1. …
=> fix: use main gear compression for some onground detections

src/systems/a320_systems_wasm/src/nose_wheel_steering.rs, src/systems/systems_wasm/src/aspects.rs, src/systems/systems_wasm/src/lib.rs
This PR inverts the nosewheel steering axis. The implementation right now is as described in the sim dialog, but as several users have reported it, other planes including the default ones implement it in the opposite direction.
- test if the nose wheel steering is still working, in the inverted way
- axis mixture 4 is not changed
=> feat: inverted nose wheel steering axis

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
This PR prevents the autopilot disconnected sound playing when spawning into the sim.
Code from @Saschl 
1. Spawn in C+D
2.  Confirm autopilot disconnect sounds does not play
3. Undertake a flight
4. Confirm that the autopilot disconnect sounds plays when AP push button pressed or yoke is moved while AP is on
=> fix(sounds): Prevent autopilot sound on Cold and Dark spawn

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_TipsManager.js
This PR changes to code to show a warning of enabled assistant functions so that this does not happen in main menu and only when being in the cockpit.
- Tip should not appear in main menu
=> fix: only show warning due to enabled assistants when in cockpit

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml, src/systems/systems/src/landing_gear/mod.rs
This PR fixes merge issues due to PR #6893 and adds a small piece of code that was on Exp but was missed to be added to the gear PR. It ensures LGCIU errors are only counted when sim is ready.
=> fix: sound issues due to #6893 and count LGCIU errors only when sim is ready

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js, src/atsu/src/ATC.ts, src/atsu/src/com/webinterfaces/NXApiConnector.ts
This PR fixes the freetext-issues based on the NXApi-telex protocol.
Additionally is NXApi marked as default freetext-protocol if Hoppie is disabled.
A last fix handles UNABLE responses much better on "REQUEST LOGON" message.
- Select FBW as freetext system and send yourself a telex-message -> check discord if message is sent -> wait for COMPANY MSG on upper ECAM -> read message in AOC/RECEIVED MESSAGES -> COMPANY MSG on upper ECAM removed
- Disable Hoppie on EFB -> Open Freetext in AOC menu -> expect FBW preselected -> Enable Hoppie -> Fill out INIT A -> Open Freetext in AOC menu -> Expect HOPPIES preselected
- Send REQUEST LOGON to ATC station -> NEXT STATION: XXXX on DCDU -> respond with UNABLE -> NEXT STATION: XXXX removed and Connection …
=> fix(atsu): Fixes for NXApi-Freetext and CPDLC Logon-issues

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_WindPage.js
Relates #7061
I'm tired of spending so much pre-start time entering wind manually 😢 
Two changes are in this PR:
1. Making the maximum MCDU wind profile maximum flight level higher than FL390. Specifically up to FL450.
2. This adds a workable wind requests system to the Wind/Temp MCDU screens. It uses the Simbrief data obtained with the flight plan. This should be workable to avoid a lot of manual data entry by pilots until further per-waypoint wind profile work can be completed. 
Mostly just coloring Wind Request, removing the inop, and adding a * on all 3 wind pages. Screenshots:
Old:
New:
Honeywell 2009 Manual, from Table B-1, MCDU Data Format for changes to max FL entered from FL390->FL450:
For the wind request color and star:
The most difficult part of this was constructing the …
=> feat(cdu): Wind Requests v1

src/fbw/src/ThrottleAxisMapping.cpp
Fixes #7183
This PR adds initialization of the current throttle position on IDLE when the configuration is saved or loaded from file. This improves the initial position of the throttle when overall but especially when only using keyboard.
Before this PR the initial position of `0` and the resulting position was depending on the calibration.
- test if throttle is initialized with IDLE low value when loading the plane, pressing "load from file" or "save" on the EFB calibration page
- it should work as usual for the rest
1. Click on the **A32NX** download link at …
=> fix: initialize throttle position to IDLE

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_ATSU.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_WindPage.js
This just ensures that the alternate wind info is requested from simbrief. Originally, I missed this data being present and thus didn't implement it.
No UI changes, just behavior.
See #7158
Fixes: https://discord.com/channels/738864299392630914/758149448399847424/974077025029603388
Discord username (if different from GitHub): USA-RedDragon#1776
Ensure Descent Wind requests fill the Alternate data as well.
=> fix(cdu): Wind request: Obtain alternate wind data during descent wind request

src/fbw/src/model/FlyByWire.cpp
This PR fixes the occasional stuck of the rudder on one side.
- play heavy with the wind and get TAS (true airspeed) to `0`
=> fix(fbw): rudder stuck on one side

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/guidance/GuidanceManager.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts, src/fmgc/src/guidance/lnav/legs/CA.ts, src/fmgc/src/guidance/lnav/legs/CF.ts, src/fmgc/src/guidance/lnav/legs/CI.ts, src/fmgc/src/guidance/lnav/legs/CR.ts, src/fmgc/src/guidance/lnav/legs/RF.ts, src/fmgc/src/guidance/lnav/legs/VM.ts
Related to https://github.com/flybywiresim/a32nx/issues/7060
Add a much more robust comparison to determine duplicate legs. This prevents legs from being incorrectly removed from some procedures.
Before (Navigraph data):
After (Navigraph data):
Comparison (MSFS/Navblue):
Testing a selection of SIDs, STARs, and approaches (viewing in plan mode and an MCDU F-PLN should be sufficient). LPMA05 GOSG1E with Navigraph/Jeppesen data was the original problematic one, but please test other procedures to ensure they're still correct too.
1. On the left side, click on the bottom …
=> fix(fmgc): robust comparison of legs

docs/a320-simvars.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml
This PR adds a new simvar called `A32NX_GND_EQP_IS_VISIBLE` that exposes the current visibility of ground equipment.
Same logic already reviewed and Q&A.
No need for test, simvar used internally in `flypadosv3`.
Discord username (if different from GitHub): @bouveng
=> fix(model): expose gnd equipment visibility simvar

flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_TipsManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, src/shared/src/notification.ts, src/shared/src/popup.ts
Fixes an issue where notifications would persist on the main menu if a notification was active when the pause screen was triggered. Achieved by dismissing any active A32NX notifications when the pause menu is entered.
- Open Flight Assistants menu and enable AI Auto-Trim, AI Anti-Stall Protection, etc.
- Wait for the notification to popup
- Pause and return to main menu (note: notification will still be stuck on the pause menu, sim limitation at this time)
- Notification should dismiss after exiting to main menu and not be displayed on screen. 
1. On …
=> fix(ui): Ensure notifications are dismissed on exit to main menu

.github/CHANGELOG.md, .vscode/extensions.json
This PR fixes:
- the double entry of 0.9.0 in the changelog
- VS Code Rust plugin recommendation (the plugin unique identifier was renamed)
- no testing required
=> fix(dev): changelog and rust plugin recommendation

src/fmgc/src/flightplanning/FlightPlanManager.ts
When loading in from the world map, origin runway is sometimes ignored and not passed to FMS. This PR restores the flight plan sync from the world map to the correct and expected behaviour.
Before:
After:
Download and Load the following .FLT into MSFS
https://drive.google.com/file/d/1n4sBYpPC7VM9rOvrXbTdOG5JerUjrlJ7/view?usp=sharing
Check that the flight plan is loaded in correctly
Exit, Open a random route with a departure/arrival procedure from the world map (High altitude airways, etc).
Check that this is loaded in correctly.
1. On the …
=> fix(fms): fix sync of origin runway when loading from MSFS World Map

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic/mod.rs
It is now possible to revert gravity gear extension.
Still need to hold key binding or hold and click the crank handle to use it. 
When fully turned, once key or mouse is released , next click and hold will revert the crank handle 3 turns back to stowed position.
Use gravity gear extension on ground and in flight. If clicked and hold it should:
- release doors on ground
- release doors and gears in flight.
After use even with green system available, gear should be inoperative.
If clicked and held again, and if green system available it should:
- close doors on ground
- close doors and gears in flight. (Might need to recycle gear lever if LGCIU error)
In all conditions check that reservoir level is consistent.
Every new commit …
=> feat(hyd): unlock ability to reset gravity gear extension

.github/CHANGELOG.md, src/tcas/src/components/TcasComputer.ts
Fixes #7152
Fixes an issue where if TCAS was switched to standby while an RA is issued, the TCAS computer would stop functioning and issuing TAs and RAs when switched back to TA/RA.
Note; There are other TCAS bugs which are known issues which will not be addressed in this PR, this is a hotfix. 
- Intercept traffic around a busy airfield, then when a RA is issued, turn the TCAS mode to STBY (from TA/RA). Turn the TCAS mode switch back to TA/RA, and try to intercept traffic again. Appropriate TA/RA should be issued. 
1. On the left side, click on the bottom …
=> fix(tcas): hotfix for TCAS standby bug

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_GPWS.js
Fixes #2086
Altitude callouts were triggered when the altitude is reached, meaning that by the time the callout audio would finish after the altitude had already been passed (too late). This modifies the alert values with corrected ones (see Beheh's comment on the linked issue).
This was planned to be solved by the rust FWC, but for now as this will take some time, the current placeholder logic will be updated by this PR.
Perform a normal landing and pay attention to the altitude callouts. They should complete just before the altitude is reached while on the G/S.
1. On …
=> fix(gpws): altitude callouts now on time

src/systems/systems/src/simulation/mod.rs, src/systems/systems_wasm/src/aspects.rs, src/systems/systems_wasm/src/lib.rs
Improves variable access performance by replacing `FxHashMap<VariableIdentifier, VariableValue>` with `[Vec<VariableValue>; 3]`. Achieves a 6.74% reduction on time spent per frame in `systems` on my machine.
Do some basic flying and fiddling with some systems. Things should keep working as they were before.
=> perf: reduce variable access time

docs/a320-simvars.md, src/instruments/src/SD/Pages/Wheel/Wheel.tsx, src/shared/src/arinc429.ts, src/systems/systems/src/landing_gear/mod.rs, src/systems/systems/src/shared/arinc429.rs, src/systems/systems/src/simulation/mod.rs
This PR:
* Adds (part of) the LGCIU output bus, for a list of bits in the discrete words and their description, see the Lvar docs.
* Discrete words 2 and 4 and some bits in discrete word 3 have not been added, since the functionality for them is not currently implemented in the LGCIU.
* Modifies the WHEEL SD page to use the LGCIU output bus, and improve the indications.
* LGCIU failures should now be properly handled, and the "door partially opened" case has been added to the door indications. 
Check that the WHEEL page works correctly in all situations, including failures
Testing suggestion from Davy:
```
Use gravity gear extension on ground and in flight. If clicked and hold it should:
release doors on ground
release doors and gears in …
```
=> feat(lgciu/sd): add LGCIU bus output, modify WHEEL page for LGCIUs

src/instruments/src/ATC/index.tsx, src/instruments/src/Common/displayUnit.tsx, src/instruments/src/Common/index.tsx, src/instruments/src/Common/simVars.tsx, src/instruments/src/DCDU/elements/AffirmNegativeButtons.tsx, src/instruments/src/DCDU/elements/DatalinkMessage.tsx, src/instruments/src/DCDU/elements/MessageVisualization.tsx, src/instruments/src/DCDU/elements/OutputButtons.tsx, src/instruments/src/DCDU/elements/RogerButtons.tsx, src/instruments/src/DCDU/elements/WilcoUnableButtons.tsx, src/instruments/src/DCDU/index.tsx, src/instruments/src/SD/Pages/Cond/Cond.tsx, src/instruments/src/SD/Pages/Crz/Crz.tsx, src/instruments/src/SD/Pages/Door/Door.tsx, src/instruments/src/SD/Pages/Elec/Elec.tsx, src/instruments/src/SD/Pages/Fctl/Fctl.tsx, src/instruments/src/SD/Pages/Fuel/Fuel.tsx, src/instruments/src/SD/Pages/Hyd/Hyd.tsx, src/instruments/src/SD/Pages/Wheel/Wheel.tsx
The old SimVar hooks were based on a React context object provided by a `SimVarPovider`. This would centralize get/set calls into the context component, and allow employing a global cache. The client hooks would then call into that context, employing said global cache to access values.
On `set` operations, the global cache state would be mutated in identity, causing a re-render in every component using the hook. This was a tradeoff, effectively enabling dedupe-ing `SimVar.GetSimVarValuie` calls in the context component.
The new hooks simply employ two core mechanisms: a `useState` containing the current value, a `useRef` containing the latest timestamp of a get operation, and a `useUpdate` callback to compare the timer and get the value if necessary.
After performance testing, it is …
=> perf: improved simulation variable hooks

flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_LogoLightAmbient.fx
Changes the emitter in the ambient logo light to be a temporary one instead of an infinitive.
This have caused performance issues as new particles was generated forever.
https://devsupport.flightsimulator.com/questions/7606/potential-performance-issue-over-time-caused-by-li.html
No need to test. No harmful change, just for the better.
Discord username (if different from GitHub): @bouveng 
N/A
=> fix(lights): Remove infinitive emitter in ambient logo light.

src/systems/systems/src/landing_gear/mod.rs
This fixes a small error I made during #7173, in the LGCIU discrete word 2, where I accidentally negated the landing gear compressed bits 11, 12, 13 and 14, which is not correct according to the documentation.
This data is not used yet, so no testing is necessary.
=> fix(lgciu): write LGCIU discrete word bits as compressed instead of extended

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/systems/src/landing_gear/mod.rs, src/systems/systems/src/simulation/mod.rs
Spawning in the air was causing issues as gear always was down.
Now plane should only spawn gear down if in final or on ground.
All other flight control surfaces should init in neutral position when spawning with engines on and/or in flight
Spawn anywhere possible. Check everything is consistent in gear system.
Spawn anywhere possible. Check aileron init drooped down only on ground when engines off
Spawn anywhere possible. Check elevator init drooped down  only on ground when engines off
Spawn anywhere possible. Check rudder init in neutral position whenever spawning engines on
1. Click on …
=> feat(hyd): add spawning gear up, and correct surface positions at init

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js
- Fixed DEPARTURES and ARRIVAL page SID/STAR/TRANS scrolling on the MCDU to be true to life to the Honeywell H3 FMS.
- Now scrolls per page vs per item. 
https://user-images.githubusercontent.com/15316958/169535180-4df761d5-c3ad-44ef-b2fb-ce93d73fb647.mp4
- Fill out flight plan with arrival/departure airfield
- Select Departure, scroll up/down and verify that every departure runway/SID/transition can be selected and that scrolling is now per page
- Select Arrival, scroll up/down and verify that every arrival runway/STAR/VIA/transition can be selected and that scrolling is now per page
1. Make sure you are signed in to …
=> feat(fms): correct hw dept/arr page scrolling

scripts/build.js
This fixes a potential race condition in a build script caused by relying on the output of an asynchronous function without awaiting its termination.
The issue is resolved by using the synchronous version of the `fs.copyFile` method.
Perhaps a developer could test this PR by running the build script on their machine and making sure it runs as expected.
=> fix(build): Use synchronous `copyFile` call in build script

src/fadec/build.sh, src/fadec/src/EngineControl.h, src/fbw/build.sh
I noticed that the file for fuel persistency was written every update cycle while being on ground which showed quite a high runtime in the WASM debug window. I've added a timer to only update it every second which should be sufficient IMO.
Furthermore I've enabled clang optimization which also showed a slight improvement in runtime. Note that I used O3 which might be aggressive but I've done a few flights over the last week and didn't notice any erratic behaviour.
1. Spawn C&D and verify the fuel state is saved correctly every second (check the Modified timestamp of the file in the "work/AircraftStates" for the selected livery.
2. Take off and verify the fuel state is not updated (as it was before this change)
3. Observe …
=> perf: reduce fuel persistency update rate and enable clang optimizations

src/instruments/src/EFB/Failures/Failures.tsx
Fixes incorrect scrolling behavior on comfort view in the efb's failure page. Before it erroneously allowed the scrolling of the entire content but now should correctly allow scrolling of only the failure cards when necessary.
Before:
After:
Discord username (if different from GitHub): Erick [Z-6]#6484
Title and container should not be scrolled, only the inside of the container(outlined box) should be able to be scrolled(can't test as not enough failures on any page to warrant scrolling currently).
=> fix: incorrect scroll behavior on failures page (comfort view)

flybywire-aircraft-a320-neo/html_ui/JS/A32NX_Util.js, src/shared/src/notification.ts
Pause events were being captured and not passed through to Simconnect, resulting in problems with 3rd party external addons. This PR fixes this to allow these events to passthrough. No visible change for users.
1. Spawn in any state
2. Use flight assistant menu to enable AUTO TRIM/RUDDER/etc
3. This should spawn the incompatible options alert notification 
5. Press ESC to PAUSE and exit to the menu
6. Notification should now dismiss itself and disappear.
1. Click on the **A32NX** download link at the …
=> fix(notif): passthrough pause events

src/instruments/src/EFB/Utils/routing.tsx
Fixes an issue where clicking on the sidebar button of the current page you are on redirects you to an incorrect tab. This caused a complete crash when going to pinned charts page and clicking on 'Navigation & Charts' button on sidebar.
Discord username (if different from GitHub): Erick [Z-6]#6484
Go to an EFB page with tabs and go to any other tab than the first one. Click on the same link on the sidebar that took you to your page and your tab should not change. Go to Navigation & Charts page and go to Pinned Charts. Clicking on the sidebar link should not cause a crash of the EFB.
1. On the left side, click on …
=> fix: same page tab redirection

.github/workflows/localization.yml
This PR introduces a GitHub action that downloads the latest approved translations from Localazy to make sure they are regularly persisted into the repository. 
It uses an action that either creates or updates a PR with the changes. This PR will then need to be merged to master regularly. Every few weeks or after larger changes to translations should be sufficient. 
Uses: https://github.com/gr2m/create-or-update-pull-request-action
I had this workflow running on a test branch for a while now:
https://github.com/frankkopp/flybywire-a32nx-test/pull/9
Does not influence the aircraft or code at all - just creates/updates a PR. 
Can't be tested by QA.
Every new commit to this PR will cause a new A32NX artifact to be created, built, …
=> build: flyPadOS 3 localization update GitHub action

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FuelPredPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Cleaned up pieces of old code that resulted in double conversion when using LBS as units, in the INIT B/ FUEL PRED page's ZFW values.
=> fix: incorrect conversion in INIT B

.github/CHANGELOG.md, src/instruments/src/EWD/elements/PseudoFWC.tsx
A minor change to the flap and slat angles that may have resulted in an erroneous SLATS NOT IN T.O CONFIG or FLAPS NOT IN T.O CONFIG or during takeoff.
This doesn't fix or change the behaviour of the T.O CONF button, it just updates the angles and ensures the warning is correctly updated.
Start a Flaps 3 takeoff roll. Ensure there is no erroneous FLAPS NOT IN T.O CONFIG or SLATS NOT IN T.O CONFIG warning.
Start a Flaps 0 & Flaps Full takeoff roll. Ensure there are both the FLAPS NOT IN T.O CONFIG or SLATS NOT IN T.O CONFIG warning.
Try intermediate settings. The warning should not appear in positions 1, 2 and 3 and vanish/appear as the flaps or slats move through these positions.
For this test, ignore the T.O CONF push button.
Every new commit …
=> fix(fws): slats warning during flaps 3 takeoff

.github/CHANGELOG.md, docs/a320-simvars.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_ProgressPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/index.ts, src/fmgc/src/navigation/Navigation.ts, src/fmgc/src/navigation/RequiredPerformance.ts, src/instruments/src/ND/elements/CrossTrack.tsx, src/instruments/src/ND/pages/ArcMode.tsx, src/instruments/src/ND/pages/PlanMode.tsx, src/instruments/src/ND/pages/RoseMode.tsx, src/instruments/src/PFD/LandingSystemIndicator.tsx, src/instruments/src/PFD/instrument.tsx, src/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Add support for RNP at or below 0.3 NM. No leg RNP values are available from the MSFS nav database so only flight area default RNPs are automatically set... and the pilot can enter a specific RNP on the PROG page.
Various documents.
- Enter various RNP values on the PROG page. Anything between 0.01 and 20 should be possible.
- Check that clearing the pilot RNP value reverts to the flight area default.
- Check that L/DEV is displayed and showing proper cross-track error when an RNP of 0.3 or less is entered on the PROG page and in the terminal area (SID/STAR/APPR), and otherwise not.
- Check that xtk is shown on the ND with 2 decimals when RNP at or below 0.3 is entred on the PROG page, and XTK is between 0.02 and 0.3 NM, and …
=> feat: rnp at or below 0.3 step 1

src/systems/systems_wasm/src/lib.rs
According to 
https://devsupport.flightsimulator.com/questions/8769/requestdataonsimobject-with-sim-frame-sometimes-st.html
the period SimFrame for receiving simconnect data might be buggy and stop updating. This might explain the issue with deltatime that sometimes appears and causes erratic behaviour. VisualFrame is potentially not affected and this is what this PR attempts to try out.
This should probably tested on exp as there the issue is most present.
1. Fly and observe all systems for unwanted behaviour (hydraulic pressure for example). And of course: no hard banking and the plane should be controllable all the time. 
1. Make …
=> fix: use visualframe to avoid msfs bug

src/systems/systems/src/hydraulic/flap_slat.rs
This PR fixes a bug I introduced in #7221, regarding the impact of the flaps on the sim. Previously, the flaps systems assumed a linear flaps/slats surface angle vs. FPPU angle, and thus calculated the flaps/slat percentage as `current FPPU angle / max FPPU angle`. Now, in #7221, I changed the curve for flaps to a non linear one, which is realistic, as the way that the flaps are actuated creates a non-linear FPPU vs surface behaviour. This has now messed up the flaps angles in the sim, and thus the impact on the FM, since they are written to the sim as percentage. These percentages are now incorrect, due to the non-linear curve. To fix this situation, I have reverse-applied the LUTs, to linearize the flaps percentage. It is now again calculated correctly as `current flaps angle / max …
=> fix(flaps): reverse-apply FPPU LUTs to compensate for non-linear behaviour

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/systems/src/hydraulic/mod.rs
Two issues fixed:
- Too slow leak measurement valves allowed flight controls to move a little bit on cargo door operation start.
- Yellow valve opening as soon as yellow epump is auto shutdown was also allowing flight controls to move due to residual pressure
-Use cargo door.
-Check that no flight control move (including spoilers) when cargo door is used, or when yellow electric pump stops after cargo door operation.
=> fix(hyd): Too slow leak measurement valves operation

src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/a320_systems/src/lib.rs, src/systems/systems/src/engine/mod.rs
Using const generics for fire overhead... to  prepare for bigger planes
Fire handle cuts off the correct hydraulic engine pump.
=> chore: Fire overhead structure using const generics for bigger planes

.github/CHANGELOG.md, src/instruments/src/PFD/SpeedIndicator.tsx
This PR changes the way the barberpole indicators (Vmax, VAlphaProt) are implemented.
Instead of building them from multiple paths, they are now one path and so only translated as a whole. This makes the code simpler, and should help performance at least a tiny bit. It also creates a little visual effect: if you get too fast (or too slow, in case of the Valphaprot bar), the barberpole bar will stop moving with the speedscale. This is verified with multiple videos from FFS (see screenshots section).
This PR is a blocker for implementing the VStallWarn bar for #6913, so it would be great if this could be merged quickly.
Quick note: I had to disable the Eslint `max-len` rule for the path string lines, if there is a way to add linebreaks to strings in jsx please let me know. …
=> feat(pfd): Improve barberpole rendering on the PFD

src/instruments/src/PFD/shared/displayUnit.tsx, src/instruments/src/PFD/shared/pixels.scss, src/instruments/src/PFD/style.scss
Adds the missing backlight bleed for the PFD.
1. Backlight bleed should be identical to all other screens
2. Homecockpit mode disables backlight bleed
=> fix: restore backlight bleed on pfd

.github/CHANGELOG.md, src/instruments/src/EWD/index.tsx
#6910 put the EWD on AC bus 2 for some reason. It's actually on AC ESS. Reported by Discord user Greylock#3800 👍 .
FBW-31-09
Check that the upper ECAM (EWD) is available in EMER ELEC CONFIG... one way is to kill both AC engine gens in-flight.
=> fix(eis): move ewd to correct ac bus

Cargo.lock, src/systems/a320_hydraulic_simulation_graphs/Cargo.toml, src/systems/a320_systems/Cargo.toml, src/systems/a320_systems_wasm/Cargo.toml, src/systems/systems/Cargo.toml, src/systems/systems_wasm/Cargo.toml
Two versions of the `uom` crate were in use (`0.30` and `0.32`) thereby increasing `cargo build` time a bit. This PR consolidates them to the latest version (`0.33`).
I'd skip testing 😉.
=> build: consolidate uom versions

src/instruments/src/EFB/Failures/Pages/Comfort/index.tsx
Adds scrolling to the chapter list of the failure ComfortUI, this is needed for the added chapters in #6913.
=> feat(efb): add scrolling to failure ComfortUI

src/behavior/src/A32NX_Interior_Handling.xml
Fixed CTD when using gravity gear extension handle in the lock interaction mode
Control scheme in legacy mode, release gear by using gravity gear handle
Restart
Switch control scheme to lock mode, then release gravity gear
=> fix: ctd when using gravity gear handle in lock mode

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js, src/fmgc/src/flightplanning/LegsProcedure.ts, typings/asobo-vcockpits-instruments/html_ui/Pages/VCockpit/Instruments/Shared/FlightElements/WaypointLoader.d.ts
Substantially improve procedure loading performance with procedures containing navaids. We don't need intersection data (for airways) for stringing terminal procedures.
Check a number of SIDs, STARs and approaches. Best tested in exp for a while. Check that airways can be strung from the end of a SID.
=> fix(fmgc): improve procedure loading perf

docs/a320-simvars.md
This PR fixes an error in the LGCIU bus docs: In the discrete word 2, the shock absorber compressed bits
were the wrong way around.
=> fix(docs): Correct order of gear compressed bits in LGCIU bus doc

src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
Fixes #7438 
Fix registration decal setting broken by flyPadOSv3.
Spawn with FBW livery.
Turn Settings -> Sim Options -> Dynamic Registration Decal On, check the rego is displayed on the rear fuselage.
Turn the setting off and ensure rego is not displayed on rear fuselage.
=> fix(efb): rego setting

src/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx
For the landing calculator in the EFB, the 'Autoland' 'Yes/No' selection would change when the 'Reverse Thrust' selection value changed. This PR fixes this.
Discord username (if different from GitHub): SpiritZephyr#2349
Verify the 'Autoland' selection doesn't change when the 'Reverse Thrust' selection is.
=> fix(efb): landing calculator autoland selection

.github/CHANGELOG.md, src/instruments/src/EFB/Localization/en.json, src/instruments/src/EFB/StatusBar/StatusBar.tsx, src/simbridge-client/src/components/Health.ts, src/simbridge-client/src/components/Terrain.ts, src/simbridge-client/src/index.ts
Adds the health check status bar icon to the flyPad. 
This can be merged to master as it does not break anything if SimBridge is not running. 
Check if the icon shows the correct state of the SimBridge
=> feat: re-activated EFB status bar SimBridge health check icon 

docs/a320-simvars.md, src/systems/systems/src/navigation/adirs.rs
As the title says. Not used yet, so not testable.
=> feat(adirs): add static pressure to ADR bus outputs

.github/CHANGELOG.md, src/instruments/src/EFB/Ground/Pages/PushbackPage.tsx, src/instruments/src/EFB/Localization/en.json
Adding a switch (persistent) to turn off input from controller for rudder and elevator for pushback. 
This was added as some users use the stick during pushback for switching views or push to talk which sometimes moves the controller beyond the 5% built-in deadzone. This movement resets the movement started by the buttons. 
Turn off Controller Input 
- use buttons for pushback and test that controller input doesn't interrupt movement. 
Turn on Controller Input
- use controller to pushback
- use buttons to control pushback but do not touch controller
- use buttons to control pushback move controller -> pushback movement should stop/reset
Every new commit to this PR will cause a new A32NX artifact to be created, built, and …
=> feat: switch to turn on/off input from controller for pushback

src/simbridge-client/src/common.ts, src/simbridge-client/src/components/Coroute.ts, src/simbridge-client/src/components/Health.ts, src/simbridge-client/src/components/Terrain.ts, src/simbridge-client/src/components/Viewer.ts
ACE was currently not useable because of call the NXDataStore during initialization.
Refactoring the simbridgeUrl sttring-variable to a function call solves this issue. 
Only impacts SimBridge features:
- Health (check the flyPad status bar for the "wifi" symbol - should show a connection when SimBridge is running/connected
- Terrain, Local Files, CoRoute are not yet on master - so nothing to test there. Will be tested in Exp. 
=> fix: ACE fix - refactored simbridgeUrl to function call 

package-lock.json, package.json, scripts/fragment.js
This PR moves the production and PR build piplines to use fragmenter v0.7.0.
This provides better compatibility with clients based on fragmenter <=v0.6.0, although it is not strictly needed. Updating to this is backwards compatible (with the `keepCompleteModulesAfterSplit` option), and provides the following features to new clients:
- File-splitting for files larger than 500MB
- Compressed/uncompressed module size information in the distribution manifest
=> build: move production pipelines to fragmenter v0.7.0

src/instruments/src/EFB/Ground/Pages/ServicesPage.tsx
The flyPad Ground Services page has overlapping divs which caused interrupted click areas for the GPU button. 
This PR fixes these. 
Test for regression on the Ground Services page. 
Change should not have any negative impact. 
=> fix: flyPad ground services page fix overlapping divs 

src/instruments/src/EFB/Ground/Pages/ServicesPage.tsx
Very small improvement of the placement of the ground service page service labels 
Before:
After:
No testing required
=> fix: improved layout of the ground service page service labels

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_MCDU.xml
After several reports of users considering the display being too dark esp. in certain light situations and after SU10 this PR increases the possible max brightness of instruments in the cockpit. 
The values have been checked in dark and very bright situations and also during changing cloud situations. See [0].
Feedback is welcome as this might also be a matter of taste and various opinions. 
[0] 
https://user-images.githubusercontent.com/16833201/194756476-27f4b663-6fbb-411d-bb28-36c77f4ceef5.mp4
Test brightness of any display (PDF, ND, ECAMs, MCDU, ISIS) in as many situations as possible including flying through scattered clouds. 
See if the displays brightness settings (except ISIS which is automatic) cover the required …
=> fix: Increased overall max brightness of instruments

.github/CHANGELOG.md, src/fbw/src/AdditionalData.h, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/failures/FailuresConsumer.cpp, src/fbw/src/failures/FailuresConsumer.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp
Unfortunately #6913 removed many vital data points in the fdr files without adequate replacement. This renders FDR files useles for support purposes (AP Disconnect Analysis, COntroller Input Analysis, High AOA Analysis, etc.). 
This PR attempts to bring these data points back into the fdr files. 
Testing the FDR with this PR only is not possible. It also requires the coversion tool and graph tool. 
But it shoul be test against general issues - basically anything should work as before. Probably best to simply be used in Exp. 
1. On the left side, click …
=> fix: repair fdr data for support analysis 

.github/CHANGELOG.md, src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/systems/src/hydraulic/brake_circuit.rs
Autobrake wasn't following deceleration target properly due to huge gain
Check Low / Med / Max modes
Check plane deceleration in MED and LOW: at engagement it should not jump instantly to max braking, but ramp to 2 in low and ramp to 3 in med.
=> fix(hyd): Autobrake tuning

src/instruments/src/SD/Pages/Hyd/Hyd.tsx
Small improvement to the visuals of the HYD SD page LO AIR PRESS indication for the reservoirs, according to IRL refs.
| Before | After |
| -------|-------|
=> feat(sd): improve LO AIR PRESS indication visuals

src/systems/a380_systems/src/navigation.rs, src/systems/a380_systems_wasm/src/lib.rs, src/systems/systems/src/navigation/ala52b.rs
This PR updates the `a380_systems` for the triple radio altimeter setup of the A380. It also calibrates the radio altimeter heights according to the current A380X model.
We also introduce a minor guard in the ALA52B transceiver modeling to prevent an invalid negative height from being used for the offset timing generation.
Should not be required, as this only tweaks some numbers on the A380.
However if you do have access and want to test, you can try this [systems.wasm (needs unzipping)](https://github.com/flybywiresim/a32nx/files/10003273/systems.zip) file.
1. On the …
=> feat(navigation): update A380 radio altimters

.github/CHANGELOG.md, src/instruments/src/EFB/Ground/Ground.tsx, src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx, src/instruments/src/EFB/Localization/en.json
Closes #7561
- Adds a button to the flyPad Ground-Payload page to deboard all passengers and unload cargo. 
- Changes Icon of boarding button to signify that it can be boarding or deboarding
- Reorders the tabs for the Ground pages to make them more following the procedure flow
https://user-images.githubusercontent.com/16833201/202810935-29098dc6-8cfc-49b2-900e-d0599b6b9a28.mp4
Test loading and unloading payload (manual, SimBrief) and make sure the buttons are behaving correctly and working as intended. 
1. On the left side, click on the bottom **PR** …
=> feat: Added deboarding button to flyPad Payload page

src/instruments/src/EFB/Settings/Pages/AboutPage.tsx
QOL for devs and support to easier recognize the version in the flyPad Settings About page
Open the flyPad Settings About page and check if the new line "Pretty Release Name" is there and showing the correct information. 
=> feat: added pretty release name to flyPad about page

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/RawDataMapper.ts, src/fmgc/src/types/fstypes/FSTypes.d.ts
There is some new navdata available with AAU1. This PR makes use of it while still being compatible with previous versions of the sim. Transition names have actually been there for a long time (the begining?) but were just filled with the waypoint names... now they have the proper names... I still keep the old way as well just for bad navdata e.g. [YWKS in here](https://flightsim.to/file/2862/wilkins-runway-antarctica-ywks) has blank approach transition names. There are flight plan system issues requiring much larger changes stopping the slope appearing on the final/destination leg of the approach.
NZAA RNP23LY
ZQN:
Polderbaan ILS:
Load some approaches and check transition names (if they're different to the waypoint names in …
=> feat(fmgc): transition names and final approach slope

.vscode/settings.json
Changes the Rust default formatter setting for VSCode. The old is deprecated and was replaced.
Not needed as it doesn't change any behavior.
=> chore: Change Rust default formatter

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Menu.js
Fixes the following issue:
https://discord.com/channels/738864299392630914/785976111875751956/1022941254687916132
This pr fixes  LSK6L in ATC MENU not returning to ATSU Datalink Page.
Honeywell H3/H4 FCOM of FANS A+B & C equipped aircraft:
Discord username (if different from GitHub): Bruno_pt99#5802
Check that pressing LSK6L on ATC MENU page returns to the ATSU Datalink Page.
=> fix(atsu): LSK6L ATSU DLK return in ATC MENU

.github/ISSUE_TEMPLATE/bug_report_beta.yaml, .gitignore, scripts/metadata.js
Removed build_info.json (and any references) as build_info.json is not used any longer.
Instead a32nx_build_info.json is used since a while now.
Should have no impact.
Possible places to double check:
- flyPad Settings About page
=> build: Remove generation of build_info.json

.github/workflows/experimental.yml, scripts/cf-cdn.sh, scripts/fragment.js
This PR:
* adds a script to upload to the CloudFlare R2 CDN;
* adds a step in the experimental pipeline to upload it there as well, keeping bunnycdn for now;
* changes the fragmenter module chunk size from 500MiB to 98MiB (R2 supports 100MB uploads at most).
=> feat: upload to cloudflare cdn on exp

src/atsu/src/com/FutureAirNavigationSystem.ts
Added CPDLC addresses used on VATSIM in EPWW FIR.
[LINK 2000+ has been implemented in Poland in 2018](https://www.pansa.pl/usluga-cpdlc-juz-dziala/)
Addresses taken form [Polish VACC's TopSky Config](https://github.com/laxentis/Plugins/blob/master/TopSkyCPDLC.txt).
N/A
It's easier to download the Hoppie ATC client and initiate an ATC session with the intended to test logon code https://www.hoppie.nl/acars/prg/atc/
Logon to any of `'EPWW', 'EPWU', 'EPWB', 'EPWC', 'EPWD', 'EPWE', 'EPWF', 'EPWG', 'EPWJ', 'EPWK', 'EPWN', 'EPWR', 'EPWZ'`
In the MCDU go to ATC MENU/EMER MENU
Verify that only EMERG ADS-C OFF, SET ON* is displayed on LSK 1R and <ATC MENU RETURN on on LSK 6L
1. Make sure you are signed …
=> feat(atsu): EPWW CPDLC addresses

.github/workflows/experimental.yml
Fix for Exp CDN upload workflow
none
=> fix: Fixes CDN upload workflow for CloudFlare

src/fbw_a320/build.sh, src/fbw_a320/src/interface/SimConnectInterface.cpp, src/fbw_a320/src/interface/SimConnectInterface.h, src/fbw_a380/build.sh, src/fbw_a380/src/interface/SimConnectInterface.cpp, src/fbw_a380/src/interface/SimConnectInterface.h
* Ignore `deprecated-non-prototype` warning during C code compilation, this warning is emitted due to the zlib library, and they don't seem to plan to fix this, and instead recommend ignoring it (right now it spams many warnings)
* Use `register_key_event_handler_EX1` instead of `register_key_event_handler`, which is now deprecated.
=> chore(fbw): small compilation fixes to fbw

src/systems/systems/src/hydraulic/linear_actuator.rs
EHA actuators should not use hydraulic circuit flow when in electrical mode.
Covered by unit test
=> fix(hyd): electro hydrostatic actuator do not consume flow when in elec mode

.github/CHANGELOG.md, docs/a320-simvars.md, src/flypad-backend/src/Pushback/Pushback.cpp, src/instruments/src/EFB/Ground/Pages/PushbackPage.tsx, src/instruments/src/EFB/UtilComponents/BingMap.tsx
When leaving the flyPad Pushback page while actually pushing back should set the pushback movement to pause.
This didn't work and this PR fixes this. 
Also minor refactor to allow for better usage via LVARs in external tools. 
Test Pushback in general.
Test leaving the Pushback page while moving. Aircraft should stop. 
=> fix: pushback did not pause when leaving flyPad Pushback page

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, src/simbridge-client/src/components/McduServerClient.ts
Missed a place in the last fix - this should make ACE useable for the EFb again. 
n/a
=> fix: Fixed additional issues which prevented ACE to work

.github/CHANGELOG.md, src/fbw_a320/src/model/SecComputer.cpp, src/fbw_a320/src/model/SecComputer.h, src/fbw_a320/src/model/SecComputer_data.cpp
* Fixes an issue with the ground spoiler full extension, where the spoilers would extend when only one thrust lever was at idle, instead of both.
* Adds a condition to the partial extension, to reduce a possible bounce in the case of improper thrust handling on landing: The spoilers will partially extend when
* The Ground Spoilers are armed
* Both thrust levers are below the CLB notch
* Both MLGs are compressed
https://safetyfirst.airbus.com/app/themes/mh_newsdesk/documents/archives/a320-family-evolution-of-ground-spoiler-logic.pdf
1. On the left side, click on the …
=> feat(sec): ground spoiler logic improvements

.github/CHANGELOG.md, src/fmgc/src/flightplanning/FlightPlanAsoboSync.ts, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/RawDataMapper.ts
Currently the import from the MSFS World Map is officially supported when the The SimOptions setting "Sync MSFS Flight Plan" is set to `Load Only` or `Save`.
Unfortunately this import is still unreliable and needs imrpovement for users who prefer the MSFS World Map over SimBrief.
Current know issues:
https://github.com/flybywiresim/docs/pull/691
Test 1:
`LPPT ROKOB BOMKO ALAMA FTM NEA VRA SSN URUNA IBDER  REPSI  MEBAK  NINTU  MILPA  VADAR  FRI  SUREP  DITON  KUDIS  NUNRI  BETOS  EDDM`
Test 2:
EIDW DE28L D1 DW080 DW682 NEPOD ABIDO PESIT GWC WAFFU ELDAX PIREG SOMIL IRBAL RANUX NEBAX OBAKI BEGAR ELMUR RESIA UNTAD DIKEM ROKIB BABAG PEVAL PUL INTIT MD326 NEVRA KRO LGAV
- Plan a flight via the MSFS World Map
- Use various …
=> fix: Improve import flight plan from MSFS World Map

.github/workflows/master.yml, .github/workflows/release.yml
* Adds CloudFlare CDN upload step to master and stable release pipelines
* BunnyCDN steps are not removed for now
=> ci: upload to cloudflare in master and stable pipelines

.github/CHANGELOG.md, src/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx, src/instruments/src/EFB/Localization/de.json, src/instruments/src/EFB/Localization/en.json
Fixes #7418
Added estimated boarding time to payload view like in fuel view
---
1. Load aircraft with engines off
2. Open 'Payload' on EFB
3. Set PAX and/or CARGO -> watch 'Estimated duration'
4. Change loading time Instant/Fast/Real -> watch 'Estimated duration'
5. Start Boarding -> watch 'Estimated duration'
=> feat(efb): Add estimated boarding time

.github/CHANGELOG.md, src/instruments/src/EFB/Performance/Widgets/RunwayVisualizationWidget.tsx
Currently landing runway widget shows 18/00 when heading is between 1-5 degrees. Runway number should instead be 18/36.
- Open landing calculator page on EFB. Page should first appear with no runway heading (Runway labels ??/??)
- Enter runway heading 0-4. Runway numbers should be 18/36
- Enter runway heading 5-10. Runway numbers should be 19/01
- Enter runway heading 175-184. Runway numbers should be 36/18
- Enter runway heading 355-360. Runway numbers should be 18/36
1. Click on the **A32NX** …
=> fix(efb): landing calculator widget runway shows correct runway heading

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml, src/behavior/src/A32NX_Exterior.xml, src/behavior/src/A32NX_Interior_Handling.xml, src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/a320_systems_wasm/src/lib.rs, src/systems/a380_systems/src/hydraulic/mod.rs, src/systems/a380_systems_wasm/src/lib.rs
Wheelchocks and Safety Cones depended on LIGHT BEACON ON
Cabin announcements (Sounds) depended on LIGHT BEACON
LIGHT BEACON == Switch Position
LIGHT BEACON ON == Actual Beacon Light State
This PR fixes this so that:
- Chocks and Cones are gone when the **switch** is on
- this avoids the case of an unpowered aircraft on the runway or taxiway having them visible
- Cabin announcements only play when beacon lights are **actually on**
- Test chocks & cones visibility in powered an unpowered states depending on switch
- Test announcements playing only when aircraft is powered and switch is on. 
1. …
=> fix: Fixed sound, cones and chocks which depend on LIGHT BEACON (ON)) var

src/systems/a380_systems/src/navigation.rs
Use AC ESS instead of AC 2 bus for the RA 3 power supply. The old configuration was only fitted on early A380 MSNs.
=> fix(ra): use AC ESS for RA 3

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Fixes #7701
Fixes the cabin crew PA announcements playing twice as described in the issue #7701.
Also adds checks if PA system is powered before playing any announcements. 
Power bus for PA is DC GND/FLT and DC ESS
- Check that the cabin crew announcements play correctly when triggers are set (BEACON and power to PA)
- Check that no announcement is played without any power (DC GND/FLT and DC ESS => A32NX_CIDS_IS_POWERED) 
- Check that it does not play twice - esp. when switching on Strobe
1. Click on …
=> fix: PA announcement playing twice and without power to PA

src/fadec/a320_fadec/src/EngineControl.h, src/fadec/a320_fadec/src/SimVars.h, src/fadec/a320_fadec/src/ThrustLimits.h
At some point, the **developer state** variable failed to work as it should (discovered by @donstim and lately ratified by @Gurgel100). This PR fixes and makes the **developer state** LVar (A32NX_DEVELOPER_STATE) usable again with these three states:
- **A32NX_DEVELOPER_STATE = 0**, does not allow to change Fuel settings from the Sim's Fuel UI (only the EFB)
- **A32NX_DEVELOPER_STATE = 1**, allows to change Fuel settings from the Sim's Fuel UI and EFB (useful for development purposes)
- **A32NX_DEVELOPER_STATE = 2**, just like state '1', but without fuel burn. Useful for testing FCOM conditions which requires static weight measurements.
Note: This PR also introduces the small fix that was set on PR#7565 (https://github.com/flybywiresim/a32nx/pull/7565) and was somehow overridden.
Discord …
=> fix(fuel): Dev States effect on fuel management

.github/CHANGELOG.md, fbw-a32nx/docs/Configuration/ModelConfiguration.ini, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.h, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.h
Some few user want to use two axis to control the rudder. This is mostly the case if these users want to use racing pedals instead of flight pedals.
Normally this would not work as input to both pedals is possible which would conflict, In flight-pedals this is prevented by a physical link and also by only using one axis. 
With this PR it is possible to use two axis mapped to the MSFS `RUDDER AXIS LEFT` and `RUDDER AXIS RIGHT` inputs.
The resulting rudder value is the difference between both axis so that conflicting inputs are canceled out. 
This is option needs to be enabled in the file:
https://github.com/frankkopp/a32nx/blob/rudder-left-right/docs/Configuration/ModelConfiguration.ini 
which needs to be placed in the `work` folder of the aircraft. 
```
[flight_controls]
; enable using …
```
=> feat: option to use 2 independent axis for rudder

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/AirlinerCommon.xml
Following up on https://devsupport.flightsimulator.com/idea/14546/prevent-addons-using-default-template-names.html I audited A32NX for any templates with ASOBO prefix (bad!). We don't overwrite any of the Asobo templates in the VFS (good!), but we do have one with a name that clashes with theirs. This shouldn't be a problem for other add-ons unless they try to include our templates from the VFS, but still not great. We actually don't even use it anymore so I've simply removed it.
No functional change => no changelog.
Check that the transponder still works properly.
1. Click on the **Checks** …
=> fix(behaviours): remove unused asobo template

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
The initMcduVariables function does not exist. I suspect a bad rebase at some point introduced it (-e- it was #6716). I've noticed this in the console a few times when doing turnaround flights but never got around to investigating, but I noticed it during a code review today.
None needed.
=> fix(fmgc): erroneous call

fbw-a380x/src/wasm/fadec_a380/build.sh, fbw-a380x/src/wasm/fbw_a380/build.sh, fbw-a380x/src/wasm/flypad-backend/build.sh, igniter.config.mjs, package.json
This PR updates the directories within the igniter build script to point to the correct build output directories for the a380 WASM, making subsequent builds just a bit faster.
Discord username (if different from GitHub): Eearslya#7831
=> chore: Update A380 SimObject output folder

fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs
Accumulator is now loaded in tests that would require it fully loaded.
Unit tests only
=> fix(hyd): fixed failing tests that are sensitive to empty brake accumulator

fbw-a32nx/src/systems/instruments/src/EWD/FOB.tsx, fbw-a32nx/src/systems/instruments/src/EWD/UpperDisplay.tsx
Fixes the FOB display to properly update when the setting for metric weights is changed.
Discord username (if different from GitHub): Eearslya#7831
1. Load into the aircraft cold and dark.
1. Change the Weight Unit in EFB Aircraft Options, observe the EWD readout updates accordingly.
1. Use the EFB to fuel the aircraft, Change the Weight Unit setting again, observe it still updates properly.
=> fix(ewd): Fix FOB display on EWD

fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
When adding the new PseudoFWC to the refactored EWD component, the `realTime` clock event was used as delta time. This event does NOT give delta time, but instead the current unix timestamp, which resulted in massive delta times being given to the PseudoFWC and rendering all timers inaccurate.
This fixes it to use the EWD's actual delta time, as it should have from the beginning.
Discord username (if different from GitHub): Eearslya#7831
1. Load the aircraft, ensure it has at least 3,000kg of fuel.
2. Power up the aircraft via APU or EXT PWR. Wait for the ECAM displays to be available.
3. Set the aircraft's fuel to 2,700kg.
4. Ensure the `L+R WING TK LO LVL` warning does not appear until approximately 30 seconds have elapsed.
Every new commit to this PR will cause a new A32NX artifact to …
=> fix(fwc): Use correct deltaTime for FWC updates

.github/Contributing.md
Trivial fix of link in .github/Contributing.md 
N/A
=> docs: Simple fix of link to resources from Contributing.md

scripts/build.sh, scripts/build_a32nx.sh, scripts/build_a380x.sh, scripts/build_ingamepanels_checklist_fix.sh
With the copying of base files from src/base to out/ files removed from src/base remain in out/ until manually removed in out/ as well our the complete out/ folder is removed. 
This PR changes the build scripts to also use the --no-cache parameter normally used by Igniter to to remove the out/ folder completely therefore forcing a fresh clean build.
QA can't test this
Devs can test is the build script respects the new paramter and that it otherwise works as before. 
1. Click on the **A32NX** download …
=> chore: Added the --no-cache parameter to the build scripts for clean build

scripts/build.sh, scripts/build_a32nx.sh, scripts/build_a380x.sh, scripts/build_ingamepanels_checklist_fix.sh
The recent PR for adding a clean option to build scripts had the flaw that --no-cache could not be used any more while the sim was running (due to locked sound files which couldn't be removed).
This PR adds a separate arg `-clean` for removing the out/ folders. 
It also removes the /fbw-a32nx/bundles folder which was introduced by the Mach build introduction. 
All convenience build scripts got updated:
build.sh
build_a32nx.sh
build_a380x.sh
build_ingamepanels_checklist_fix.sh
It is still possible to use all args as before:
E.g:
`.\scripts\dev-env\run.cmd ./scripts/build.sh -r a32nx --no-cache`
`.\scripts\dev-env\run.cmd ./scripts/build.sh -r a380x -clean`
...
Devs: Try to use the build scripts as before with sim off or on. …
=> chore: Added new arg -clean for build scripts

Cargo.lock, scripts/dev-env/run.cmd, scripts/dev-env/run.sh
Added previously missing MSFS_Network.h header file.
Update to cmake version (not in use currently).
No other updates to versions as updating rust, wasi, binaryen were not working and require additional time to investigate.
Also SU12 it is expected to have a new SDK version which might require a new dev-env anyway. 
Dev only - build and aircraft should work as before. No issues expected. 
=> chore: New dev-env including previously missing header file

fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Very long translations cause issues on the flyPad's fuel page. See screenshots.
This PR adds a max width to at least make the buttons clickable. 
This is a mitigation and not a full fix. The only real fix is to shorten the translations or do a major change to the layout. 
Check Russian and other languages and make sure the page is still ok and buttons clickable. 
=> fix: mitigate flyPad fuel page issue for very long translations

fbw-a32nx/src/systems/simbridge-client/src/common.ts, fbw-a32nx/src/systems/simbridge-client/src/components/Health.ts
When the sim stutters the 200ms timeout can be too short and the healthcheck will report false. That will trigger a reconnect with the simbridge and the recurrent popups that have been reported.
A timeout of 5 seconds should mitigate this issue.
=> fix: increase timeout for simbridge healthcheck

fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Addition to the previous fix for long translations on the fuel page - this fix puts the import box with the start fuel button to the front so that button is always clickable everywhere. 
Check that start fuel button is clickable even for long translations
Check that nothin else is broken on the page. 
=> fix: Mitigation of long transaltions on flyPad fuel page 2

fbw-a32nx/src/wasm/systems/a320_systems/src/air_conditioning.rs, fbw-a380x/src/wasm/systems/a380_systems/src/air_conditioning.rs, fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_air.rs, fbw-common/src/wasm/systems/systems/src/air_conditioning/cabin_pressure_controller.rs, fbw-common/src/wasm/systems/systems/src/air_conditioning/pressure_valve.rs
This PR fixes an issue introduced in #7804 where spawning in the air was triggering a CAB PRESS EXCESS CAB ALT warning. Three fixes were needed:
- Initialization of cabin temperature: ambient when starting on ground, 24degC when starting in the air.
- Outflow valve starting state: was open, now closed. Note that when starting on the ground the OFV will take a couple of seconds to fully open now as soon as batteries are started.
- ADIRS data capture initialization in the CPCs.
Discord username (if different from GitHub): Commander Ga#1548
Spawn in the air and ensure the cabin pressure is initialized at a _reasonable_ altitude (see below for guidance):
**Aircraft Alt -> Cabin Alt (ft)**
39000 -> 8000
30000 -> 6000
20000 -> 4000
5000 -> 1000
Spawn C&D and on the runway and ensure the OFV …
=> fix(press): cabin pressure when starting in the air

fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Change to 2 to match EWD IDLE message.
Check that SPD BRK STILL OUT doesn't show on ECAM during idle descent (need to wait at least 3 minutes to check).
=> fix(fwc): idle tolerance for engine

fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
Tropopause is capped at 36089ft as per irl references.
IRL pictures, ISA table
Discord username (if different from GitHub): mico#3145
Climb above FL360 and ISA deviation should be SAT+56 at all altitudes above FL360 (see ISA table above).
=> fix(sd): ISA deviation fix

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/EWD/N1.tsx
Fixes #7849 
Changed the position of 5 and 10 scales on EWD N1 gauges to reflect RL example given in issue
Before: 
After:
(from #7251)
(negative N2, could that be a new bug?)
My first PR here 👋 
floridude#7158
Load aircraft, power on, turn up brightness on EWD
=> fix: placement of "5" and "10" scale on EWD N1 gauges (#7849)

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Fixes #4236
As soon as the decent phase is started the EFOB and FUEL PRED get dashed out. This happens because the FUEL PRED check is based on the cruiselevel, which will reset on decent phase. In this change the check for cruiselevel will be removed.
Additionally the fuel trip update in f-pln page was changed to a bit more logical and efficent way.
1. Activate DevTools
1. Open Tools -> Behaviors
1. Switch to LocalVariables and monitor "A32NX_DESTINATION_FUEL_ON_BOARD"
1. Init and setup your flight like you always do
1. After FUEL PRED Page is setup and F-PLN / FUEL PRED page is active the "A32NX_DESTINATION_FUEL_ON_BOARD" should be updated as soon as there is fuel consumption (APU/ENGINE).
1. As soon as you're in flight and the F-PLN / FUEL …
=> fix(mcdu): EFOB and FUEL PRED get dashed out at decent

fbw-a32nx/src/localization/README.md, fbw-a32nx/src/localization/build-locPak-translation.js, fbw-a32nx/src/localization/flypad/README.md, fbw-a32nx/src/localization/msfs/README.md
#7862 changed localization build - unfortunately it did not copy the locPak files to the out folder when build locally as the localization build script only runs on GitHub actions (or with argument `local`).
This PR fixes this so that these files always get copied to the out folder no matter if build is done locally or on GitHub.
Translations for flyPad and locPak (MSFS - e.g. A32NX loading tips, etc.) are possibly impacted. 
Both should still work when build via GitHub action or locally.  
1. Click …
=> fix: Fixing localization build script for local builds

fbw-a32nx/src/localization/build-locPak-translation.js
The nightly workflow for localization changes does not have the out folder and therefore failed with the new version of the locPak build script.
This PR fixes this.
none
=> fix: Fix for nightly GitHub localization action

.github/CHANGELOG.md, .gitignore, fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/instruments/src/SD/Pages/Bleed/elements/EngineBleed.tsx, fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic.rs, fbw-a32nx/src/wasm/systems/a320_systems/src/pneumatic/wing_anti_ice.rs, fbw-a380x/docs/a380-simvars.md, fbw-common/src/wasm/systems/systems/src/apu/mod.rs
Fixes #7953
This PR introduces pressure sensors as components in the bleed system. The BMC reads pressure values from those sensors where needed instead of accessing the physical pressure computed by the simulation. In the future, these components will also be subject to failures.
The pressure regulation setpoints and APU bleed air temperature output have also been adjusted to match real life more closely.
For now, very few visible changes are expected. One of the notable ones is that the bleed pressure indication on the BLEED SD page should properly go to 0 when there is no pressure difference to the atmospheric pressure.
The usual stuff
- Start cold & dark
- Turn on APU and APU bleed, make sure pressure shown on the BLEED …
=> feat(bleed): Implement pressure sensors in bleed system

.github/CHANGELOG.md
VNAV features will not be included in 0.11. This updates the changelog to reflect that.
=> fix(changelog): move vnav to 0.11 entry

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/SD/Pages/Fuel/Fuel.tsx
Fixes #7968
Fix amber logic for centre tank xfr valves.
Spawn in the air with centre tanks empty. Ensure centre transfer valves are green when closed in auto and manual transfer mode.
=> fix(sd): fuel xfr valve amber logic

fbw-a32nx/src/systems/fmgc/src/flightplanning/ManagedFlightPlan.ts
Fixes #8057
Fixes a rare bug where the "NEW ACC ALT-HHHH" repeatedly pops up when the lowest climb constraint and the acceleration- or thrust reduction altitude are the same.
This was essentially a floating point error, fixed by rounding the values involved in the comparison.
Try going through the reproduction steps in #8057, make sure the issue does not occur. Maybe also try a different airport to make sure there are no regressions.
=> fix(fms): round lowest climb constraint

fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VnavDriver.ts
#7080 introduced logic to hide magenta/amber constraint circles on the ND in certain flight phases. This also meant that no constraint circles showed up during preflight. This PR makes sure that constraint circles for climb constraints show up in the preflight phase.
After the change
- Try a departure with an altitude constraint on it. Make sure there is an amber/magenta circle around the waypoint on the ND.
=> fix(eis): show constraint circles in preflight phase

fbw-a32nx/src/systems/instruments/src/Common/definitions.scss, fbw-a32nx/src/systems/instruments/src/EWD/EWD.tsx, fbw-a32nx/src/systems/instruments/src/EWD/UpperDisplay.tsx, fbw-a32nx/src/systems/instruments/src/EWD/style.scss, fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/definitions.scss, fbw-a32nx/src/systems/instruments/src/NDv2/FmMessages.tsx, fbw-a32nx/src/systems/instruments/src/NDv2/TcasWxrMessages.tsx, fbw-a32nx/src/systems/instruments/src/PFD/shared/definitions.scss, fbw-a32nx/src/systems/instruments/src/SD/Common/definitions.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Apu/Apu.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Bleed/Bleed.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Bleed/elements/EngineBleed.tsx, fbw-a32nx/src/systems/instruments/src/SD/Pages/Door/Door.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Elec/Elec.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Fuel/Fuel.scss, fbw-a32nx/src/systems/instruments/src/SD/Pages/Status/Status.scss, fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.scss, fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
Fixes #8036 
This PR primarily aims to improve the accuracy of static components (lines, boxes, aircraft shapes etc.) on the SD, EWD and ND. See the screenshots and the mentioned issue for a list of changes. Also note that there may be other inaccuracies on some of the affected SD pages,
but only the issue with grey lines is addressed here.
| Before  | After  |
|---|---|
| ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/08903676-a327-4118-ab59-8d0e3918e57c) | ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/fbe63251-b230-4ef2-af75-d2ba5d203fca)  |
| ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/2e29271a-81c7-43ed-b42a-46cfe5bb2848) | ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/49da697b-93e6-498c-b0ce-98a585739a7d) |
| …
=> feat(sd/ewd): improve visual accuracy for static components

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectedNavaids.js, fbw-a32nx/src/systems/fmgc/src/navigation/LandingSystemSelectionManager.ts, fbw-a32nx/src/systems/fmgc/src/navigation/NavaidTuner.ts
Make ILS auto-selection more robust, in particular de-tuning when no longer needed. Also fixed a small bug where empty selected navaid lines could show up with a frequency of 0.0 only (the blank type changed on the TS side in a refactor, but was missed here in raw JS with no types).
Check that ILS auto-tuning works in a full flight at both ends. Check that switching from an ILS approach to an RNP approach de-selects the ILS.
=> fix(fm): ils auto-selection robustness

fbw-a32nx/src/systems/simbridge-client/build.js
Fixes remote mcdu not functioning because it isn't building (after #8073) 
- Run SimBridge
- Load aircraft (cold & dark or in runway)
- Power aircraft
- Check Remote MCDU works 
=> fix: remote mcdu not building properly

fbw-a380x/src/wasm/systems/a380_systems/src/electrical/alternating_current.rs, fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
As the name says. Changes the fault legend of the AC ESS FAULT light to illuminate when the AC EMER bus is not powered.
The power source for the button is DC ESS, so the light is on when AC EMER is not powered and DC ESS is powered.
=> feat(elec-a380): ALTN ESS FEED P/B FAULT illuminates when AC EMER is not powered

fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx
In my previous PR I erroneouslyadded a "whenArinc429SsmChanged" filter to fcdcDiscreteWord, which prevented the visibility of the pitch protection indicators to be display properly. This has been fixed.
Spawn and make sure the pitch protections are shown as active ("green lines"). Disable ELAC 1 and 2 (or go into alternate or direct law any other way) and make sure the pitch protections are shown as disabled on the pfd (amber crosses instead of green lines)
1. Click on the **A32NX** download link at …
=> fix: pitch prot indicators visibility

fbw-a32nx/src/systems/instruments/src/ISIS/AltitudeIndicator.tsx
Returns the metric ALT setting to its previous default of off.
nothing to test really, just a reversion to the state before the ISIS pr
=> fix(ISIS): Fix up metric ALT default state

.github/CHANGELOG.md, fbw-a32nx/src/wasm/fadec_a320/src/EngineControl.h, fbw-a32nx/src/wasm/fadec_a320/src/SimVars.h
This patch allows the APU to consume fuel (from the left inner tank).
Known issues not fixed by this PR:
- The APU has no fuel flow when the left inner tank fuel pumps are off (https://github.com/flybywiresim/aircraft/issues/8146).
Check that the left inner tank fuel level reduces when the APU is running with the left inner tank pumps on.
=> feat: apu fuel consumption

fbw-a380x/src/wasm/systems/a380_systems/src/lib.rs
Fixes some bugs in the EGPWC code to enable the TERR ON ND in the A380
No testing required.
=> fix(nd): a380 TERR ON ND

.github/CHANGELOG.md, fbw-a32nx/src/localization/flypad/en.json, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx
Adds a textual note to the fuel and payload page when GSX Sync is enabled - see screenshots below.
This should help reduce support requests for people having activated the sync and wondering why the controls do not work/disappeared. 
Test the appearance of the text note on the fuel page when GSX sync is enabled in settings. 
Also if available test fueling and loading with GSX as well (I do not have GSX and could not test this)
=> feat: adding note to UI when GSX Payload Sync is enabled

fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h
Small PR that updates the electrical busses used for the F/CTL computers:
PRIM/SEC Number | Bus
-----|------
1 | DC ESS
2 | DC EHA
3 | DC 1
FACs are no longer connected to any bus, since they only serve as placeholder for the FE functions.
=> feat(efcs): use correct buses for A380 F/CTL computers

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts, fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx, fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/providers/FuelSystemPublisher.ts
The WING TK LO LVL memo has a CTR TK MODE SEL...MAN line that should be away when the button is pressed. This PR hooks the line up to the button. It also tidies some legacy stuff in the EWD instrument and adds a fuel system publisher that can provide all the fuel data.
Run one wing tanks down to < 700 kg. Make sure the CTR TK MODE SEL line goes away when you press the MODE SEL to MAN.
=> fix(fwc): ctr tk mode sel memo line now works

fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fadec_a380/src/FadecGauge.h
This PR replaces usages of `SIMCONNECT_PERIOD_SIM_FRAME`, introduced by #7835 with `SIMCONNECT_PERIOD_VISUAL_FRAME`.
`SIMCONNECT_PERIOD_SIM_FRAME` seems to create issues, where simconnect only sends every 1s instead of every sim frame, which of course causes all sorts of issues. VISUAL_FRAME does not appear to have this issue, so we will use that instead.
=> fix: use VISUAL_FRAME instead of SIM_FRAME for simconnect requests

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, fbw-a32nx/src/systems/fmgc/src/flightplanning/GeoMath.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/LegsProcedure.ts
Introduces basic support for FA legs in  the same fashion as we currently support CA and VA legs. Not sure why we never did this before as a basic measure to improve a lot of SIDs.
In the past (old screenshot from another old PR):
Now, the 2000 foot FA leg is there:
Fly some departures with FA legs. A random selection:
Airport | SID| Runway (B is for both)
-- | -- | --
YBCS | SWIFT8 | RW15
LOWK | KFT1L | RW10L
OIAW | GODM1B | RW12
LEHC | HUE1B | RW30L
OIMM | RAMI1K | RW13B
EDDF | TAU2Q | RW25L
OLBA | LATE1D | RW21
LGSK | SIGF1B | RW01
KGSB | GSB4 | RW26
MMZH | VILT2A | RW09
OIMM | EMES1A | RW31B
OIHR | DEKB1C | RW26
KSDL | MRRIC1 | RW21
OIZH | PIRA1E | RW17B
LELN | ZMR2G | RW05
LFML | MTG6C | RW31L
LFBO | LACO6A | RW14B
UTFA | …
=> feat(fm): basic fa leg support

fbw-a380x/src/wasm/systems/a380_systems_wasm/src/nose_wheel_steering.rs
Correct steering angle of 70/75 vs 75/90 and Animation Degree 360 -> 140.
A380 AC
Testing N/A not needed
=> fix: nose wheel steering for non-320 airbus

fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts
Fixes #8183
Correctly draws the Origin and Destination airport in white instead of magenta. 
It is a one line change and should have no effect on anything but the drawing of the airport symbol on the ND
Test should make sure that when only from/to airports are entered they show up in white on the ND
=> fix(ND): correct color of FROM/TO airport

fbw-a32nx/src/systems/instruments/src/NDv2/shared/map/PseudoWaypointLayer.ts, fbw-a32nx/src/systems/instruments/src/NDv2/shared/map/WaypointLayer.ts
This fixes the color of the course reversal arrow so it no longer becomes magenta or amber depending on the vnav constraint prediction at the waypoint
It also fixes the orientation of the arrow since it used to follow the inbound course but no longer does in the current NDv2 implementation. 
Before:
After:
Discord username (if different from GitHub): \_chaoz_
You can force the course reversal arrow by inserting a hold at a waypoint. 
You need to choose a waypoint with a vnav constraint, or add one yourself.
The prediction will only show on waypoints that are a few waypoints ahead from your current waypoint.
For the orientation, just play with different courses for the hold and the arrow should change accordingly
Every new commit to this PR will cause a new A32NX artifact …
=> fix(ND): fix the color and orientation of course reversal arrow

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts, fbw-a32nx/src/systems/fmgc/src/guidance/lnav/legs/TF.ts, fbw-a32nx/src/systems/shared/src/NavigationDisplay.ts
Fixes #8174
Corrects altitude/flight level formatting with respect to transition altitude and transition level. For constraints we explicitly know their type so we can pick the correct one, but for other altitudes on the MCDU F-PLN page we need to try to guess because VNAV does not provide us this information.
Test some procedures with the transition altitude (PERF TO) and transition level (PERF APPR, labelled as TRANS ALT) set to different altitudes. Make sure the trans alt only affects climb altitudes and the transition level only affects cruise and descent altitudes. See the fixed issue for more context if needed.
1. Make sure you are signed in to …
=> fix(fm): altitude formatting

fbw-a32nx/src/systems/instruments/src/EFB/Assets/A380SeatOutlineBg.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Seating/SeatMapWidget.tsx, fbw-a32nx/src/wasm/systems/a320_systems/src/payload/mod.rs, fbw-a32nx/src/wasm/systems/a320_systems/src/payload/test.rs, fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs, fbw-a380x/src/wasm/systems/a380_systems/src/payload/mod.rs, fbw-a380x/src/wasm/systems/a380_systems/src/payload/test.rs, fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs, fbw-common/src/wasm/systems/systems/src/payload/mod.rs
Fixes bug where using GSX deboarding would instantly deboard the plane
Fixes #8062
Note: You will need GSX to test the first two instructions of this PR
1. Use GSX Deboarding to deboard
2. Ensure that passengers do not instantly deboard and that deboarding completes as per normal. You may have to retry a few times to ensure that it works in all conditions with varying pax amounts. 
With/Without GSX
3. Ensure "Boarding Completed" sound does not play when fully deboarding the aircraft.
1. Click on the **A32NX** download …
=> fix(payload): misc payload fixes after refactor

fbw-a32nx/src/wasm/systems/a320_systems/src/payload/test.rs, fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/lib.rs, fbw-a380x/src/wasm/systems/a380_systems/src/payload/test.rs, fbw-a380x/src/wasm/systems/a380_systems_wasm/src/lib.rs, fbw-common/src/wasm/systems/systems/src/payload/mod.rs
Fixes #7972
- Fixes passenger and cargo loading behavior on turnaround when using GSX caused by several GSX variables returning unexpected data
- Workaround deboarding using buses with GSX causing plane to instantly deboard after the first bus
You will need GSX to test this PR
- Do a full boarding of the plane with GSX (Request boarding, etc) using a jetway
- Do a full deboarding of the plane with GSX (Request deboarding, etc) ) using a jetway
- (Turnaround, do not go back to the main menu and reload the flight) Do a full boarding of the plane with GSX using multiple buses
- Do a full deboarding of the plane with GSX using multiple buses
1. Make sure …
=> fix(payload): workaround broken gsx turnarounds and bus deboarding

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/SD/Pages/Apu/Apu.tsx
Fixes #8198
Fixes #8001
It seems an `L:` prefix before an LVar access was lost in #8118. This caused the APU bleed pressure reading to be shown as 'XX'. This also checks the correct ADR depending on the position of the ATT/HDG switching knob.
Discord username (if different from GitHub): BlueberryKing
When the APU is running, ensure that the APU bleed pressure indication is only 'XX' when
- The ATT/HDG switching knob is in the NORM or F/O position and ADR 1 is off
OR
- The ATT/HDG switching knob is in the CAPT position and ADR 3 is off.
1. Click on the **A32NX** …
=> fix(sd): fix apu bleed pressure indication

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes an issue where the FM annunciator light did not illuminate when it should due to a typo.
Not needed.
=> fix(mcdu): annunciator light not illuminating

.github/workflows/experimental.yml, .github/workflows/ingamepanels-checklist-fix.yml, .github/workflows/master.yml, .github/workflows/pr.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, scripts/setup.sh
- Removes `rm -rf node_modules/` in `setup.sh`, which is overkill and was mostly used for when we built our own version of `msfs-sdk`. Speeds up process for switching branches locally. `npm ci` already does a clean install.
- The option is conserved via a `--clean` flag which can be passed to `setup.sh`, which is done in all CI workfflows
=> build: remove nuking of node_modules/ in setup.sh

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Performance/Widgets/LandingWidget.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/AtsuAocPage.tsx, fbw-common/src/systems/datalink/router/src/webinterfaces/NXApiConnector.ts, fbw-common/src/systems/shared/src/config.ts, fbw-common/src/systems/shared/src/index.ts
Depends on https://github.com/flybywiresim/api/pull/144 ✔️ 
- refactor: move weather source map to shared
Want to share this between the ATSU and the EFB rather than two separate definitions that may get out of sync.
- fix(efb): use weather source map
Map config weather providers to the API sources in the EFB so we actually get the selected weather source (it was defaulting to VATSIM before).
- feat(efb): add aviationweather.gov/noaa metar source
Add NOAA/avitationweather.gov as a METAR source with their new API, from https://github.com/flybywiresim/api/pull/144
- fix(efb): remove non-working ivao taf and metar
IVAO METARs are not even implemented in the FBW API, and the TAF source does not work as the old IVAO API is offline.
- chore(efb): auto-format landing widget …
=> feat: aviationweather.gov(noaa) metar source and efb fixes

.github/CHANGELOG.md, fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileComputationParameters.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/SpeedProfile.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/profile/BaseGeometryProfile.ts, fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx, fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Fixes #8190 
- Various layout improvements of the PERF CLB, PERF CRZ and PERF DES pages.
- Implement option to preselect a managed descent speed.
- Implement CHECK SPEED MODE message.
- Only allow preselecting a selected CLB speed in CAS.
- Allow preselecting a cruise speed as CAS or Mach.
- Show cruise speed as CAS below FL250 and as Mach above FL250.
- Implement option to modify PRED TO altitude on PERF CLB and PERF DES pages.
- Add DES predictions in selected modes.
Limitations:
- No EXPEDITE predictions yet on the PERF DES page.
Discord username (if different from GitHub): BlueberryKing
- CHECK SPEED MODE
- This message should appear when you the Climb or Cruise phase starts with a selected speed on the FCU, but no preselected speed on the respective CLB or CRZ page.
- CLB speed …
=> fix(mcdu): improve PERF pages

fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
On startup in C/D the aircraft plays a master warning until the startup EWD messages are empty. This was caused by the pseudo FWC checking whether the aircraft was on ground only after checking for dual engine failure which meant that the FWC didn't update the on ground status until after the check for dual engine failure and since the on ground status was initialized with false, the dual eng failure triggered on initial load.
This PR changes the order of those checks so that the setting of the on ground status happens first.
Discord username (if different from GitHub): \_chaoz_
just a quick fix that shouldn't affect anything beyond the fwc initialization.
1. start C/D
2. power up the aircraft
3. no master warning should occur
Every new commit to this PR will cause a new …
=> fix(fwc): Fixes the Master Warning on startup

fbw-a32nx/src/systems/instruments/src/ND/ND.tsx
Last PR erroneously swapped VOR1 and VOR2 on the NDs, this is fixed now.
=> fix: capt nd shows VOR1

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/PFD/LandingSystemIndicator.tsx, fbw-a32nx/src/systems/instruments/src/PFD/instrument.tsx, fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
Fixes #8173.
Refactors the ILS info to be more idiomatic and efficient (we don't need to alter the DOM constantly for things that aren't visible), and makes the ILS frequency visible whenever it is valid, with no requirement for a signal to be received as in the refs.
See linked issue.
Try some ILS frequencies and make sure the info at the bottom left behaves properly. Make sure the frequency is always visible when tuned and LS is turned on. Fly at least one ILS approach from outside the ILS range and make sure the info appears correctly.
1. On the left side, click on …
=> fix(pfd): show ils frequency when loc not received

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
Fixes #8281
If runway is undefined (i.e. missing in msfs scenery) the MCDU crashes as it tries to access it for ILS information. This is fixed now   and should have the same behaviour as the Departures page.
1. Choose a FROM/TO pair, where the destination has missing runways in default msfs scenery (e.g. EIDW). Try to select an arrival and ensure the MCDU does not crash.
=> fix: prevent mcdu crash if runway is undefined

fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Services/A320_251N/A320Services.tsx
In my ASU implementation I forgot to re enable the ASU button in the EFB when conditions were right again.
This fixes that oversight.
Discord username (if different from GitHub): \_chaoz_
1. Start the aircraft on the ramp
2. Enable ASU ground service
3. Call for pushback
4. All Groundservices including ASU should be removed and disabled
5. Stop Pushback
6. All Groundservices including ASU should be available again
=> fix(EFB): ASU now correctly reenables after disabling due to moving once stopped

.github/CHANGELOG.md, fbw-a32nx/docs/Configuration/ModelConfiguration.ini, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.h
This PR adds a precontrol to the roll angle controller of the lateral law. Due to this change, the dynamic response `roll rate command -> roll rate` is improved, without affecting the stability of the control law. Due to this improvement in dynamic response, it is possible to reduce the characteristic frequency of the roll rate controller, which will:
* improve the stability margin of the controller, and
* decrease the "strength" of the roll angle hold behaviour of the control law, increasing the effect of wind.
Since the stability margin is improved, it is possible to also increase the maximum simulation rate without affecting the stability of the lateral law. Thus:
* the default maximum simrate was increased to 8
* the default minimum effective fps was reduced to 5.
On my setup, I was …
=> feat(efcs): add precontrol to roll angle controller

fbw-a32nx/src/wasm/fbw_a320/src/model/LateralNormalLaw.cpp
Fixes a small issue where the omega_0 of the roll law was going to either 0 or NaN, when exceeding 400kts CAS, due to the default setting in MATLABs interp1d function to not extrapolate (the maximum x-value of the LUT was 400kts). Now, extrapolation is active and points have been added to ensure a 0-gradient at the edges (i.e. the value remains constant below 0kts and above 400kts).
=> fix(efcs): prevent uncommanded roll over 400kts

.github/CHANGELOG.md, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.h, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.h
Fixes #8325
Adds EX1 event handling support to the fbw events. Although not required currently by the fbw events it still allows 3rd parties to treat the A32NX identically to other aircraft where the EX1 events supposedly are supported. 
[docs.flightsimulator.com/flighting/html/Programming_Tools/SimConnect/API_Reference/Events_And_Data/SimConnect_TransmitClientEvent.htm](https://docs.flightsimulator.com/flighting/html/Programming_Tools/SimConnect/API_Reference/Events_And_Data/SimConnect_TransmitClientEvent.htm)
[docs.flightsimulator.com/flighting/html/Programming_Tools/SimConnect/API_Reference/Events_And_Data/SimConnect_TransmitClientEvent_EX1.htm](https://docs.flightsimulator.com/flighting/html/Programming_Tools/SimConnect/API_Reference/Events_And_Data/SimConnect_TransmitClientEvent_EX1.h …
=> feat: Support EX1 events to be used for fbw events

fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp
Re-add the `Events::` enum name specifier after it was (erroneously) removed in #8326, which causes a large number of conflicts in #7587
=> fix: add enum name after #8326

.github/workflows/master.yml
Installer uses cf and we upload the full package to github as an alternative for the installer.
Removing the upload of fragments to github as I could not find/remember any usage currently
=> fix: remove upload of fragments to github

fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
Fixes #8401
This fixes a small issue with the ELAC 2 powersupply switching logic: the condition for the blue hydraulic status was reversed.
Previously, if the primary supply (DC2) of ELAC 2 was failed, it would switch to DC HOT 2 bus for 30s, after that it would turn off if the blue hyd was powered. In reality, this should have been reversed, i.e. it will switch to the HOT BUS for 30s, and then it will turn off if blue hyd is **low** (the full logic has some more conditions, which are omitted here as they are not modified).
This causes issues during TEFO, as only blue hyd and EMER ELEC is available then: After 30s, ELAC 2 will be switched off, which causes the right aileron to be no longer controlled, thus moving to the neutral hinge moment position, which is deflected upwards, which …
=> fix(efcs): fix blue hyd condition for ELAC 2 standby elec supply

.github/CHANGELOG.md, fbw-common/src/systems/instruments/src/ND/shared/RadioNavInfo.tsx
Fixes #8441
Take the flag bit logic from NDv1 into NDv2 to fix the regression.
Switch the ADF/VOR switches to ADF. Tune ADF1 manually with VOR1 tuned automatically. Check that the M flag is visible. Repeat for ADF2.
=> fix(nd): adf tuning flags

fbw-a32nx/src/systems/fmgc/src/flightplanning/new/DataManager.ts
Fix for fms-v2 branch: Do not explicitly reference the Fmgc namespace/variable, since WaypointFactory is exported via index.ts anyways. In the A380x MFD, Fmgc throws an "undefined" error. 
as discussed in discord
Discord username (if different from GitHub): floridude
Try storing/deleting pilot-defined waypoints. Untested on A32NX so far. 
=> fix: fms-v2 fmgc variable ref

fbw-common/src/systems/shared/src/parseMetar.tsx
Some regions seem to deviate from the METAR standard and add an "=" at the end (e.g. https://www.avmet.ae/mtinfo.aspx) which broke our metar parser. 
This PR fixes this. 
Test if METARs are parsed correctly on the flyPad Dashboard for various ICAOs.
Good examples are WIEE or WILL - but anything from Indonesia seems to have the = at the end. 
(https://aviation.bmkg.go.id/latest/station.xml)
=> fix: parseMetar to accept "=" as eom delimiter

fbw-a32nx/src/wasm/fbw_a320/src/model/PitchNormalLaw.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/PitchNormalLaw.h
This PR introduces a small change in the way the $\theta_c$-Value is generated in the new flare law, primarly, it increases the maximum rate allowed for pitch attitude commmands. This prevents an unexpected pitch down at 50ft RA.
=> fix(efcs): fix pitch down at 50ft in new flare law

fbw-a32nx/src/systems/instruments/src/EFB/Settings/ThrottleConfig/BaseThrottleConfig.tsx
Bug fix for the A380 throttle calibration when using 2 axes
A380 only change
Test 2 axes calibration in the A380
=> fix: Fixed calibration with 2 axes for A380

fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx
Fixes the issue where refueling wouldnt complete and would stop fuel usage by engines or APU
Discord username (if different from GitHub): \_chaoz_
Really just test instant refueling during flight or any other situation where engines or the APU is running.
=> fix(refuel): fix instant refueling when engines or APU is running

fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws.h, fbw-a32nx/src/wasm/fbw_a320/src/model/AutopilotLaws_data.cpp
This PR introduces the following improvements:
1. Improves Autoland flare performance on various runways and conditions.
1. Performance in go-around is improved.
Note: a CHANGELOG entry has not been added by intention (because Autoland improvements are already mentioned recently, therefore this information would be redundant).
One Engine Out (OEO) operations are excluded for now.
Instructions for (1)
Perform an Autoland in different situations (runways, wind) that are capable for automatic landings. 
ℹ️ You can do additional landings on non-certified runways to have a reference on performance, but these landings do not count for the result.
Instructions for (2)
Perform an Autoland with different situations (runways, wind) and perform a normal and a late go-around (late go-around below …
=> feat(ap): improvements to Autoland (part 2)

fbw-a380x/src/wasm/fbw_a380/build.sh
Add new cpp file to build script, this was forgotten in #8483.
=> fix(a380-fbw): add new file to build script

fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp
This PR implements a delay before starting to update the fbw wasm:
* Delay until `A32NX_IS_READY` is true
* Delay until `SIMULATION TIME` is greater than 2s.
This is done to be more in line with the sytems wasm, which implements the same delay.
Previously, the fbw wasm started updating earlier than the systems wasm (particularly in air starts, as `SIMULATION TIME` does not update there until the "Ready to Fly" button is pressed), which resulted in some data generated by the systems, particularly electrical supplies, not being properly initialized when the fbw wasm starts updating. Now, the fbw wasm starts in sync with the systems wasm. This fixes two issues:
1. The FACs now are immediately powered when the fbw wasm starts to update, which gets rid of the FAC fault when starting in the air …
=> fix(fbw): delay init of fbw wasm to align with systems

fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/CdsDisplayUnit.tsx, fbw-a380x/src/systems/shared/src/electrical.ts, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/systems/a380_systems/src/avionics_data_communication_network.rs, fbw-a380x/src/wasm/systems/a380_systems/src/electrical/direct_current.rs, fbw-a380x/src/wasm/systems/a380_systems/src/electrical/mod.rs
=> feat(a380-elec): more accurate dc ess behavior

.github/workflows/a380x-exp.yml
To support easier QA this workflow creates a build of the a380x-experimental qa branch and puts it on the CDN. 
This build only works together with the A32NX and the private a380 repo build. 
n/a
=> chore: Add a380x-exp.yml workflow

fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
Fixes an issue where the 3d throttle were above 0 when in IDLE for the A380X.
With this change it is no longer visible on the levers that reversers are activated as the levers stay at 0 in the A380X. It is still visible in the EWD though - showing REV.
The reverser levers are not yet modelled in the XML (the 3d model has them). Once these are modelled then putting thrust to reverse will move these levers. 
Check if the throttle levers work as before. Other than that IDLE is at 0 now there should be no other changes or effects. 
1. On the left side, click on …
=> fix(A380X): Show 3D Throttles at 0 when IDLE

fbw-common/src/wasm/extra-backend/Pushback/Pushback.cpp
Removed debug output accidentally left in.
not required
=> fix: Removed debug output from Pushback code

.github/CHANGELOG.md, fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml, fbw-a32nx/src/behavior/src/A32NX_Exterior.xml
This fixes the landing lights being able to retract or extend without any AC power. Now they need AC power to move and should that power be lost during movement, they will stop in position and only continue moving once power is restored.
Additionally I also created a LVAR for the current position of the landing lights since it can now be anywhere between 0 and 100 percent extended.
1. Start C/D
2. move either Landing light switch into the OFF position
3. Check externally that no movement has occured
4. Activate ground power
5. Check externally that the lights move to extend
6. move either landing light switch into the retract position
7. wait a few seconds (less than 8)
8. cut ground power
9. check externally that the …
=> fix(lights): Landing Light movement now only possible with power + position LVAR

fbw-common/src/systems/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx
The flyPad Weather Widget started requesting METAR information for invalid ICAOs which when for example entering "EDD," led the api to return ALL available metar and the flyPad to try to display these. This also caused the sim to freeze in some cases.
This PR improves the input validation to avoid this in the future. 
Try to enter valid and invalid ICAOs and make sure the Weather Widget behaves correctly. 
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** …
=> fix: Fixed input parser for ICAO for weather widget

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
The P/D format now accepts an optional leading sign on the distance.
Note: as the feature is not yet implemented, I decided a changelog entry will only cause confusion.
Pylots; not books.
Setup a flight plan, type place/dist format (`<any waypoint/fix/navaid in your plan>/<optional + or - sign, then a distance up to 999.9>` e.g. `OCK/-5`) on the scratchpad and try to insert it into the flightplan; you should get "NOT YET IMPLEMENTED" on the scratchpad. …
=> fix(fms): pd format accepts sign

.github/CHANGELOG.md, fbw-common/src/systems/instruments/src/EFB/Settings/sync.ts
Fixes the default values for boarding rate and align time. Fixes a console error that resulted from the invalid defaults. There is a changelog for boarding rate as it was broken in 0.11, but the align time was only broken in https://github.com/flybywiresim/aircraft/pull/8530 which hasn't been in a stable release.
None.
=> fix: boarding rate and align time defaults

.github/CHANGELOG.md, fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
Fixes #7815 
Updated the SimOptions page to now use loc for values for text under SimBridge connection related settings in EFB.
Updated en.json localization page to include keys that will be used as text in SimOptions setting in EFB
Discord username (if different from GitHub): implasma#0
Turn on FlyPad
Navigate to Settings, then Sim Options page
Scroll down till you get to SimBridge settings where you can see simbridge related settings.
Text should show properly in English (you should be able to see SimBridge Host Machine, This PC, Remote PC etc. in English properly)
1. On the left side, click on the …
=> fix: Add missing localization in efb

fbw-a32nx/src/systems/instruments/src/ISIS/AutoBrightness.tsx, fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.cpp, fbw-a32nx/src/wasm/extra-backend-a32nx/src/LightingPresets/LightingPresets_A32NX.h
Adds an LVar to the offset value of the ISIS brightness which is otherwise automatic. 
This PR makes it possible to store/load this value with Lighting Presets.
Test if the ISIS offset brightness is now stored and loaded via the Lighting Presets. 
=> fix: lvar for brightness offset of ISIS for it support light presets

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js, fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Correctly implements non-cancellable warnings (overspeed and one of the gear not down cases) so they **can** be cleared from the ECAM, but the master warning light and CRC **cannot** be cleared. The overspeed Vfe warnings are also marked as non-cancellable as they were not before.
A32NX:
- Overspeed the plane to trigger the overspeed warning. Press the master warning button and make sure the light + CRC audio stays on. Press CLR on the ECAM control panel and make sure the overspeed warning clears, but the master warning + CRC remains. Press the master warning button again to ensure it still can't cancel the audio + light.
- Trigger a cancellable red warning... I suggest FLAPS NOT ZERO by extending flaps above FL200. Press …
=> feat(fwc): non-cancellable warnings

fbw-common/src/systems/shared/src/aircraftTypeCheck.ts
Temporary fix for getAircraftType - will be redone in PR #8500 or #8599 anyway.
Uses aircraft TITLE simvar which can be overwritten by liveries and is therefore not reliable. 
not required
=> fix: Temporary fix for getAircraftType

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg, fbw-a32nx/src/wasm/systems/a320_systems_wasm/src/nose_wheel_steering.rs, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/flight_model.cfg, fbw-a380x/src/wasm/systems/a380_systems_wasm/src/nose_wheel_steering.rs
This PR fixes two things related to the NWS:
* Enables the sim NWS to move when standing still (was previously only possible visually, but not functionally)
* Enhance the previous hack required to cancel out the rudder effect on the NWS, by limiting the NWS amplitude to the commanded value. This removes jittering that happens when the rudder is moved.
NOTE: There is still the issue that when giving opposite rudder and tiller orders, the sim's NWS command due to the rudder deflection can only be cancelled, but the NWS doesn't steer in the tiller direction as it should. AFAIK. there is nothing we can do about that.
Confirm that
* There is no more slight oscillation in the taxi path when using the rudder (very noticeable when using pedal disc, but …
=> feat(nws): add better NWS hacks

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-build.yml, .github/workflows/pr-semantics.yml
1. Renames the PR action for building the aircraft from 'PR' to 'PR Build' (as well as the file name) so that it is more easily locatable as some PRs may have multiple actions run under the 'PR' label, making it slightly frustrating to find the right build, especially for the QA team. This also improves visibility for working with the repository. 
This PR also updates the 'PR template text' for the new label. 
2. Renames the PR semantic titles action from 'PR' to 'PR Semantics' (as well as the file name) so that it is more identifiable in the checks tab and when working with the repository. 
No QA needed. 
1. Make sure you are signed in to …
=> ci: Rename workflows from 'PR' to more descriptive names 

fbw-common/src/systems/instruments/src/EFB/Checklists/Checklists.tsx
Fixed a small bug that completed checklist in previous flight phases were no longer shown as completed in later flight phases. 
Very simple fix - might not require a test.
If tested then check that checklists stay completed when in later flight phases and that checklist still become "relevant" when flight phases change - good example is after touchdown - this checklist is not relevant while still in the air and it is not checked for completeness (when autocomplete is on) before touchdown.  …
=> fix: Fixed bug in checklist to not display previous checklists as completed

fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/FadecSimData_A32NX.hpp, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp
Fixes Flex TO after fadec rewrite. Units are not consitently used throughout the plane (i.e. flex temp is written with unit "number" and requesting "celsius" does not work correctly in this case).
Fixes #8616
=> fix(fadec): flex temp unit conversion

fbw-a32nx/src/behavior/src/A32NX_Exterior.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/engines.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Exterior.xml, fbw-a380x/src/systems/instruments/src/EWD/elements/EGT.tsx, fbw-a380x/src/systems/instruments/src/EWD/elements/IgnitionBorder.tsx, fbw-a380x/src/systems/instruments/src/EWD/elements/N1.tsx, fbw-a380x/src/systems/instruments/src/EWD/elements/ThrustGauge.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/EngineColumn.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/IgnitionBorder.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Engine/elements/StartValve.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/HydPage.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/elements/Engine.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Hyd/elements/HydraulicSystem.tsx, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp
Changes the units for LVars used in the fadec rewrite to "Number" and fixing all related usages of these vars. 
Also changes A32NX and A380X turbine rotation animation behavior XML to use unit Number.
In general the team has decided to only use "Number" for LVars going forward and refactor existing non-number LVars at a later point in time. 
before:
https://github.com/flybywiresim/aircraft/assets/16833201/f7fa29b0-9e2e-4010-8147-4650afcb95e4
after:
https://github.com/flybywiresim/aircraft/assets/16833201/d9cb1153-32c6-4577-9977-4a34f29654f7
A32NX:
Check turbine rotation animation for different N1 - best visible when starting or shutting down. 
Compare to current master to see if improved 
A380X
Check the Fadec related systems:
* …
=> fix: Changing A380X LVar units used in fadec to Number

fbw-common/src/wasm/cpp-msfs-framework/cmake/TargetDefinition.cmake, igniter.config.mjs
cpp-wasm-cmake task was running every time due to a config mistake. 
This PR fixes it.
Still the A380X PFD build is triggered every time - haven't found a cause yet.
n/a - build only 
=> build: fixed igniter cache config for cpp wasm

.vscode/c_cpp_properties.json, CMakeLists.txt, fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.cpp, fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.h, fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/Fadec_A32NX.cpp, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.cpp, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.h, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/Fadec_A380X.cpp, fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/MsfsHandler.cpp, fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/MsfsHandler.h, scripts/build-cmake.sh
- Makes some fixes to build env. and scripts, especially ensuring the igniter build fails when the cmake script or build fails.
- Adds a new simulation delta time to the C++ framework, which works similarly to the delta time in the old FADEC, accounting for simrate.
- Fixes the delta time used for FADEC calculations to use the sim-rate dependent simulation delta time.
Note: I recommend https://flightsim.to/file/45543/sim-rate-selector for controlling the sim rate if you don't already have a convenient means of doing so.
- Setup a flight at a cruise level in ISA weather (clear skies preset is okay), and achieve stable flight with the AP and ATHR ON.
- Use the chrono to time how long it takes to consume a given quantity of fuel …
=> fix(fadec): fuel consumption at higher simrates

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
**A380X only, no QA needed.**
Disable lower ISIS, until implementation of A380X ISIS is in place.
(to avoid two identical ISIS being shown)
n/a
none
=> fix(a380x): disable lower ISIS temporarily

fbw-a32nx/mach.config.js, fbw-a32nx/src/systems/atsu/fmsclient/tsconfig.json, fbw-a32nx/src/systems/instruments/src/DCDU/index.tsx, fbw-a32nx/src/systems/instruments/src/SD/Pages/Eng/Eng.tsx, fbw-a32nx/src/systems/sentry-client/tsconfig.json, fbw-a32nx/src/systems/simbridge-client/tsconfig.json, fbw-a32nx/src/systems/tcas/tsconfig.json, fbw-a32nx/src/systems/tsconfig.json, fbw-a380x/mach.config.js, fbw-a380x/src/systems/atsu/tsconfig.json, fbw-a380x/src/systems/fmgc/tsconfig.json, fbw-a380x/src/systems/tcas/tsconfig.json, fbw-a380x/src/systems/tsconfig.json, fbw-common/src/systems/datalink/aoc/tsconfig.json, fbw-common/src/systems/datalink/atc/tsconfig.json, fbw-common/src/systems/datalink/router/tsconfig.json, fbw-common/src/systems/tsconfig.json, package.json, pnpm-lock.yaml
Most of our tsconfigs override typeRoots, which stops typescript from finding types in node_modules. Notably that prevented the jest types from being found so our tests were all red squiggles with no hints. This PR adds node_modules/@types to the typeRoots. There was also an issue with one of our dependencies (`esbuild-style-plugin`) requiring a `@types/sass` package which is malformed/empty, and caused typescript to complain about the typing config. The package seems to be unmaintained so we move to a fork that removes this useless dependency: https://github.com/g45t345rt/esbuild-style-plugin/issues/33.
Now our jest tests having typings.
As this PR only shuffles some typing deckchairs there is no QA.
None required.
Every new …
=> fix: typescript type resolution

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, fbw-a32nx/src/behavior/src/A32NX_Exterior.xml, fbw-a32nx/src/behavior/src/A32NX_Interior_Generics.xml
Remove the erroneous gear condition (which was also broken as the gear var loads 100, not 1), and move the template to a more appropriate location.
https://github.com/flybywiresim/aircraft/assets/9995998/1f304e4d-e418-42b7-8d4f-09e1b2fd9c3c
Check that the red parking brake light on the front gear works as in the video above.
=> fix(lg): nose gear park brake light

.github/workflows/pr-build.yml, fbw-common/src/systems/instruments/src/EFB/Navigation/Navigation.tsx, fbw-common/src/systems/instruments/src/EFB/Navigation/Pages/NavigraphPage/NavigraphChartSelector.tsx
Fixes small regression that prevented the plane symbol on the charts from showing.
1. Open a chart in the EFB and make sure the yellow plane symbol is being shown and moves correctly. Also check that it is shown in the proper location (e.g. SIDS/STARS and Taxi charts)
2. Use the "Fit chart to width" and "Fit chart to height" functionality and verify panning and zooming still works afterwards. 
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** …
=> fix(charts): plane symbol not visible

.github/CHANGELOG.md, fbw-common/src/systems/instruments/src/ND/shared/map/WaypointLayer.ts
Fixes #8691
Previously, when the active leg termination was a tuned navaid, the symbol appeared in white. This is incorrect, tuned navaids should appear in cyan. This PR fixes it.
see issue #8691 
There are more errors in the ND symbology. For example, symbols from the EFIS overlay should be behind flightplan symbols. I don't have the capacity to fix these issues at the moment, so I will restrict the PR to this small fix.
- Load up on the runway, tune navaids on the RAD NAV page, make sure they appear in cyan.
- Make tuned navaids the active leg by using a DIR TO for example, check that the navaid is still cyan.
- Check different combinations of EFIS filters, active waypoints and tuned navaids.
Every new commit to this PR will cause new A32NX …
=> fix(nd): fix active leg navaid color

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/fcu.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/html_ui/Pages/VCockpit/Instruments/LegacyA380X/FCU/A380_FCU.js
Clear out the git stash... Adds the TRUE/MAG button on the FCU.
- Spawn in a region at lower latitude (so the magnetic database is available). Press the true/mag button and ensure the PFD and ND switch to true ref mode. Press it again and make sure they switch back.
=> feat(a380x): true/mag button

fbw-a32nx/src/systems/fmgc/src/flightplanning/new/uplink/CoRouteUplinkAdapter.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/uplink/SimBriefUplinkAdapter.ts
This fixes an FMS crash when the route uplinked from SimBrief is DCT without waypoints. A Discord user found this on a WMKK-WSSS routing.
- Generate a route without any waypoints in between
- Uplink using INIT REQUEST
- Make sure the route is uplinked normally
=> fix(fms): fix crash when uplinking DCT route

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Fixes #8732
We now use null instead of undefined for performance data. Fix checks in JS MCDU perf page
1. Load the plane, power up and open the PERF Page on the MCDU. It should show and not blank out.
=> fix: check for null for perf data

fbw-a32nx/src/systems/fmgc/src/flightplanning/new/plans/BaseFlightPlan.ts, fbw-a32nx/src/systems/fmgc/src/guidance/Geometry.ts, fbw-a32nx/src/systems/fmgc/src/guidance/geometry/GeometryFactory.ts, fbw-a32nx/src/systems/fmgc/src/guidance/lnav/TransitionPicker.ts, fbw-a32nx/src/systems/fmgc/src/guidance/lnav/legs/IF.ts
Fixes #8742 
Previously leg sequences of CI -> IF -> TF was not dealt with properly in the geometry computation. This is fixed now.
FMMI RWY11 MJ4E before
FMMI RWY 11 MJ4E after
LPLA RWY 33 REGLA1B after
LPFR RWY 10 BAROK7E after
EGPH ILS 24 via TLA
Fly the listed procedures (with MSFS navdata), make sure that the SIDs are displayed properly with and without speed predictions. Make sure the procedures are flown properly.
1. Click on either **flybywire-aircraft-a320-neo** or …
=> feat(fms): implement intercepts of track-to-fix legs

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/flight_model.cfg, fbw-a380x/src/wasm/systems/a380_systems/src/airframe/mod.rs, fbw-a380x/src/wasm/systems/a380_systems/src/airframe/test.rs, fbw-a380x/src/wasm/systems/a380_systems/src/fuel/mod.rs, fbw-a380x/src/wasm/systems/a380_systems/src/fuel/test.rs, fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs, fbw-a380x/src/wasm/systems/a380_systems/src/payload/mod.rs
This PR adjusts the W/B of the A380. Mainly, it was discovered that the reference datum to model coordinate system conversion was incorrect, resulting in MSFS z-coordinates that were significantly (in order of a few meters) incorrect. This PR now fixes many measurements with the new conversion.
Changes:
* Adjust L/G contact point positions to match correct positions and weighed L/G loadings
* Adjust empty weight to match OEW
* Adjust empty CG to match OEWCG
* Adjust fuel tank positions to match correct positions
* Adjust aero center position to match correct 25% chord position.
Also, this PR fixes many of the A380 rust module W/B parameters, such as fuel tank, cargo stations and empty CG position, that were never updated. It also updates the LEMAC and L/G positions according to the …
=> fix(a380): various W/B fixes

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts
Previously, the FMS would produce nonsensical predictions if an approach with a steeper-than-normal (>3.5°) final approach was selected. This PR fixes this behavior. Note that the TOO STEEP PATH message is not implemented in this PR, this is merely meant to be an improvement over the current behavior.
Perform a full flight to ending in an approach with final approach gradient >3.5°. Ensure predictions in the FMS and on the ND are reasonable throughout the flight and managed descent can be used.
Some example destination airports are LOWI, LFML, EGLC, ENTC.
1. Click on the **Checks** …
=> fix(fms): fix vnav crash on steep approaches

fbw-a380x/src/systems/systems-host/systems/LegacyGpws.ts, fbw-a380x/src/systems/systems-host/systems/PseudoFWC.ts
Changes gpws & FWC on the A380 to take into account the landing flap setting selected on the FMS as there is no dedicated flap 3 button.
FCOM
bruno_pt99
=> fix(gpws/ewd): A380x Flap 3 selection check

fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts, fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
Fixes #8810
Implements the FACF flag for localiser-based approaches, and corrects the glideslope intercept altitude according to ARINC 424 coding rules.
Before:
After:
ARINC 424
No changelog as this is an fms-v2 bug that's never been in a stable release.
Select some ILS approaches of your choice in a flight plan, and check the GS INTCP altitude on the destination VERT REV page against charts.
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the …
=> fix(fms): gs intcp altitude

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Fixes the landing memo logic to use the LGCIU data. This means the memo will not go green until the gear is actually down.
Yes.
Perform an approach. Descend below 2000 feet RA with the landing gear still up; extend the gear and ensure the LDG GEAR DN line does not go green until all 3 gears are actually down (confirm on the wheel page on SD).
=> fix(fws): landing memo gear logic

.github/ISSUE_TEMPLATE/bug_report_a32nx.yaml, .github/ISSUE_TEMPLATE/bug_report_a380x.yaml, .github/ISSUE_TEMPLATE/feature_request_beta.yaml, fbw-a380x/README.md
- Change discord username hint
- Add bug report template for A380X, modify existing one to A32NX (including labels)
=> feat(a380x): New issue template for A380X bug reports

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js, fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts, fbw-a32nx/src/systems/fmgc/src/efis/EfisVectors.ts, fbw-a32nx/src/systems/fmgc/src/flightphase/FlightPhaseManager.ts, fbw-a32nx/src/systems/fmgc/src/flightphase/index.ts, fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts, fbw-a32nx/src/systems/fmgc/src/index.ts, fbw-a32nx/src/systems/fmgc/src/navigation/LandingSystemSelectionManager.ts, fbw-a32nx/src/systems/fmgc/src/navigation/NavaidTuner.ts, fbw-a32nx/src/systems/fmgc/src/navigation/Navigation.ts, fbw-a32nx/src/systems/fmgc/src/navigation/RequiredPerformance.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.tsx, fbw-common/src/typings/fmgc.d.ts, fbw-common/src/typings/fs-base-ui/html_ui/JS/common.d.ts, fbw-common/src/typings/types.d.ts
Fixes #8740
- Rip a bandaid off and refactor the flight phase to use the event bus.
- Selected navaids reset on entering the done phase.
See linked issue.
Perform a full flight. Ensure the FMS works normally. Tune manually some navaids in the FMS. Ensure just after landing (30 seconds) that the navaids are all reset back to auto-tuned navaids (M flags disappear on the ND etc. See the linked issue for a video).
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** …
=> feat(fmgc): selected navaids reset on done phase

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js, fbw-a32nx/src/systems/fmgc/src/efis/EfisSymbols.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts, fbw-common/src/systems/instruments/src/ND/shared/map/ConstraintsLayer.ts
Fixes the following:
- The MCDU F-PLN page no longer shows altitude constraints for xA legs.
- The ND no longer shows altitude constraints or constraint predictions for xA legs.
- The ND now draws the constraint ring shadow correctly, and does not hide it when the CSTR option is off.
- The MCDU F-PLN page no longer shows the ALT CSTR field for xA legs, and entry is disabled for the destination leg too.
Setup a flight plan with an altitude terminated leg in the departure and at least one other altitude constraint.
- Toggle the EFIS CSTR button on/off and ensure the altitude constraint prediction circle(s) on the ND do not change in brightness.
- Ensure the altitude terminated leg does not have an altitude constraint prediction …
=> fix(fms/nd): altitude constraint display on altitude terminated legs

fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/tcas/src/components/TcasComputer.ts, fbw-a32nx/src/systems/tcas/src/lib/TcasConstants.ts
This PR adds Lvars to the TCAS outputs that are necessary to create the TCAS vertical resolution advisory output word:
1. The RA type (crossing, reversal, etc.) which is currently not output
2. The advisory rate to maintain, which is currently only output as the green sector range, which is inconvenient
3. The up and down advisory, which is currently output as the red sector ranges, which is inconvenient.
The word also requires information if the current state is clear of conflict, but I decided that this is out of scope for this PR.
These outputs are currently unused, but will be used in the FMGC PR (#7587) as it will add a TCAS bus shim. A possible future PR could also add the TCAS output bus directly, and change over the PFD to it as well.
For information, the A429 word is structured …
=> feat(tcas): add additional lvars for A429 word compatability

fbw-a32nx/src/wasm/fbw_a320/.clang-format, fbw-a32nx/src/wasm/fbw_a320/build.sh, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fbw_a380/.clang-format, fbw-a380x/src/wasm/fbw_a380/build.sh, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp
Mini-PR to add the NOMINMAX macro define to the fbw, and fix code accordingly. Also adds a separate `.clang-format`-file to the fbw folders, as #8640 changed the global clang-format-config, which would result in huge changes in all fbw cpp files and thus merge conflicts.
=> chore: add NOMINMAX to fbw, revert clang-format change for fbw

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
This PR makes sure that the lateral and vertical revision pages at the destination (i.e the missed approach point) always show the runway ident in the title, rather than the leg ident.
According to pilot feedback
Check the vertical and lateral revision pages of the missed approach points on approaches that do not end at the runway threshold (e.g LPMA RNP A 05, LGSR VOR 15) and make sure that they show the runway ident ("LPMA05", "LGSR15") …
=> fix(fms): always show runway ident on lat/vert rev page

fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs, fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs, fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
This PR updates the ADR low speed warning discretes with the correct logic when unpowered or invalid, and also inverts the discrete 4. It also updates the usages of discrete 4 accordingly.
The logic is as follows (false is open circuit, true is ground):
- Discretes 1-3 are false when at low speed, and true when at high speed, while 4 is inverted.
- All discretes are false when the ADR is unpowered (represented by the IR selected knob being OFF)
- Discretes 1-3 remain in their previous state when the CAS is invalid but the ADR is powered (represented by the ADR p/b being off), while 4 is false in this case.
Currently the only usage of the discretes on the A32NX is for the L/G safety valve. The rest of the discretes are only used in the A380X.
* …
=> fix(adirs): fix ADIRS low speed warning discrete logic

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NavRadioPage.js, fbw-a32nx/src/systems/fmgc/src/index.ts, fbw-common/src/systems/shared/src/RadioUtils.spec.ts, fbw-common/src/systems/shared/src/RadioUtils.ts
Fixes #8944
Fixes VHF frequency entry on the RADIO NAV page.
Also prepares us a little more for transitioning to BCD for frequencies in the FMS.
- Ensure that VOR frequencies in the range 108.00-117.95, in 0.05 MHz steps can be entered on both sides, and frequencies outside that range or spacing cannot.
- Ensure that ILS frequencies in the range 108.00-111.95, in 0.05 MHz steps can be entered on both sides, and frequencies outside that range or spacing cannot. …
=> fix(fms): nav radio frequency entry

package.json, pnpm-lock.yaml, scripts/fragment-ingamepanels-checklist-fix.js, scripts/fragment_a32nx.js, scripts/fragment_a380x.js, scripts/fragmenter_version.js
- Bump fragmenter to v0.8.0
- Specify version in fragmenter scripts
Not needed.
=> build: bump fragmenter to v0.8.0 and specify version

fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnArr.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/common/ConfirmationDialog.tsx
Adds confirmation button to activate approach phase.
FCOM & https://youtu.be/DtIF26FEZug?t=127
Missing ? char on the font file is out of scope for this PR & couldn't find any better reference for the approach button.
bruno_pt99
=> fix(a380x/mfd): add approach phase button confirmation

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cameras.cfg
This PR fixes the wrong default eyepoint in virtual reality (VR). Up to now, the eyepoint was inside the cabin, now it's the default pilot position as in 2D with the red and white ball being correct.
Test eyepoint in VR.
=> feat(a380x/cameras): fixed default eyepoint in VR

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Engine.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
Fixes #8886 
- Fixes detent TLAs to match decals in 3D model
- Fix drag XML code so thrust levers can be dragged again (disabling reverser in the meantime, don't know how to get that to work, and I can't figure it out)
- Fix detent sounds
1. Verify that thrust lever detents matches the decals in the 3D model
2. Verify that thrust lever detent clicks (i.e. sounds) are still audible as expected
3. Verify that dragging the thrust levers modifies the thrust setting (reversers don't work)
4. Verify that HW throttles, and F1-F4 key control still works for the throttle
1. Click on the **Checks** tab on the …
=> fix(a380x/eng): XML fix for thrust levers

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
This PR changes the vertical speed reference for the touchdown sounds to use a derived signal from radio altitude (as it is in the A32NX). This improves correctness in the case of sloped runways.
Land with different vertical speeds also on sloped runways. Ensure sounds are still working.
=> feat(a380): Change touchdown sound to use radio vertical speed as reference

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/cameras.cfg
This PR adjusts and improves the default VR head position.
Test head position in virtual reality (VR).
=> feat(a380): further improved default VR position

fbw-a380x/src/wasm/fbw_a380/CMakeLists.txt
CMake config fixed after files have been chenged/renamed/removed in other PR.
This config allows IDE who use the CMake config to also have syntax highlighting and code navigation for the fbw wasm code. 
n/a - only changes cmake config - no impact on aircraft
=> build: fixes cmake config after other PR changed and removed files.

fbw-a380x/docs/a380-simvars.md, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/interactive-parts.xml
- Delta pressure L:Var has changed, but XML was not, this fix ensures the windows cannot be opened if cabin is pressurized. 
- No testing required
=> fix(a380x/window): Hotfix for Windows in Flight

fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/autobrakes.rs, fbw-a380x/src/wasm/systems/a380_systems_wasm/src/autobrakes.rs, fbw-common/src/wasm/systems/systems/src/engine/reverser.rs, fbw-common/src/wasm/systems/systems/src/hydraulic/reverser.rs
#9074
Autobrake should only disarm from Instinctive Disconnect button if AB is in progress.
Added handling of MSFS AB DISARM binding input
Instinctive disconnect (Autothrottle disc button) should only disarm AB when AB is decelerating (Except in RTO)
MSFS AB DISARM input should always set the AB knob in disarm position
=> fix(brakes): Instinctive disconnect only when AB active

fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts
- Calculates approach speeds without ADR data, enabling FMS predictions when on ground with ADR delivering NCD data
- Fixes TS error in FMC.ts: ``AirlineModifiableInformation['EK'].eoAccAlt`` doesn't exist anymore
Set up FMS on ground without engines started, and ADIRUs on OFF (i.e. not aligned). FMS F-PLN page should show VNAV predictions (speed/alt) if route, weights and V speeds were entered. 
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the …
=> fix(a380x/fms): Bring back predictions on ground

fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx, fbw-common/src/systems/instruments/src/OANC/Oanc.tsx
Fixes #9107 
- Disables the automatic selection of BTV runway at 300ft, which lead to BTV disconnects before
1. **With navigraph linked in EFB:** Perform normal approach with BTV runway and exit selected through the OANS, and BTV armed. Should NOT disarm at 300ft RA
2. **Without navigraph linked in EFB:** Perform normal approach with BTV runway and requested stopping distance selected through the "fallback OANS control panel (MAP DATA)", and BTV armed. Should NOT disarm at 300ft RA …
=> fix(a380x/btv): Remove problematic auto-selection of BTV runway 

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
Turned off emissives for no simulated systems with BPs on upper overhead.
Decoupled the overhead NSS AVNCS switch from the Cockpit Door Video Switch (some previous copypasta).
Discord username (if different from GitHub): Shrike
=> fix(A380x): Turned off PB lights for INOP systems on upper OVHD 

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
Fixes an issue where constraints at the IAF would be discarded when the approach was string to the arrival.
Also removes a `console.log` I accidentally left in in a previous PR.
Before: 
After:
Try entering different destinations, arrivals and approaches, make sure that the constraints at the IAF always matches the charts.
=> fix(fms): merge constraints when stringing

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Fixes #9150 
Reverser, ambient sounds
=> fix(a380x): Sounds update Oct 28th: Reversers, misc (xml part)

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_BaroSelector.js
Remove fs9gps from the FCU baro unit auto init, and fix it so it works (hopefully).
- Set the baro unit to auto in the flypad.
- Spawn at an airport in the USA and ensure the unit auto-inits to in.Hg.
- Spawn in most of the rest of the world and ensure the unit auto-inits to hPa.
- Set the baro unit to hPa in the flypad, spawn in the USA, and ensure the unit auto-inits to hPa.
- Set the baro unit to in.Hg in the flypad, spawn somewhere living in the future, and ensure the unit auto-inits to in.Hg.
1. …
=> fix(a32nx/fcu): baro unit auto init

fbw-a32nx/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/src/systems/instruments/src/EFB/index.tsx, fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
Hides the EFB Setting for loading and synching from and to the MSFS Flight Plan (World Map, etc.) in the A380X until the feature is migrated to the A380X. 
Check regression in the A32NX - should not have any impact and still showing the setting.
In the A380X the setting should be hidden. 
=> fix: A380X temporarily deactivate the MSFS-PLN sync in the A380X

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/FCU/Managers/BaroManager.ts
Fixes #9161
Fixes an issue where the baro presel would not recognise changes in the baro unit after selecting STD mode.
Select STD mode, then change the baro unit selector. Rotate the knob and make sure the pre-sel uses the newly selected baro unit.
=> fix(a380x/fcu): pre-sel not recognising baro unit change

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/GSX.cfg
Remove bulk cargo from GSX profile
After some discussion, we want to remove the bulk cargo from the A380X GSX profile, since the belts were overlapping.
=> fix(a380x): Remove bulk cargo from GSX profile

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Removes AP_DC_new, which shouldn't be called anymore. Regression from state before last sound update. 
=> fix(a380x/sound): Remove old remnant of AP disconnect sound

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/FCU/FcuFsInstrument.tsx
Fixes https://github.com/flybywiresim/aircraft/issues/9092
The OverheadPublisher was not being instantiated anywhere, so the subscription in the Baro/Altitude components was never receiving any events. Now they should show the test values as expected.
Pending model release...
See issue for pictures
Discord username (if different from GitHub): nothematic
1. Load into the sim & power on
2. Press light test switch
3. Altitude should show "88888" and baro should show "8.8.8.8"
1. Click on either **flybywire-aircraft-a320-neo** or …
=> fix(a380x/fcu): altitude and baro instruments should show values during light test

fbw-a32nx/src/wasm/fbw_a320/CMakeLists.txt, fbw-a380x/src/wasm/fbw_a380/CMakeLists.txt
Last update to fbw code did not update the CmakeLists.txt files which are used by some IDEs to understand the code for highlighting and navigation.
n/a
=> chore: added fbw files to CMakeLists.txt

.github/CHANGELOG.md, fbw-common/src/wasm/terronnd/build.sh, fbw-common/src/wasm/terronnd/src/navigationdisplay/display.h
Previously, the terrain NanoVG texture was recreated on every terrain update (several times per second) but this is not necessary and we can instead reuse the same texture all the time as the size of the terrain image never changes (there is a failsafe in place in case this assumption is broken). In order to do this, I had to use the `stbi` library to manually parse the PNG data and then upload it to the existing texture.
This also seems to fix the reported memory leak within MSFS (not within SimBridge) when using TERR display, but to confirm this further, long haul testing would be needed. It appears that creating and then deleting a texture causes a memory leak within the MSFS NanoVG backend.
1. Start a several hour long flight in the A380X …
=> fix(nd): reuse the terrain NanoVG texture and fix memory leak

.github/CHANGELOG.md, fbw-a380x/docs/a380-simvars.md, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/ecam-cp.xml, fbw-a380x/src/systems/instruments/src/SD/SystemDisplay.tsx, fbw-a380x/src/systems/shared/src/EcamSystemPages.ts, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsMemos.ts
On the A380 the ECP ALL button was not active and the cycling through pages had the wrong order.
It also missed the extra pages the A380 has compared to the A320.
This PR changes the index numbers of the pages for easy cycling using the index. 
This includes the public API which uses the index numbers to allow opening a page by setting a LVAR. 
In the A380 power up the aircraft and:
- test all page buttons and ensure the correct page is shown. 
- use the ALL button to cycle though all pages.
- Cycling should start with the page after the currently active page and end with page where it started. 
- It should wrap around and start with the engine page again
- Release the ALL button and press it again - should start a new cycle …
=> fix: A380X fix page cycling with ACP ALL button

.github/CHANGELOG.md, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.cpp, fbw-a380x/src/wasm/fbw_a380/src/model/A380PitchNormalLaw.h
This PR improves the performance of AP guidance in cruise and other situations with a simulation rate of 4x with 30 fps. Higher FPS should work even better.
Perform a flight and try 4x simulation rate especially in cruise.
=> feat(a380x/ap): improved support of 4x simulation rate

.github/CHANGELOG.md, fbw-common/src/systems/datalink/common/src/com/FutureAirNavigationSystem.ts
These stations were lost in #8466 .
=> fix(a32nx/fans): restore portuguese station codes

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnDirectTo.tsx
DIRECT TO selection of active waypoint results in index 0 and thus onModified leads to no action. Changed the condition to check for null in the onModified action to allow selection of active waypoint.
In flight with an active flight plan select the active waypoint as DIRECT TO.
=> fix(a380x/mfd): Fixed DIRECT TO selection of active waypoint does nothing

.github/workflows/master.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
=> ci: fix rename standalone part 001

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/PFD/FlightPathVector.tsx
Fixes #9237
* fix VV display logic caused by incorrect duID checks. CPT VV button was turning on the VV on both PFDs. Both CPT and FO VV buttons will now turn on their respective PFDs only.
During the debugging process, I found the same function getDisplayIndex declared 4 times in different files with 3 different variants. One of them in PFD.tsx returns a different value from the other declarations, this might be due for the refactor to standardise/collect the declaration into a common function instead to avoid more issues in the future.
Discord username (if different from GitHub): Heclak
1. Press the CPT VV pb on the CPT EFIS CP, only the CPT PFD VV should be toggled on/off
2. Press the FO VV pb on the FO EFIS CP, only the FO PFD VV should be toggled on/off
Every new commit to this PR …
=> fix(A380X/PFD): Fix CPT VV button turning on VV on both PFDs

fbw-a32nx/docs/SPAD.neXt/flybywire-aircraft-a320-neo.xml
Updates the SPAD custom event configuration after talking to the SPAD developer. 
Adding correct Categories and Subcategories.
SPAD regularly imports these events in to their default so users don't have to import or set them up themselves. 
n/a
=> docs: Updated SPAD config after clarification with SPAD

fbw-a32nx/docs/a320-events.md, fbw-a32nx/src/wasm/fbw_a320/src/interface/SimConnectInterface.cpp
Adds missing /16 factor for KOHLSMANN_SET, and also add the same factor to the custom event, to facilitate setting inHg with four significant digits.
=> fix(fcu-api): fix KOHLSMANN_SET and custom baro set events

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Fixes #9598 
fixes said issue by removing old requirements for warning sounds
1. spawn C/D
2. make sure no sounds are played when using the fire test PB for example
3. turn on EXT Power
4. wait for initialization of the FWC to complete (5-10sec )
5. use fire test PB
6. warning sounds should play
=> fix(sounds): removed old sound restrictions for warning sounds

.github/CHANGELOG.md, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts
With the FMS reset implemented, we now get a "NO ZFW OR ZFWCG DATA" sensed procedure after every landing. Somehow the flight phase inhibitions were incorrectly filled in the FWS implementation.
=> fix(a380x): Fix "NO ZFW OR ZFWCG DATA" after landing

fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata21-22-23.tsx, fbw-a380x/src/systems/shared/src/OperatingSpeeds.tsx, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts
=> fix(a380x): Fix erroneous "T.O SPEEDS TOO LOW" warning

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts, fbw-a380x/src/systems/shared/src/OperatingSpeeds.tsx
Fixes #9609 
Fixes MFD/FMS error when selecting CONF 1, might crash the FMS on climb
=> fix(a380x/fms): Fix VLS computation for CONF 1

.github/CHANGELOG.md, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/efis-cp.xml
Illuminates ND range & mode selector lights on the efis control panel during light test
bruno_pt99
1) Perform a light test with the airplane powered and verify all the lights illuminate on the range & mode knob as per the screenshot above on both sides.
2) Change ND range & mode settings and ensure the light updates accordingly on the knob.
3) With no power to the aircraft, verify that the range & mode selectors on both sides do not illuminate, even with the annunciation light switch in the test position.
1. On the left side, find and click on …
=> fix(a380x/efis): illuminate range & mode selector during light test

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFpln.tsx
Fixes [#9709](https://github.com/flybywiresim/aircraft/issues/9709)
Rounded the predicted altitudes to the nearest 10
Before:
After:
1. Add departure SID
2. Look at predicted altitudes in the MFD
=> fix(a380x/mfd): fix: round altitude constraints to nearest 10ft in MFD

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/ND/instrument.tsx, fbw-a380x/src/systems/instruments/src/ND/instrument.tsx, fbw-common/src/systems/instruments/src/ND/ND.tsx, fbw-common/src/systems/instruments/src/ND/TerrainMapThresholds.tsx, fbw-common/src/systems/instruments/src/NavigationDisplay.ts
Removes leading 0s on the terrain display for A380X.
Blanks lower elevation if value is 0 on both planes.
bruno_pt99
A380X:
1) Turn on the terrain on ND somewhere and verify the values appear as the screenshots above without leading 0s.
2) Fly over the ocean, ensure lower elevation blanks once it is the lowest elevation displayed, such as the third screenshot.
A32NX:
1) Turn on terrain on ND and verify the values appear with leading 0s. …
=> fix(a380x/nd): Remove leading 0s from terrain elevation

.github/CHANGELOG.md, fbw-common/src/systems/datalink/router/src/webinterfaces/HoppieConnector.ts, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AtsuAocPage.tsx
fix: Use SERVER Callsign as to in the isStationAvailable Method for the HoppieConnector
Fixes #9704 
Fixes #9722 
Changed the `to` Callsign when checking whether a station is available on Hoppie to `SERVER` as that field gets ignored and `ALL-CALLSIGNS` is the only special fake callsign
https://www.hoppie.nl/acars/system/tech.html
https://github.com/flybywiresim/aircraft/issues/9704
1. Power up Aircraft as normal
2. Enter INIT Page
3. Open ATC Communications page -> Ground Requests -> Departure
4. Enter online Station Code
5. Should work instead of displaying "NO ACTIVE ATC"
1. Click on the **Checks** …
=> fix: Use SERVER Callsign for the Hoppie is Station Available Check

.github/CHANGELOG.md, fbw-a380x/src/systems/failures/src/a380.ts, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/failures/FailureList.h, fbw-a380x/src/wasm/fbw_a380/src/failures/FailuresConsumer.cpp
Fixes the erroneous failure codes from the A380, and adds them to the EFB for PRIM, SEC and FCDC.
FCDC only functional after #9694 
Removes PFD failures, they weren't functional and would only make sense with reconfiguration logic implemented. 
No QA required. 
=> fix(a380x): Add PRIM/SEC/FCDC failures to EFB

fbw-a380x/src/systems/shared/src/OperatingSpeeds.tsx, fbw-common/src/systems/shared/src/MathUtils.spec.ts, fbw-common/src/systems/shared/src/MathUtils.ts
There is no need to need temperature here. Add tests to confirm => no QA. Use 1013.25 as ISA sea level pressure rather than rounded 1013.
=> fix(mathutils): remove machToKCas temperature dependency

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js, fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts
Improve robustness of procedure loading, discard procedures that are missing data rather than discarding entire airports.
Sort the procedures in the A32NX FMS (this is necessary when navdata is coming from multiple sources).
This potentially helps with INTERNAL ERROR, and certainly helps with some navdata issues I've seen.
Loading some airports in the A32NX, and ensure the procedures work okay (step through in PLAN mode), and that procedures are sorted in order on the arrival and departure pages.
1. On the left side, find and click on the **PR …
=> fix(fms): more robust navdata error handling and sorting

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx, fbw-a380x/src/systems/instruments/src/MFD/shared/Adirs.ts, fbw-a380x/src/systems/shared/src/OperatingSpeeds.tsx, fbw-common/src/systems/shared/src/MathUtils.spec.ts, fbw-common/src/systems/shared/src/MathUtils.ts
Fixes #9764 
Fixes #9741 
- Also update characteristic speeds when ADR CAS data NCD (i.e. low speed/standstill)
- Remove CI-dependent cruise speed calculation, not mature enough
- Fix speed/mach switchover
- Fix FMS/PERF page formatting: `---` when no value for speeds
1. Set up FMS with CRZ ALT > FL310, confirm #9764 doesn't occur anymore (i.e. managed speed is switching to correct mach speed above FL300)
2. Confirm that characteristic speeds on T.O PERF page show correct speeds, depending on weight
1. …
=> fix(a380x/fms): Fix mach crossover altitude & T/O perf characteristic speeds

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableDeparturesPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsInit.tsx, fbw-common/src/systems/instruments/src/EFB/Efb.tsx, fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AboutPage.tsx, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/TroubleshootingPage.tsx, fbw-common/src/systems/instruments/src/EFB/TroubleshootingContext.tsx, fbw-common/src/systems/shared/src/Troubleshooting.ts, fbw-common/src/systems/shared/src/index.ts
Adds a troubleshooting page under the about page in the EFB for advanced user support. The idea here is to log things that have user visible errors that don't provide enough info to determine the cause, e.g. "INTERNAL ERROR" in the FMS. It is not intended to be a general-purpose error log as it would lose it's usefulness when filled with lots of random messages like the debugger.
Hopefully we can figure out the recent spike in these INTERNAL ERRORs.
Needs https://github.com/flybywiresim/aircraft/pull/9559 merged first (for isMsfs2024 function).
Go to the about page on the EFB, and then click Troubleshooting.. check that the info displayed is accurate and the layout reasonable. If you know of a repro to cause an INTERNAL ERROR …
=> feat(efb): troubleshooting page

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, fbw-common/src/systems/shared/src/Troubleshooting.ts
Always coerce the error to a string before it gets serialised, to ensure we get exception messages in the log.
=> fix: coerce troubleshooting logs to strings

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Same fix as in https://github.com/flybywiresim/aircraft/pull/9772 but for the a380.
No testing needed IMO, same changes as in https://github.com/flybywiresim/aircraft/pull/9772
=> fix: LocalVFar typo in a380 sound.xml

.github/CHANGELOG.md, fbw-a380x/src/systems/shared/src/OperatingSpeeds.tsx
Fixes #9333 
Fixed an issue where vapp was taking the full headwind factor instead of 1/3 of the steady headwind.
Before:
After:
Reference image is linked in the issue #9333 
waveif
=> fix(a380x/fms): Vapp wind correction

fbw-a380x/src/systems/instruments/src/MFD/pages/common/AbstractHeader.tsx
#9765 introduced an error in the flight number display (tried to display an object as string) because of an oversight in the review. 
No changelog needed. 
=> fix(a380x/mfd): Fix callsign display after #9765

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFpln.tsx
Changes softkey navigation in F-PLN page to scroll through "pages".
Disables down navigation softkey once the end of the flightplan is in view.
Adds individual line scroll navigation through KCCU (old softkey behavior).
https://github.com/user-attachments/assets/4e46853f-4350-4b59-99c0-b2dbdf9ea169
https://youtu.be/AI8yFhuEa4Q?t=5201
bruno_pt99
1) Program a flight plan of your choice and go to the F-PLN page on the MFD.
2) Using the arrow up and arrow down keys on the KCCU verify that the FPLN page scrolls line by line.
2.1 Once the start of the flightplan is visible, the up arrow up key does nothing. 
2.2 Once the end of the flightplan is displayed (if you have an alternate, it will be the end of it instead), the arrow down …
=> fix(a380x/mfd): Change soft key behaviour to page & add individual line scroll through KCCU in FPLN

.github/CHANGELOG.md, README.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
Enables the database swap confirmation prompt from Honeywell H4, adds the year to the second database dates, and updates the readme accordingly (let's have more H4 PRs!). Also fixed some layout issues on this page while I'm here.
Before:
After:
Private.
Try swapping nav databases on the A/C status page. You should receive a confirmation prompt as above, and nothing should happen until confirmed. When confirmed flight plan data etc. should be erased (this is the fastest way to "reset" the FMS). The cancel button should cancel the confirmation and do nothing else. …
=> feat(a32nx/fms): add h4 db swap confirm

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/flightplanning/CruiseStep.ts, fbw-a32nx/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/README.md, fbw-a380x/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/DestinationWindow.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/FplnRevisionsMenu.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/InsertNextWptFrom.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFpln.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnArr.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnDep.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnDirectTo.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnHold.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.scss, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsInit.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/common/widget-style.scss, fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/DropdownMenu.tsx, fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/InputField.tsx, fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/RadioButtonGroup.tsx, fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts, fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
Fixes #9486 
Adds step climbs to A380X.
Changes:
Out of scope (i.e. not implemented):
- Optimum step point (requires deeper FMS changes)
- Subscriptions cleanup for pages other than VERT REV to be done in #9807 
Changelog will be added shortly before merge.
1) Load up cold&dark at airport, plan long enough flight (>3h) in Simbrief; Enable "Auto Step Climb" in EFB Realism Settings
2) Fill in FMS as per normal procedures
3) Insert step climbs or step descends (not too close to T/C or T/D, otherwise they'll get ignored)
4) Delete step climbs or descends (clear altitude and/or waypoint field), see whether that works
5) Enter step climb above max FL, should be ignored with "ABOVE MAX FL" message
6) Start flight, take-off, fast forward to cruise (sim …
=> feat(a380x/fms): Add (auto) step climbs; Allow CLB/DES constraint selection

fbw-a32nx/src/systems/fmgc/src/components/fms-messages/FmsMessages.ts, fbw-a32nx/src/systems/fmgc/src/components/fms-messages/TooSteepPathAhead.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/FlightPlan.ts, fbw-a32nx/src/systems/fmgc/src/guidance/Geometry.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/ConstraintReader.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileManager.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VnavDriver.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/ClimbStrategy.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/DescentPathBuilder.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/DescentStrategy.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/GeometricPathBuilder.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/GeometricPathPlanner.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/IdlePathBuilder.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/TacticalDescentPathBuilder.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/profile/NavGeometryProfile.ts, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/profile/TemporaryCheckpointSequence.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFpln.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.tsx, fbw-a380x/src/systems/instruments/src/MFD/shared/NXSystemMessages.ts, fbw-common/src/systems/shared/src/FmMessages.ts, fbw-common/src/systems/shared/src/MathUtils.ts
When the FMS predicts that a segment between two altitude constraints cannot be met, it shows a TOO STEEP PATH marker.
When the aircraft sequences the first of those constraints, the linear deviation (yoyo) will jump, putting the aircraft high on profile. When a vertical profile is predicted to have a TOO STEEP PATH segment, the "TOO STEEP PATH AHEAD" scratchpad message is shown. On the vertical revision page of the legs before and after the marker, the TOO STEEP PATH BEYOND indication is shown.
This affects both the A32NX and the A380X.
- Spawn, enter a flight plan, ZFW, and cruise altitude to ensure you get vertical predictions in the flight plan.
- Enter an arrival/approach segment with a steep descent imposed by the …
=> feat(fms): implement TOO STEEP PATH

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx, fbw-common/src/systems/instruments/src/OANC/Oanc.tsx, fbw-common/src/systems/instruments/src/OANC/OancMovingModeOverlay.tsx
Fixes issue after #9725 
- Reorder layers: Aircraft symbol over every part of the airport map, lubber line over compass rose, compass rose stays static w.r.t. to screen position (doesn't move when panning)
- Disable MAP DATA input field when navigraph not available
- Enable BTV fallback input field again when navigraph is not available
**Important: You need to use a manual build which contains the Navigraph auth secrets for Scenario 2.** 
Download here: https://www.swisstransfer.com/d/84caa995-5956-4644-ad1d-ca51a59d5e52
and unzip to `flybywire-aircraft-a380-842\html_ui\Pages\VCockpit\Instruments\A380X` in community folder
**Scenario 1: No navigraph subscription, use BTV fallback only**
1. If you have a Navigraph ultimate sub, make sure to …
=> fix(a380x/oans): Fix compass rose/lubber line layer order & BTV fallback input field

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/FlightPlan.ts
Fixes a few issues with flight plan modifications:
1. After deleting a discontinuity, it could happen that the turn of the new leg went the wrong way due to the leg constellation. This is fixes by creating a TF leg from the leg after the discontinuity.
2. After truncating the flight plan by insertion of an existing waypoint or using DIR to, the outbound turn would sometimes go the wrong way because the following leg was coded with a forced turn. This is fixed by removing the forced turn on the following leg.
Before: 
After:
Before:
After:
- Fly a procedure with a forced turn, try going DIR to the leg with the forced turn (indicated by a left/right arrow in the FPLN page). Make sure the turn goes the wrong way.
- Clear …
=> fix(fms): remove forced turn on following leg after leg insertion

fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer.cpp
Fixes #9881
Use Mach * 100 for the `FCU_SPD_SET ` event. As SimConnect event parameters are integers, we have to use this convention to send decimals.
=> fix(a32nx/fcu): use mach * 100 for selected mach set event

.github/CHANGELOG.md, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
Fixes issue with rounding the mach speed, which leads to the mach overspeed warning never triggering. 
=> fix(a380x/fws): Rounding error for OVERSPEED warning (based on Mach)

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableDeparturesPage.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_LateralRevisionPage.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_VerticalRevisionPage.ts
- Sort runways alphabetically in departure/arrival selection screen
- Fix not all runways being selectable as runway-only approaches because the list was too short
- Make "Return" button on lateral and vertical revision pages return to the previous flight plan position rather than the top
- Check departure/arrival runway selection is sorted alphabetically
- Check you can select all runways as approaches (no instrument approach, just the runway)
- Go to the lat/vert rev page from the flight plan page, ensure that pressing "Return" puts you back to the original position on the flight plan page
1. Make sure you are signed in …
=> fix(a32nx/fms): sort runways alphabetically

fbw-a32nx/src/systems/instruments/src/PFD/SpeedIndicator.tsx
Fixes red MACH flag shown on PFD when value is NCD. (regression introduced by #9894) 
bruno_pt99
Spawn on the runway and verify no red MACH flag is visible.
With ADR failed, ensure red "MACH" flag appears on PFD. Verify it doesn't appear in other conditions.
Verify mach value appears once > 0.5 during acceleration and disappears once < 0.45 during deceleration
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 …
=> fix(a32nx/pfd): only show mach flag if FW

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts, fbw-common/src/systems/instruments/src/ND/ND.tsx, fbw-common/src/systems/shared/src/simvar.spec.ts, fbw-common/src/systems/shared/src/simvar.ts
Fix alignment of the approach message. It's always 9-chars wide, left-aligned.
Load up an approach, get into at least cruise phase, and close to the destination, and check that the approach message appears correctly aligned (compare to the lubber line).
=> fix(nd): approach message alignment

fbw-common/src/wasm/cpp-msfs-framework/MsfsHandler/MsfsHandler.cpp
From what I could see, the simconnect connection is not closed when the gauge is destroyed. This should be fixed now.
=> fix: close simconnect in wasm framework

fbw-a380x/src/systems/instruments/src/PFD/PFD.tsx, fbw-a380x/src/systems/instruments/src/PFD/PitchTrimDisplay.tsx
Fixes bug/regression with latest auto THS PR: 
The white line for demarking the maintenance position was visible before landing, which should not happen.
1. During engine start, before take-off: White line in PFD pitch trim indicator should not be displayed
2. After landing, when GS below 30kts: White line should appear
=> fix(a380x/pfd): Pitch trim display: White line visibility only after landing when below 30kts GS

fbw-common/src/systems/shared/src/FbwAircraftSentryClient.ts, fbw-common/src/systems/shared/src/PilotSeat.ts
This did not appear in QA as the sentry DSN is not set in QA builds..
MSFS2024 "ingame" status of the GameStateProvider appears to be starting when in walkaround mode. Unfortunately the popup is bugged there and cannot be clicked. In the briefing status it works fine, so I used that for now.
I did not change the MSFS2020 code (it also worked fine with the briefing state but I couldn't test enough).
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 …
=> fix(a32nx): error reporting popup being stuck

fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
Fixes #9854
Fixes an issue where the preselected cruise speed/mach value was shown during the descent phase. This happened because the value was not properly reset.
Go through the steps to reproduce the linked issue. Ensure the issue no longer occurs.
=> fix(a32nx/fms): fix preselected cruise speed/mach value showing in the descent phase

fbw-a380x/src/systems/extras-host/modules/light_sync/LightSync.ts
Fixes #9969
Set the RMP brightness semi-correctly, as best as we can while we still support FS2020. The XML watches the localvar so will update the IE state when it's changed.
Spawn in the A380X, rotate the RMP knobs and make sure the brightness doesn't jump, per the linked issue.
=> fix(a380x/extras): set rmp brightness correctly

.github/CHANGELOG.md, fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
Fixes #10037
Add the proper condition for going amber with TO CONF in phase 2. Trivial enough change to not require QA I think, especially as it would be hard to do unless you know how to set the flight phase manually. The previous condition was simply the wrong one, which shortcutted the proper logic in other phases as well.
If somebody does test it, you can see the repro in https://github.com/flybywiresim/aircraft/issues/10037. …
=> fix(a32nx/fwc): pred w/s off memo to conf colour

.github/CHANGELOG.md, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg, fbw-a380x/src/systems/instruments/src/FCU/Components/NdData.tsx, fbw-a380x/src/systems/instruments/src/FCU/style.scss
Partial of #9889
Texture size reduced to 2560 in preparation of model update to change UV layout
Tried reducing it to 1280x1280 but the gauges would be pixelated. 2560 is the lowest without pixelated. Could consider reducing it to 2048 but might result in diminishing returns.
Discord username (if different from GitHub): Heclak
1. Load aircraft and turn on annunciator test mode. Change that FCU labels are still in the correct place.
2. Interact with the FCU to change values and check for rendering errors. This might appear as large fonts. This PR doesn't fix any existing FCU bugs like in #9636 
1. On the …
=> feat(a380x/fcu): reduce fcu texture size from 5120 to 2560

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/BleedPage.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedApu.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedEngine.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedGauge.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedGnd.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedHotAir.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedMixerUnit.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedPack.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/Valve.tsx
This PR improves the visuals of the BLEED SD page, and adds/changes the following indications and logics:
* APU duct and valve indications no longer depend on pack status, but only on APU valve position
* Improved and more granular crossbleed indications, now only depending on crossbled and APU valve position and no longer pack status
* Engine bleed duct indication now depends on engine bleed valve, and crossbleed and APU valves depending on engine position. No longer depends on pack flow control valve
* Mixer unit bleed air user indication color now uses pack flow control valve and ram air inlet, no longer engine 1 and 2 HP valve position.
Make sure the bleed indication changes mentioned above make sense in various bleed system conditions. …
=> feat(a380x/sd): Improve SD BLEED page visuals and logic

fbw-common/src/systems/shared/src/ViewListenerUtils.ts, fbw-common/src/systems/shared/src/failures/failures-orchestrator.spec.ts, fbw-common/src/systems/shared/src/failures/failures-orchestrator.ts, fbw-common/src/systems/shared/src/index.ts, fbw-common/src/typings/fs-base-ui/html_ui/JS/common.d.ts
Fix the RegisterViewListener typing and fix this call. This didn't cause any user-visible issue as you would only need it to work when you reload a WASM gauge in-flight while some failures already exist on the orchestrator, so no changelog.
Not testable.
=> fix(efb): failure listener registration

fbw-a380x/src/systems/systems-host/systems/Communications/AudioManagementUnit.ts
Fixes an issue where the AMU would not read the RMP states correctly, and end up falling back to the offside RMP.
Check that the COM RECEIVE EX1 and COM TRANSMIT vars line up with the selections on the pilot's RMP (either auto or manually selected in flypad sim settings).
=> fix(a380x/rmp): amu not reading rmp state

fbw-a32nx/src/systems/instruments/src/PFD/AltitudeIndicator.tsx, fbw-a380x/src/systems/instruments/src/PFD/AltitudeIndicator.tsx
Fixes the metric altitude not working since #9659. I missed the wonky pattern with the state object inside the component when bulk updating the altitude consumers. Copied the FIXME from the 320 to the 380 PFD as well. Didn't want to fix the whole thing here as I want a quick fix that can be merged straight away.
=> fix(pfd): metric alt dead

fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/TopTabNavigator.tsx
Fix color of the outside edge of the MFD tabs not matching the label. The colour of the tab should be uniform.
BEFORE
AFTER
Check tabs color are uniform.
=> fix(a380x/mfd): fix mfd tab navigator outer edge color styling

fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsFlightPhases.ts
Change the A380X to use Simplane like the A32NX for now to work around the logic being inadequate.
Capture an FCU altitude in STD mode. Adjust the baro pre-select so it's more than 200 feet different to pressure alt and make sure there's no c-chord.
=> fix(a380x): fix c-chord when baro alti changes in std

.github/CHANGELOG.md, fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/AircraftOptionsPinProgramsPage.tsx
Rename the "Weight Unit" pin program to it's actual name "US Units", and turn it into a toggle. Many users were confused when it affects more than just weights.
Before:
After:
Make sure the option still works on the weights, runway lengths, and cabin temperatures.
=> fix(efb): rename us units option to reflect reality

.github/Contributing.md, scripts/build.sh, scripts/build_a380x.sh, scripts/dev-env/run-local.cmd, scripts/dev-env/run.cmd
Allows the 4k texture variable to come from the environment, and loads the .env into the container for local builds. Now I don't need to try remember the -4k flag when I work on the 380.
=> build: allow USE_4K_TEXTURES to be defined by environment

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts
Fixes #10155 
Improved arrival runway length display: replaced fixed meter value with user selected unit using `NXUnits.mToUser(...)`, including proper formatting and alignment.
Discord username (if different from GitHub): lucasiq
1. Enable US units on EFB
1. Load a flight plan
1. Check rwy lenght units in the arrival page
=> fix(A32X/MCDU): use NXUnits on arrival airport runway lengths

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/LegacyFmsPageInterface.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_InitPage.ts
Fixes #10171
Fixes the automatic cruise temperature calculation to follow the ISA profile
Before:
After:
- Load in
- Enter a cruise level on INIT A
- Make sure it corresponds the the ISA temperature using some online tool for example.
=> fix(a32nx/fms): fix automatic cruise temperature calculation according to isa

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/guidance/vnav/VerticalProfileManager.ts
Fixes #10148
Changed the operator so the message can only be shown less than 150nm from destination airport.
manual
jonny_23
1. Load into aircraft at an airport such as LPMA or LPPT.
2. Program MCDU with the destination LPLA, ILS 33 via CUDLY.
3. Takeoff and reach cruise phase, ensure TOO STEEP PATH AHEAD message isn't shown.
4. Once aircraft is less than 150nm from LPLA ensure the TOO STEEP PATH AHEAD message is show on the MCDU in amber. …
=> fix(a32nx/fms): fix incorrect TOO STEEP PATH AHEAD message logic

fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_Core/A32NX_GPWS.ts, fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/flaps_computer.rs
This PR adds the implementation of the FAP discrete outputs from the SFCC
Not necessary
ATA 27-50
N/A
Discord username (if different from GitHub): python
Perform normal landing with FLAPS 3 (and FLAPS 3 pushbutton): verify no alarms from EGPWS
Perform landing with FLAPS FULL: verify no alarms from EGPWS
Perform landing with FLAPS 2: verify EGPWS alarm goes off
=> feat(a320/sfcc): added implementation of SFCC FAP discrete outputs

fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h
I have completed binding of LGCIU DISCRETE WORD 4 to the LVAR in FBW
Not necessary
N/A
I added support for LGCIU DISCRETE WORD 4 in #10115, but I didn't notice that there was a placeholder for LGCIU DISCRETE WORD 4 in the FBW code.
This Arinc word is currently unused in the FBW library, therefore it doesn't have an impact on the simulation.
Discord username (if different from GitHub): pythonist
Both A320 and A380: Perform a standard circuit and verify normal aircraft operation. …
=> feat(fbw): completed LGCIU A429 interface in FBW

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx, fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts
Just a small PR that implements the BAT 1 OFF and BAT 2 OFF ECAM messages.
- Ensure warning does not show up if battery is off and both engines are off.
- After having started an engine, turn batteries off one by one, ensure correct warning shows up. No master caution should come up with the warning.
- If the batteries are turned off in-flight or during takeoff, the warning should only show up after about 60 seconds in the air and not while in T.O INHIBIT.
- Make sure the ELEC system page shows up when the warning occurs.
1. On the left side, …
=> feat(a32nx/fws): implement BAT 1(2) off ECAM message

fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/instruments/src/EWD/shared/EwdSimvarPublisher.tsx, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_Core/A32NX_GPWS.ts, fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.h, fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/flaps_computer.rs, fbw-a32nx/src/wasm/systems/a320_systems/src/hydraulic/mod.rs, fbw-a380x/docs/a380-simvars.md, fbw-a380x/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx, fbw-a380x/src/systems/systems-host/CpiomC/FlightWarningSystem/FwsCore.ts, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.h, fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/flaps_computer.rs, fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
This PR adds the simulation of a dual SFCC.
Failures and cross-talk aren't implemented. All readers of SFCC ARINC words are set to use `SFCC_1`.
Not necessary
ATA27-50 system
To be merged after #10151
I would like to continue the work started in the draft PR https://github.com/flybywiresim/aircraft/pull/7632 which aims to rewrite the SFCC. Instead of making a big PR, I would like to make incremental changes.
Discord username (if different from GitHub): pythonist
Test on A320 and A380.
With plane ready for takeoff, move the flaps lever through all the positions and verify that the flaps/slats move accordingly on the external model and the EWD.
1. …
=> feat(sfcc): implemented dual SFCC simulation

fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_Core/A32NX_FWC.ts
Fixes takeoff config button not triggering takeoff memo
=> fix(a32nx/fws): to config button not triggering TO memo

fbw-a32nx/src/wasm/fbw_a320/src/recording/FlightDataRecorder.cpp, fbw-a380x/src/wasm/fbw_a380/src/recording/FlightDataRecorder.cpp
Handle the failure if opendir fails and returns NULL. Fixes an infinite loop in readdir in SU4 beta.
Devsupport post: https://devsupport.flightsimulator.com/t/su4-readdir-fails-when-theres-an-open-handle-on-child-file-entry/16720
Spawn either A32NX or A380X in SU4 beta, and ensure it doesn't lock up the sim.
=> fix(fdr): handle opendir fail
