A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js
The page is not ready, but i thought you might want to give a look at it
=> new branch for my upcomming ECAM bleed page

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
probably not the best way to do this, first time tinkering with js. but it works and does not glitch with the fuel page
kindly do not commit unless code is reviewed
=> EICAS starts on door page

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
once the apu is shutdown and N% back to 0, the apu page shows XX on the gauge
=> APU page now shows XX on apu shutdown

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml, A32NX/layout.json
- Included PCK for sounds.
- Modified sounds.xml for removal of 60 & 70 foot callouts
=> Removal of callouts

.gitignore
Fixed .gitignore (again).
Need that .DS_Store in there for the Mac programmers!
=> Fixed .gitignore (again)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/layout.json
Corrected various wrongly displayed modes on the FMA, none of these modes should have been appearing with FD disabled.
=> Corrected various wrongly displayed modes on the FMA with FD disabled.

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/layout.json
This PR will change the ADIRSTimer depending on the latitude.
Links to #150
=> IRS Align time based on latitude

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml, A32NX/layout.json
=> IRS Align Time

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.js
reworked the gauge completely. removed the gauge disapearing when power is off
=> Completely modified BRK Gauge

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/layout.json
Fixed various FMA issues, again.
=> Fixed various FMA issues, again.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPATE.md
Allows people to submit issues via a template. This makes things a lot cleaner and a more eye friendly environment.
*An example of what a Issue looks like*
=> Add Issue and PR template

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/en-US.locPak, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/layout.json
Fixed various FMA issues, improved overall logic too!
=> Fixed various FMA issues.

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
=> fix apu stuck in shuttingdown

A32NX/.editorconfig
=> build: change newline to CRLF in .editorconfig

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Corrected typo in FMA code, fixes error on APPR hold pressed.
=> Corrected typo in FMA code, fixes error on APPR hold pressed.

A32NX/build.py
Created by BiologicalNanobot#5285, approved by kiwi2021#0001
=> Build.py changes

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
On spawn it would acknowledge and remove all EICAS Memos. This line prevents it from happening. 
All credit to Discord ID: BiologicalNanobot#5285 (filed on behalf)
=> Fix Indication acknowledged on spawn

A32NX/.editorconfig
See discussion in #340.
I swear this is the last one 😆
=> build: set trailing newline to false in .editorconfig

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/Shared/MFD/NDInfo.js
=> add vanilla NDInfo.js

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
=> fix(fma/thrust): change LVR MCT logic

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/ILSIndicator.js
Adds support for 'G/S*' and 'LOC *' FMA modes, fixes 'THR CLB' appearing when on the ground.
Needs testing from the public before it's merged! 👍
=> Adds support for 'G/S*' and 'LOC *' FMA modes, fixes 'THR CLB' appearing when on the ground.

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/layout.json, A32NX/manifest.json
This PR fixes #402 and changes are inline with soon to be implemented ELEC systems so that no changes/bare minimal changes may be required once ELEC systems are implementede.
=> Fixed issue with self test turning on incorrectly on APU/GPU state change

A32NX/layout.json, A32NX/manifest.json
=> update layout and minfest

.github/Contributing.md
Add contributing.md to establish a consistent workflow
=> Add Contributing.md

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml
=> fix seatbelts and other switches

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes #466 
Fixed climb phase activating when spawning at high altitude airports
=> Fixed climb phase activating when spawning at high altitude airports

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Airbus_A320neo_Checklist.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Streamlined the checklists and made correction according to the new SOP published in the discord.
I also added instrument highlighting where possible without modifying modelbehaviourdefs.
https://i.imgur.com/NcQ3mN1.png
TODO for checklists: Add PartIDs for instruments in modelbehaviourdefs where possible to implement highlighting for most instruments. After that I will work on evaluation of checklist items through simvars.
=> Streamlined checklists, added highlighting where possible.

A32NX/build.py
Fixes #432
Adds effects directory to build script so the effect files are loaded properly. This was causing issues with the takeoff/taxi lights, as well as ambient light problems.
=> Add effects directory to build script

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
* Fixed TO CONFIG warnings not appearing.
* Fixed CONFIG PARK BRAKE ON warning formatting.
* Fixed TO memo appearing too early.
=> Fixed issues with TO memo and config warnings

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Closes #474 
* Added CABIN......CHECK to ECAM memos
* Changes to CABIN READY when ALL, FWD, or AFT call button is pressed.
* Resets when flight phase changes
=> Added CABIN......CHECK to ECAM memos

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
Fixes #199
* Adds functionality to the F/CTL rudder indicator.
=> Add moving rudder to F/CTL ECAM page

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
Corrects chrono reset behavior so it behaves realistically.
from FCOM: 
I honestly should have double checked this before submitting the second PR, but lacked the documentation at the time.
=> Correct chrono reset behavior

.github/Contributing.md, docs/resources.md
Add links to Dga's devtools, and tips for developing.
I have seen a lot of people who don't yet know about the tools we have available now. I made these changes so there's an easy place to go for this information.
=> Add dev tools and teps to resources.md

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/layout.json, A32NX/manifest.json
The mod adds the sidestick cursor displayed in ground mode.
=> Add ground mode sidestick cursor

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
fixing a simple logic error from previous PR to fix self test when spawn on runway
=> fix cold and dark logic

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js
=> make ND compass spin after alignment

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/systems.cfg, A32NX/effects/LIGHT_A32NX_BeaconBellyOmni.fx, A32NX/layout.json, A32NX/manifest.json
Fixes #384 
The current pull request fixes the beacon lights so they won't bleed into the cockpit.
**Screenshots**
_None Provided_
_None Provided_
=> [Beacon Lights] There're no longer bleeding into the cockpit

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.js
Fixes # Quick fix on brakes now it's tied to wheel RPM
This quick fix is stop the brakes from heating when in flight , no more pressing brakes in air and having brakes over heat
NONE - check code for the changes 
=> Replace ground with RPM

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Added dummy switch for TCAS
- Starts in STBY
- Variable L:A320_Neo_ATC_TCAS
=> Added Dummy TCAS switch with variable for usage

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Fixes #593 and Fixes #580 
* Changes LDG LT memo logic so that the memo is shown when at least one landing light is extended (according to FCOM in issue #580)
* Adds NW STRG DISC memo when in pushback
=> Small additions/fixes

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js
Fixes #609
Add Barometer display to ISIS. 
Before:
After:
Reference:
I decided to go with displaying both units (as seen in some 320s) for now until we can get the appropriate menu systems to change that display.
=> Display barometer readout on ISIS

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
Partially fixes and required for https://github.com/flybywiresim/a32nx/issues/499
- Create waypoint vertical revision page frontend
- Show proper constraints for waypoints in the flight plan page
- Switch to flight level display if alt is higher than trans alt in the flight plan page
[https://i.postimg.cc/qRWBvXmh/FP.png](https://i.postimg.cc/qRWBvXmh/FP.png)
[https://i.postimg.cc/G3knDCtS/vert.png](https://i.postimg.cc/G3knDCtS/vert.png)
~~Edit logic NYI for vert rev page, read only for now.~~
UPDATE: Added limited altitude restriction editing functionality, see commit message for details.
=> [CDU] Create waypoint vertical revision page frontend and correct some flight plan displayed values

A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Added Fire Buttons lighting up on test
https://gyazo.com/dd5465cd15b773ba046f5b58925d574e
https://gyazo.com/95a326eed86a2187eefec06d1dffa25e
https://gyazo.com/bde1951b5f8b48d65d97ea905c28508e
Not the prettiest solution but they dont have any emmisive parts so its the best we can do i believe
=> Added Fire Buttons lighting up on test

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Init value at Norm as stated by Jayzee
Switch should remain in Norm unless abnormal ops
=> Added Dummy AudioSwitching knob on top overhead

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
Fixes #562 
* Fixed flight phase not changing to takeoff on a second flight without reloading the aircraft
=> Fixed flight phase stuck in takeoff

types/types.d.ts
* Added more functions etc. in types.d.ts
=> Even more type annotations

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #679 
APU Fire Test button no longer says INOP.
Discord username: Sabes#8668
=> Fix #679 APU Fire Test "INOP"

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Partially addresses #533 
fixes= "text in top left and right should be flush with corner of screen"
Allings title to top ( ILS, VOR TEXT )
=> MFD/ND Text position fixes

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
Small fixes/improvements in the checklists:
- Audio Switching Panel no longer INOP
- ALT Windows > ALT Window
- INT Reception Knob is INOP
- Seatbelt Signs don't have AUTO
- Weather Radar Tilt is INOP (was missing in 1 of the many occurences)
- TCAM > TCAS, which is not INOP (was done in the Checklist.xml but not in the  Library.xml)
=> small improvements to the checklists

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.js
Brought A320_Neo_FCU.js in line with the Asobo changes in 1.8.3.0, see #719
Discord username (if different from GitHub): DoTo#5564
=> Port A320_Neo_FCU.js from 1.8.3.0

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
Port ND changes from asobo patch
=> port ND changes from 1.8.3.0

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js
Port latest asobo changes from SAI.
also fix indenting because this file was screwed up.
=> Port SAI changes from 1.8.3.0

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
See #719
Merges changes in `Airbus_FMA.js` from `asobo-1.8.3.0` branch.
N/A
N/A
=> fix(pfd/fma): merge changes from asobo-1.8.3.0

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Fixes #333 
Gear lever is no longer able to come up when on ground.
=> Fix #333 No Gear Up on Ground

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
Changed the speeds and angle of steering authority to be closer to the real ones, according to FCOM values. The full range of speed authority cannot be tweaked correctly though in the absence of a real Nose Wheel Steering system independent logic from the rudder steering system. So the following tradeoff:
-1 Modified the speed limit for gear extension : 260 kts
-2 Modified the max speed for full deflection as per NWS settings (20 kts)
Note: The NWS is supposed to be still operative until 80 kts but since this is not independent, the decrease in steering authority is too slow, so the threshold is set to 40 kts, as this is the rudder max deflection speed, in order to avoid too tight turns at high speed during taxi.
-3 The min deflection rudder at 40kts has been set to 6 degrees which is the …
=> [STEERING] Changes in rudder steering speeds authority and max steering angle (Update flight_model.cfg)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.js
=> fix radio lights test bug

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
Fixes #793
Old code was tied to eng starter, which isn't tied directly to the switches exactly, so now have it using a more robust simvar that is tied to the engine switches.
=> fix ground cursor

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_GPSMonitor.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSStatus.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSStatusFrozen.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PositionFrozen.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PositionMonitorPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.js
This PR makes the GPS and Position Monitor pages of the CDU Data section dynamic, meaning they will continuously update to display the current values. It also includes realism and cosmetics improvements for these pages.
lukas_#6140
=> Make GPS and Position Monitor CDU pages dynamic, cosmetics/realism

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_AirwaysFromWaypointPage.js
Fixes #798
Fixes the airways page after the most recent update, should work as before now.
https://youtu.be/VSqSoNgb8-k
=> [CDU] Fix airways page after 1.8.3

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
No issue but one can be created if needed.
Update ground cursor visuals and its limits. Not 100% perfect but should be way better anyway. Let me know if you'd like to see some additional tweaks to be made.
**Before**
**After**
[Reference](https://youtu.be/cv41hm4JEB8?t=98)
Discord username (if different from GitHub): VeGe-#4631
=> Ground cursor improvements

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.js
Fixes #877
to test, spawn on runway and make sure pfd altimeter is going bonkers
=> fix pfd altimeter scrolling like crazy

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_DOOR.js
- Minor updates to fuselage SVG
- New cockpit oxygen display (top right) updated for Neo variants
- "CKPT OXY" turns amber if Crew Oxy Supply pushbutton on overhead is off
- Updated SVG for door open indicators
- Over-wing emergency exits are now always armed
=> Update Door ECAM page

.github/CHANGELOG.md, .github/Contributing.md
Add Changelog.md
This allows better and more accurate log of changes to the project as well as allowing the contributors to credit themselves for their changes.
Every time a PR is made, a CHANGELOG has to be provided with it.
=> Add Changelog

A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/ATC/A320_Neo_ATC.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BAT/A320_Neo_BAT.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/BRK/A320_Neo_BRK.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/Clock/A320_Neo_Clock.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/RTPI/A320_Neo_RTPI.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html
Porting over all file references in .html files from 1.9.3.0
**References**
https://github.com/flybywiresim/a32nx/compare/master...asobo-1.9.3
Discord username (if different from GitHub): DoTo#5564
=> Fix broken file references due to 1.9.3.0

A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.css, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/A32NX_BaseNDCompass.js, A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
Ported changes to MapInstrument.js, BaseNDCompass.js, NavSystem.js
Fixes issues with ND.
=> Port ND changes from 1.9

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
#964 
AttitudeIndicator was missed when porting the changes over for 1.8.3, so I did that in this PR.
Those changes seem to fixed the horizon detachment issue that @1Revenger1 fixed in #611, so I went with Asobos fix to keep us closer to their code.
The 1.8.3 and 1.9.3 changes tweaked some visuals, mach speed is bigger, airspeed indicator shifter to the left a little bit.
Before (master):
TODO
After:
=> Porting over PFD changes from patch 1.9.3 (and some from 1.8.3)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Ported CDU js changes from 1.9.3.0
**References**
https://github.com/flybywiresim/a32nx/compare/master...asobo-1.9.3
Discord username (if different from GitHub): DoTo#5564
=> Port CDU changes from 1.9.3.0

A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js
Fixes #976
copied from my discord rambling:
> another missed change from the previous patch
> kind of
> i think what happened was
> around the time when the last patch dropped a couple weks agoi
> someone had a PR opened which copied NavSystem.js from vanilla into our codebase
> but they opened the pr before the patch dropped
> so it was the old version
> then got merged later
> surprised it didnt cause issues until now
> the reason we didnt see an error was because its inside a promise callback
> i palced a bunch of console logs throughout flight plan manager, and noticed some stopp logging after my waypoints were added
>then put a geiant try catch block in and caught and logged the error
**References**
Discord …
=> fix no route on ND by copying in missed NavSystem changes from 1.8.3

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Core/A32NX_APU.js
Removed fuel patch that was implemented by Iceman™ as it's not longer needed.
**References**
=> Removed MSFS Update 1.8.3.0 Fuel Patch

A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Fixes the same related issues as https://github.com/flybywiresim/a32nx/pull/893, code was adjusted for 1.9.3. 
See https://github.com/flybywiresim/a32nx/pull/893.
**References**
See https://github.com/flybywiresim/a32nx/pull/893.
See https://github.com/flybywiresim/a32nx/pull/893.
=> [CDU] Fix PR #893 after 1.9.3

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDInfo.js
Fixes #860
Change ND sizes
- Speed & Wind text size.
- Waypoint info size.
- Compass size.
- ILS Title colour.
- VOR/ADF size and position
=> Fix #860 ND Sizes

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
NA
Made a quick change to fix the sound of avionic fans playing in external view
NA
**References**
NA
NA
NA
Boris#9134
=> Hotfix to make av fan loop sound playing in external view

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_Fuel.js
Fixes #28 
- Adjusted size, layout, and position of multiple elements to match real fuel ECAM page on A320neo
- Fixed issue with APU indicator not accurately reflecting APU pump status
- Fixed wrong center pump indicators (mentioned in issue above)
Before:
After:
**References**
Referenced documents provided by Ares.
Discord username (if different from GitHub): Iceman#5540
=> Fuel ECAM visual adjustments and center/APU pump indicator fix

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
Fixes #923 
Adjust vertical Flight Director offset. Attitude indicator was slightly updated in https://github.com/flybywiresim/a32nx/commit/5e3c694bdabf17d02e99361436e16fc9e0a4f279. In the end the offset adjustment needs to be very tiny but every detail matters!
Images taken by faking FD to dead center 0, 0 in code since difference small as this is difficult to notice while flying. Look carefully to the center rectangle which is now as as close as it visually can.
**Before**
**After**
**References**
Common knowledge I think.
Discord username (if different from GitHub): VeGe-#4631
=> Minor vertical offset correction to Flight Director

.github/workflows/pr.yml
=> upload zip as artifact in PRs

src/sound/Actor-Mixer Hierarchy/AIRCRAFTS/AIRCRAFT_WWISEDATA/AIRCRAFT_PLAYER/Asobo_A320_NEO_Improved.wwu, src/sound/FlightSim.airbo.wsettings
Made fuel pumps 5 db quieter
I have changed the fuel pumps to be 5 db quieter. This was complained about by a few people, including real life pilots so I turned it down so it is barely audible.
As written before, a few pilots and engineers said it was too loud.
=> [Sounds] Made fuel pumps 5 db quieter

README.md
Changed link in Readme.md to be dynamic.
Discord username (if different from GitHub): Externo#2359
=> Updated README.md dynamic link to latest installer

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
Fixes #1254
self-explanatory
N/A
N/A
N/A
=> fix(ecam): fix self-test

.github/CHANGELOG.md
fixed limit spd text (which i messed up and nooooobody noticed ;) )
added small detail decals
added more decals to chronometer
cleaned up base cockpit texture (less dirt)
BEFORE:
AFTER:
BEFORE SPD:
AFTER SPD:
i tried to replicate the plastic glossiness when light gets shined onto it, but the compression of msfs textures makes this almost impossible, infact that is why the default texture looks so low quality.
1. On the right side, slick on the …
=> [TEXTURES]cockpit texture changes

.github/CHANGELOG.md
=> fix: changelog

A32NX/ModelBehaviorDefs/Asobo/Common/Deice.xml, A32NX/ModelBehaviorDefs/Asobo/Common/Subtemplates/Deice_Subtemplates.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
Fixes #882
* Fixes Anti-Ice buttons in the CJ4
=> CJ4 Anti ice fix

manifest-base.json, package.json
* Bumped versions in manifests for 0.4.0
=> build: bump versions for 0.4.0

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Emergency revert. Latest master broken.
Can't seem to fix both the issue and the PR changes.
=> Revert "Fix #1054 L/G ECAM Warning"

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FCU/A320_Neo_FCU.css
=> fix: tweak FCU colors

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_APU.js
Fixes #1484 
- APU BLEED PSI now shows "XX" when ADIRS is not aligned
See issue
=> fix: make APU bleed PSI XX if ADIRS not aligned

A32NX/html_ui/CSS/A32NX_Display_Common.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.css, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_WHEEL.html
=> fix: slight ECAM color changes, WHEEL page adjustments

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
Fixes #1515
- "Flood Flight" -> "Flood Light"
=> fix: typo in checklist

.github/CHANGELOG.md
Changes aft overhead circuit breaker decal from 'LIGHTNING' to 'LIGHTING'
**Before**
**After**
**WRONG**
https://www.oxfordlearnersdictionaries.com/definition/english/lightning_1#:~:text=lightning-,noun,the%20sky%20caused%20by%20electricity
**CORRECT**
https://www.oxfordlearnersdictionaries.com/definition/english/lighting
=> Fix: Changed 'LIGHTNING' to 'LIGHTING'

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1610
Fixes #1591
Fixes #1582
Revert part of PR #1505 (the live update part) and fixed some issues after 1.10.7, like DECEL not showing anymore.
The live update implementation was faulty and a proper one requires more time to write and test.
=> [CDU] Revert part of PR #1505 and fix some issues after 1.10.7

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO-LIVERY/MODEL.FBW/model.cfg
The New MSFS Update needs this for livs to work.
=> Liveries 0.5 (2)

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO-LIVERY/aircraft.cfg
The New MSFS Update needs this for livs to work.
=> Liveries 0.5

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1561
- Do not round flight level to nearest 5
See #1561
=> fix(mcdu/init): do not round CRZ FL to nearest 5

manifest-base.json
Fixes Installer cannot correctly verify if up to date when development version is installed.
Bumped version
Discord username (if different from GitHub): Externo#2359
=> Bump version to 0.4.1

src/instruments/README.md
Just improve the instrument doc a bit to explain how to render.
=> Improve instrument doc

.github/CHANGELOG.md
Proper font and spelling fix
None.
Changed the decal font to what it should be, and fixed the spelling of compass.
Please check every decal, as just because it appears good on my end, doesn't mean it'll look good for all.
Please test different resolutions and settings, as my resolution is 1680 x 1050 on medium.
Aubrey Jane#7563
=> Decals Change

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
Fixes a typo in the ILS Approach checklist: "Leading Gear" -> "Landing Gear"
=> Fix typo in ILS Approach checklist

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Fixes #1852
Fixed the flight plan in the FMS when the origin and destination are the same.
=> [FMS] Fix F-PLN for identical FROM/DEST

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IRSInit.js
Fixes #1844 
Remove space between ALIGN ON REF and arrow
Before (with space between ALIGN ON REF and arrow)
=> [MCDU] Align on ref space

README.md
Adds a link to the [source](https://github.com/Externoak/A32NX-installer/) for the downloader. A lot of folks (myself included) are hesitant to blindly download and run installers, even when they are linked to by reputable projects. This just adds an extra link to check out the source before downloading for those who prefer that.
=> minor: update README with link to downloader source

README.md
Fixing some grammatical and spelling issues in the README.md, I have confirmed the correct spelling/punctuation/grammar using grammarly.
=> Fixing typos and grammatical errors

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AltimeterIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/HSIndicator.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/VerticalSpeedIndicator.js
"This PR adds the Elec page to the ECAM. It adds the HTML, JS and CSS required to display the page."
This pull request is a duplicate of #1062, but I needed to create a new branch for it in order to merge master into the feature branch, since there were several conflicts.
**All credits go to github.com/ramon54321**
See https://github.com/flybywiresim/a32nx/pull/1062
Needs system integration (WASM) - the actual functionality is not implemented. Requires visual re-working and adjustments for new backlighting and custom font which were added to the A32NX after this feature branch was created.
The build script will have already been run with the latest changes, so no need to rerun it once you download the …
=> Ramon54321: feat(ecam-elec): Add elec ecam js and html 

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
=> [FMS] Bugfix for #1652

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_SvgFlightPlanElement.js
Improved the displayed flight path on the navigation display, should now at least touch each waypoint.
Approach waypoints are not affected, seems there's a bug lurking around regarding transitive points.
Couldn't find better real references than the ones below, also looked around at all the other sims and they all seem consistent and much closer to this than the default.
[https://www.youtube.com/watch?v=9VfI4Pyam1E](https://www.youtube.com/watch?v=9VfI4Pyam1E)
[https://youtu.be/HoPBog14zV8?t=5366](https://youtu.be/HoPBog14zV8?t=5366)
1. Click on …
=> [ND] Improve flight path shape display

A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/NavSystems/LogicElements/A32NX_FlightPlanManager.js
Report the aircraft type, origin, and destination to the API for map usage.
Compatible API is deployed.
=> Report origin, destination and ac type to the API

A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Tie reporting to free text
legal and stuff....
=> Tie reporting to free text

A32NX/html_ui/Pages/A32NX_Utils/NXApi.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_FreeText.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
=> feat: change telex settings key

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_FTCL.js
Adjusted the ELEV cursor display so it matches the upper limits.
[https://youtu.be/9rHtTwqel_A?t=1216](https://youtu.be/9rHtTwqel_A?t=1216)
=> [ECAM] Adjust elevator pointer upper limits on F/CTL page

.eslintrc.json, .gitattributes, .gitignore
The project was configured to enforce LF only line-endings through `eslintrc.json`. However, the majority of Windows Git users have Git's `autocrlf` on by default. It automatically converts LF line endings to CRLF, thus most Windows users will run into problems.
By removing the linting and instead using `.gitattributes`, we can make this correct and easy to work with for all users.
For further details see: https://git-scm.com/docs/gitattributes#_end_of_line_conversion
**Note that this PR changes ` .eslintrc.json` despite the explicit warning in that file not to.**
The build script will have already been run with the latest changes, so no …
=> Automatic Git CRLF handling

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #1916
- Fixed scratchpad gets deleted (empty error message was shown, was not a bug, just a bad error message)
- Improved error message handling
=> [MCDU] Fixed bad error message handling (critical bug)

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
=> fix(mcdu): TypeError on next page for pages without next pages

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AirspeedIndicator.js
- Corrected length of speed bands withe line.
Before (left) After (right)
=> [PFD] Improved svg line length

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
Ported messages:
- `V1/VR/V2 DISAGREE`
- `CHECK MIN DEST FOB`
=> [CDU] Port type II messages to new system

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
This fix should make the bank more even between left and right, and the aircraft on AP is now more responsive during HDG select and NAV. (note: I'm not the curator of this! Imenes just told me to make this PR)
Temporary fix, no reference was provided, credit goes to Idle Betazoid#944 for raising the issue!
Discord username (if different from GitHub): ChristopherXie#3904, Idle Betazoid#944
=> Attempts to fix AP issue

A32NX/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js
=> fix: bad unit name

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/apron.FLT
This was introduced as a possible workaround for the current AP issues. Unfortunately it did not bring the desired effect therefore I suggest removing it to avoid possible side effects.
=> Removed MaxBankIndex from apron.flt

docs/README.md, docs/a320-simvars.md, src/fbw/build.sh, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/InterpolatingLookupTable.cpp, src/fbw/src/InterpolatingLookupTable.h, src/fbw/src/inih/INIReader.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/interface/SimConnectInterface.h, src/fbw/src/main.cpp, src/fbw/src/main.h, src/fbw/src/model/FlyByWire.cpp, src/fbw/src/model/FlyByWire.h, src/fbw/src/model/FlyByWire_data.cpp, src/fbw/src/model/FlyByWire_private.h, src/fbw/src/model/FlyByWire_types.h, src/fbw/src/model/rtwtypes.h
- includes fix for throttle issues by handling them directly
- allows configuration of throttle to map to detents correctly
- adds support of proper sidestick position display using l-vars
- description of throttle configuration added
⚠ WASM build is not fully working yet, the reading and writing of the config file will fail in the meantime.
=> Latest changes from wasm repository

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
Fixes #2125
Fixed the issue of weather being selected but not showing-up after switching to PLAN mode.
Discord username (if different from GitHub): Union Araken#4083
=> [ND] Fix weather radar not showing after switching to plan view

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
=> Activate custom fly-by-wire per default

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.cfg
=> Fixed typo in panel.cfg

src/fbw/build.sh, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/interface/SimConnectInterface.cpp
=> Fbw build fix

docs/README.md, src/fbw/build.sh, src/fbw/src/FlyByWireInterface.cpp
=> build: fix build script for fbw

src/fbw/build.sh, src/fbw/src/FlightDataRecorder.cpp, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h
This PR adds logging of the throttle input and output values to the console of MSFS. This should ease the setup of the throttle configuration. Logging can be disabled via ini-file.
Secondly, this PR adds a flight data recording functionality. It's enabled by default at the moment and writes up to 5 files with 54000 entries which means around 47 MB. At 60 FPS this contains about 15 min of flight.
All parameters are configurable via ini-file. If the file is not found, it will be created. …
=> [FBW] Logging for throttle and flight data recording function

.github/CHANGELOG.md, A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml, A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.html, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js, A32NX/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/Svg/A32NX_TCAS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
This is a modification of Asobos default "TCAS"
There are many features still missing, but the conditions for which traffic is displayed should be greatly improved.
* Features missing: 
* RA generation and display
* TCAS messages on the ND
* proper on ground detection for traffic aircraft
* display of aircraft that are not live traffic
* sounds
* Features implemented:
* Traffic display based on display knob: THRT, ALL, ABV, BLW
* Display of vertical speed and relative alt
* Realistic symbols for traffic threat status: white hollow for no threat, white filled for proximate, amber for TA, red for RA (although no RA will be generated)
* This is only a temporary solution, until we find a way to move TCAS to WASM, where we could also implement the missing features (and more).
This shouldn't …
=> TCAS improvements

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_LateralRevisionPage.js
This PR fixes a minor layout thing I missed back in #1845.
=> [CDU] Tweak layout on LAT REV page

.github/CHANGELOG.md, A32NX/html_ui/Pages/A32NX_Utils/NXLogic.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
This PR introduces 3 icing-related ECAM warnings and memos:
- ICE DETECTED
- SEVERE ICE DETECTED
- ICE NOT DETECTED
The icing model in MSFS is a little simple and agressive, so we're just making do with what we have here. The ENG ANTI ICE buttons don't seem to actually do anything in the sim, but we'll just trigger that warning anyway as a first sign of some ice happening.
Works great together with #2246.
QA: Please ensure that all the new warnings here work, and especially also that they don't appear under unexpected circumstances. Some of them (like ICE NOT DET) have a significant delay built into them (>2 minutes), so you may need to wait a bit for them to appear.
The build script will have already …
=> [ECAM] Add icing related ECAM warnings and memos

A32NX/html_ui/Pages/A32NX_Core/A32NX_GPWS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Previously, the AIRLINER_MINIMUM_DESCENT_ALTITUDE and AIRLINER_DECISION_HEIGHT used "number" as the unit. This PR corrects this to feet.
=> Correct MDA/DH simvar unit

package.json, src/instruments/rollup.config.js
* replace `node-sass` with `sass`
=> build: replace node-sass with sass

src/instruments/src/EFB/Efb.tsx
Fixes EFB.tsx Errors Coming Up During Build Process 
Just changed a typo in EFB.tsx 
Discord username (if different from GitHub): myselfaaryan#0001
=> Fix Build Errors for EFB.tsx

LIGHT_A32NX_LeftRunway.fx, LIGHT_A32NX_TaxiLarge.fx
=> Changed two small values for lights

A32NX/effects/LIGHT_A32NX_LeftRunway.fx, A32NX/effects/LIGHT_A32NX_TaxiLarge.fx
=> Fixed Taxi/Runway Light brightness value

A32NX/ModelBehaviorDefs/A32NX/Interior/A32NX_Interior_Misc.xml, A32NX/ModelBehaviorDefs/Asobo/Airliner/Airbus.xml, src/instruments/src/SD/Pages/Apu.jsx, src/instruments/src/SD/Pages/Bleed.jsx, src/instruments/src/SD/Pages/Cond.jsx, src/instruments/src/SD/Pages/Door.jsx, src/instruments/src/SD/Pages/Elec.jsx, src/instruments/src/SD/Pages/Eng.jsx, src/instruments/src/SD/Pages/Fctl.jsx, src/instruments/src/SD/Pages/Fuel.jsx, src/instruments/src/SD/Pages/Hyd.jsx, src/instruments/src/SD/Pages/Press.jsx, src/instruments/src/SD/Pages/Wheel.jsx, src/instruments/src/SD/PagesContainer.jsx, src/instruments/src/SD/index.jsx
* Base code for React ECAM SD page switching
=> feat: add base SD page code

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.css
Discord Username: `Snapmatics#0001`
=> MCDU Popup Background Fix

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/panel/panel.xml
Similar to #2441 in that the SAI had it's circuit ID decremented meaning it would not work, this has been fixed in this PR
N/A
Caused by #2119 changing the circuit IDs
Discord username (if different from GitHub): ThatRedMelon#6756
=> Fix SAI not working

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MenuPage.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_ADIRS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_ATIS.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_METAR.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_AOC_TAF.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_Menu.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_REALISM.js, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_TELEX.js
- Restructured Options Menu
- Added AOC, FMGC and REALISM categories
Before:
After:
=> [CDU] Rework Options Page

src/instruments/src/Common/definitions.scss, src/instruments/src/SD/StatusArea/StatusArea.jsx, src/instruments/src/SD/Text/Text.jsx, src/instruments/src/SD/Text/Text.scss, src/instruments/src/util.mjs
* Add SAT and TAT to reworked ECAM
=> [ECAM REWRITE] Added SAT and TAT to SD

package.json
=> build: bump version for 0.5.0

.github/CHANGELOG.md
Fixes No Issue
Added a v0.6.0 to the changelog
=> Added v0.6.0 to changelog

README.md
According to the answer, the title of the last question in the Q&A section of README.md should be "Why is my version not the same as what I see others using?" instead of "Why is my version now ...."
=> Fixes title of a question in the Q&A section of the README.md

.gitignore, .npmrc, scripts/setup.sh
=> ensure package-lock.json is eradicated

.github/Contributing.md
=> fix instructions in Contributing.md

.github/PULL_REQUEST_TEMPLATE.md
* Added "Testing instructions" section to PR template
=> docs: added "Testing instructions" section to PR template

.github/CHANGELOG.md, package.json
=> build: up versions for 0.5.1

.github/workflows/release.yml
Reverts flybywiresim/a32nx#2612
=> Revert "build: release on tag created"

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/aircraft.cfg
=> fix sim title

docs/a320-simvars.md
Minor fix (line 04)
- minor proposal line 05
- 
There is no break on code. Just minor fixes in documentation
=> Minor fix (line 04)

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/SAI/A320_Neo_SAI.html, src/instruments/src/DCDU/style.scss
Changed DCDU & SAI backlight to match the other displays
Spawn C&D and check colour when off, and colour when on
Every new commit to this PR will cause a new A32NX artefact to be created and uploaded.
1. On the right side, click on the **Artefacts** drop down and click the **A32NX** link
=> fix: Display BG on DCDU & SAI

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
* Buttons on the f/o mcdu can now be used.
N/A
N/A
Currently, only the buttons on the captains mcdu work.
Make sure the f/o mcdu buttons work.
=> Enable F/O MCDU buttons

.github/CHANGELOG.md
Fixes #2679
Fixed the overlapping text on the chronometer.
Discord Username: `Snapmatics#2424`
=> [TEXTURE] Chronometer Text (Overlapping Issue)

.github/CHANGELOG.md, A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/Checklist/Library.xml
Removed various outdated INOPs from the checklists
N/A
N/A
N/A
Go through the checklists ;)
=> Remove various outdated INOPs from the checklists

.github/CHANGELOG.md
=> doc: correct CHANGELOG.md from #2954 and #2940

src/instruments/src/Common/definitions.scss, src/instruments/src/SD/Pages/Cond/Cond.jsx, src/instruments/src/SD/Pages/Cond/Cond.scss, src/instruments/src/SD/PagesContainer.jsx
=> [ECAM REWRITE] COND page

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
- Removed redundant code introduced by #3015
Insert take off speeds and check V1/VR/V2 Disagree message appears when v1 > vr > v2
=> [CDU] Removed redundant code for to check

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
At high altitudes, like 35000 feet and up, on idle you could hear this weird beeping sound on the outside - i have fixed it in this pr
Slew or fly up to 35000-39000 feet and go idle on the exterior and listen
=> fixed morse code sound on idle at high altitudes

.github/CHANGELOG.md
As part of some merge action one of my CHANGELOG lines got duplicated by other PRs.
=> Fix duplicate changelog entry

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.html, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/EICAS_Common.html
After the display performance PR (#2976) was merged I've been seeing warnings on my EICAS screens due to duplicate scripts. I've tried moving all referenced scripts from LowerECAM/UpperECAM to the top-level (EICAS), and that fixes the error for me locally at least. In some cases the error prevented the aircraft from starting up at all.
=> Fix potential EICAS crash from duplicate scripts

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js
Fixes "ENG OUT ACC" label on Performance / Go Around page on MCDU.
* see Take Off page
* http://www.a320dp.com/A320_DP/nav-flight-management/sys-14.5.52.html
* check the label comparing it with Perf / Take Off page
* check that assignment of the value works as expected
=> fix(CDU): ENG OUT ACC label on Perf page

README.md
- Update FMGS to Honeywell Pegasus II
- Update FWC Std. to H2F9E
=> docs: update simulation info

.github/workflows/pr-target.yml, .github/workflows/pr.yml
=> build: add PR title workflow

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.html
Fixes a silly little typo that slipped through #3054.
=> fix: typo in A320_Neo_EICAS.html 

src/instruments/src/EFB/Dispatch/Dispatch.tsx, src/instruments/src/EFB/Efb.tsx, src/instruments/src/EFB/Settings/Settings.tsx
Changed the text inside of the settings efb page to INOP
=> feat: made settings page INOP

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/AttitudeIndicator.js
The pitch bar of the flight director is a bit off (downwards). That means if you're flying exactly the pitch that the FD commands, the bar is a bit off downwards. The change will re-align the flight director pitch bar.
Before:
After
=> fix: flight director pitch bar alignment

src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Fixes #3307 
I fixed the fuel quantity in the EFB dispatch page from 26,725 kg to 21,005 which is the correct value.
See issue
Discord username (if different from GitHub): @Arman#5297
=> fix: EFB dispatch fuel quantity

package.json, src/instruments/src/EFB/Dashboard/Widgets/WeatherWidget.tsx, src/instruments/src/EFB/Ground/Ground.tsx, src/instruments/src/EFB/README.md, src/instruments/src/EFB/index.jsx
Fixed weather card icon, and some refactoring.
Discord username (if different from GitHub): myselfaaryan#2092
=> fix: EFB [Minor Changes 🚀]

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A32NX_NDCompass.js
* Removed label from the smallest circle of the ND in arc mode
Before:
After:
Ensure that the label has been removed from smallest circle of the ND.
=> fix(nd): remove label from smallest circle in arc mode

.gitignore
=> fix: add /src/systems/target/ to .gitignore

A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/sound/sound.xml
Adds ptu in cockpit wwise event in code. this does not do anything until #3340 is merged
1. Start one engine, stay in cockpit. Look for the HYD PTU indication and make sure the PTU is ***NOT HEARD***
=> feat: add ptu in cockpit wwise event

.github/workflows/pr.yml, package.json, scripts/dev-env/run.cmd, scripts/dev-env/run.sh, scripts/setup.sh, src/instruments/src/EFB/Dashboard/Dashboard.tsx, src/instruments/src/EFB/index.jsx
* Update to `@flybywiresim/map` 0.5.2
* Fix `dev-env` version
* Use local data instead of API for locating current flight
* **Note:** `origin` and `destination` do not currently work
* Ensure the EFB map locates your aircraft correctly
* Ensure the EFB map follows your aircraft as it moves
* Ensure no performance degradation
=> build: fix failing workflows and builds

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_Request.js
Linter fix
Discord username (if different from GitHub): arturkuma#6639
I think it does not require any testing
=> fix: linter

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
Add "BRK FAN" memo to right side upper ECAM.
ESLD
=> fix: add brake fan memo

.github/CHANGELOG.md
=> fix(cdu): missing changelog for ILS autofill fix

.github/PULL_REQUEST_TEMPLATE.md
Updated QA instructions to fit with the current process and corrected two minor grammatical errors. 
Discord username: Imenes#8739
=> chore: update QA instructions in the PR template

README.md
=> docs: update FWC standard in README.md

src/instruments/src/ATC/index.tsx
Fixes #3807
* Fixes a code issue caused by a wrong for abort condition.
* Transponder should now show all codes correctly.
=> fix: Transponder showing codes with 3 leading 0s incorrectly

.github/CHANGELOG.md, A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/OPTIONS/A320_Neo_CDU_OPTIONS_FMGC.js
- Changed typo from ALT to H (altitude to height)
=> fix(mcdu): options page text overlap and typo

.github/workflows/master.yml, .github/workflows/release.yml
https://lftp.yar.ru/lftp-man.html
N/A
N/A
N/A
=> build: ignore time and size on LFTP upload

src/instruments/src/EFB/Components/Button/Button.tsx, src/instruments/src/EFB/Settings/Settings.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/BaseThrottleConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
Added throttle settings page to set the provided simvars to allow an easiert configuration.
=> feat: throttle detent mapping in efb

src/systems/README.md
Systems design documentation.
Not applicable.
=> docs(systems): design documentation

A32NX/html_ui/JS/A32NX_ObjectDumper.js, src/tools/heapdump/README.md, src/tools/heapdump/app.py
Add script to enable counting & dumping of object hierarchy
Follow src/tools/heapdump/README.md and check whether you get an object dump.
=> feat: Add script to enable counting & dumping of object hierarchy

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js
- Fixed acc alts and thr red alt to be clearable again.
Manually enter an altitude for each of the fields, then clear the fields and monitor small font with auto-populated altitudes again.
=> fix(mcdu): takeoff performance page

.github/CHANGELOG.md
* Add forgotten changelog entries
=> chore: add changelog entry for #3675 and #3794

package.json
[1.1.4 gives us stderr output when tasks fail](https://github.com/flybywiresim/igniter/pull/2).
There have been a few discussions on Discord in the past couple of days about difficulty troubleshooting failing tasks.
* Make sure the addon still works
=> chore: roll igniter to 1.1.4

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
Before:
After:
- Check From/To text alignment,
- Check CRZ FL /TEMP space,
- Check CRL FL TEMP missing ° on entry boxes are fixed,
- Check CRZ FL TEMP / is small when automatic populated.
=> fix(mcdu): init a small improvements

scripts/cdn.sh
Change the CDN upload URL
N/A
N/A
N/A
=> build: change cdn upload url

src/instruments/src/EFB/Ground/Ground.tsx
Just some spacing adjustments for the new layout.
=> feat: adjust ground services layout for flypados-v2

docs/README.md
Updates README.md to include an action to work on for the Engines (Descent/ Approach Idle)
=> docs: updated README.md

A32NX/pt-BR.locPak
Fixed some messages in the pt-BR loading tips. 
-
-
Discord username (if different from GitHub): TansyEliot#9914
-
=> fix: pt-BR loading tips

A32NX/de-DE.locPak
small grammar fix for the german loading tips translation
-
-
Discord username (if different from GitHub): Nyhmbo#9999
-
=> fix: loading tips german grammar

A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/Airbus_FMA.js
Change MDA and DH on FMA to BARO and RADIO per EIS2. Follow-up on #3643.
Setup ILS approach in F-PLN, and set BARO, check PFD, then set RADIO and check PFD.
=> fix(pf): replace dh/mda with radio/baro

README.md
=> chore: update README with hard fork warning

.github/workflows/pre-release.yml
* Fix `pre-release.yml` to use new package name
=> ci: update pre-release.yml

flybywire-aircraft-a320-neo/fr-FR.locPak
* Fix punctuation spaces.
* Fix units case + typo
* Added french translation for  "COCKPIT.TOOLTIPS.APU_AVAILABLE" String.
=> fix: french loading tips

src/instruments/src/EFB/Components/Button/Button.tsx, src/instruments/src/EFB/Ground/DoorToggle.tsx, src/instruments/src/EFB/Ground/Ground.tsx
Changed event used by the Button component to remove the need of clicking multiple times in order to activate it.
Also fixed a bug in ground services that left doors inpoerable after it was disconnected manually by the game
1. Check that all buttons on the EFB work as intendend and do not require multiple clicks.
2. Activate the pax ramp and catering on the ground services page and wait until they are finished.
3. Check that the fwd and aft door are still operable
4. Verify that pushback directions only work after the tug was requested
1. On the left …
=> fix(efb): unresponsive buttons and deactivated doors

src/tools/heapdump/README.md
This fixes a few markdown errors in the readme file located in `src/tools/heapdump`
=> fix: readme in tools

src/fbw/src/EngineData.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h
Included three additional Engine LVars for the fuel model:
A32NX_FUEL_AUX_LEFT_PRE
A32NX_FUEL_AUX_RIGHT_PRE
A32NX_FUEL_CENTER_PRE
=> feat: FDR new engine LVars

src/fbw/src/EngineData.h, src/fbw/src/FlyByWireInterface.cpp
Fixes a build error introduced by latest fuel system changes.
=> fix: duplicate and missing variables

.github/workflows/experimental.yml
This PR adds the experimental branch as git workflow. 
It makes it much easier to handle the experimental version later, because you don't need to take care of that part then. Otherwise when resetting the branch to a certain branch or version or rebasing it, you always need to ensure you're not messing up this thing. Also when build changes are needed you can directly do it at once on master.
=> build: added experimental branch as workflow

.github/ISSUE_TEMPLATE/bug_report.md
- Adds dedicated code block to allow the users to paste their build_info.json content with more cleanly and structured.
=> style(bug report): add code block for build_info.json content

.github/ISSUE_TEMPLATE/bug_report.md
=> docs(github): correct bug_report template

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_Handling.xml
Fixes #4342
* See title
* Make sure the trim wheel works as expected
* Try to turn the wheel past it limits (in both ways)
=> fix: Trim limits are now no longer able to be exceeded by using the right trim wheel

.github/ISSUE_TEMPLATE/bug_report.md
Changed 'Mod Version' to 'Aircraft Version'
=> docs(template): bug report change 'mod' to 'aircraft'

.github/CHANGELOG.md
Upscaled the fuselage to 8K and the engines & wings to 4k.
Removed the A32NX and the green stripe from the engines.
I have since fixed the strange thing on the "y" in 'fly' by the right side of the door.
While essentially a duplicate, this is the one to use. I made a mistake when pushing the changes (deleted my fork, recreated the branch, and it wouldn't let me push the changes because it was already up to date) and this was the easiest way to fix it.
See #3797.
On my system, I can manage low-medium (Ryzen 5 1600AF, RX 580, 16 Gb ram) , and my monitor is 1600 x 900. there may be little, if any visual difference between before and after. See testing instructions for further. 
Discord username (if different from GitHub): Aubrey Jane#7563
Especially those who can run the sim on all medium …
=> feat: Upscaled FBW livery, removed A32NX text and the horrid green stripe from the engines.

src/instruments/src/EFB/Components/Form/Input/Input.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
=> fix: initialize persisted values for exisiting configuration

src/instruments/src/EFB/Settings/ThrottleConfig/BaseThrottleConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
=> fix: set axisvalue and deadzone on load from file

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/engines.cfg
At some extreme environmental conditions (high altitude airports and high temperatures), the engine oscillated violently. The issue was the internal EGT limiter taking over and not letting the engine go to higher RPMs. The issue has been solved by getting rid if the internal limiter until we have the new EGT limit in the FADEC code.
1. Go to a high altitude airport (i.e. KDEN)
2. Set engine power to 50% N1 and give it some time for temperature to build up
3. Accelerate to TOGA
4. No more oscillations will be observed
1. On the left side, click on the …
=> fix: engine oscillations at high temperature conditions

.github/workflows/autopilot-custom-fpm.yml
* Add a CI workflow for the `autopilot-custom-fpm` branch
=> ci: add build for autopilot-custom-fpm

src/instruments/src/EFB/Settings/ThrottleConfig/DetentConfig.tsx, src/instruments/src/EFB/Settings/ThrottleConfig/ThrottleConfig.tsx
=> fix: layout adaption of throttle config

.github/ISSUE_TEMPLATE/config.yml
- Added config.yml
- Disallowed blank issue template use
<!--## How to download the PR for QA
=> docs(template): disallow blank templates

.github/ISSUE_TEMPLATE/config.yml
Why do we need this?
People need guidance on where to ask questions, this place looks like a great spot to give them options.
Examples:
https://github.com/flybywiresim/a32nx/issues/4671
https://github.com/flybywiresim/a32nx/issues/4675
- Added link to our discussion tab on github as well as our support channel on discord.
=> docs(template): improve user guidance

.github/ISSUE_TEMPLATE/bug_report_beta.yaml
Remove pre-defined values as they allow the user not to fill in the field at all, we should use the placeholder feature instead which displays (as long as nothing has been entered) an example.
Discord username (if different from GitHub): 
=> docs(template): remove pre-defined value -> use placeholder

.github/ISSUE_TEMPLATE/bug_report_beta.yaml
- Added placeholder for build info field
=> docs(template): add placeholder for build info

.github/ISSUE_TEMPLATE/bug_report_beta.yaml, .github/ISSUE_TEMPLATE/feature_request_beta.yaml
- Removed pre-filled title
Removed the pre-filled/defined title to make the default space holder visible instead and prevent people from not entering a title.
=> docs(template): use space holder over pre-filled title

docs/README.md, docs/a320-events.md, docs/a320-simvars.md
Allows for better navigation through the documentation
- Added list of content to
- readme
- 320-events
- a320-simvars
=> docs: make docs great again

README.md
I made a typo in my last simbrief PR and changed the MTOW back from 79400 to 79000kg. For that the link needs to be changed again. 
https://www.simbrief.com/system/dispatch.php?sharefleet=eyJ0cyI6IjE2MjAyMTYxMzY2MjciLCJiYXNldHlwZSI6IkEyME4iLCJjb21tZW50cyI6IkZCVyBBMzJOWCIsImljYW8iOiJBMjBOIiwibmFtZSI6IkEzMjBORU8gRkJXIiwiZW5naW5lcyI6IkxFQVAtMUEyNiIsInJlZyI6IkQtQUZCVyIsImZpbiI6IiIsInNlbGNhbCI6IiIsImhleGNvZGUiOiIiLCJjYXQiOiJNIiwicGVyIjoiQyIsImVxdWlwIjoiU0RFMkUzRkdISUoxUldYWSIsInRyYW5zcG9uZGVyIjoiTEIxIiwicGJuIjoiQTFCMUMxRDFPMVMyIiwiZXh0cmFybWsiOiIiLCJtYXhwYXgiOiIxODAiLCJ3Z3R1bml0cyI6IktHUyIsIm9ldyI6IjQxMDA1IiwibXpmdyI6IjY0MzAwIiwibXRvdyI6Ijc5MDAwIiwibWx3IjoiNjc0MDAiLCJtYXhmdWVsIjoiMTkwNDUiLCJwYXh3Z3QiOiIxMDQiLCJkZWZhdWx0Y2kiOiIiLCJmdWVsZmFjdG9yIjoiUDAwIiwiY3J1aXNlb2Zmc2V0IjoiUDAwMDAifQ-- …
=> fix(docs): fixed Simbrief MTOW to 79000kg

package.json
=> chore: increment package.json

README.md
=> docs(readme): restructured header

.github/CHANGELOG.md, src/behavior/src/A32NX_Interior_Misc.xml
Fixes #2852
Just a small enhancement of the update logic to repect the state of the "switch" that is being change by the keybindings.
Discord username (if different from GitHub): saschl#9432
Should be a quick test.
1. Add bindings to a device of your choice (autobrake min, medium and max)
2. Check that the bindings activate the corresponding autobrake level
3. Check that autobrake max can be engaged on ground
4. Check that autobrake max cannot be engaged in flight
5. Check that autobrake max does not disarm on ground
6. Perform a rejected takeoff above 70 knots and ensure the max autobrake engages and the decel light illuminates
7. Perform a landing and verify the plane is braking and the decel light illuminates
Note: currenty I see no binding to deactivate the autobrake.. if anyone got …
=> feat: rework autobrake keybindings

flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/A320_Neo_EICAS.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_BLEED.js, src/behavior/src/A32NX_Interior_Engine.xml
This PR fixes some errors/warning that are shown in the dev console of MSFS related to the plane.
=> fix: fix some errors and warnings

src/behavior/src/A32NX_Interior_Misc.xml
* Changes out template for the console light switch, since the current one causes errors because of the missing `LIGHT_TYPE` parameter
=> fix: change template for console light switch

src/behavior/src/A32NX_Interior_Fire.xml, src/behavior/src/A32NX_Interior_Printer.xml
This PR fixes some small scripts errors resulting into error in dev mode console.
=> fix: XML behavior script errors

flybywire-aircraft-a320-neo/ModelBehaviorDefs/A32NX/Airbus.xml, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/behavior/src/A32NX_Interior_ADIRS.xml, src/behavior/src/A32NX_Interior_FCU.xml, src/behavior/src/A32NX_Interior_Fire.xml, src/behavior/src/A32NX_Interior_Generics.xml, src/behavior/src/A32NX_Interior_Misc.xml, src/behavior/src/A32NX_Interior_Printer.xml, src/behavior/src/A32NX_Interior_RMP.xml
This PR fixes a lot of XML errors and warnings that could be seen in dev console.
=> fix: fixed errors and warnings in model behavior XML

src/model/brkfan/brkfan.gltf, src/model/build.js, src/model/onbat/onbat.gltf
Replaces #4851 
* Fixed invalid material references in some LODs
* Fixed invalid byte offsets
* Fixed nodes existing more than once in the hierarchy
* Fixed extensions not being added to `extensionsUsed`
* Removed duplicate materials
Make sure there are no issues with model modifications.
=> fix: model script issues

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #4863
- Replaced used simvar with the actual selected fcu alt
Try to enter a new valid crz fl or alt.
=> fix(mcdu): sometimes bad crz fl validation

src/behavior/build.js
RNP translation errors previously went by unnoticed because igniter only prints stderr if the process failed (non-zero exit code), and the code would just be blank in the output. This causes the build to fail, and the error to be printed out.
=> build: fail on RNP errors

Cargo.lock, scripts/build.sh, scripts/dev-env/run.cmd, scripts/dev-env/run.sh, src/fadec/build.sh, src/fbw/build.sh, src/systems/a320_systems/src/lib.rs, src/systems/systems/src/lib.rs
This PR switches to a newer version of the dev-env with SDK 0.13 and llvm 12.
Do a short flight and check that airplane behaves like latest development version.
=> build: update to dev-env with SDK 0.13

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/WaypointLoader.js, src/fmgc/src/flightplanning/RawDataMapper.ts, src/instruments/buildSrc/simulatorBuild.mjs, src/instruments/src/ND/config.json
Some fixes regarding loading of arrivals and airways. Includes some improvements in WaypointLoader (from Working Title) that fixes the loading of airways for some waypoints.
=> fix: custom fpm arrivals

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #5032
- Fixed tropo field input handling as per reference
See linked issue
Manipulate tropo field/value on init-a
_allowed format is NNNN or NNNNN_
=> fix(mcdu): init-a tropo entry validation

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #5079
- Allow for 3 digit thr red or acc alt
Enter a 3 digit thr or acc alt
=> fix(mcdu): perf page thr red/acc alt entry validation

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, src/behavior/src/A32NX_Interior_MCDU.xml
Fixes #5080
- Added clear scratchpad when clear button held for ~1sec.
[Source](https://github.com/flybywiresim/a32nx/pull/4996)
Press and hold the clr button on the mcdu and see the entire scratchpad being cleared.
Situations: (Press and hold)
_`INITIAL SCRATCHPAD STATE` -> `SCRATCHPAD WHEN CLR PRESSED` -> `SCRATCHPAD WHEN HELD`_
- `FBW RULE` -> `FBW RUL` -> ` `
- `A` -> ` ` -> ` `
- `CLR` -> ` ` -> ` `
=> feat(mcdu): scratchpad clear on clr held

.github/workflows/pr-qa-reg.yml
- First implementation for quality assurance project automation to add new PRs.
PRs are being added to the project when opened as PR or Ready for Review.
Draft PRs are not being added right away.
As a long term solution we'll have to create a new solution to meet our individual expectations.
=> chore: add registration workflow for qa project

.github/workflows/pr-qa-reg.yml
- This pr changes the event type to resolve permissions issues with the action itself.
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
=> chore(workflow): QA change event type

.github/workflows/pr-qa-reg.yml
- Added support for `pull_request_target` event
- Created docker image
PR fixes this issue
=> chore(workflow): added support for newly used event

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
- Removed simbrief username conversion (no longer needed)
None really, changes don't change anything lol.
=> refactor(mcdu): remove simbrief username conversion

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/FMGC/A32NX_FlightPhaseManager.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_InitPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Fixes #5112
Fixes #5215
- ATC now using correct callsign
- Some vars are now being properly defined
Perform a flight as per usual, observe linked issues are fixed.
=> fix(mcdu): multiple small changes for re-initialization

src/behavior/src/A32NX_Exterior.xml
Fixes #5238
Wipers are no longer inhibited above 230 knots.
Komp.
Make sure the wipers work at all speeds.
=> fix: wipers no longer inhibited by speed

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/Waypoint.js, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/data/flightplan.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts, src/instruments/src/ND/FlightPlan.tsx, src/instruments/src/ND/index.tsx, src/instruments/src/ND/pages/PlanMode.tsx, src/instruments/src/ND/utils/MapParameters.ts
=> feat(cfpm): dist in flt plan page and approach selection robustness

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
=> fix: more discontinuity clearing cases

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts
=> refactor(cfpm/mcdu): Refactored code for mcdu flight plan page

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Last PR i made the announcements for the PAs for takeoff and landing be too muffled, now i made them clearer. Let me know how this sounds compared to the old one.
=> fix: takeoff and landing announcement mixing

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
I made it by accident so if the pull up callout played once, it would keep playing continuously. This pr fixes that
=> fix: pull up callout looping

src/instruments/buildSrc/igniter/tasks.mjs
=> fix: use path.join in igniter/tasks.mjs

docs/a320-simvars.md
=> chore(docs): fix content

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/A320_Neo/Map/A32NX_MapInstrument.js
Fixes #5440 
TERR radar on ND has been restored to previous functionality.
N/A
N/A
- Check that the terrain radar works > 500 ft altitude
- Check that WX Radar functionality has not been broken in the process (Use rain preset)
=> fix(mfd): Restored TERR radar functionality

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_LocalVarUpdater.js
Now using the new engine variables instead of the default (vanilla) ones.
Perform engine start etc. as normal and observe pack noise audible when engine N1 > 17% or engine is running normally.
=> fix(sound): pack one

src/instruments/src/EFB/Efb.tsx, src/instruments/src/EFB/TODCalculator/Data/Data.tsx
Fixes #5698
Fixes issue with too many re-renders caused by inappropriate additional dependencies in a useEffect.
=> fix: large performance loss when using vertical speed sync

.github/CHANGELOG.md, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/FlyByWire.cpp, src/fbw/src/model/FlyByWire.h, src/fbw/src/model/FlyByWire_data.cpp
Reverts flybywiresim/a32nx#5737
=> fix: Revert "feat: V/S push in ALT* and improved turn coordination"

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts, src/instruments/src/EFB/TODCalculator/Data/Data.tsx
* Better nm indicator for flight plan distances
* Readability changes
* Added logic for restricting clearing of FROM and TO waypoints when autopilot is engaged, 
* Fixed bug with discontinuity not being added on entering new arrival.
* Fixed bug with active waypoint display
* Fixed bug with duplicate waypoints/duplicate origin/destination waypoints in flight plan.
* EFB distance calculator distance to go sync restored
* Workaround for distancetoFP being incorrectly set to 0 on some waypoints
* Better lateral calculation logic (ADIRS)
=> refactor(mcdu/fmgc): f-pln A cleanup (readability) and bug fixes

src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Updates max number of passengers for updated weight and balance configuration in #5547. This minor update should probably not be merged until that PR is merged. Alternatively, it could be incorporated into that PR. (I did not include a changelog entry for this change because it is just a trivial change and in case it is incorporated into #5547. I can go back and include one if necessary.)
The only change made by this PR is to change the maximum number of passengers for the airplane shown on the EFB Dispatch Overview page from 180 to 174. #5547  is based on 174 passengers.
Discord username (if different from GitHub): donbikes#4084
Check to make sure the maximum passenger number shown on the EFB Dispatch Overview page is 174.
Every new commit to this PR will cause a new …
=> fix: Update max passenger number on EFB Dispatch Overview page

src/instruments/src/EFB/Dispatch/Pages/OverviewPage.tsx
Revert max fuel displayed on EFB to 23,721 until MSFS Fuel UI override is in place.
No testing required
=> revert: max fuel on EFB Overview Page

manifest-base.json, package.json
Set package version to upcoming major stable (0.8.0-dev) and update details on manifest-base
=> chore: version bump on package and manifest

.github/ISSUE_TEMPLATE/feature_request_beta.yaml
- Corrected the label from `Enhancement` to `Request` as the label naming changed.
=> fix: request template label

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO.xml, src/model/build.js, src/model/models.json
Fixes #1022
Partial #3387
Landing lights operate independently and fully retract when the other is not retracted (half-retracted before).
Left retracted, right on.
Check that landing lights extend and retract independently.
=> fix(model): landing light animation

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Scratchpad.js
When CLR is in the scratchpad, and character keys are pressed, the CLR is removed and the new characters start at the left.
No changelog as new scratchpad code just landed and already has one.
#pilot-feedback
Press CLR to get CLR on the scratchpad. Type something in and enter it into a field... should work just fine.
=> fix(mcdu): clear CLR before adding new chars

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Enhanced the entire spool up from idle to TOGA
Changed the AP Disconnect audio to be higher quality
Improved the sound of the gear retracting and extending
Improved the solenoid lock sound on the side stick
Start up the engine and take off normally. Listen to the spool up on takeoff. Try flex and toga takeoffs. After rotation, retract gear and listen to - 1. the sound of the wheels slowing down (a brushing kind of sound) and 2. the sound of the gear hydraulic whines. Engage autopilot and listen to the click of the solenoid. On landing, listen to the sound of the engines, and when dropping gear there should be another good quality sound of the gear whines. After disconnecting autopilot, check that the solenoid lock sounds (one click followed by …
=> feat: engine sound enhancements and others

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/sound/sound.xml
Fixed issue where sounds were buggy on dev and were the older ones after cfms merge.
To test - check that the autopilot disconnect beeps THREE times and has a triple click. Old sounds had 4 beeps and 3 clicks.
=> fix: old sounds after cfms merge

docs/a320-simvars.md, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/FlyByWireInterface.h, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h, src/fbw/src/model/AutopilotStateMachine_data.cpp, src/fbw/src/model/AutopilotStateMachine_types.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp, src/instruments/src/PFD/FMA.tsx
This PR adds the FINAL common AP/FD mode, but only the actual mode logic, and not the FMS changes required for it.
This means that the PR should not change any existing functionality at the moment, but is only a part of the changes required for RNAV approaches, the other part being FMS changes, which will be implemented at a later date.
=> feat(ap): FINAL mode

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/panel/panel.cfg
Looks like system gauges need at least 1 pixel width and height to be loaded...
CJ4(https://github.com/Working-Title-MSFS-Mods/fspackages/blob/main/src/workingtitle-aircraft-cj4/SimObjects/Airplanes/Asobo_CJ4/panel/panel.cfg) and CRJ panel.cfg
Verify the aircraft loads into the game and all systems are running (screens on, throttle and engines responding)
=> fix: compatibility with 1.21.18 hotfix

.vscode/launch.json, src/fadec/build.sh, src/fbw/build.sh
This PR configures VSCode and modifies some compiler/linker flags to enable debugging.
To debug, just compile the FBW or FADEC WASM with `.\scripts\dev-env\run.cmd ./src/fbw/build.sh --debug`. This will set the appropriate flags in the shell scripts to generate debug symbols. Then, in VSCode, go to the "Run and Debug" tab, and click on the green play button while the sim is running. This will attach the debugger to the Sim's Process and start the debugging session.
Can't really be tested by QA, since you will have to compile the plane yourself. This PR is intended for devs only.
1. Click on the **Checks** tab …
=> feat: Set up VScode and clang for debugging C++ WASM

src/fadec/src/EngineControl.h, src/fadec/src/FadecGauge.h, src/fadec/src/SimVars.h, src/fadec/src/Tables.h, src/fadec/src/ThrustLimits.h, src/fadec/src/common.h
=> feat: FADEC code update for thrust limits

src/mcdu-server/client/src/McduButtons.css
Fixes #6595
* Removed blue highlight when clicking buttons on chrome on android
1. Open the remote mcdu on an android device
2. Ensure the blue highlight is no longer present when clicking buttons
=> fix(mcdu-client): remove blue highlight on chrome on android

src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/model/AutopilotLaws.cpp, src/fbw/src/model/AutopilotLaws.h, src/fbw/src/model/AutopilotLaws_data.cpp, src/fbw/src/model/AutopilotLaws_types.h, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine_data.cpp, src/fbw/src/model/AutopilotStateMachine_types.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp
This PR further improves the Autoland capability. The flare law has been improved so that the reduction of V/S is more constant and smooth.
- do several Autoland in different conditions
=> feat: further tuning of G/S and FLARE law

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js, src/atsu/src/AocSystem.ts, src/atsu/src/com/Datalink.ts, src/atsu/src/com/NXApiConnector.ts, src/atsu/src/index.ts, src/atsu/src/messages/AtisMessage.ts, src/atsu/src/messages/WeatherMessage.ts
Fixes a report in Discord about broken ATIS requests at KDTW
Fixes a MCDU crash due to empty ATIS messages.
- Try all different ATIS sources in EFB
- Request three kinds of ATIS
- If ARR or DEP requested, but not available -> Combined is used
- If Enroute is requested, but not available -> ARR is used, if available
- Any failure results in "D-ATIS NOT AVAILABLE"
- Test of METAR/TAF
- airport provides METAR/TAF data: METAR is shown
- METAR/TAF unavailable: message contains "NO METAR/TAF UNAVAILABLE"
1. …
=> fix(atsu): Atis requests

.github/CHANGELOG.md, package.json
This PR fixes the package.json for TCAS.
=> fix: package.json for TCAS

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_AOC_RequestsAtis.js
Fixes issue in discord
It was not possible to toggle between printer and MCDU.
This PR fixes it and sends the ATIS to the correct endpoint
Send ATIS to Printer and DCDU
For available and missing ATIS
=> fix(atsu): send ATIS to printer

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Utils/NXSystemMessages.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/NavSystems/A320_Neo/A32NX_NavSystem.js, src/fmgc/src/flightphase/FlightPhaseManager.ts, src/fmgc/src/flightphase/index.ts, src/fmgc/src/guidance/lnav/legs/index.ts, src/fmgc/src/index.ts
These are a bunch of fixes I accumulated while working on some other stuff. None of them big enough for their own PR but I also didn't want to tie them into the cfms-15 lifetime.
Check that FMGC flight phases increment correctly on the MCDU. Check that attempting to clear the FROM or active waypoint on the F-PLN page gives a `NOT ALLOWED IN NAV` scratchpad message.
=> fix: misc fixes

scripts/build.js
Fixes a build issue related to decals.
- Ensure that textures look normal after loading the plane.
=> fix: build for decals

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js
Fix a crash on DIR TO page.
Kennedy
Make sure you can press CLR and enter it on LSK L1 when you have a waypoint selected/entered on the DIR TO page.
=> fix(mcdu): handle clr dir to wpt

package.json
Fixes the linting no longer working due to https://github.com/yannickcr/eslint-plugin-react/issues/3218.
=> build: pin eslint-plugin-react version

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml, src/model/efb/flypad.gltf
Fixes #5764
Fixes #4008
Adds a copy of the flyPad on the F/O side. The display is a mirror of the captain's side rather than an independent EFB... That could be improved in future but not for now.
Check that all EFB interactions work well on both sides.
=> feat(efb): f/o flypad

.github/CHANGELOG.md, Cargo.lock, src/systems/a320_hydraulic_simulation_graphs/Cargo.toml, src/systems/a320_systems/Cargo.toml, src/systems/a320_systems/src/hydraulic/mod.rs, src/systems/a320_systems_wasm/Cargo.toml, src/systems/a320_systems_wasm/src/lib.rs, src/systems/systems/Cargo.toml, src/systems/systems/src/apu/mod.rs, src/systems/systems/src/hydraulic/aerodynamic_model.rs, src/systems/systems/src/hydraulic/linear_actuator.rs, src/systems/systems/src/hydraulic/mod.rs, src/systems/systems/src/simulation/mod.rs, src/systems/systems/src/simulation/update_context.rs
Implements an aerodynamic drag and lift model that can be applied to any moving part, be it cargo door, gear doors, control surfaces....
Any hydraulically controlled component will have to fight aerodynamic forces, providing a realistic feedback for all control surfaces.
Standard operations:
1. Check that current aileron droop function on power off works properly
2. Check that aileron control when hydraulic power is available works properly (no wobble, positioning is correct)
3. Shutting down all hydraulic power in flight should result in aileron staying close to neutral position due to relative wind
Ludicrous operations:
Use custom weather with editable wind
1. Wind from back of the plane should accelerate droop down if …
=> feat(hyd): aerodynamic model for moving parts

.github/CHANGELOG.md, src/fmgc/src/guidance/GuidanceController.ts
This PR aims to improve resilience of the FMGC main loop in case of certain parts failing. As an example on the VNAV branch the LNAV part should not fail when VNAV path calculation is for some reason not working.
- LNAV should work as usual, no impact to be expected in normal operation
=> feat: increased resilience of FMGC main loop

src/instruments/src/SD/Pages/Fctl/Fctl.tsx
* Fixes a positioning issue of the elevator hydraulic indications, which was introduced in #6832
Before:
After:
=> fix(sd): fix elevator hydraulic indications

src/instruments/src/EFB/Failures/Failures.tsx
=> feat: show active failures

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
=> fix(cdu): revert socket changes

src/instruments/src/Common/EWDMessages.tsx
A fix for a very minor typo (missing whitespace for the indent).
Before
After
=> fix(fws): A/SKID N/WS FAULT typo

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js
* Removes uses of non-existent (and unused anyway) classes since SU9
=> fix: su9 fmgc loading

.github/CHANGELOG.md, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
Add LSK for vert rev on the destination line at the bottom of F-PLN.
Check that pressing the right LSK on the bottom destination line gives the VERT REV at destination page.
=> fix(mcdu): vert rev at dest

src/instruments/src/ND/pages/RoseMode.tsx
Track line still depended on the flightPlanManager which is no longer synced across to the ND (instead vectors, symbols, etc. are send over the bus like the real aircraft).
=> fix(nd): correct track line logic

src/fmgc/src/efis/EfisSymbols.ts, src/fmgc/src/efis/EfisVectors.ts, src/instruments/src/Common/hooks.tsx, src/instruments/src/ND/elements/FlightPlanVectors.tsx, src/instruments/src/ND/elements/Traffic.tsx, src/instruments/src/ND/index.tsx, src/shared/src/FlowEventSync.ts, src/tcas/src/components/TcasComputer.ts
Found an interesting conversation in the WT Discord. 
https://discord.com/channels/750764704175226992/925798646912516117/954353842412195930
Just a prototype, I want to check whether it has advantages for our use cases.
=> feat: use flowevent to replace coherent events

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Somehow got exp stuff in #6995 😬 
=> fix(fmgc): revert bad rebase changes

.eslintignore
There were a lot of eslint errors when running within a tree that has been built in.
=> fix(build): add missing eslint ignores

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/guidance/lnav/LnavDriver.ts
Fixes #7015
- Fix crash of f-pln page after sequencing last leg (e.g. go around).
- Fix to waypoint bearing sent to the ND (make it magnetic).
- Fix new cruise alt message (not changed during previous refactor).
- Check that to waypoint bearing at the top right of the ND lines up with the ND bearing ring.
- Have F-PLN page open during go-around and make sure it doesn't crash on crossing the runway threshold.
=> fix(fmgc/mcdu): various small issues

src/fmgc/src/efis/EfisSymbols.ts, src/instruments/src/ND/elements/CrossTrack.tsx, src/instruments/src/ND/elements/FlightPlan.tsx
Tweak constraint circle and waypoint ident rendering to match photo refs.
=> fix(nd): tweak waypoint rendering

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_DepartReq.js, src/atsu/src/ATC.ts, src/atsu/src/com/webinterfaces/HoppieConnector.ts, src/atsu/src/index.ts, src/atsu/src/messages/CpdlcMessage.ts, src/atsu/src/messages/CpdlcMessageElements.ts, src/instruments/src/DCDU/elements/MessageStatus.tsx, src/instruments/src/EFB/Settings/Settings.tsx
Fixes #7064
Fixes #7077
Some messages are interpreted in a wrong way. This PR fixes issues with DCL and rare CPDLC messages
1. Test that PDC with ATC-response is handled correct (DCL from ATC classified as UM169 or UM183)
2. Send "MAINTAIN FLXXX" to A/C and should be classified as UM19)
3. Check the STANDBY is abbreviated by STBY and NEGATIVE by NEGATV on the DCUD
4. Validate that it is possible to send WILCO/UNABLE after STBY is sent
5. Change METAR/ATIS source in EFB and check in localhost:19999 of EFB if connection is active if METAR and ATIS are IVAO or VATSIM
6. Connect to Hoppie, disconnect from internet, reconnect to internet and check if Hoppie connection is still active
Every new commit to this PR will cause a new A32NX …
=> fix(atsu): fix message interpretation

src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Set a discontinuity when the arrival and approach selected do not have a common fix.
Test STAR/APPR/VIA combos that do and don't connect... ensure discontinuity is present when they shouldn't be connected, and not when they should.
=> fix(fmgc): discontinuity when star/appr disconnected

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_Waypoint.js, msfs-avionics-mirror/src/msfstypes/pages/vcockpit/instruments/shared/flightelements/flightplanmanager.d.ts, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/LegsProcedure.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/RawDataMapper.ts, src/fmgc/src/guidance/GuidanceController.ts, src/fmgc/src/index.ts, src/shared/src/flightplan.ts
- show forced turn direction
- show fix annotation above first leg on the page
- fix up leg annotations per Honeywell doc + refs
Honeywell R1A Pilot Guide
Photos
Test that forced turns are shown on the F-PLN page... for this I used EGKK ILS 26L from VASU1G via WILLO:
On procedures/flightplans of your choice:
Check that no course annotation is shown on the left above a waypoint manually inserted into the flight plan enroute.
Check that procedure names and airways annotations are shown where there is no course annotation and part of one of those.
1. On …
=> fix(mcdu): f-pln page annotations

src/instruments/src/Common/persistence.tsx, src/instruments/src/EFB/Settings/Pages/AboutPage.tsx
* Added Sim Version to About Page in Settings
N/A
=> feat: sim version in about page

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/FlightElements/A32NX_WaypointLoader.js, src/fmgc/src/flightplanning/ManagedFlightPlan.ts
Properly string arrivals were having a discontinuity inserted for a couple of reasons:
- only one pending request for a facility was supported... but each LegsProcedure might request the same facilities concurrently
- not quite the right logic for finding the discont
String STARs to approaches and make sure they have a discontinuity when the wrong via etc. is selected, and are continuous otherwise.
=> fix: discontinuity in properly strung arrival

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_DirectToPage.js, flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, src/fbw/src/model/AutopilotStateMachine.cpp, src/fbw/src/model/AutopilotStateMachine.h, src/fbw/src/model/AutopilotStateMachine_data.cpp, src/fmgc/src/efis/EfisVectors.ts, src/fmgc/src/flightplanning/FlightPlanManager.ts, src/fmgc/src/flightplanning/ManagedFlightPlan.ts, src/fmgc/src/flightplanning/WaypointBuilder.ts, src/fmgc/src/guidance/GuidanceController.ts, src/fmgc/src/guidance/lnav/TransitionPicker.ts, src/fmgc/src/guidance/lnav/legs/DF.ts, src/fmgc/src/guidance/lnav/legs/IF.ts, src/fmgc/src/guidance/lnav/transitions/DirectToFixTransition.ts
Fixes #7016 
Test various direct tos... waypoints in the flightplan, and not in the flight plan.
=> feat: direct to with anticipated turn

flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_TipsManager.js
This PR fixes some typos in the new warning dialog.
=> fix: typos in assistance warning

src/instruments/src/EWD/elements/PseudoFWC.tsx
Fixes #7126
If a warning or caution is triggered, cancelled and then re-triggered, the master warning/caution light does not illuminate and there is no audible warning or caution. This has been fixed.
1. Spawin C&D
2. Power up aircraft and flip NW anti-skid inactive on/off
3. Check that failure is cleared and can be recalled
4. Check that resolving failure (by flipping NW anti-skid switch also resolves failure
5. Once failure resolved, trigger failure again. You should see and hear the master caution
6. Spawn in flight
7. Trigger a master warning by lowering the flaps when travelling at 280 knots. Raise and lower, ensuring the warning is retriggered
8. Attempt any other failures you fancy together. Ideally, they should be resolveable e.g. …
=> fix(fwc): Visual and audible warning/caution fix

src/fbw/src/AdditionalData.h, src/fbw/src/FlightDataRecorder.h, src/fbw/src/FlyByWireInterface.cpp, src/fbw/src/interface/SimConnectData.h, src/fbw/src/interface/SimConnectInterface.cpp, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp
This PR adds the information is certain assistance functions are enabled to the FDR.
- plane should work as normal, only recording function affected
=> feat: added assistance information to FDR

flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/flight_model.cfg
MSFS AI assistances are not compatible with the addon and cause trouble (engine going to idle after takeoff, tiller not working) etc.). This forces all assistances to be off via an entry in the flight_model.cfg.
1. Spawn in the plane and make sure it behaves normally.
2. Go to the main menu, turn on all assistance settings and spawn in the plane again. Verify that it is not possible to change assistance settings (in the toolbar + in the settings menu).
3. Taxi, Takeoff and ensure the behavior has not changed even after enabling the settings in the menu before spawning. …
=> feat: disable all MSFS assistance settings

package.json
This PR updates the version of the development version to 0.9.0.
- test if the plane can still be loaded and shows the new version in the content manager
=> build: update to version 0.9.0

src/fmgc/src/guidance/lnav/TransitionPicker.ts, src/fmgc/src/guidance/lnav/legs/HX.ts, src/fmgc/src/guidance/lnav/legs/IF.ts, src/fmgc/src/guidance/lnav/transitions/DirectToFixTransition.ts
I accidentally left some changes in that weren't needed anymore. Cleaned them up, and additionally a lint error I came across while doing it.
Check that DIR TO and holds work okay.
=> chore(fmgc): clean up unneeded changes from #7114

src/instruments/src/ISIS/ISISDisplayUnit.tsx
Force css animations on in the ISIS.
Check that the selected bug in the bugs screen flashes with "menu animations" turned off in MSFS settings.
=> fix(isis): force css animations

.github/workflows/experimental.yml, .github/workflows/master.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, scripts/install-source.js
- fixes environment variables not available in node.js script
none
=> fix(ci): installer version detection

.github/workflows/release.yml
=> fix(ci): wrong stable asset name variable

src/instruments/src/Common/hooks.tsx, src/instruments/src/EWD/elements/PseudoFWC.tsx, src/instruments/src/ND/pages/ArcMode.tsx
Fixes #7216
Fixes issues caused by PR #7180 (See issue 7216)
- Check that ND arc mode refresh updates as expected
- Check that T/O CONFIG responds correctly.
- Check that SELECTED HDG bug is working on ND
=> fix: hotfix for hook dependencies

manifest-base.json
Remove the dependency on the default A320. This should not be needed since the hard fork.
No QA required.
=> fix: remove manifest dep on asobo a320

src/instruments/src/PFD/PFD.svg
This adds the source PFD SVG. It's an inkscape SVG, so for applying changes to the instrument itself, I export from inkscape as "optimized SVG" so that I can just copy the elements without the unecessary inkscape stuff in it.
Also, the FBW Display EIS font needs to be installed on the OS so that the text is rendered properly.
There are no functional changes here, so no QA necessary.
=> feat: add PFD source SVG

.github/CHANGELOG.md, src/instruments/src/BAT/index.tsx
Fixes #7284
This PR fixes the battery voltmeters so they only update one digit at a time, as per the real thing.
https://streamable.com/7oy5hg
https://www.youtube.com/watch?v=s3NySU5Hv4w
https://www.youtube.com/watch?v=ZiyR4juG1hE#t=25s 
Spawn in on the ground. Turn the lights test on/off. Observe the digits "sliding in", as per the reference above.
=> feat(elec): make BAT voltmeters update one digit at a time

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
* Fixed an issue with being unable to select certain approaches due to wrong max page length calculation
https://www.youtube.com/watch?v=twwUjHXdNVU
1. Spawn and enter the following routes in (via sim-brief or manual entry)
KLAS/26R RADYR2 BLAQQ DCT SHTNR ANJLL4 KLAX/24R
KFLL/28R REGAE1 PERMT AR16 ILM SBY J79 VILLS DPK DPK3 KBDL/24
ESGG/21 TOPLA3J TOPLA DCT PENOR N133 DOMAG T240 OGDAV OGDAV4T EPGD/29
YPAD/05 PANKI3 PANKI H247 CULIN Y59 RIVET RIVET3 YSSY (No Arrival Runway Selected)
SBGL/15 TIVRO1A TIVRO DCT IBDA1A SBSP/35L
1. You are able to successfully enter these routes with the departures and arrival pages in the MCDU.
1. MCDU does not break on these pages when buttons are mashed/pressed in an odd order
1. …
=> fix(mcdu): fix scrolling behaviour on arrivals page

.github/CHANGELOG.md, src/mcdu-server/client/src/App.css, src/mcdu-server/client/src/App.jsx, src/mcdu-server/client/src/McduScreen.jsx
Fixes #6842
Added a 4:3 aspect ratio compatibility mode to the remote mcdu client, which reduces margins for better button alignment with mcdu hardware. To use it, add `/43` to the URL.
Before             |  With 4:3 mode
:-------------------------:|:-------------------------:
1. Open the remote mcdu with 4:3 mode by adding `/43` to the URL
2. Ensure there are no formatting issues on any pages
=> feat(mcdu-client): 4:3 aspect ratio compatibility

docs/a320-simvars.md, flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/systems.cfg
Make the A32NX_DEVELOPER_STATE Lvar persistent so it doesn't go away when changing flight scenarios, restarting etc. This will persist across sim restarts as well.
=> feat: persistent dev state

src/systems/a320_systems/src/hydraulic/mod.rs
Added test case for emergency extension just in case
Unit test so no QA needed
=> chore(hyd): added gear emergency unit test

src/systems/a320_systems_wasm/src/ailerons.rs, src/systems/a320_systems_wasm/src/elevators.rs, src/systems/a320_systems_wasm/src/rudder.rs
Fixes errors in log console about MapMany and Simvar declaration
=> chore(sys): fix aspect log errors

src/fbw/src/FlightDataRecorder.h, src/fdr2csv/src/FlightDataRecorderConverter.cpp, src/fdr2csv/src/main.cpp
Adds the new fields created in `AdditionalData` by #7426 to the FDR2CSV, and increments interface versions.
=> fix(fdr): fix FDR interface after #7426

src/tcas/src/components/TcasComputer.ts
Fixes #7519 
PR #7506 broke compatability with injected traffic, as the new property for on ground status in the SU X traffic API is broken for injected traffic. This PR reverts the breaking changes in 7506. 
Discord username (if different from GitHub):2Cas#1022
Test with both injected traffic (VATSIM/FSLTL) and live traffic (MSFS Live Traffic, not AI Traffic)
1. Load in C&D at FAOR (or another high altitude airfield), with either multiplayer, live traffic or VATSIM/FSLTL traffic enabled (live traffic and traffic from addons i.e. FSLTL preferred)
2. Power on, Turn on ATC XPDR and switch TCAS mode to TA/RA, etc.
3. Check that no traffic that is parked at a gate or taxiing on ground is displayed on the traffic display.
4. Load in on approach at FAOR (or another high altitude airfield) and …
=> revert(tcas): reverted back to fallback on ground logic (injected traffic compatability fix)

src/fmgc/src/efis/NearbyFacilities.ts
- Fixes an error spam from `NearbyFacilities`
- Make sure the EFIS filters work
=> fix: error spam from NearbyFacilities

flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js, src/instruments/src/EFB/UtilComponents/Form/SimpleInput/SimpleInput.tsx
Rookie mistake in #7585... calling this.scratchpad.guid before this.scratchpad is constructed. I also added the rest of the params for the FOCUS_INPUT_FIELD calls just in case.
=> fix: init order for scratchpad

package.json
=> chore: bump build version

Cargo.toml
Add some test profile optimisations so the stack memory is not  requested at each test bed affectation
=> fix: fix rust tests stack overflow

scripts/cdn.sh
Tested on Exp, upload was successful. Should resolve "out of memory" errors in the upload step.
=> fix: use -T to avoid memory issues on runner

src/fmgc/src/flightplanning/LegsProcedure.ts
Fix bug noticed by @Benjozork 
=> fix(fmgc): station declination used wrong leg

.github/workflows/master.yml
Step 2
1. Make a copy of `master` --> `master-legacy` - DONE
2. In master: Deactivate master workflow - WIP
3. In master-legacy: Change the master.yml workflow to run on master-legacy - this should now work as master beforehand (incl. upload to CDN)
4. In master-legacy: Do a full build on `master-legacy` and check if the build works and the CDN upload works
5. In Installer Config: change releaseModel to `master-legacy` branch
6. In Installer: Check if the installer works with the new config and shows the correct version
7. In `repo-refactor` branch: Deactivate master workflow and also comment out everything from the `Get and delete vmaster pre-release zip asset` step to the end of the workflow
8. In `repo-refactor` PR: Squash-merge `repo-refactor` PR/branch to `master` branch
9. In …
=> chore: Repo restructure - deactivate master workflow

fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
=> fix: do not convert internal values

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
Fixes #7755
Fix LOC deviation scaling on ROSE LS mode.
Check that PFD and ND (ROSE LS) LOC deviation matches.
=> fix(nd): loc deviation scaling

.github/workflows/experimental.yml
Fix copy-pasta in github workflow.
=> fix: exp workflow zip name

fbw-a32nx/src/systems/atsu/src/AOC.ts
This fixes an issue where the `COMPANY MSG` memo will not clear if an AOC message is deleted before it is read.
Discord username (if different from GitHub): Eearslya#7831
1. Use the AOC menu to request a METAR or ATIS report.
1. Confirm `COMPANY MSG` appears on the ECAM after a few moments.
1. Use the AOC menu to open and read the message. Confirm `COMPANY MSG` disappears from ECAM.
1. Repeat steps 1-2, then use the CLR key to delete the message without reading it. Confirm `COMPANY MSG` disappears from ECAM.
1. Click on the **A32NX** download link at the bottom …
=> fix(aoc): Update unread message count when messages are deleted

.eslintrc, .github/workflows/ingamepanels-checklist-fix.yml, .gitignore, fbw-ingamepanels-checklist-fix/README.md, fbw-ingamepanels-checklist-fix/src/base/flybywire-ingamepanels-checklist-fix/html_ui/InGamePanels/Checklist/ChecklistCheckpointLine/ChecklistCheckpointLine.css, fbw-ingamepanels-checklist-fix/src/base/flybywire-ingamepanels-checklist-fix/html_ui/InGamePanels/Checklist/ChecklistCheckpointLine/ChecklistCheckpointLine.html, fbw-ingamepanels-checklist-fix/src/base/flybywire-ingamepanels-checklist-fix/html_ui/InGamePanels/Checklist/ChecklistCheckpointLine/ChecklistCheckpointLine.js, fbw-ingamepanels-checklist-fix/src/base/manifest-base.json, igniter.config.mjs, package.json, scripts/build_ingamepanels_checklist_fix.js, scripts/build_ingamepanels_checklist_fix.sh, scripts/fragment-ingamepanels-checklist-fix.js, scripts/install-source-ingamepanels-checklist-fix.js
Adds a separate package that fixes a bug for rendering the Asobo checklists with nested blocks.
Without the fix nested `Block` elements in checklists are rendered incorrectly (the alignment is wrong) and contain phantom (duplicate) items:
The fix improves the indentation and prevents the phantom items from being generated.
This was originally a part of #7627, however, I have split it out to this pull request.
⚠ This change does impact the entire game and other aircraft as it overrides (in the virtual file system, no files on disk are changed) some core game files.
However, it has now been updated so that the override in it's own package that can be uninstalled (or not installed in the first place) in the unlikely event that it causes a conflict with another addon.
Discord username (if …
=> feat: Add workaround/fix for rendering issue in MSFS checklists

fbw-a32nx/src/systems/instruments/src/SD/style.scss
Fixes https://github.com/flybywiresim/a32nx/discussions/7799
SD has a slightly different background hue to other displays.
=> fix(sd): add proper background colour

fbw-common/src/wasm/systems/systems/src/hydraulic/mod.rs
Clamp random distribution to an absolute min/max value
Not needed
=> fix(hyd): fix random test fail

fbw-a32nx/src/systems/instruments/src/EWD/instrument.tsx
When rebasing #7748 for merge, a fix from #7801 was accidentally regressed. This PR re-fixes the issue.
=> fix(fwc): Remove extra delta time given to FWC

fbw-a32nx/src/systems/instruments/src/Clock/instrument.tsx
=> fix: remove instrument did not load message

fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx
Adds the "+" indication when ISA temps are above 0
Missing "+"
After:
=> fix: missing plus sign for isa temp

.github/CHANGELOG.md
Oops forgor changelog items for that PR.
NO QA
=> docs: changelog for 7652

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/ND/pages/ArcMode.tsx, fbw-a32nx/src/systems/instruments/src/ND/pages/PlanMode.tsx, fbw-a32nx/src/systems/instruments/src/ND/pages/RoseMode.tsx
Fixes #7845
Turns out we were still using the old plane icon removed in #7826. Created an entirely new one scaled off photos... bit more accurate than the old one 😆.
Check that plane appears okay on ND.
=> fix(nd): plane icon

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/fbw-a32nx/ND/TRAFFIC_NORMAL.svg, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/fbw-a32nx/ND/TRAFFIC_PROXIMITY.svg, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/fbw-a32nx/ND/TRAFFIC_RA.svg, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Images/fbw-a32nx/ND/TRAFFIC_TA.svg, fbw-a32nx/src/systems/instruments/src/ND/elements/Traffic.tsx
Oopsie, we were using these too. 😬 
=> fix(nd): re-add tcas icons

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
Fixes a report of the dev-channel
Adapts the switch-db function to the new fmsclient-structure of the datalink code
=> fix(atsu): adapt to refactored code

.github/CHANGELOG.md, fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/systems/instruments/src/Common/EWDMessages.tsx, fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts, fbw-a32nx/src/systems/shared/src/arinc429.ts
Add two reminder warnings during landing:
- GND SPLR NOT ARMED
- SPD BRK STILL OUT
- GND SPLR NOT ARMED
- Should occur during approach below 800 ft RA when gear is down, speedbrakes and retracted, and ground spoilers are not armed.
- SPD BRK STILL OUT
- Should occur during climb (above 1500 feet)/cruise/descent (above 800 feet):
- When an engine is above idle and the speedbrakes are deployed for more than 80 seconds,
- During a TCAS RA requiring positive V/S if the speedbrakes are deployed,
- Should occur during approach:
- When speedbrakes are out below 800 feet RA. …
=> feat(fwc): add landing warnings

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js
Reverts flybywiresim/a32nx#7830
=> revert: #7830 feat(fwc): A32nx minimums exposed by fmgc

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_SelectWptPage.js
Fix formatting of -0.
Go to LICC, try enter IAA as a vor/ils/waypoint somewhere in the FMS, check that you don't see "0-0" (-0 padded to 3 digits with "0"s).
=> fix(fms): lat/lon close to zero on DUPLICATE NAMES page

fbw-a32nx/src/systems/shared/src/FmMessages.ts
#7879 introduced two duplicate ids for FmMessage.
=> fix(fms): fix duplicate FmMessage ids

fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
Update power sources after electrical update 
=> feat(hyd): A380 -> connect eha actuators on eha elec buss

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/NDv2/FmMessages.tsx, fbw-a32nx/src/systems/instruments/src/NDv2/TcasWxrMessages.tsx
Fixes #8054
Fix masks below TCAS/WXR and FM messages.
Real ND.
Check the messages mask the map below when present and do not when not present.
=> fix(nd): tcas/wxr and fm message map masking

fbw-a32nx/src/systems/instruments/src/NDv2/shared/map/WaypointLayer.ts
* Tiny fix for the VOR EIS symbol. See Screenshots.
| Before | After |
|--------|------|
| ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/d454fb88-e805-480d-98e8-7480dc9797ff) | ![grafik](https://github.com/flybywiresim/a32nx/assets/39596827/9a6e61ea-c137-47c2-9d68-98961c4d0389) |
=> fix(nd): correct VOR EIS symbol

.github/workflows/pr-qa-reg.yml
Fixes the project automation workflow for the new repository name.
Discord username (if different from GitHub): Micah (micahbcode)
=> fix(ci): project automation workflow fixed for new repo name

.github/Contributing.md
Changed the links to link to /aircraft instead of /a32nx
No need to test, only changes the contributing.md
=> docs: update links in Contributing.md to the renamed repo

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, fbw-a32nx/src/systems/instruments/src/PFD/AltitudeIndicator.tsx, fbw-a32nx/src/systems/instruments/src/PFD/AttitudeIndicatorHorizon.tsx, fbw-a32nx/src/systems/instruments/src/PFD/DigitalAltitudeReadout.tsx, fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx, fbw-a32nx/src/systems/instruments/src/PFD/shared/ArincValueProvider.ts, fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx, fbw-a32nx/src/systems/instruments/src/PFD/shared/SimplaneValueProvider.ts
Fixes #8067
Implements proper MDA/DH/NO DH logic and fixes some related issues + refactoring to more conventional avionics framework style along the way. Also fixed a bug with selected heading which the linter found while I was in the file.
Notes: We have some awkward issues with the various Arinc429Register/Value/RegisterSubject types and getting data across the bus, piping it around etc. Needs a bit of thought and probably a lot of cleanup.
Various.
Check that NO DH in the PERF APPR RADIO field correctly displays NO DH on the FMA. Check that BARO and RADIO mininima work okay on the FMA, altitude tape (for MDA, digital readout goes amber below MDA, and there's an amber marker on the alt tape), and RA (amber DH appears above the artificial …
=> fix(pfd/fm): implement mda/dh/no dh logic

.github/ISSUE_TEMPLATE/bug_report_beta.yaml
This PR removes the 'experimental' option from bug issue template dropdown.
Discord username (if different from GitHub): alepouna
This PR does not change anything on the aircraft, so no testing is required. 
=> chore(repo): remove experimental option from issue template

fbw-a32nx/src/systems/instruments/src/NDv2/shared/RadioNeedle.tsx
Fixes #8131
Initial sub for adfneedle was missing to make it show up in arc mode if no other mode had been selected before.
1. Tune NDB and enable ADF needles. They should show up after activation. (Stay in arc mode and do not switch to any other mode to verify this).
=> fix: add initial notification for adf needle

.github/CHANGELOG.md
=> fix(chore): add changelog for #8066

.github/ISSUE_TEMPLATE/feature_request_beta.yaml
This PR aims to remove the "Experimental" option from the "Feature Request" dropdown template.
Experimental was removed from the installer a while ago.
Discord username (if different from GitHub): Bernardo R
=> chore: remove "Experimental" from "Feature Request" dropdown template

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PerformancePage.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FMC/A32NX_FMCMainDisplay.js, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/legs/FlightPlanLeg.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/ApproachSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/ApproachViaSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/ArrivalEnrouteTransitionSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/ArrivalRunwayTransitionSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/ArrivalSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/DepartureEnrouteTransitionSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/DepartureRunwayTransitionSegment.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/new/segments/DepartureSegment.ts
Fixes a few issues with speed constraint handling during the missed approach.
This PR targets the fms-v2 branch and does not require normal QA.
=> fix(fms): fix speed constraint handling during missed approach

.github/workflows/master.yml, .github/workflows/pr.yml
Removing docker images after our build, freeing up additional 10GB of space as of today.
1. Download the artifact and confirm the plane loads into the sim like always.
=> fix(ci): provide more space on runner

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_AtisAutoUpdate.js
Fixes #8157 
Changes LSK6L return prompt in ATIS AUTO update page to ATIS menu from ATC menu
Before:
After:
Provided in the original issue
bruno_pt99
Press LSK6L and make sure it returns to the ATIS page.
=> fix(atsu): Change ATIS auto update LSK6L to ATIS menu

.github/CHANGELOG.md, package.json
0.11 is branched. Dev is now for 0.12.
None
=> chore: bump to v0.12.0

package-lock.json, package.json
Upgrades msfssdk to the latest version, picking up [0.5.0 from AAU2](https://github.com/microsoft/msfs-avionics-mirror/releases/tag/framework-0.5.0) and [0.6.0 from SU13](https://github.com/microsoft/msfs-avionics-mirror/releases/tag/framework-v0.6.0). None of the breaking changes listed should affect us, and a quick smoke test shows no issues for our instruments.
Picks up some nice new features, like additional SubscribableMapFunctions, and the one that motivated me to update is binding subscribables to CSS class and style objects.
Perform some full flights and see if there are any regressions noticed.
1. Make sure you are signed …
=> chore: upgrade msfssdk to v0.6.0

fbw-a32nx/src/systems/instruments/src/ND/ND.tsx, package-lock.json
Capt ND will show ILS2,  FO ND will show ILS1. This was a regression that is fixed now
=> fix: swap ils receiver index

fbw-a32nx/src/systems/instruments/src/PFD/HorizontalTape.tsx
=> fix: missing small ticks on heading tape

fbw-common/src/systems/instruments/src/ND/shared/map/CanvasMap.tsx, fbw-common/src/systems/instruments/src/ND/shared/map/TrafficLayer.ts
Enums were only declared, but not defined which resulted in exceptions when the ND received traffic from TCAS.
=> fix: traffic not shown on ND

docs/README.md
Simple change of the docs readme file to change the repo reference from a32nx to aircraft as it is right now.
Discord username (if different from GitHub): alepouna
No QA needed, no aircraft changes.
=> docs: change a32nx repo reference to aircraft

fbw-a380x/src/systems/instruments/src/Common/Shapes.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/ElecAc/elements/AcEssFeedLine.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/ElecAc/elements/BusBar.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/ElecDc/elements/BusBar.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/ElecDc/elements/Dc1Dc2BusTie.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/ElecDc/elements/Dc1DcEssBusTie.tsx, fbw-a380x/src/systems/instruments/src/index.scss
This PR fixes a few issues that occured after the move to the monorepo:
* Update the `index.scss` which was missed in #8333
* Fix some small issues related to the ELEC AC, DC, F/CTL and WHEEL pages.
=> fix(a380-sd): fix some regressions after move to monorepo

fbw-a32nx/src/systems/instruments/buildSrc/igniter/tasks.mjs, fbw-a32nx/src/systems/instruments/src/ND/config.json, fbw-a380x/src/systems/instruments/buildSrc/igniter/tasks.mjs, fbw-a380x/src/systems/instruments/src/ND/config.json
Add a way for instruments to have extra dependencies, and add a dep for the shared ND to each aircraft ND. It's very annoying when you make changes to the ND and they don't trigger the ND to rebuild 😬 .
=> fix(build): nd dependencies

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Fixes #8414 
Add decimal in mach mode
[Youtube Example 1](https://www.youtube.com/watch?v=gNIP7t-fH3c&t=773s)
[Youtube Example 2](https://www.youtube.com/watch?v=Vq8Lj0pp39o)
Discord username (if different from GitHub): Budzique#1196
Fly above mach transition, observe mach decimal
=> fix(FCU): Fix Mach Decimal

fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/DoorPage.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/A380XDoors.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/CabinDoor.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/CargoDoor.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/Outline.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/Oxygen.tsx
Still had this lying around on the old repo, thought I should PR it.
| Before| After|
|--------|--------|
| ![grafik](https://github.com/flybywiresim/aircraft/assets/39596827/62401537-94d4-4284-a314-b77b1376730a) | ![grafik](https://github.com/flybywiresim/aircraft/assets/39596827/84ef2662-8212-4ca4-9e1b-604b463b602b) |
=> feat(a380-sd): door page visual update

.github/CHANGELOG.md, fbw-a32nx/src/localization/flypad/en.json, fbw-a32nx/src/systems/instruments/src/EFB/Dashboard/Widgets/FlightWidget.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Efb.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/A320_251N/A320Payload.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/A380_842/A380Payload.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/Payload/Payload.tsx, fbw-a32nx/src/systems/instruments/src/EFB/Store/features/simBrief.ts
Reverts flybywiresim/aircraft#8415
Because of issues with Simbrief fetching too rapidly
=> revert: "feat(EFB/SimBrief): Automatically import SimBrief Fuel & Payload"

fbw-a380x/src/systems/instruments/src/PFD/DigitalAltitudeReadout.tsx
**Purely A380X, and small change --> No QA needed**
Follow-up to #8463 
Fixes a really stupid error where I left a debug altitude injection in production code
Discord username (if different from GitHub): I choose to stay anonymous due to embarrassment reasons
=> fix(a380x/pfd): remove debug altitude injection

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js
Fixes #8549
Fixes a wrong comparison (1 vs true).
=> fix: mach and trk text missing in fcu

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml
As the title says. Was previously incorrect.
=> fix(a380): make elec pmp ON p/b momentary, and OFF p/b non-momentary

fbw-a32nx/src/wasm/fadec_a320/build.sh, fbw-a32nx/src/wasm/fbw_a320/build.sh, fbw-a380x/src/wasm/fadec_a380/build.sh, fbw-a380x/src/wasm/fbw_a380/build.sh, fbw-common/src/wasm/cpp-msfs-framework/cmake/TargetDefinition.cmake, fbw-common/src/wasm/terronnd/build.sh
Enable the extra mem info for SU15 in all the C++ builds.
Need https://github.com/flybywiresim/aircraft/pull/8585 for this to work (although it is safe to merge without).
=> build: enable mem info for su15

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_EXTERIOR.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/engines.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/systems.cfg
**A380X only, no QA needed.**
Model changes by Repsol: Lights update. 
Needs latest model update (_240330)
n/a
=> fix(a380x/model): by repsol: lights, model & texture changes

fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FADEC.js, fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.cpp
Fixes a fadec migration regression bug where the center tank transfer did not work correctly. 
@Saschl for your testing - needs developer to properly test this ;)
=> fix: Fixing Center Tank transfer

fbw-a32nx/docs/a320-simvars.md
Add document for this Lvar which indicates when the VS/FPA window should be dashed, or 00oo (no plus).
N/A
=> docs(fcu): vs/fpa state

fbw-common/src/systems/instruments/src/ND/pages/plan/index.tsx
Fixes plane symbol on plan mode showing incorrectly before ppos is available.
1. Start C&D, power up plane and select PLAN mode on ND
2. Set all three ADIRS to NAV and wait for alignment.
3. Plane symbol should not appear before alignment is completely finished.
4. Check that the orientation and position of the symbol is correct.
5. Verify the symbol moves and rotates correctly when taxiing and after takeoff.
1. Click on either **flybywire-aircraft-a320-neo** or …
=> fix: improved conditions for plane symbol on plan page

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg
Fix the A380X MFD to match the UV map that is now in the a380x repo. This is useful for devs as we work on master rather than the new MFD branch.
=> fix(a380x): mfd uv map

scripts/build.sh
**No QA needed, local build change only**
Disables global FBW_TYPECHECK, which was introduced by mistake. 
=> fix(a380x): Disable global FBW_TYPECHECK

.github/workflows/a380x-exp.yml
Doesn't build properly, wrong Navigraph secrets are being chosen.
Change workflow file to include A32NX secrets, since we don't support a multi-token environment right now (being worked on in another PR, could take a while though)
=> fix(build): a380x experimental build fix

fbw-common/src/systems/instruments/src/EFB/Navigation/Navigation.tsx
Fixes SVG position when bounding box is offset quite a bit from the top of the chart. Use x1, y2 from bounding box information now to place it properly.
Test e.g. LGAV VOR03Y FINAL and make sure the plane is visible. Also check taxi maps for accuracy.
=> fix: airplane symbol with offsets

fbw-a32nx/src/systems/fmgc/src/flightplanning/new/FlightPlanService.ts
- Fix origin and destination not being reported to TELEX API which was broken since fms-v2
- Enter a FROM/TO and flight number
- Make sure your flight appears on the website map https://flybywiresim.com/map/
=> fix: telex reporting of origin/dest

fbw-common/src/systems/instruments/src/EFB/Performance/Widgets/TakeoffWidget.tsx
Fixes #8736 
Some text on the takeoff performance calculator in the EFB was black while white theme was selected.
Ensure all text is visible on the takeoff performance page in the EFB with all three themes.
=> fix(efb): fix invisible text with light theme

fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/FuelConfiguration_A32NX.cpp, fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FuelConfiguration_A380X.cpp, fbw-common/src/wasm/cpp-msfs-framework/CMakeLists.txt, fbw-common/src/wasm/cpp-msfs-framework/lib/inih/ini_fbw.h, fbw-common/src/wasm/cpp-msfs-framework/lib/inih/ini_type_conversion.h, fbw-common/src/wasm/extra-backend/LightingPresets/LightingPresets.h
Fixes creation of the folder for ini files (fuel saving).
Test if fuel state is saved to an ini file when the work does not already have the "AircraftStates" folder. This folder should be created. 
=> fix: ini library folder creation

fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx
Centered ALT & G/S vertical armed modes. Increased spacing on V/S FMA and width of mode change box according to 380.
https://youtu.be/lGXyY45d-S8?t=286
https://youtu.be/lGXyY45d-S8?t=356
https://youtu.be/WzxSiEWK3cg?t=1
https://youtu.be/_Dx3Ze6PUi4?t=24
Not 100% sure about the alt magenta as I couldn't find any ref but for consistency I centered it.
bruno_pt99
=> feat(pfd): 380 vertical fma improvements

fbw-a32nx/src/systems/instruments/src/PFD/config.json, fbw-a380x/src/systems/instruments/src/PFD/config.json
Fixes the PFD build deps so they don't build every time.
=> fix(pfd): build deps

fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/interface/SimConnectInterface.cpp, fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.cpp, fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer.h, fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_data.cpp, fbw-a380x/src/wasm/fbw_a380/src/model/A380PrimComputer_types.h
Fix A380 spoilers deploying on ground at too low speeds, reason was that the wheel RPM was not converted to kts as expected.
Also update ground spoiler logic, and add spoiler lift function (as a placeholder without engine condition)
=> feat(a380-prim): splr fixes and updates

fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata21-22-23.tsx
- Add all remaining checklist items for ATA chapters mentioned above
- PseudoFWC logic
Discord username (if different from GitHub): NONAmr2433
=> chore(a380x): Finish adding checklist items and pseudoFWC logic for ATA 21, 27, 28, 31, 33, and 70 abnormal procedures

fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.tsx
Fixes a small bug I created in master.
=> fix(a380x): fms init

.github/workflows/pr-qa-reg.yml
GitHub sunset the repository level Projects feature, and moving them the org level. The action we use to automate the QA process has been updated to use the new board.
No QA required.
=> ci: Fix GitHub Project action

fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx, fbw-a380x/src/systems/instruments/src/SD/StatusArea.tsx
- Remove an erroneous comment in the A32NX ISA delta code.
- Fix the ISA delta calculation and display logic.
- Quantise the FOB and GW values.
- Convert the FOB to US units when selected.
=> fix(a380x/sd): permanent data area isa delta and weights

fbw-a380x/src/base/flybywire-aircraft-a380-842/config/a380x/a380-842/checklists.json5, fbw-a380x/src/systems/extras-host/modules/pushbutton_check/PushbuttonCheck.ts, fbw-a380x/src/systems/instruments/src/EWD/elements/Idle.tsx, fbw-a380x/src/systems/instruments/src/PFD/AltitudeIndicator.tsx, fbw-a380x/src/systems/instruments/src/PFD/SpeedIndicator.tsx, fbw-a380x/src/systems/instruments/src/SD/Pages/Press/elements/OutflowValve.tsx, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsMemos.ts, fbw-a380x/src/systems/systems-host/systems/LegacyFwc.ts, fbw-a380x/src/wasm/fbw_a380/src/FlyByWireInterface.cpp
Adds two extra flight phases to the FWC specific to the A380 which allows for better memo & abnormal sensed phase behavior.
A380 FCOM
Due to all phases after "3" being different, I had to shift or add the new phases in some places (fws, ewd, pfd etc.), as a result, some regression testing might be needed. In addition, some memos might require a phase inhibition review (mostly the ones with the 320 phase inhibition logic). 
bruno_pt99
1. Click on either **flybywire-aircraft-a320-neo** …
=> feat(a380/fws): A380 flight phases

.github/workflows/localization.yml
Fixes the localization github workflow which persists any changes to the localization files via Localazy
N/A - github workflow
=> chore: Fix localization workflow

fbw-a380x/src/systems/instruments/src/RMP/Systems/RmpStateController.ts
Fixes #8774
Fix wrong RMP pot.
=> fix(a380x/rmp): rmp 2 pot

fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/EcamMessages/AbnormalSensed/ata34.tsx, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsAbnormalSensed.ts, fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts
Adds SURV XPDR STBY ecam message
FCOM
bruno_pt99
=> feat(a380/fws): transponder standby ecam message

fbw-common/src/systems/shared/src/RadioUtils.ts
=> docs: fix RadioUtils.unpackBcd16

fbw-a380x/src/systems/instruments/src/EFB/config.json
Fix dep I missed the other day.
=> fix(a380x/efb): igniter dep

fbw-a380x/src/systems/instruments/src/RMP/Systems/RmpStateController.ts
Fix typo in local vars (missing L: prefix).
=> fix(a380x/rmp): rmp power local var typo

fbw-a32nx/src/systems/instruments/src/EWD/PseudoFWC.ts
Testing was not enough on #9039. The local var names were wrong as well as the missing prefix.
=> fix(fwc): gear compressed wiring

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Fixes #9032 
- Engines rework
- Balancing
- cavcharge volume dependent on LOCALVAR_FWC_VOLUME RTPC event
=> fix(a380x): Sounds update Oct 2024 by Boris

fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/sound/sound.xml
Latest changes by Boris. 
When merged, remember to point to the latest large-files commit. 
=> chore: Sound update Oct 25, 2024

.github/CHANGELOG.md
0.12.0 changelog is now complete. Master is 0.13.0.
=> docs: master is now 0.13

.github/ISSUE_TEMPLATE/bug_report_a380x.yaml, fbw-a380x/README.md
Improves wording on the INOP page. Previous version lead to misunderstanding. 
Removes ATA chapter headings for which no entries exist. 
=> docs: Fix a380x inop page wording

.github/CHANGELOG.md
@frankkopp feel free to change the wording if you want :)
=> fix(docs): added changelog entry for #9146

package.json
=> build: master is now 0.13.0

fbw-a380x/README.md
Clarifies what has been implemented/not implemented for automatic/manual fuel transfers and for fueling
Discord username (if different from GitHub): donbikes
=> fix(a380x/docs): Clarify fuel system items inop

scripts/git_build_info.js
Harden the build info a bit so it will fall back if the GITHUB_SHA is falsy (some fragmenter scripts rely on this), and ensure the rest of the build info is filled if `git tag -l --contains HEAD` returns non-zero (seems to do so on certain git versions when HEAD is not tagged).
=> build: harden git info

fbw-a380x/README.md
=> docs(a380x): add afs cp alt button to inop

.github/CHANGELOG.md
Whoops, wrong plane, and found missing saschl.
=> docs: fix changelog

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.scss, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx
Fixes #9266 
Reduces height of some elements, to give flex-grow some space to breathe. For some users, layout was overloaded vertically which lead to the THS FOR ... line not being rendered. 
Complete cockpit preparation as per SOP, go to FMS/ACTIVE/PERF, confirm that page shows without layouting issue. Should look like above. 
=> fix(a380x/fms): Fix FMS/PERF/TO layouting issue

.github/CHANGELOG.md, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/A380_COCKPIT.xml, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/model/behaviour/legacy/generated/A32NX_Interior_Misc.xml
=> fix(a380x): Fix RCDR GND CTL push button

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/src/systems/instruments/src/EWD/config.json, fbw-a380x/src/systems/instruments/src/EWD/elements/EclClickspots.tsx, fbw-a380x/src/systems/instruments/src/EWD/elements/WdAbstractChecklistComponent.tsx, fbw-a380x/src/systems/instruments/src/EWD/instrument.tsx, fbw-a380x/src/systems/instruments/src/EWD/style.scss, fbw-a380x/src/systems/instruments/src/MFD/pages/common/IconButton.tsx, fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts, fbw-common/src/systems/instruments/src/EFB/Localization/data/en.json, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
Fixes #9344 
Adds virtual soft keys to EWD when checklists are shown. Option can be enabled via the EFB, Settings -> Realism
My imagination
Open up C/L on the EWD using the ECAM CP, verify that toggling the soft keys in the EFB works, and that the soft keys in the EWD have the same functionality than the HW ones in the ECAM CP. 
=> feat(a380x): QoL: Add virtual ECL soft keys

.gitattributes
This PR tries to improve conflict behavior of the CHANGELOG file when working with PRs.
No testing of the aircraft required as nothing is changed.
=> chore: try to improve deconflicting with CHANGELOG

.github/Contributing.md
removes mention of the asobo branch from the contributing.md as it is irrelevant.
=> fix(github): remove old asobo branch mention

.github/CHANGELOG.md
=> docs: add missing entry to CHANGELOG.md

docs/README.md, fbw-a32nx/src/localization/README.md, fbw-a380x/src/localization/README.md, fbw-common/src/systems/instruments/src/EFB/Localization/README.md
Updating the repo tree documentation
N/A
=> docs: updating README.md with current repo structure

.github/CHANGELOG.md, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_NewWaypoint.js, fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_PilotsWaypoint.js, fbw-a32nx/src/systems/fmgc/src/flightplanning/DataManager.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/WaypointEntryUtils.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/interface/DataInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
Fixes #9095 
Uses station declination as magvar instead of database for PBX/PBD waypoints. This has been fixed before but regressed in fms-v2.
Before (KSFO Quiet Bridge Visual)
After
Use testing instructions of original PR https://github.com/flybywiresim/aircraft/pull/8182
=> fix(fms): use station declination for pbx/pbd

fbw-a32nx/src/wasm/fbw_a320/CMakeLists.txt
To allow CMake based IDEs use the cpp code the CMake config was updated. 
n/a
=> fix: Update CMakeLists.txt 

fbw-a32nx/docs/a320-simvars.md, fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer.h, fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer_data.cpp, fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer_types.h
Add QFE as a prin program option to the FCU, currently hardcoded to QFE not avail.
Also clarify documentation relating to baro setting SSM logic
=> feat(fcu): add QFE pin prog option

fbw-a380x/src/wasm/systems/a380_systems/src/hydraulic/mod.rs
A bit more patience
Nothing to test
=> chore(test): Fix random test fail

fbw-a32nx/src/systems/instruments/src/FCU/Components/AfsDisplay.tsx, fbw-a32nx/src/systems/instruments/src/FCU/Components/EisDisplay.tsx, fbw-a32nx/src/systems/instruments/src/FCU/Components/HdgDisplay.tsx, fbw-a32nx/src/systems/instruments/src/FCU/Components/SpdDisplay.tsx, fbw-a32nx/src/systems/instruments/src/FCU/Components/VerticalDisplay.tsx, fbw-a32nx/src/systems/instruments/src/FCU/FCU.tsx
Modernize the TS FCU portion, as it was created some time ago and the avionics framework has been updated since then.
There should be no functional changes
Verify that the FCU still works as before
=> refactor(fcu): modernize FCU avionics-framework code

fbw-a32nx/src/systems/instruments/src/FCU/Components/EisDisplay.tsx
Fixes #9595 
Fixes attached issue
Check that there is a leading zero in the baro window below 1000 hPa
=> fix(fcu): add leading zero below 1000hPa

fbw-a32nx/src/wasm/fbw_a320/src/model/FcuComputer.cpp
Set the bits in the FCU output bus of QNH and QFE to false, if STD mode is active. Changed to conform to new refs.
=> fix(fcu): set QNH bit to false when in STD

.github/workflows/pr-build.yml
- removes the large-files submodule in the `PR Tests & Build / Lint (pull_request)` workflow to accelerate workflow run time
foxtrotsierra
Not required
=> ci: remove large-files submodule from lint

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/PFD/PFD.tsx, fbw-a380x/src/systems/instruments/src/PFD/PitchTrimDisplay.tsx
Fixes #9762 
Additional clean-up: Remove references to failures which were removed (PFD failure without reconf logic doesn't make sense)
=> fix(a380x/pfd): Fix precision of pitch trim indicator

fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts
Fixes mini regression from https://github.com/flybywiresim/aircraft/pull/9680
=> fix(a32nx): make discontinuities deletable again

fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/ObservableFlightPlan.ts, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnFixInfo.tsx
Fixes #9832
Fixes a crash of the FIX INFO page after deleting a FIX. This was caused when attempting to access a null object.
Perform the steps in the original issue. Ensure that the page does not crash.
=> fix(a380x/mfd): fix crash of fix info page

fbw-common/src/systems/instruments/src/OANC/OancMarkerManager.ts
A bug prevented flags/crosses from being deleted via the MAP DATA tab; The affected function returned too early
=> fix(a380x/oans): Fix deleting taxiway crosses/flags via the MAP DATA tab

.github/CHANGELOG.md
Adds changelog, was forgotten in the PR. 
=> fix(a380x/oit): Changelog addition

.github/CHANGELOG.md, fbw-a32nx/src/systems/fmgc/src/flightplanning/DataManager.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts
Fix the lat/lon waypoint ident to always use the extended format in the 380X.
Enter or import lat/lon waypoints and ensure they don't have the short LLnn format.
=> fix(a380x/fms): lat/lon waypoint ident

package.json
In quite possibly one of the worst design decisions I've ever seen, vitest runs completely differently depending on whether it's in a CI environment or not. If it's not on CI it runs in watch mode, which utterly fails in our dev environment, and uses up all CPU. Instead we explicitly invoke it in run mode now so the tests work in our dev environment.
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** …
=> fix: do not launch tests in watch mode

.github/CHANGELOG.md, fbw-common/src/systems/shared/src/ApproachUtils.ts
Fix the approach name format for suffixed approaches on MCDU pages.
Check some approaches at your favourite airports to ensure they appear correctly, and never extend past the column under the V of AVAILABLE.
=> fix(a32nx/fms): mcdu approach name format

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A320_Neo_CDU_MainDisplay.ts, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts
- Add approach via differentiation per H4 changes.
- Remove INSERT/ERASE prompts for TMPY on APPROACH VIAS page as on the real thing.
- Swap the up/down arrows which were always wrong.
On request.
Select a variety of approaches at different airports with a without STARs selected and ensure the VIAS page shows all of the transitions, with those connecting to the selected STAR show as "available" and those not as "other appr vias". …
=> feat(a32nx): approach via differentiation and layout fix

fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/IconButton.tsx, fbw-a380x/src/systems/instruments/src/OIT/OitFooter.tsx, fbw-a380x/src/systems/instruments/src/OIT/OitHeader.tsx
PR #9624 introduced duplicate keys for IconButton icons, leading to visual errors (duplicate arrows rendered) in the OIT and ATCCOM page. This PR fixes that. 
After PR:
=> fix(a380x/cds): De-duplicate button icons (visual fix)

.github/CHANGELOG.md, package.json
Bump the version in master to 0.14, as 0.13 is now branched off.
=> chore: bump version to 0.14

.eslintignore, fbw-a32nx/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/mach.config.js, fbw-a380x/src/base/flybywire-aircraft-a380-842/SimObjects/AirPlanes/FlyByWire_A380_842/panel/panel.cfg, fbw-a380x/src/systems/instruments/src/EFB/index.tsx, fbw-a380x/src/systems/instruments/src/OITlegacy/OitLegacy.tsx, fbw-a380x/src/systems/tsconfig.json, fbw-a380x/src/systems/ui/README.md, fbw-a380x/src/systems/ui/buildSrc/directories.mjs, fbw-a380x/src/systems/ui/buildSrc/igniter/tasks.mjs, fbw-a380x/src/systems/ui/src/.eslintrc, fbw-a380x/src/systems/ui/src/Notifications/Notification.scss, fbw-a380x/src/systems/ui/src/Notifications/config.json, fbw-a380x/src/systems/ui/src/Notifications/instrument.tsx, fbw-a380x/src/systems/ui/src/Notifications/tsconfig.json, fbw-a380x/src/systems/ui/src/index.scss, fbw-a380x/src/systems/ui/src/util.js, fbw-a380x/src/systems/ui/tsconfig.json, fbw-common/src/systems/instruments/src/EFB/AircraftContext.ts, fbw-common/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx, fbw-common/src/systems/ui/src/Notifications/Notifications.tsx, fbw-common/src/systems/ui/src/Notifications/index.ts, fbw-common/src/systems/ui/src/Notifications/style.scss, fbw-common/src/systems/ui/src/Notifications/tsconfig.json, igniter.config.mjs
=> feat: notifications first step + enhanced efb experience

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/MfdPageDirectory.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsFuelLoad.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsInit.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/common/FmsHeader.tsx, fbw-a380x/src/systems/instruments/src/MFD/pages/common/widget-style.scss, fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/UiWidgets/TopTabNavigator.tsx
Update tab bar appearance to the one found on later avionics batches
Remove DEBUG page from menu 
Fix some errors after <InputField> refactor
=> fix(a380x/mfd): Update tab bar layout with overlapping tabs

fbw-a32nx/src/systems/fmgc/src/guidance/vnav/descent/ApproachPathBuilder.ts
Fixes an issue where speed constraints were improperly handled if they were part of the final approach
Before:
After:
Load up an approach at your favorite airport. Set a speed constraint < 190 kts on one of the final approach legs, or before it.
Make sure that the predictions make sense and there are no TOO STEEP PATH segments.
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of …
=> fix(fms): fix predictions with speed constraint on final approach

fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/FlightPlan.ts, fbw-a32nx/src/systems/fmgc/src/guidance/geometry/GeometryFactory.ts
Fixes a bug that was introduced in #8841, where the coded turn direction was removed on a leg after performing a DIR to. This should not happen for legs that require a coded turn direction, such as hold legs (Hx).
Image of the bug
Enter a hold in the FMS, perform a DIR to the hold fix, ensure the hold is shown and flown correctly.
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom …
=> fix(fms): do not remove forced turn on legs that require them

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts
Adds the approach VIA auto-selection functionality.
https://github.com/user-attachments/assets/148d7953-be81-4006-a8ce-393b87b43bc9
pylot
Selecte some STAR/approach combos that join up with an approach transition. Ensure the via/transition is automatically selected when there is only one available. Insert into the legs are strung correctly.
Select some STAR/approach combos that don't join up with any transition, but with some transitions. Ensure no via/transition is selected, but the VIA page is shown with all the vias under "OTHER VIAS". Insert into the legs are strung correctly.
1. …
=> feat(a32nx/fms): add via auto-selection

fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/plans/BaseFlightPlan.ts
There was a report of FMS crashes after the merge of https://github.com/flybywiresim/aircraft/pull/10050. This is a fix for this crash by checking for `undefined` on flight plan elements.
=> fix(fms): check for undefined before removing forced turn

.github/CHANGELOG.md, fbw-a32nx/src/systems/instruments/src/ND/style.scss
Fixes [#10118 ]
Increases text size of “MODE CHANGE” and “RANGE CHANGE” messages on ND. 
Before : 
After : 
Before : 
After : 
Discord username (if different from GitHub): lucasiq
Change range and ND mode
=> fix(A32NX/nd): ND range change & mode change font size

.github/CHANGELOG.md, fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts, fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcInterface.ts, fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/F-PLN/MfdFmsFplnVertRev.tsx
Use the EFOB to compute an estimated gross weight at the step climb points, and from that calculate the max alt. This fixes spurious STEP ABOVE MAX ALT messages for future step climbs.
Load a long haul flight plan, and insert the step climbs. They should all be valid/not above max alt assuming the plan is good. Change one of the earlier steps to a level that is too high, but at/below the last steps, and ensure you do get STEP ABOVE MAX ALT in the message area and in the DIST/TIME columns as in the screenshot above.
1. On the left side, find …
=> fix(a380x/fmc): use efob to compute step alts

.gitattributes
Test GLTF files as binary for git purposes. They are not diffable or mergeable, and just make a mess of `git diff`.
=> chore: treat gltf as binary

fbw-a32nx/src/systems/fmgc/src/flightplanning/WaypointEntryUtils.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/legs/FlightPlanLeg.ts, fbw-a32nx/src/systems/fmgc/src/flightplanning/waypoints/WaypointFactory.ts, fbw-common/src/systems/navdata/client/backends/Msfs/Mapping.ts, fbw-common/src/systems/navdata/shared/types/BaseFix.ts, fbw-common/src/systems/navdata/shared/types/Runway.ts, fbw-common/src/systems/navdata/shared/types/Waypoint.ts
Treat `Runway` as `Fix`. We make sure that runway legs use a runway fix as their waypoint with the correct section and subsection code.
Also removes a conversion from airports to terminal waypoints.
- Enter a normal flight plan, make sure you can enter an arrival
- Select a runway-only as approach, make sure you can change the arrival again
- Enter airports, runways, VORs, NDBs and normal waypoints into the PROG page …
=> fix(fms): treat runways as fixes

.github/CHANGELOG.md
Add some additional guidance to the changelog notes.
=> docs: add changelog guidance

.github/CHANGELOG.md
- resized textures that are not a power of 2
- reduced texture size of the same texture file in the 8K textures that are a single flat colour
- fixes issue of some exterior textures not loading in 2024 SU3
Requires MSFS2024 SU3
- Load aircraft and check that no pink textures appear on the top or anywhere else on the aircraft. Refer to image above for the problem areas.
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or …
=> fix(a380x): resized texture files that are not a power of 2

fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts
Fixes #10319
Fixes unit conversion issue introduced through #10308 where I changed the variable the CDU uses for fuel measuring from lbs to kg. 
1. Start cold and dark
1. Load and refuel aircraft
1. Complete preflight in MCDU using a flight plan
1. Observe INIT FUEL PRED page while starting engine
1. No large changes in EFOB and EXTRA fuel should be detected
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download …
=> fix(a32nx/fuel): Fqi FOB unit conversion removed

README.md
Updated README with EIS2 version for A320.
N/A
N/A
N/A
N/A
=> docs: added EFIS configuration to A320 README
